### ISSUE TITLE
BigDecimal.ZERO not considered a "decimal"

### ISSUE THREAD

**Issue by Tristan971** [DiUS/pact-jvm#1001]
Hello, ran into a bit of an issue today, migrating from Pact 3.6.11 to 4.0.4 (for JDK 11 support).

It does seem that the new core matchers, specifically for numbers, will not consider `BigDecimal#ZERO` to be a decimal?

Specifically the issue is in the [following snippet](https://github.com/DiUS/pact-jvm/blob/master/core/matchers/src/main/kotlin/au/com/dius/pact/core/matchers/MatcherExecutor.kt#L237-L248) :
```kotlin
fun matchDecimal(actual: Any?): Boolean {
  val result = when {
    actual == 0 -> true
    actual is Float -> true
    actual is Double -> true
    actual is BigDecimal && actual.precision() > 0 -> true
    actual is JsonPrimitive && actual.isNumber -> decimalRegex.matches(actual.toString())
    else -> false
  }
  logger.debug { "${valueOf(actual)} (${typeOf(actual)}) matches decimal number -> $result" }
  return result
}
```

Which does check for BigDecimal, but in conjunction with a precision > 0 when `BigDecimal#ZERO` is defined [as follows](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/math/BigDecimal.java#L338) (at least in OpenJDK 11) 
```java
    // Constants
    /**
     * The value 0, with a scale of 0.
     *
     * @since  1.5
     */
    public static final BigDecimal ZERO =
        ZERO_THROUGH_TEN[0];

    /**
     * The value 1, with a scale of 0.
     *
     * @since  1.5
     */
    public static final BigDecimal ONE =
        ZERO_THROUGH_TEN[1];

    /**
     * The value 10, with a scale of 0.
     *
     * @since  1.5
     */
    public static final BigDecimal TEN =
        ZERO_THROUGH_TEN[10];
```

Which causes an issue because the previous matcher (in 3.6.11 at least) was as follows:
```kotlin
NumberTypeMatcher.NumberType.DECIMAL -> {
  logger.debug { "comparing type of ${valueOf(actual)} to a decimal at $path" }
  if (actual !is Float && actual !is Double && actual !is BigDecimal && actual != 0) {
    return listOf(mismatchFactory.create(expected, actual,
      "Expected ${valueOf(actual)} to be a decimal number",
      path))
  }
}
```

where just being the BigDecimal type was enough to match the "decimal" PACT kind.

I suppose this might have been asked before, but I wasn't quite able to find info on how you would recommend proceeding? (assuming this is voluntary, that is)

Best regards

**Comment by uglyog** [comment]
This passes for me as I'm getting `BigDecimal.ZERO.precision() == 1`, which is actually wrong

**Comment by Tristan971** [comment]
Might be JVM implementation dependent what the scale of cached BigDecimal instances are.

Check the source for your JVM's BigDecimal.

Nonetheless, BigDecimal should match decimal no matter the scale simply because it literally is the definition of the class to hold decimal values.

At the end of the day, an integer is a decimal number ; requiring that decimals specifically describe non-integer ones should be only an extra opt-in matching ; especially if it is JVM dependent and thus subject to change when upgrading/switching JVMs.

Or at least that's my reasoning

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change.

**Comment by uglyog** [comment]
The decimal matcher is there to match any numbers with digits after the decimal point (like currency that would require exactly 2 digits after the decimal point). It matches floating point numbers as well as numbers represented by BigDecimal class.

**Comment by Tristan971** [comment]
Ah yes that's fine!
