### ISSUE TITLE
pact-jvm-consumer: Message should return metadata as Map<String, Object>

### ISSUE THREAD

**Issue by msa-itsonix** [DiUS/pact-jvm#1006]
I am using au.com.dius:pact-jvm-consumer-junit5 in version 4.0.4.

When defining a pact with the MessagePactBuilder dsl, you can provide metadata through withMetadata giving a Map<String, Object>, where Object can be a raw value, a Matcher or a Generator. But the resulting Message returns its metadata as Map<String, String>.

	@Pact(consumer = "MyConsumer")
	public MessagePact somethingHappend(final MessagePactBuilder builder) {

		final Map<String, Object> expectedMetadata = new HashMap<>();
		expectedMetadata.put("myLongProperty", 10L);

		return builder.given("something happend")
				.expectsToReceive("MyEvent")
				.withMetadata(expectedMetadata)
				.toPact();
	}

	@Test
	public void myEventIsReceived(final List<Message> messages) {
		final Message message = Iterables.getOnlyElement(messages);
		final Map<String, String> metaData = message.getMetaData();
		// expected Map<String, Object> here, but this contains the String "10"
		// for key "myLongProperty" => no chance to convert it back
	}

This is a problem when integrating with messaging frameworks that also provide metadata with raw Object values instead of String (like IMessage of azure servicebus in my case) because you can't translate the pact Message to such a message representation then (at least not with hard workarounds.)

Shouldn't Message just return the raw metadata. To keep the API compatible I would propose to add something like getRawMetadata that returns Map<String, Object>.

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change

**Comment by msa-itsonix** [comment]
Thanks for the fast reply.
The map's signature now changed to Map<String, Object> in 4.0.5 but the contained value is still a String. Running the following test (with au.com.dius:pact-jvm-consumer-junit5:4.0.5) will fail:

```
@ExtendWith(PactConsumerTestExt.class)
public class MyTest {

	@Nested
	@PactTestFor(providerName = "MyProvider", providerType = ProviderType.ASYNCH, pactVersion = PactSpecVersion.V3)
	public class GivenSomethingHappend{

		@Pact(consumer = "MyConsumer")
		public MessagePact somethingHappend(final MessagePactBuilder builder) {

			final Map<String, Object> expectedMetadata = new HashMap<>();
			expectedMetadata.put("myLongProperty", 10L);

			return builder.given("something happend")
					.expectsToReceive("MyEvent")
					.withMetadata(expectedMetadata)
					.toPact();
		}

		@Test
		public void myEventIsReceived(final List<Message> messages) {
			final Message message = messages.get(0);
			final Map<String, Object> metaData = message.getMetaData();
			final Object exectedLongProperty = metaData.get("myLongProperty");
			assertTrue(Long.class.isAssignableFrom(exectedLongProperty.getClass()));
		}
	}
}
```

I also noticed that on the provider side the tests will also fail when an event is produced containing the expected metadata property as long with an error message indicating the consumer expected a string, which is not correct here. Looking at the generated json of the pact, one can see that the expected metadata is also contained as string although it should be a json number:

```
{
  "consumer": {
    "name": "MyConsumer"
  },
  "provider": {
    "name": "MyProvider"
  },
  "messages": [
    {
      "description": "MyEvent",
      "metaData": {
        "myLongProperty": "10"
      },
      "providerStates": [
        {
          "name": "something happend"
        }
      ]
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "4.0.5"
    }
  }
}
```

**Comment by uglyog** [comment]
4.0.6 has been released with the updated fix
