### ISSUE TITLE
A `TestTemplateInvocationContextProvider` must not return an empty stream

### ISSUE THREAD

**Issue by t1** [DiUS/pact-jvm#1007]
The javadoc of `TestTemplateInvocationContextProvider# provideTestTemplateInvocationContexts` says: This method is only called by the framework if `#supportsTestTemplate` previously returned `true` for the same `ExtensionContext`. Thus, this method must not return an empty `Stream`.

But the junit5 `PactVerificationInvocationContextProvider` returns an empty stream if it doesn't find any pacts. This results in the cryptic error message from JUnit 5: `org.junit.platform.commons.PreconditionViolationException: No supporting TestTemplateInvocationContextProvider provided an invocation context`

Can we throw an exception instead.

**Comment by uglyog** [comment]
4.0.6 has been released with this fix
