### ISSUE TITLE
JUnit5 provider tests contain pact broker password in the logs 

### ISSUE THREAD

**Issue by verkhoro** [DiUS/pact-jvm#1009]
Hey,
I am using `pact-jvm-provider-junit5`, version 4.0.4. The source is configured with `@PactBroker` annotation. Test logs contain the password to our pact broker
```
Verifying a pact between ...
  [Using PactBrokerSource(host=${PACT_BROKER_HOST}, port=${pactbroker.port:}, scheme=https, pacts={Consumer(name=...
... options={authentication=[basic, username, password]}, tag=null))]})]
```

These logs are stored in CI and local logs might be sent over slack. This kind of logging should be turned on explicitly if developers need it for debugging.

We have slf4j in the project and yet I don't see the logger name in above line, so I can't filter it out. I also checked root logger setup and it is set to INFO in prod and test.

I will appreciate any ideas if this log statement doesn't appear in your standard setup.
Thanks!

**Comment by verkhoro** [comment]
Hey, I can work on the fix if you need help after the issue is triaged.

**Comment by uglyog** [comment]
I actually think #1015 has fixed this

**Comment by verkhoro** [comment]
This is great! I can confirm that the issue is fixed. Thank you
