### ISSUE TITLE
headers injection for pact-jvm-provider-spring

### ISSUE THREAD

**Issue by sab1l** [DiUS/pact-jvm#1010]
More than an issue this may be a lack of knowledge from my side.

How can we add headers (such as user-agent) following the [MockMvc test examples provided in github repo](https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-spring) ?
[This test](https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-spring/src/test/groovy/au/com/dius/pact/provider/spring/MvcProviderVerifierSpec.groovy) seems to provide a way to inject headers, but I'd say it's building the request from scratch instead of retrieving it from pact broker or file (as in github readme examples).
For now, we removed the user-agent header from the consumer declaration as we agree it's not needed there, since it can be different for each consumer.
But then we also had to make it optional from the controller to be able to validate the contract, since it's not clear how to inject this on provider test side :sweat:
It's quite ok for user-agent but some other headers (e.g. locale) may be mandatory for the controller under test and different for each client running the test. So they would be excluded from the contract declaration and still would be needed for validation.
Thanks for sharing your point of view on this topic!

**Comment by uglyog** [comment]
You can do it with a request filter. See https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java#L104
