### ISSUE TITLE
Request query gets mangled/encoded

### ISSUE THREAD

**Issue by joehoag** [DiUS/pact-jvm#1018]
I'm using pact-jvm-consumer 4.0.2 (protocol version 2) to write some consumer-side pact logic and produce a JSON file.  If I specify a url/query like this:

```
                .uponReceiving("A request for favorite courses")
                .path(favoriteCoursesPath)
                .method("GET")
             .query("include[]=term&include[]=total_scores&include[]=license&include[]=is_public&include[]=needs_grading_count&include[]=permissions&include[]=current_grading_period_scores&include[]=course_image&include[]=favorites")
                .headers(DEFAULT_REQUEST_HEADERS)
```

I get this generated in the json contract file:

```
        "query": "include[]\u003dterm%2C+include%5B%5D%3Dtotal_scores%2C+include%5B%5D%3Dlicense%2C+include%5B%5D%3Dis_public%2C+include%5B%5D%3Dneeds_grading_count%2C+include%5B%5D%3Dpermissions%2C+include%5B%5D%3Dcurrent_grading_period_scores%2C+include%5B%5D%3Dcourse_image%2C+include%5B%5D%3Dfavorites"
```

(If I use encodedQuery() instead of query(), I get the same thing.)

This query isn't interpreted correctly by our server logic, so we don't get the right fields back in our result, so our pact tests fail.

When I was using version 3.5.12 of the pact-jvm-consumer, it just echoed my query verbatim to the json file.  How can I do that (i.e., avoid encoding) in v4.0.2?  (I had to move to 4.0.2 to get the fix for https://github.com/DiUS/pact-jvm/issues/958.)

**Comment by joehoag** [comment]
Even worse is when something like this is output to the json file:

```"query": "include[]\u003dterm, include[]\u003dtotal_scores, include[]\u003dlicense, include[]\u003dis_public, include[]\u003dneeds_grading_count, include[]\u003dpermissions, include[]\u003dfavorites, include[]\u003dcurrent_grading_period_scores, include[]\u003dcourse_image, include[]\u003dsections\u0026state[]\u003dcompleted, state[]\u003davailable"
```

And that's another big problem that I'm encountering -- the manner of encoding is very unpredictable, and of questionable correctness.  Again, I really wish there was a way to specify "don't encode my query!".

For now, I am relying on a series of sed commands to undo all of the encoding in the json file that is produced.

**Comment by uglyog** [comment]
Version 4.0.7 has been released with this change

**Comment by joehoag** [comment]
Thank you!
