### ISSUE TITLE
XML body does not get unescaped

### ISSUE THREAD

**Issue by tweek-in-a-box** [DiUS/pact-jvm#102]
I'm using the Specs2 consumer framework to produce my pact file. The provider only talks XML, thus I end up with something like

    "body" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><user name=\"pact1623356631\"><password><value>pact</value></password><active>true</active><attributes/></user>"

in the pact file. I then use the SBT plugin to verify this pact against the provider, but the payload is not escaped resulting in a 400 response. I've isolated the problem to [Pact.scala#L24](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/scala/au/com/dius/pact/model/Pact.scala#L24) which is intended to format a potential JSON payload. It seems that this is unintentionally causing the XML body to be escaped again. When I eliminate this line and use this custom build version, my verifyPacts passes.

The following shows the problem on the REPL:

	scala> import org.json4s._
	import org.json4s._
	scala> import org.json4s.JsonDSL._
	import org.json4s.JsonDSL._
	scala> import org.json4s.jackson.JsonMethods._
	import org.json4s.jackson.JsonMethods._
	scala> val json = parse("""{"body" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><user name=\"pact\"><password><value>pact</value></password><active>true</active><key></key><attributes/></user>"}""")
	json: org.json4s.JValue = JObject(List((body,JString(<?xml version="1.0" encoding="UTF-8" standalone="yes"?><user name="pact"><password><value>pact</value></password><active>true</active><key></key><attributes/></user>))))
	scala> JString(pretty(json))
	res0: org.json4s.JsonAST.JString =
	JString({
	  "body" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><user name=\"pact\"><password><value>pact</value></password><active>true</active><key></key><attributes/></user>"
	})

I've tested this with commit 1e5ae30 of pact-jvm.

**Comment by uglyog** [comment]
It probably makes more sense to pretty print the body when outputing it, not when reading the pact file.

**Comment by tweek-in-a-box** [comment]
Hi Ronald,

Thanks for your reply. Did you want me to make this change? I will probably only get to it next Monday, and I'm still fairly new to Scala. Apart from that I'm very happy to give it a try. So depending on Content-Type of the request/response I'll add support for pretty printing XML/JSON in the PactSerializer and remove the line mentioned above?

Cheers,
Fabs

**Comment by uglyog** [comment]
I'm thinking just to remove that line. I don't think the serialization code should be changing the bodies. It should be up to the consumer framework code to format the body appropriatly.

**Comment by uglyog** [comment]
Turns out we can't remove the line, because that breaks loading pact files with json bodies. But I added an if to check for strings. Hopefully this resolves your issue.

**Comment by tweek-in-a-box** [comment]
Hi Ronald,

I can confirm this is working now with 55eb028. Thanks for fixing this! Are you planning to do a release any time soon?

Thanks,
Fabs

**Comment by uglyog** [comment]
There are a few issues still waiting for confirmation, but there is nothing stopping a release. I'll deploy it to maven central this evening (Australian Eastern Standard Time).

**Comment by uglyog** [comment]
2.1.13 is in maven central

**Comment by tweek-in-a-box** [comment]
I've already updated, thanks again! :) I think we can close this now?
