### ISSUE TITLE
fromProviderState on path doesn't work in pact-jvm-consumer-groovy

### ISSUE THREAD

**Issue by yaelhol** [DiUS/pact-jvm#1022]
I used fromProviderState on path parameter, but it doesn't work:
withAttributes(method: 'get', path: fromProviderState('/shoppingCart/v2.0/shoppingCart/${shoppingcartId}', '/shoppingCart/v2.0/shoppingCart/ShoppingCart_05540051-1155-4557-8080-008a802200aa'), 
            query: ([mask: 'returnStockInformation,returnNote', includeExpiredShoppingCart: 'false', excludePrices: 'true']))

I see that the contract is generated wrongly. The generator for the path is created on the response instead of on the request. When I modify the contract manually, it's working.

**Comment by uglyog** [comment]
Version 4.0.7 has been released with this change
