### ISSUE TITLE
Pact provider test fails with au.com.dius.pact.core.model.RequestResponsePact cannot be cast to au.com.dius.pact.model.Pact

### ISSUE THREAD

**Issue by jayakanthprasadt** [DiUS/pact-jvm#1029]
**Consumer gradle:**
	compile group: 'au.com.dius', name: 'pact-jvm-consumer-junit_2.12', version: '3.6.14'
	compile group: 'au.com.dius', name: 'pact-jvm-consumer-java8', version: '4.0.6'

**Provider gradle:**
     compile group: 'au.com.dius', name: 'pact-jvm-provider-junit_2.12', version: '3.6.14'
	compile group: 'au.com.dius', name: 'pact-jvm-provider', version: '4.0.6'

While running the pact provider test, getting the below exception. Pact file is copied to provider location. 

**_java.lang.ClassCastException: au.com.dius.pact.core.model.RequestResponsePact cannot be cast to au.com.dius.pact.model.Pact_**

import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.springframework.boot.SpringApplication;
import org.springframework.web.context.ConfigurableWebApplicationContext;

import au.com.dius.pact.provider.junit.PactRunner;
import au.com.dius.pact.provider.junit.Provider;
import au.com.dius.pact.provider.junit.State;
import au.com.dius.pact.provider.junit.loader.PactFolder;
import au.com.dius.pact.provider.junit.target.HttpTarget;
import au.com.dius.pact.provider.junit.target.Target;
import au.com.dius.pact.provider.junit.target.TestTarget;

_**```
@RunWith(PactRunner.class)
@Provider("store-search-service")
@PactFolder("pacts")
public class PactProviderTest {
	@TestTarget
	public final Target target = new HttpTarget("http", "localhost", 8087);
	 private static ConfigurableWebApplicationContext application;
	 
	@BeforeClass
	public static void start() {
	    application = (ConfigurableWebApplicationContext) 
	      SpringApplication.run(StoreSearchServiceApplication.class);
	}
	
	@State("GET StoreInfo 200 NEW")
	public void toGetState() { }
	 
}
```**_

**Comment by uglyog** [comment]
Please don't mix major versions of the Pact-JVM libraries. If you're using 'pact-jvm-consumer-java8', version: '4.0.6' than you need to also use 'pact-jvm-consumer-junit', version: '4.0.6' (or any 4.0.x versions)

**Comment by jayakanthprasadt** [comment]
Thanks @uglyog , It is working fine now. I used the below in both producer and consumer. versions mismatch was the problem then. Thank you.

	_compile group: 'au.com.dius', name: 'pact-jvm-consumer-junit_2.12', version: '3.6.14'
	compile group: 'au.com.dius', name: 'pact-jvm-consumer-java8_2.12', version: '3.6.14'

    compile group: 'au.com.dius', name: 'pact-jvm-provider-junit_2.12', version: '3.6.14'
	compile group: 'au.com.dius', name: 'pact-jvm-provider_2.12', version: '3.6.14'_
