### ISSUE TITLE
The request body is escaped after it is rebuilt by using value injected from provider state

### ISSUE THREAD

**Issue by tainguyenvn** [DiUS/pact-jvm#1031]
I define Pact for the POST request. The request body uses the existing value (e.g. IDs), or sometimes it should use a unique value (e.g create an entity where the entity name must be unique). So I use value injected from provider state. The body also contains data in XML format. My problem is after provider injects value and rebuild the body, the XML string is escaped, so it make the request fail. Below is details:

Define Pact in Consumer:
ResouceName.json file defines body in JSON format
```
{
  "entityName": "${eName}",
  "xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
}
```

Create pact:
```
String strBody = Resources.toString(Resources.getResource("/ResouceName.json"), Charsets.UTF_8);

@Pact(
        provider = "Test_Provider",
        consumer = "Test_Consumer"
    )
    public RequestResponsePact createEntity(PactDslWithProvider builder)
    {
        return builder
            .given("A entity name not exists")
            .uponReceiving("A request to create new entity")
            .path(/test)
            .method(HttpMethod.POST.name())
            .headers(ImmutableMap.of(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE))
            .body(PactDslRootValue
                .valueFromProviderState(strBody,strBody.replace("${eName}","mock-name")))
            .willRespondWith()
            .status(HttpStatus.OK.value())
            .body(new PactDslJsonBody()
                .stringType("entityName","mock-name")
            )
            .toPact();
    }
```

From Provider:
```
@State("A entity name not exists")
    public Map<String, Object> generateUniqueName() throws Exception
    {
        String name = RandomStringUtils.random(5, true, true);  
        HashMap<String, Object> map = new HashMap<>();
        map.put("eName", name);
        return map;
    }

```
When executing test from provider, the value injected successfully but the body is escaped like as:

`{\r\n  \"entityName\": \"dGcna\",\r\n  \"xml\": \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n\"\r\n}`

I expect it should be:
`"{"entityName": "dGcna","xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"}"`

That's why it makes the request fail. 
I am using **au.com.dius:pact-jvm-provider-junit_2.12:3.6.14**

Could anyone help me to resolve this issue? Thanks

**Comment by minhdoan159** [comment]
@tainguyenvn I faced same issues, fortunately see this ticket.
@uglyog Any ideas on it?  Whether is a bug or we are using wrong method for body with XML format. Could you please help to take a look on it?

**Comment by tainguyenvn** [comment]
@uglyog Or do we have method to inject value to request body, something  like "bodyFromProviderState". It's similar to pathFromProviderState, queryParameterFromProviderState

**Comment by uglyog** [comment]
With my test, I'm getting

```
127.0.0.1 - POST /data

X-ContractTest: [true]
Connection: [keep-alive]
User-Agent: [Apache-HttpClient/4.5.5 (Java/11.0.6)]
Host: [localhost:39451]
Accept-Encoding: [gzip,deflate]
Content-Length: [153]
Content-Type: [application/json]
{"entityName":"sNQINKQPAHifCYf2ietz","xml":"\u003c?xml version\u003d\"1.0\" encoding\u003d\"UTF-8\"?\u003e\n\u003centity name\u003d\"mock-name\"/\u003e"}
```

It is only the embedded XML which is being escaped.

**Comment by uglyog** [comment]
Note this is with version 4.0.6, so you might trying upgrading the version of Pact-JVM

**Comment by tainguyenvn** [comment]
@uglyog Thank you for your update.
However, I have been writing Pacts on framework JUnit version 3.6.11.

Build.gradle:
- Consumer side:
dependencies {
testCompile 'au.com.dius:pact-jvm-consumer-junit_2.12:3.6.11'
}

- Provider side:
dependencies {
compile 'au.com.dius:pact-jvm-provider-junit_2.12:3.6.11'
}

If I change to version 4.0.7 like:
Consumer side: testCompile 'au.com.dius:pact-jvm-consumer-junit:4.0.7'
Provider side: compile 'au.com.dius:pact-jvm-provider-junit: 4.0.7'

Many annotations, methods  in Consumer side are unknown. It appears all pacts must be updated too. 

Could you please help to make update on version JUnit 3.6.11

Thanks again

**Comment by tainguyenvn** [comment]
@uglyog Could you refer the Pact file mentioned in the comment above to fix this issue?

Thanks

**Comment by uglyog** [comment]
Ah, the issue is with the generators and not the body!

**Comment by uglyog** [comment]
@tainguyenvn you should not be using the generator to replace the entire body, just the fields that correspond to value that need to change, i.e.,

```json
"generators": {
          "body": {
            "$.entityName": {
              "type": "ProviderState",
              "expression": "${eName}"
            }
     }
}
```
How was this pact file created?

**Comment by tainguyenvn** [comment]
@uglyog From what I understood, we can only use generator to replace to fields in the RESPONSE BODY by using .valueFromProviderState method. (Refer to this page: https://github.com/DiUS/pact-jvm/tree/master/consumer/pact-jvm-consumer-junit)

But now I want to replace fields in the REQUEST body in JSON format. Could you please share me a piece of codes to create the such pact file as you said. 
My dependency:

dependencies {
testCompile 'au.com.dius:pact-jvm-consumer-junit_2.12:3.6.11'
}

**Comment by uglyog** [comment]
That's not true, you replace fields in the request body. The response is what is then compared to the expected body.

**Comment by tainguyenvn** [comment]
> That's not true, you replace fields in the request body. The response is what is then compared to the expected body.

Hi @uglyog 

So could you give me an sample code to replace fields in the request body using pact-jvm-consumer-junit_2.12:3.6.11?

Thanks

**Comment by uglyog** [comment]
This is the only example I could find: https://github.com/DiUS/pact-jvm/blob/71014f639a47d810c851b6a087139e7d0de3e38e/consumer/pact-jvm-consumer-junit5/src/test/groovy/au/com/dius/pact/consumer/junit5/ProviderStateInjectedPactTest.groovy#L35

**Comment by tainguyenvn** [comment]
> This is the only example I could find:
> 
> https://github.com/DiUS/pact-jvm/blob/71014f639a47d810c851b6a087139e7d0de3e38e/consumer/pact-jvm-consumer-junit5/src/test/groovy/au/com/dius/pact/consumer/junit5/ProviderStateInjectedPactTest.groovy#L35

@uglyog This example is used to verify the expected results in the response body. 

However I want to replace the fields in the request body. It appears that the current framework does not support that. Should I create a ticket for this? 

Thanks

**Comment by uglyog** [comment]
The body can be applied to both the request and the response

**Comment by tainguyenvn** [comment]
Got it. It works for me. Thanks so much
