### ISSUE TITLE
Deferred PactRunner initialization causes JUnit 4.13 to not pick up any pacts

### ISSUE THREAD

**Issue by mikahjc** [DiUS/pact-jvm#1035]
The changes from #1021 are causing the test runner to not have any children when `getFilteredChildren()` in JUnit is called when the runner is configured by JUnit. `getFilteredChildren()` does a one-time initialization of the `filteredChildren` field, but gets called before `PactRunner.run()` does. I'm seeing this with the Maven Surefire plugin and with IntelliJ's JUnit runner on JUnit 4.13. JUnit 4.12 doesn't exhibit this behavior because of a change in the `getFilteredChildren()` method.

One solution is to call `initialize()` when `getChildren()` is called, but that may counteract the changes in #1020/#1021.

**Comment by uglyog** [comment]
@mikahjc it looks like this issue is not related to the deferred initialisation change, but rather changes to the JUnit 4.13 TestClass which is used to get the annotations on the test class.

**Comment by uglyog** [comment]
Version 4.0.7 has been released with this change

**Comment by mikahjc** [comment]
4.0.7 appears to have resolved the issue.
