### ISSUE TITLE
Pact MismatchException when trying to create contract file for a POST request

### ISSUE THREAD

**Issue by reemadhiman92** [DiUS/pact-jvm#1038]
Hello,
I am trying to create a contract file for a POST request.
But i am getting following error : - (PactMismatchException)
<img width="704" alt="Capture" src="https://user-images.githubusercontent.com/51132417/75785176-99b2d180-5d63-11ea-8665-4064e2393c58.PNG">

This works fine for the GET request. Can anyone please help with this ??
This is my code -

 @Rule
	    public PactProviderRuleMk2 provider = new PactProviderRuleMk2("ResponseDataProvider", "localhost", 8082, this); //create this rule with mocked server
	 @Pact(consumer = "ResponsedataConsumer")
	    public RequestResponsePact createPact(PactDslWithProvider builder) {
	        Map<String, String> headers = new HashMap();
	       headers.put("Authorization", "ECommerceDistributedAPIKey");
	       headers.put("X-Source", "AB");
	        headers.put("Content-Type", "application/json");
	        
	        Map<String, String> header1 = new HashMap();
		        headers.put("Content-Type", "application/json");
	       

	        return builder
	                .given("Test Post")
	                .uponReceiving("Post Request")
	                .path("/api/ECommerceDistributed/api/v1/collectionpoints")
	                .query("countryisoCode=SE&postalCode=41326&city=.&streetAddress=.&maxCollectionPoints=12&networks=instabox_SE")
	                .method("POST")
	                .headers(headers)
	         
	                 .body("{\r\n" + 
	                		"            \"dimensions\": [{\r\n" + 
	                		"                    \"dimension\": [{\r\n" + 
	                		"                            \"height\": 1.1,\r\n" + 
	                		"                            \"length\": 1.1,\r\n" + 
	                		"                            \"weight\": 1.1,\r\n" + 
	                		"                            \"width\": 1.1\r\n" + 
	                		"                        }\r\n" + 
	                		"                    ]\r\n" + 
	                		"                }\r\n" + 
	                		"            ],\r\n" + 
	                		"            \"lengthUom\": \"METER\",\r\n" + 
	                		"            \"quantity\": 1,\r\n" + 
	                		"            \"productId\": \"ART120006905\",\r\n" + 
	                		"            \"weightUom\": \"KG\"\r\n" + 
	                		"        }\r\n" + 
	                		"  ") 
	               
	                .willRespondWith()
	                .status(200)
	               .headers(headers)
	                .body("{\r\n" + 
	                		"\"id\": \"Course3\",\r\n" + 
	                		"\"name\": \"Spring Boot\",\r\n" + 
	                		"\"description\": \"6K Students\",\r\n" + 
	                		"\"steps\": [\r\n" + 
	                		"\"Learn Maven\",\r\n" + 
	                		"\"Learn Spring\",\r\n" + 
	                		"\"Learn Spring MVC\",\r\n" + 
	                		"\"First Example\",\r\n" + 
	                		"\"Second Example\"\r\n" + 
	                		"]\r\n" + 
	                		"}")

**Comment by uglyog** [comment]
I'm assuming your resolved your issue?

**Comment by reemadhiman92** [comment]
Yes ,I figured it out.
 Thank you so much for replying  :)
