### ISSUE TITLE
'Template Objects' in PactDslJsonBoday and PactDslJsonArray

### ISSUE THREAD

**Issue by jamessawle** [DiUS/pact-jvm#104]
Currently, each Pact must explicitly define each part of its expected response. Whilst this gives clarity on exactly what is expected, this can make them difficult to read when there are repeated Objects in a response, or even across responses. Especially when one of the 'template objects' has 30 fields and nested arrays as well'

As such it would be nice to make the protected 'putObject' methods public on both the PactDslJsonBody and the PactDslJsonArray. On the array, it would also be beneficial to be able to have a second wrapper method that allowed for the object to be added n times.

Any ideas would be much appreciated, and I will prepare a pull request.

**Comment by uglyog** [comment]
Closing, as pull request was merged
