### ISSUE TITLE
Help with verifying Pact with real provider. Getting 400 error while running provider side test.

### ISSUE THREAD

**Issue by reemadhiman92** [DiUS/pact-jvm#1040]
Help with verifying Pact with real provider. Getting 400 error while running provider side test.
This is my test - 

@RunWith(PactRunner.class) // Say JUnit to run tests with custom Runner
@Provider("ResponsedataProvider")  // Set up name of tested provider

@PactFolder("C:\\Users\\test\\eclipse-workspace\\com.ISC.demo\\target\\pacts")    //location from where to pick up pact file from

    @State("Test Post") 
    public void hammerSmith() {
        System.out.println("Request to get response" );
    }

    @TestTarget // Annotation denotes Target that will be used for tests

   public final Target target = new HttpTarget("https", "test.centiro.com", 443 , "/api/ECommerceDistributed/api/v1/collectionpoints?countryisoCode=SE&postalCode=41326&city=.&streetAddress=.&maxCollectionPoints=12&networks=instabox_SE");

}

I am getting 400 response when i run this , the request is working i tried with postman. Not sure how to proceed further. Any help would be really appreciated.
Thanks

**Comment by uglyog** [comment]
You're passing the pull path with the query parameters to the HttpTarget. That field is meant for providers where they are mounted on a path, and combines with the path from the pact file. Query parametrers should not be supplied there.
