### ISSUE TITLE
pact-jvm-consumer-junit README references nonexistent classes

### ISSUE THREAD

**Issue by TomRK1089** [DiUS/pact-jvm#1056]
The README appears to be out of date for the Pact JUnit 4 project. It references nonexistent classes `ConsumerPactTestMk2` and `PactProviderRuleMk2`. These types are not found when I reference this library with Maven. I assume the correct types are the un-suffixed `ConsumerPactTest` and `PactProviderRule`.

**Comment by uglyog** [comment]
Ah, yeah, those are the old 3.x classes.
