### ISSUE TITLE
Template method within PactDslJsonArray not generating matchers within an array

### ISSUE THREAD

**Issue by jamessawle** [DiUS/pact-jvm#106]
The new 'template' methods on PactDslJsonArray are not placing the matchers within an array (sorry for that), causing Pacts not to match.

Will have a look tonight to see if I can come up with a quick fix for this; but may need some help :s

**Comment by uglyog** [comment]
oh, yeah. Oops. Sorry, forgot about the matchers.

**Comment by jamessawle** [comment]
Thanks, the fix solves the issue. Can not wait to simplify our CDC generation code with the next release :D
