### ISSUE TITLE
valueFromProviderState method cannot verify values in number type

### ISSUE THREAD

**Issue by tainguyenvn** [DiUS/pact-jvm#1061]
```java
.body(new PactDslJsonBody()
     .valueFromProviderState("accountId", "${accountId}", 123))
```

```java
dependencies {
compile 'au.com.dius:pact-jvm-provider-junit_2.12:3.6.14'
}

```
In fact, the data type of "accountId" is number, but values injected from the provider states are parsed as an expression, which will always be a string. So the pact verification always fails.

Please help to update framework verify values in number type.
Thanks

**Comment by uglyog** [comment]
If you don't use an expression, it will use the raw value from the state change callback. I.e.,

```java
.body(new PactDslJsonBody()
     .valueFromProviderState("accountId", "accountId", 123))
```

**Comment by uglyog** [comment]
Version 4.0.9 should now work as expected

**Comment by tainguyenvn** [comment]
@uglyog Is there any way to fix in branch of 3.6.14 because my pacts were created in that version? Thanks so much

**Comment by uglyog** [comment]
3.6.15 has been released

**Comment by tainguyenvn** [comment]
Thanks so much @uglyog
