### ISSUE TITLE
Pact provider verify fails with au.com.dius.pact.core.model.messaging.Message cannot be cast to au.com.dius.pact.core.model.RequestResponseInteraction

### ISSUE THREAD

**Issue by anacrbraganca** [DiUS/pact-jvm#1065]
Using pact-jvm-provider-gradle, even though the verification is successful and the pacts are also published successfully, the pactVerify task is breaking with message: **au.com.dius.pact.core.model.messaging.Message cannot be cast to au.com.dius.pact.core.model.RequestResponseInteraction**. 

Pact JVM Provider version: 'au.com.dius:pact-jvm-provider-gradle:4.0.0'

**Comment by uglyog** [comment]
I think this has been fixed in a later version. Can you try with the latest 4.0.9?

**Comment by anacrbraganca** [comment]
You're right @uglyog :) 4.0.9 version worked for me. Thank you!
