### ISSUE TITLE
pact-jvm-provider-junit5-spring MockMvcTestTarget

### ISSUE THREAD

**Issue by BramVanImpe** [DiUS/pact-jvm#1072]
Hi,

first of all, excuse me if this is not the right place to ask a question. I'll be happy to post it somewhere else if needed.

The documentation of the "pact-jvm-provider-junit5-spring" mentions that you can use the "MockMvcTestTarget" class in orde to verify contracts against a MockMvc environment.

This class doesn't seem to be included in the dependency however. Can you point me in the right direction?

Thanks a lot!

Best regards

**Comment by uglyog** [comment]
This hasn't been released yet, it will be in version 4.0.10 which should be out soon.

**Comment by BramVanImpe** [comment]
Thanks, I'll use the Junit4 set-up until then.

**Comment by straurob** [comment]
Is there any update on this? I'm using the following dependency but it seems as if `MockMvcTestTarget` is still not available?

        <dependency>
            <groupId>au.com.dius.pact.provider</groupId>
            <artifactId>junit5</artifactId>
            <version>4.1.7</version>
        </dependency>

**Comment by uglyog** [comment]
@straurob all the spring classes are in `au.com.dius.pact.provider:spring`

**Comment by uglyog** [comment]
And `au.com.dius.pact.provider:junit5spring` for JUnit5 support.

**Comment by straurob** [comment]
Thanks a lot. It's working fine now :slightly_smiling_face:

**Comment by hairinwind** [comment]
It is now 2024. I am still looking for the answer. Thanks for this post. 
I just don't understand why the package information is not put in the web page. https://docs.pact.io/implementation_guides/jvm/provider/junit5spring
