### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by michaelbull** [DiUS/pact-jvm#1073]
Hi, I have noticed you are redistributing my [`kotlin-result`](https://github.com/michaelbull/kotlin-result) library in your [core](https://github.com/DiUS/pact-jvm/tree/master/core/support/src/main/kotlin/au/com/dius/pact/com/github/michaelbull/result) package. This is great and I'm thankful for your use of my library. 

The classes include a comment which links back to my repository, which is appreciated, however you are missing the [license file](https://github.com/michaelbull/kotlin-result/blob/master/LICENSE) that **must** appear in all copies.

Please can you either depend on this library explicitly from a repository such as [Maven Central](https://search.maven.org/search?q=g:com.michael-bull.kotlin-result) (to avoid shipping the source yourselves) or include the license? Thanks in advance.

**Comment by uglyog** [comment]
I have removed the in-lined version of your library.

**Comment by michaelbull** [comment]
That's fantastic, thanks for the cooperation!
