### ISSUE TITLE
When using valueFromProviderState within array, the generated index starts with -1

### ISSUE THREAD

**Issue by tainguyenvn** [DiUS/pact-jvm#1074]
I have a POST request to get status of the list of users as below:

.path("/userStatus")
.method(POST)

Body:
{
    "userIds":["id1", "id2"]
}

where id1, id2 are retrieved from provider states

I define the pact by using valueFromProviderState to inject values from provider state : 
.path("/userStatus")
.method(POST)
.body(new PactDslJsonBody()
        .array("userIds")
        .valueFromProviderState("${id1}","John")
        .valueFromProviderState("${id2}","Marry")
            .closeArray()
)

And Pact generated like:

"body": {
          "userIds": [
            "John",
            "Marry"
          ]
        },
        "generators": {
          "body": {
            "$.userIds[-1]": {
              "type": "ProviderState",
              "expression": "${id1}"
            },
            "$.userIds[0]": {
              "type": "ProviderState",
              "expression": "${id2}"
            }
          }
        }
		}

The index "-1" makes the pact Verification error. I tried updating the indexes to start with 0 manually and it works correctly. 

Please help to update the framework so that the index starts with 0 in this case. Thanks

I am using version 3.6.14

**Comment by uglyog** [comment]
3.6.15 has been released

**Comment by tainguyenvn** [comment]
Thanks @uglyog
