### ISSUE TITLE
Pact publish & verify failing with java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement

### ISSUE THREAD

**Issue by anacrbraganca** [DiUS/pact-jvm#1077]
I'm facing an issue when trying to Publish & Verify a pact using **MessagePactBuilder** and **MessagePact**. 
Looks like it's something related with **gson** version, but I already forced in the service to fetch the same version as used in Pact **(2.8.6)** and through gradlew dependencies task I can see that the correct version is being used. I tried with Pact versions **4.0.9** and **4.0.10**. Getting following error:

In publish: 
* What went wrong:
Execution failed for task ':pactPublish'.
> com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;

Stacktrace:
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;        
at au.com.dius.pact.core.pactbroker.PactBrokerClient.uploadPactFile(PactBrokerClient.kt:184)        
at au.com.dius.pact.provider.gradle.PactPublishTask$_publishPacts_closure1.doCall( PactPublishTask.groovy:60)        
at au.com.dius.pact.provider.gradle.PactPublishTask.publishPacts(PactPublishTask.groovy:50)       
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

In verify:
* What went wrong:
A problem occurred evaluating root project '{service name}'.
> com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;

Stacktrace:
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;        
at au.com.dius.pact.core.pactbroker.HalClient.handleHalResponse(HalClient.kt:320)        
at au.com.dius.pact.core.pactbroker.HalClient.getJson(HalClient.kt:312)        
at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:273)        
at au.com.dius.pact.core.pactbroker.HalClient.fetch(HalClient.kt:268)        
at au.com.dius.pact.core.pactbroker.HalClient.navigate(HalClient.kt:256)        
at au.com.dius.pact.core.pactbroker.PactBrokerClient.fetchConsumersWithSelectors(
PactBrokerClient.kt:140)      
at au.com.dius.pact.provider.ProviderInfo.hasPactsFromPactBrokerWithSelectors(ProviderInfo.kt:84)        
at au.com.dius.pact.provider.ProviderInfo.hasPactsFromPactBroker(ProviderInfo.kt:61)        
at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(
BeanDynamicObject.java:479)        
at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)        
at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)

**Comment by acarpe** [comment]
I resolved this exact problem moving the plugin's configuration in the root folder's build.gradle

**Comment by uglyog** [comment]
Could you let us know what version of Gradle you are using?

**Comment by anacrbraganca** [comment]
@uglyog the version of Gradle is 4.10.2

**Comment by anacrbraganca** [comment]
@acarpe moving pact plugin's configuration? You mean moving to before or after any task?

**Comment by acarpe** [comment]
my app is structured in this way:
```
+---my-app
|   +---my-app-domain
|   |   \---build.gradle
|   +---my-app-web
|   |   \---build.gradle
|   \---build.gradle
```
because all my contract tests are under `my-app-web` I initially placed all the dependencies and the plugin configuration under the my-app-web’s  build.gradle .
Than I thought… “I’m running gradle from the root folder… let me try to move only the plugin configuration on the root’s build.gradle … and it worked!

So in my `my-app\build.gradle` I have:
```
buildscript {
	ext {
		kotlinVersion = '1.3.70'
		pactVersion = '4.0.10'
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"
		classpath "au.com.dius:pact-jvm-provider-gradle:${pactVersion}"
	}
}

apply plugin: 'au.com.dius.pact'


group = 'it.my-app'

repositories {
	mavenCentral()
}
```

and in my `my-app\my-app-web\build.gradle` I have just:
```
pact {
    publish {
        pactDirectory = "$buildDir/pacts"
        pactBrokerUrl = 'https://my-pact-broker.host.com'
        pactBrokerUsername = 'my-broker-username'
        pactBrokerPassword = 'my-broker-password'
    }
}

dependencies {
    ...
    testImplementation group: 'au.com.dius', name: 'pact-jvm-provider-spring', version: "${pactVersion}"
    testImplementation group: 'au.com.dius', name: 'pact-jvm-consumer-junit', version: "${pactVersion}"
}
```

**Comment by anacrbraganca** [comment]
@acarpe thank you so much for the detailed explanation. In my case, the pact dependencies & plugin are already there in gradle root file :/ so it won't apply to me.

**Comment by anacrbraganca** [comment]
> @uglyog the version of Gradle is 4.10.2

Edit: I updated to Gradle 5.6.4 and still seeing the same error :/

**Comment by JoaoGFarias** [comment]
Maven 3.6.2 user here. Same problem.

I've found interesting that I couldn't see the Gson dependency on IntelliJ's project view. I've tried adding it to my dependencies (2.8.6 (latest) and 2.8.2 versions).

The problem continues. The weirdest part is that the downloaded JsonParser doesn't have the _parseString_ method, although [I can see it on Gson repo](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/JsonParser.java#L46).

My download .jar has this:

![image](https://user-images.githubusercontent.com/1585655/80584224-a5dca780-8a11-11ea-99f7-cbc98d6f1f19.png)

**Comment by uglyog** [comment]
@JoaoGFarias is the download jar in your Maven repository?

**Comment by kvakos** [comment]
@anacrbraganca try to use strict versio of com.google.code.gson:gson 
`testRuntimeOnly("com.google.code.gson:gson") { version { strictly("2.8.6") } }`

I had same issue this somehow fix gradle plugin problem.

**Comment by czterocyty** [comment]
Hi,

I've got the same problem with Gradle 6.4 and pact plugin 4.0.10.

Seems that `com.google.code.gson:gson:2.8.5` came with kotlin plugin and it was loaded first in my project:

```
+--- org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.3.72
|    \--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72
|         +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72
...
|         +--- com.google.code.gson:gson:2.8.5
|         \--- de.undercouch:gradle-download-task:4.0.2
```

I fixed `2.8.6` gson version in plugins' classpath and problem disappeared:

```
buildscript {
  classpath {
    classpath "com.google.code.gson:gson:2.8.6"
  }
}
```

For gson changes you can consult https://github.com/google/gson/blob/master/CHANGELOG.md#version-286

**Comment by anacrbraganca** [comment]
Hi @kvakos, @czterocyty thanks for the response and sorry for the delay!

@kvakos I've tried that approach, didn't work for me... In my project, I'm able to force the **Gson** version in this declarative way or overriding the resolution strategy and still I get the same error. @czterocyty tried that as well and didn't succeed.
I also tried to run verification in a container, just to exclude cache issues possibilities.
I tried to get some insights of Gson library inside pact-jvm as well and this is what I can see: 
<img width="616" alt="Screen Shot 2020-05-18 at 17 52 31" src="https://user-images.githubusercontent.com/5640676/82258959-2b78b680-9931-11ea-96e2-3c7adc173c5f.png">
<img width="602" alt="Screen Shot 2020-05-18 at 17 52 48" src="https://user-images.githubusercontent.com/5640676/82258974-316e9780-9931-11ea-9cc4-41367e0dc6c1.png">
It's a real weird issue (at least for me) because, when I debug the task, It shows me the correct version of com.google.gson.JsonParser class... but when I try to evaluate/execute the sentence (parseString()), it's when it's throwing the NoSuchMethod error.

**Comment by uglyog** [comment]
I have removed GSon as the JSON parser (as of version 4.1.0)

**Comment by JoaoGFarias** [comment]
Sorry for the late reply, I was able to solve the issue by updating Gson to 2.8.6, although not doing it would be secure for other services I work on.
@uglyog I see that Pact-JVM 4.1.0 is not on [MVN repository](https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer-junit). Is it normal to take a while for releasing it there?
Sorry my ignorance in the Pact release process to Maven.

**Comment by uglyog** [comment]
Version 4.1.0 has had the modules renamed. The new module is https://mvnrepository.com/artifact/au.com.dius.pact.consumer/junit

**Comment by johnboyer** [comment]
I'm having the same problem with `pact-jvm-provider-junit5` version `4.0.10`

```
java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseReader(Ljava/io/Reader;)Lcom/google/gson/JsonElement;

	at au.com.dius.pact.core.model.DefaultPactReader.loadPactFromFile(PactReader.kt:359)
	at au.com.dius.pact.core.model.DefaultPactReader.loadFile(PactReader.kt:326)
	at au.com.dius.pact.core.model.DefaultPactReader.loadPact(PactReader.kt:175)
	at au.com.dius.pact.core.model.DefaultPactReader.loadPact(PactReader.kt:172)
	at au.com.dius.pact.provider.junit.loader.PactFolderLoader.load(PactFolderLoader.kt:33)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.resolvePactSources(PactJUnit5VerificationProvider.kt:407)
	at au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider.provideTestTemplateInvocationContexts(PactJUnit5VerificationProvider.kt:373)
```
