### ISSUE TITLE
The issues on the Provider State are not reported

### ISSUE THREAD

**Issue by anddreiu** [DiUS/pact-jvm#1082]
Because of the nature of my project, I am doing some actions (some API calls) in the Provider State so that I can run then the Provider tests. One thing that I've noticed is the fact that if something goes wrong in the Provider State (for example, the response of the API call is not the expected one), this is not reflected in the report. The interaction that would use that Provider State will not be executed, so the interaction will not present in the report and might be missed when checking the results.

Could it be flagged that the Provider State failed, so the interaction was not executed?

Thanks

**Comment by uglyog** [comment]
How are you running the verification tests?

**Comment by anddreiu** [comment]
I verify pact with JUnit 4 tests. So I'm running the verification tests using `mvn clean test` and I specify the test suite which contains the pact tests.

**Comment by uglyog** [comment]
Do your provider state methods throw an exception when they fail?

**Comment by anddreiu** [comment]
Sorry for this late reply. In most of the cases the provider state methods throw an exception. In this case, the report will not contain that specific interaction.

**Comment by uglyog** [comment]
Are you referring to the JSON or Markdown report, or on the standard output? Or are you referring to the JUnit test report?

**Comment by anddreiu** [comment]
I am referring to the generated Pact reports: JSON and Markdown reports. If the provider state throw an exception, then the interactions itself is not run and won't be populated anything in the pact report.

**Comment by uglyog** [comment]
Ok, good, that should be easy to fix.

**Comment by uglyog** [comment]
4.1.1 has been released

**Comment by anddreiu** [comment]
Tested and confirmed that it works fine. Thanks!
