### ISSUE TITLE
JUnit5 alternative for @PactVerification(value = "method", fragment = "fragment")

### ISSUE THREAD

**Issue by eustimenko** [DiUS/pact-jvm#1084]
Is there any alternative for `@PactVerification` annotation in JUnit5 consumer? 
I need `fragment` parameter

I tried `@PactTestFor` annotation `pactMethod` parameter, but that does not help me

Junit4 code

```
@Pact(provider = "provider", consumer = "consumer")
public RequestResponsePact createPact(PactDslWithProvider builder) {

}

@Test
@PactVerification(value = "provider", fragment = "createPact")
public void test() {
}
```

**Comment by wesleythomaswilliams** [comment]
Are you looking for:

`@PactTestFor(pactMethod = "fragment_name")`
