### ISSUE TITLE
tag not printed out in junit output for provider tests

### ISSUE THREAD

**Issue by anto-ac** [DiUS/pact-jvm#1097]
This was meant to have been introduced with https://github.com/DiUS/pact-jvm/pull/999, but it's not working.

**Comment by anto-ac** [comment]
@aplsup, I think you had an idea of what was wrong here.

**Comment by uglyog** [comment]
I think you need to raise this as an issue against the Pact Broker project. The new endpoint being used takes all the tags as parameters (called selectors), and then returns a list of matching pacts. But it does not provide any details about which tag is for which pact.

The other option is to print out all the selectors used.

**Comment by anto-ac** [comment]
I don’t think this ever actually work, even before any new endpoint was used. 

The use case is, by the way, that we’d like to see in the output which tag or tags we failed to verify for each test.

**Comment by uglyog** [comment]
It does display the notices from the Broker in standard output, which includes the tags:

```
Verifying a pact between Foo Web Client and Activity Service

  Notices:
    1) The pact at https://test.pact.dius.com.au/pacts/provider/Activity%20Service/consumer/Foo%20Web%20Client/pact-version/384826ff3a2856e28dfae553efab302863dcd727 is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'test'
    2) This pact has previously been successfully verified by a version of Activity Service with tag 'master'. If this verification fails, it will fail the build. Read more at https://pact.io/pending
```

**Comment by anto-ac** [comment]
I don't see that in the junit output when tests are failing, which makes it difficult to understand what's going on when more than one tag is verified.

**Comment by anto-ac** [comment]
@aplsup is working on this but struggling to install the package locally
