### ISSUE TITLE
Are JDK11, SpringBoot 2.+ fully implemented

### ISSUE THREAD

**Issue by ribmanthey** [DiUS/pact-jvm#1100]
Hi

I'm updating a project we have to JDK11.  It utilises pact.  I'm now working through lifting the JDK8 dependencies, so far as JDK9 modules is concerned, now mandatory for JDK11.

I find that pact is introducing SpringBoot 1.5 into the transitive dependencies (and 1.5 lacks JDK9 "module" definitions - ie: module-info.java

Plus the java versions are limited to 1.8 in the build.gradle files in pact, here: https://github.com/DiUS/pact-jvm/blob/master/build.gradle lines 34-35,85

Also if I search for module-info.java using the File Finder tool in github, it's not apparent.

Can you confirm whether this is a known issue, unknown or a known red-herring?

Thanks
Rob

**Comment by uglyog** [comment]
Pact-JVM doesn't include SpringBoot as a dependency, only the Spring module. You should be able to exclude that version if you are using a later version of Springboot.

It doesn't have any module definitions, but does have the `Automatic-Module-Name` entry in the manifest files. The build limits the compiled files to 1.8, but it will run on all versions up to 14. The Travis CI build for the project runs JDK 8-13, and I dev with JDK 12, so it will definitely work with 11.

**Comment by ribmanthey** [comment]
Hm.  To add some flesh, this is what I can see in my IntelliJ Gradle panel, hence my comments ...

![image](https://user-images.githubusercontent.com/1704497/82869944-74a0ba00-9f72-11ea-83db-a58113e76e8f.png)
As always gentle corrections are a delight to the mind.  Fire away ...

**Comment by uglyog** [comment]
Sorry, I meant the pact-jvm-provider-spring module. Just exclude the dependency from that module.

**Comment by ribmanthey** [comment]
Ok.  I'll try that Thursday and report back.
Thanks for the quick reply.

**Comment by ribmanthey** [comment]
To close this out, I used this solution, introduced in Gradle 6.4:  https://docs.gradle.org/6.4/samples/sample_java_modules_multi_project.html
`    plugins.withType(JavaPlugin).configureEach {
        java {
            modularity.inferModulePath = true
        }
    }` 
This covers off for pre-Java9 libraries that are ignorant of modules.
