### ISSUE TITLE
Micronaut and Provider Pact Verification

### ISSUE THREAD

**Issue by chuckleslord** [DiUS/pact-jvm#1106]
I've run into a bit of an issue and haven't found anywhere on StackOverflow, etc. where anyone has a solution.

I'm running a micronaut provider with Jwt Secured endpoints. I've got the pact verification test to work up till the JWT header comes up. The TargetRequestFilter isn't being hit. Here is the code I'm working with:

```
@PactFolder("pacts")
@MicronautTest
@Provider("some-service")
public class ITRestContractBaseSpec {

    @Inject
    EmbeddedServer server;

    @BeforeEach
    void setupTestTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget(server.getHost(), server.getPort()));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @TargetRequestFilter
    public void exampleRequestFilter(HttpRequest request) {
        //TODO: Add JwtToken header here
	log.info("THIS IS NEVER HIT");
    }

    @State("Body is Valid.")
    public void bodyIsValid() {
    }
}
```

To clarify, this spins up, and the pact hits the endpoint, but won't hit inside of the TargetRequestFilter. When I try to use PactRunner, it won't run with the Micronaut EmbeddedServer. Is there a known workaround or a MicronautPactRunner available? Or is this bunk?

**Comment by uglyog** [comment]
With JUnit 5, you don't need the `@TargetRequestFilter`, you can just inject the request into your test methods. Something like:

```
    @BeforeEach
    void setupTestTarget(PactVerificationContext context, HttpRequest request) {
        context.setTarget(new HttpTestTarget(server.getHost(), server.getPort()));

        //TODO: Add JwtToken header here
    }
```

**Comment by akashagarwal7** [comment]
> With JUnit 5, you don't need the `@TargetRequestFilter`, you can just inject the request into your test methods. Something like:

@uglyog would you be able to advice upon how would someone go about resolving the `HttpRequest` param using Springboot with junit5? 

I also can't find which package does the `HttpRequest` class belong to and there are multiple candidates for the same.

**Comment by akashagarwal7** [comment]
> With JUnit 5, you don't need the `@TargetRequestFilter`, you can just inject the request into your test methods. Something like:
> 
> ```
>     @BeforeEach
>     void setupTestTarget(PactVerificationContext context, HttpRequest request) {
>         context.setTarget(new HttpTestTarget(server.getHost(), server.getPort()));
> 
>         //TODO: Add JwtToken header here
>     }
> ```

This (at least now) needs to be done using `@TestTemplate` annotation instead of `@BeforeEach`.

**Comment by uglyog** [comment]
Yes, you are correct. The test target needs to be setup in the before, so Pact knows to create a request for the test. That can then be injected into the main test function.
