### ISSUE TITLE
Unable to format ZonedDateTime

### ISSUE THREAD

**Issue by s1apped** [DiUS/pact-jvm#1107]
Hi,

There is an issue with ISO_ZONED_DATE_TIME  format e.g `2020-01-01T10:00+01:00[Europe/Warsaw]` using `LambdaDslObject date`.

`au.com.dius.pact.consumer.MockServer)]: Illegal pattern component: V`

`body.date("date", "yyyy-MM-dd'T'HH:mmZZZV", ZonedDateTime.parse("2020-01-01T10:00+01:00[Europe/Warsaw]"));`

Looks like the problem is that Pact is using FastDateFormat which seems to be based of SimpleDateFormat. The solution would be to move to DateTimeFormatter

**Comment by uglyog** [comment]
I've updated the datetime methods to use Java DateTimeFormatter. The expression to match that value will now have to be `yyyy-MM-dd'T'HH:mmXXX'['VV']'`.

BTW, `date` was the wrong method to use. It should have been `timestamp` which I have now renamed to `datetime`.

**Comment by uglyog** [comment]
4.1.1 has been released

**Comment by anto-ac** [comment]
@uglyog the new test you've added is failing when building on my machine.
![image (3)](https://user-images.githubusercontent.com/30859172/84175020-472a3500-aa77-11ea-80c2-464eb27ef24d.png)

**Comment by anto-ac** [comment]
can we close this?

**Comment by anto-ac** [comment]
This was fixed and backwards compatibility with previously working date formats is guaranteed, at least for now.
