### ISSUE TITLE
pact-jvm-consumer-junit: type matcher does exact match?

### ISSUE THREAD

**Issue by peterlitvak** [DiUS/pact-jvm#111]
I have the following matching rules:
```
"body" : {
        "addresses" : [ {
          "someProp" : "wyVAbWfGtKzMYodnbmid"
        }, {
          "someProp" : "gDhgtTvKZqAeZfqIOgUA"
        }, {
          "someProp" : "hzbPMFEBosihlNvNTgsU"
        } ],
        "name" : "ggncZxASEudXfuslkZGI"
      },
      "responseMatchingRules" : {
        "$.body.addresses[1].someProp" : {
          "match" : "type"
        },
        "$.body.addresses[0].someProp" : {
          "match" : "type"
        },
        "$.body.name" : {
          "match" : "type"
        },
        "$.body.addresses[2].someProp" : {
          "match" : "type"
        }
      }
```
And expect them to match the following response:
```
{"name":"name1","addresses":[{"someProp":"p1"},{"someProp":"p2"},{"someProp":"p3"}]}
```
but instead get a matcher error:
```
 Diff:

 @3
         {
 -            "someProp": "wyVAbWfGtKzMYodnbmid"
 +            "someProp": "p1"
         },

 @6
         {
 -            "someProp": "gDhgtTvKZqAeZfqIOgUA"
 +            "someProp": "p2"
         },

 @9
         {
 -            "someProp": "hzbPMFEBosihlNvNTgsU"
 +            "someProp": "p3"
         }

 @12
     ],
 -    "name": "ggncZxASEudXfuslkZGI"
 +    "name": "name1"
 }
```
I was under impression that "type" match means that value of the property is not important only the type is.

**Comment by peterlitvak** [comment]
Clarification: The name, although mentioned in diff, is correctly matched by type, only the array elements are matched exactly.

**Comment by jamessawle** [comment]
My team had this issue when the contract was pact 2.12 and the verification was 2.11, ensuring both were the same version solved it. This has not been an issue with 2.12 and 2.13.

**Comment by uglyog** [comment]
There was a change in version 2.1.12 to use square brackets for array indices to bring it in line with the other pact implementations. See https://github.com/DiUS/pact-jvm/releases/tag/2_1_12 

As per @jamessawle comment, check that all your versions are the same.

**Comment by peterlitvak** [comment]
I'm using gradle so the consumer dependency is:
```
compile('au.com.dius:pact-jvm-consumer-junit_2.11:2.1.13')
```
And for the provider test (gradle 2.2) I'm using the following plugin setting:
```
plugins {
    id "au.com.dius.pact" version "2.1.1"
}
```
And getting this error. Is there a different version of the plugin that I should use?

**Comment by peterlitvak** [comment]
Ok, seems to work with x.10 the way I expected to, there are errors with x.12 and x.13 with state change settings which I'll post separately.
Thank you for your help.
