### ISSUE TITLE
Provider 4.1.0 verifies only first tag from the list

### ISSUE THREAD

**Issue by s1apped** [DiUS/pact-jvm#1113]
Hi,

I have updated to latest provider 4.1.0 and looks like it broke verification for multiple tags.
```
'au.com.dius.pact.provider:junit5:4.1.0'
'au.com.dius.pact.provider:spring:4.1.0'
'au.com.dius.pact.provider:junit5spring:4.1.0'
```
When there is more then one tag e.g `systemProperty 'pactbroker.tags', 'dev,master'` then only first seems to be verified. Please see below examples where `dev` tagged contract has 2 interactions and `master` 1.
**provider 4.0.10:**
![4 0 10](https://user-images.githubusercontent.com/32245059/83750998-6df6fe80-a666-11ea-9813-221772481b0e.png)
**provider 4.1.0:**
Only `dev` tag is verified
![4 1 0](https://user-images.githubusercontent.com/32245059/83751236-c928f100-a666-11ea-9aa9-34ef0781ec8e.png)

Not sure if it's related to **Bug** https://github.com/DiUS/pact-jvm/issues/1086

**Comment by anto-ac** [comment]
This is stopping us from upgrading to 4.1.+ and make use of the much improved test output.

**Comment by pkuras** [comment]
It seems like the issue is caused by a call to `.first()` on this line: https://github.com/DiUS/pact-jvm/blob/master/core/pactbroker/src/main/kotlin/au/com/dius/pact/core/pactbroker/PactBrokerClient.kt#L195

**Comment by anto-ac** [comment]
I've attempted putting together a fix, but I might be on the wrong track.
https://github.com/anto-ac/pact-jvm/pull/1

@uglyog What do you think?

**Comment by anto-ac** [comment]
@s1apped I've created a PR to fix this.
