### ISSUE TITLE
@TargetRequestFilter is not invoked with Junit5

### ISSUE THREAD

**Issue by sathesherode** [DiUS/pact-jvm#1115]
I have the below code to add authentication to request header but it is not getting called.
```
    @TargetRequestFilter
    public void requestFilter(MockHttpServletRequestBuilder request) {
        request.header("username", "someuser");
        request.header("password", "somepassword");
    }
```

`@TargetRequestFilter` is invoked when using `@RunWith(SpringRestPactRunner.class)` but it is not called when using `Junit5 + @ExtendWith(SpringExtension.class)`.

**Comment by uglyog** [comment]
You don't need to use `@TargetRequestFilter` with JUnit 5, because you can just inject the request object into your methods. Just add it as a parameter to a `@BeforeEach` method or the `@TestTemplate` method.
