### ISSUE TITLE
Connection refused error : Pact Integration with Jbehave

### ISSUE THREAD

**Issue by Manoj0251** [DiUS/pact-jvm#1119]
Normally my pact tests are working fine, as we have multiple services and integrations we are trying to improve pact tests with integrating with jbehave and better reporting. I am getting the below error : 

"org.apache.http.conn.HttpHostConnectException: Connect to localhost:8082 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
	at org.apache.http.client.fluent.Request.execute(Request.java:177)"

Any suggestion where I am going wrong or how to solve the issue.

my pact Test : 

@PactVerification("xyz-provider")
    public void testDesignTimeModel() throws IOException
    {
        assertEquals(200, Request.Get("http://localhost:8082/xyz/v1/tenants/3fa85f64-5717-4562-b3fc-2c963f66afa6")
                                            .execute()  ----> this is where it fails 
                                            .returnResponse()
                                            .getStatusLine().getStatusCode());
    }

**Comment by Manoj0251** [comment]
I am creating an endpoint on localhost and verifying it, below is the complete code 
`
    @Test
    @PactVerification("XYZ-provider")
    public void testDesignTimeModel() throws IOException
    {
        assertEquals(200, Request.Get("http://localhost:8082/xyz/v1/tenants/3fa85f64-5717-4562-b3fc-2c963f66afa6").execute().returnResponse().getStatusLine().getStatusCode());
    }

    @Rule
    public PactProviderRule rule = new PactProviderRule("ETS-provider","localhost", 8082, PactSpecVersion.V1,this);
    private DslPart getDesignTimeModelBody;

    @Pact( provider = "XYZ-provider", consumer = "ABC-Consumer")
    public RequestResponsePact createPact(PactDslWithProvider builder)
    {
        getDesignTimeModelBody = new PactDslJsonBody()
                                    .booleanValue("autoProvision",true)
                                    .stringType("billingAddress")
                                    .stringType("city")
                                    .stringType("companyName")
                                    .stringType("companySize")
                                    .stringType("version")
                                    .stringType("zip");
    return builder
                .given("Get Tenant Usage ")
                .uponReceiving("Indicates request was successful and the policies are returned")
                .path("/xyz/v1/tenants/3fa85f64-5717-4562-b3fc-2c963f66afa6")
                .method("GET")
                .willRespondWith()
                .status(200)
                .headers(getHeaders())
                .body(getDesignTimeModelBody)
                .toPact();
    }

    public static Map<String, String> getHeaders()
    {
        Map<String, String> headers = MapUtils.putAll(new HashMap<String, String>(),
                new String[]{"Content-Type", "application/hal+json"});
        return headers;
    }`


it works as is now, but when I call the test using jbehave statements using given or when or then. it throws me connection refused.

Not sure where I am going wrong  or in what order I need to call so that my pact JSON will bs generated

**Comment by mefellows** [comment]
The test shown here is a JUnit test using Pact specific annotations - so it's possible that JBehave does not play nicely with Pact tests. Is there a reason why you're combining the two?

Pact is going to start up the service on port `8082` as you've specified, so when run through another framework those annotations may do nothing - hence why the server is not starting on port `8082`. I'm afraid this looks to be a JBehave specific issue.

**Comment by Manoj0251** [comment]
Thank you for the update.
Actually, I have multiple pact tests which I need them to run at once and generate the pact files.

**Comment by Manoj0251** [comment]
> The test shown here is a JUnit test using Pact specific annotations - so it's possible that JBehave does not play nicely with Pact tests. Is there a reason why you're combining the two?
> 
> Pact is going to start up the service on port `8082` as you've specified, so when run through another framework those annotations may do nothing - hence why the server is not starting on port `8082`. I'm afraid this looks to be a JBehave specific issue.

Thank you for the update.
Actually, I have multiple pact tests which I need them to run at once and generate the pact files.
And with some reporting

**Comment by mefellows** [comment]
> When running multiple pact tests which can generate a report for others to understand or categorizing them will be good and easy to understand

I'm sorry, I don't understand the question. What feature would you like to see and what is the current behaviour?

**Comment by Manoj0251** [comment]
I have multiple pact tests which cover different consumers and providers. I am able to run all the contract tests at once but there aren't any reports generated, all I am asking is doesn't pact provide any reporting mechanism?

**Comment by uglyog** [comment]
@Manoj0251 is supports generating test reports for verification in JSON and Markdown formats. These are configured either with the build tools (Maven or Gradle) or with annotations for JUnit. For example https://github.com/DiUS/pact-jvm/blob/master/provider/junit/README.md#verification-reports
