### ISSUE TITLE
Is "fuzzy"/partial match possible?

### ISSUE THREAD

**Issue by peterlitvak** [DiUS/pact-jvm#112]
Is there a way to to the fuzzy/partial match?
For example to verify that an array of any/certain size is returned by the provider regardless of its content.
Verify that a response object has at certain fields but the extra fields are Ok to be present in the response and ignored by matcher?

**Comment by bethesque** [comment]
We're working on it v2 of the pact specification. For example flexible
array matching: https://github.com/bethesque/pact-specification/issues/14
v2 will allow type based matching and regular expressions.

On Sat, Apr 11, 2015 at 5:59 AM, Peter Litvak <notifications@github.com>
wrote:

> Is there a way to to the fuzzy/partial match?
> For example to verify that an array of any/certain size is returned by the
> provider regardless of its content.
> Verify that a response object has at certain fields but the extra fields
> are Ok to be present in the response and ignored by matcher?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DiUS/pact-jvm/issues/112>.
>



-- 
Bethany Skurrie
Software Developer

DiUS Computing Pty. Ltd.


*where ideas are engineered *Phone: +61 3 9008 5400
Mobile: +61 415 413 713

www.dius.com.au

This email is intended solely for the use of the addressee and may contain
information that is confidential or privileged. If you receive this email
in error please notify the sender and delete the email immediately.

**Comment by uglyog** [comment]
Extra fields in the response are ignored. See https://github.com/bethesque/pact-specification#pact-specificaton-philosophy for the philosophy behind this.

**Comment by peterlitvak** [comment]
Thank you!
