### ISSUE TITLE
Content-Type header check is case sensitive

### ISSUE THREAD

**Issue by psfblair** [DiUS/pact-jvm#1121]
I was getting anomalous behavior where the Content-Type header wasn't matching; when I had the expected value as "application/json" it would tell me it was failing to match "application/json; charset=UTF-8" and when I expected the latter it would tell me it was failing to match the former. I finally discovered that there were two Content-[Tt]ype headers in the received request. 

It turns out that my client was sending only one Content-type header, but that there is a case-sensitive check in PactDslRequestWithPath in the body(DslPart) method which says that if the request headers do not contain the key "Content-Type" to add it. This is a case-sensitive match and results in two headers on the request if the client is sending the header with a different case.

**Comment by anto-ac** [comment]
Fixed in 4.1.2
