### ISSUE TITLE
Kotlin and usage of @PactVerifications

### ISSUE THREAD

**Issue by sab1l** [DiUS/pact-jvm#1126]
I tried to apply the following example in Kotlin [1], but I get a compilation syntax error `An annotation can't be used as the annotations argument` since Kotlin doesn't seem to support nested annotations.

If I work around I get a runtime exception [2] in case the following code is used:
```
    @Test
    @PactVerifications(
        PactVerification(value = [PROVIDER_NAME], fragment = "createPactList"),
        PactVerification(value = [PROVIDER_NAME], fragment = "createPactListEmpty")
    )
```

1: https://github.com/DiUS/pact-jvm/blob/09babcae993c628f2725c32c8b08b8d5ab3201ac/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderWithMultipleFragmentsTest.java#L99-L102
2:
```
java.lang.UnsupportedOperationException: Could not find method with @Pact for the provider MyService
	at au.com.dius.pact.consumer.BaseProviderRule.evaluatePactVerifications(BaseProviderRule.java:96)
```

**Comment by uglyog** [comment]
I was able to convert the test to Kotlin: https://github.com/DiUS/pact-jvm/blob/master/consumer/junit/src/test/kotlin/au/com/dius/pact/consumer/junit/pactproviderrule/PactProviderWithMultipleFragmentsKotlinTest.kt

**Comment by sab1l** [comment]
Great, many thanks for clarifying that one!
