### ISSUE TITLE
Pact file not generated------au.com.dius.pact.consumer.PactMismatchesException:

### ISSUE THREAD

**Issue by Sridhar1974** [DiUS/pact-jvm#1129]
in target folder expect for pact file i can see all oder files

package nl.ing.closeaccount.integration.service;

import au.com.dius.pact.consumer.dsl.PactDslJsonBody;
import au.com.dius.pact.consumer.dsl.PactDslWithProvider;
import au.com.dius.pact.consumer.junit.PactProviderRule;
import au.com.dius.pact.consumer.junit.PactVerification;
import au.com.dius.pact.core.model.RequestResponsePact;
import au.com.dius.pact.core.model.annotations.Pact;
import au.com.dius.pact.core.model.annotations.PactFolder;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ing.api.toolkit.http.filter.Peer2PeerTrustFilter;
import com.ing.api.trust.jwt.p2p.PeerToPeerTrustTokenBuilder;
import com.ing.bakercatalogue.util.spring.HttpUtils;
import junit.framework.Assert;
import nl.ing.riaf.core.RIAFBaseApplication;
import org.glassfish.jersey.servlet.WebConfig;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.context.annotation.Bean;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.*;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class ClosePackagePact{

     @Rule
    public PactProviderRule mockProvider = new PactProviderRule("PackageManagementAPI", "localhost", 8080, this);

    @Pact(provider = "PackageManagementAPI", consumer = "pCloseAccountAPI")
    public RequestResponsePact createPact(PactDslWithProvider builder) {
        Map<String, String> headers = new HashMap<>();
        headers.put("X-ING-REQ-CTX", "P2P-token");
        headers.put("Content-Type", "application/json");
        headers.put("Accept", "application/json");
        headers.put("X-XSRF-TOKEN", "abcd");
        headers.put("Cookie", "XSRF-TOKEN=abcd");

        PactDslJsonBody requestBody = new PactDslJsonBody()
                .stringValue("accountNumber", "NL");

        PactDslJsonBody responseBody = new PactDslJsonBody()
                .stringValue("status", "Success")
                .uuid("internalRequestId");

        return builder
                .uponReceiving("Creating a new request for the PackageManagementAPI")
                .path("/api/packages/for-closing/")
                .method("POST")
                .body(requestBody)
                .headers(headers)
                .willRespondWith()
                .body(responseBody)
                .status(200)
                .toPact();
    }

    @Test
    @PactVerification

    public void test() throws IOException {

        Assert.assertTrue(true);
    }

![image](https://user-images.githubusercontent.com/61754761/84778345-7f45f080-b000-11ea-8b12-04f6e615567c.png)

![image](https://user-images.githubusercontent.com/61754761/84778330-77864c00-b000-11ea-9119-5acec78e0155.png)

**Comment by uglyog** [comment]
Your test is not doing anything.

```
public void test() throws IOException {
    Assert.assertTrue(true);
}
```

All it does is assert true. You should read though docs.pact.io to understand how Pact works.

If the mock server does not get the expected requests, it will fail the test and not write any Pact file out.

**Comment by Sridhar1974** [comment]
Thx you ver much...I am able to generate pact file.. one thing I  noticed is that at least one test verification should be there to check for any one inputs from pact file or else it will fail
