### ISSUE TITLE
Pact jvm introduces special character instead of dot in the path

### ISSUE THREAD

**Issue by DeepikaVJ** [DiUS/pact-jvm#1132]
I had a "path":"/some.random/api/get" while generating the pact received it as 
 "path": "/some╒random/api/get"
Pact was adding special characters instead of dot in the url 
Pact version I'm using is **au.com.dius.pact.consumer:junit5:4.1.0**

**Comment by mefellows** [comment]
Can you please provide a reproducable example of your issue? It's hard to work out from this report how Pact has done this.

**Comment by DeepikaVJ** [comment]
This was my pact setup


`
@Pact(consumer = “some_consumer”)
fun createCustomerSearchPact(pactDslWithProvider: PactDslWithProvider): RequestResponsePact? {
    return pactDslWithProvider
        .given("I have a search term to search an item”)
        .uponReceiving("a request for item search ")
        .matchPath(“/some.item/api”)
        .method("POST")
        .matchHeader("Content-Type", "application/json;charset=utf-8")
        .matchHeader("accept", "application/json;charset=utf-8")
        .body(itemPayload)
        .willRespondWith()
        .status(200)
        .body(itemResponse)
        .toPact()

`

Generated pact
`

{
  "provider": {
    "name": "CustomerProvider"
  },
  "consumer": {
    "name": "some_consumer"
  },
  "interactions": [
    {
      "description": "I have a search term to search an item ",
      "request": {
        "method": "POST",
        "path": “/some料ritem/api/item”,
        "headers": {
          "Content-Type": "application/json;charset=utf-8",
          "accept": "application/json;charset=utf-8"
        },
        "matchingRules": {
          "path": {
            "matchers": [
              {
                "match": "regex",
                "regex": “/some.item/api”
              }
            ],
            "combine": "AND"
          },
          "header": {
            "Content-Type": {
              "matchers": [
                {
                  "match": "regex",
                  "regex": "application/json;charset=utf-8"
                }
              ],
              "combine": "AND"
            },
            "accept": {
              "matchers": [
                {
                  "match": "regex",
                  "regex": "application/json;charset=utf-8"
                }
              ],
              "combine": "AND"
            }
          }
        }
      },
      "response": {
        "status": 200,
      },
      "providerStates": [
        {
          "name": "I have a search term to search an item"
        }
      ]
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "4.1.0"
    }
  }
}

`

When the pact is generated  "**.**"(/some.item/api) in the path is replaced by special character (/some料item/api),

**Comment by uglyog** [comment]
This is actually a feature. `matchPath` takes a regular expression, and with regular expressions, a period (`.`) means match any character. And as you have not provided an example path (the second parameter to `matchPath`), it's generating a random value from the the regular expression.

If you mean to have an actual period in the path, you need to escape it in the regular expression.

`.matchPath(“/some\\.item/api”)`

**Comment by uglyog** [comment]
If you mean to match any character at that position, provide an example value:
`.matchPath(“/some.item/api”, “/someXitem/api”)`

**Comment by uglyog** [comment]
If you don't want to actually match the path with a regular expression, then don't use the `matchPath` method, but use `path` instead which just takes a string value.

**Comment by DeepikaVJ** [comment]
Thanks that helped and worked by using path instead of matchPath
