### ISSUE TITLE
How to do a POST call by using Pact 

### ISSUE THREAD

**Issue by Dattasaisukumar** [DiUS/pact-jvm#1145]
Hi All
             I am trying to do a POST Call by using PACT. Below is how I wrote my code which is not working , can anyone please help me on how to do a POST call , I am not able to upload my GITHUB url . so copy pasting my code here 

@RunWith(SpringRunner.class)
@SpringBootTest
public class PactBaseConsumerTest extends ConsumerPactTest{
	@Autowired
	ProviderService providerService;
	@Override
	@Pact(provider="ProviderJson", consumer="ConsumerJson")
	public RequestResponsePact createPact(PactDslWithProvider builder) {
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("Content-Type", "application/json;charset=utf-8");
		return builder
		.given("example verification")
		.uponReceiving("request verification")
		.path("/comments")
		.method("POST")
		.headers(headers)
		.body("{\r\n" + 
				"    \"id\": 2,\r\n" + 
				"    \"body\": \"some comment\",\r\n" + 
				"    \"postId\": 2\r\n" + 
				"}")
		.willRespondWith()
		.headers(headers)
	    .toPact();
		}
	@Override
	protected String providerName() {
		return "ProviderJson";
		}
	@Override
	protected String consumerName() {
		return "ConsumerJson";
		}
	@Override
	protected void runTest(MockServer mockServer, PactTestExecutionContext context) {
		providerService.setBackendURL(mockServer.getUrl());
		Information information = providerService.getInformation();
		//assertEquals(information.getTitle(),"sunt aut facere repellat provident occaecati excepturi optio reprehenderit");
		}
}

**Comment by uglyog** [comment]
Is this doing a POST?
```
Information information = providerService.getInformation();
```
That looks like it would be doing a GET request.

**Comment by Dattasaisukumar** [comment]
Hi 
        Actually I have changed my code in restTemplate level. now I have one more Issue 
I am having two separate  maven  projects for Consumer side testing and Provider side Testing. In Provider side level we are using a class level annotation called @PactFolder() in which I am passing a Hardcoded value . Can you please let me know how we can pass values dynamically to it. I have Pact files in one Maven Project and I want to use that Pact folder path in Proivder side maven project

**Comment by Dattasaisukumar** [comment]
Hi 
      I got the Solution thankyou :)
