### ISSUE TITLE
Please add code examples for consumer version selectors docs in pact.docs.io

### ISSUE THREAD

**Issue by bethesque** [DiUS/pact-jvm#1149]
As part of the process of making the Pact docs more user friendly, we'd like to start writing feature documentation once, and providing code examples for each of the languages, rather than everyone having to write the same docs over and over again in each language.

The documentation for the consumer version selectors can be our first opportunity to give this approach a try. I have written the behavioural docs, but we need code examples from each of the languages. Can one of the maintainers of this repository (or any other Pact user of this language!) please add (via direct edit/PR as your permissions allow) code samples for the examples found here https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors#examples If you press the EDIT button, it will automatically fork and open a page to edit.

To add a new language, just add a comment with the name of the language (eg. ) and an example surrounded by "```".

If you would like to link to these docs in your own READMEs, please use the short link `https://docs.pact.io/consumer_version_selectors` (rather than the deep link into the broker section).

Thanks all!

**Comment by tinexw** [comment]
Hi,

the documentation seems to already contain Java examples (well, JUnit to be fair). The referenced class in them does not exist so I opened a small PR to fix that: https://github.com/pact-foundation/docs.pact.io/pull/37

Some features are currently not supported by JUnit so I was wondering to mention that in the docs? Otherwise I would suggest to close this ticket. Let me know what you think.

**Comment by uglyog** [comment]
@tinexw do you know which features are not supported? We should implement them, if that is the case.

**Comment by tinexw** [comment]
[In the docs](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/) three more examples are mentioned for Ruby and Java:

1. [Using a fallback tag for coordinated branch development](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/#using-a-fallback-tag-for-coordinated-branch-development) 
1. [Verifying a pacts where one consumer is a mobile application#](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/#using-a-fallback-tag-for-coordinated-branch-development)
1. [Verifying the overall latest pact for each consumer](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/#verifying-the-overall-latest-pact-for-each-consumer)

They map from what I can tell to the following features:

1. Support for `fallbackTag`
1. Support for `consumer`
1. Support only `latest` (without having to specify a tag)

If you can confirm that those are not supported I can create dedicated issues for each of them (and might start working on it ;-) )

**Comment by tinexw** [comment]
Actually, it’s not true what I wrote above. Only 1. is missing (fallback tag)
I will update the docs accordingly and create a new issue for the fallback tag in this repo.

**Comment by tinexw** [comment]
Actually, there already seems to be a ticket for the fallback tag: #946
Maybe you can change the description? Then we don't need to create a new one.

**Comment by uglyog** [comment]
Done: https://github.com/pact-foundation/docs.pact.io/commit/cbfb20fe608b39773c28ecea0ea0e7ac38663ebb
