### ISSUE TITLE
Gradle task pactPublish fails (400 bad request) and does not print error message

### ISSUE THREAD

**Issue by borwoj** [DiUS/pact-jvm#1150]
### Steps to reproduce

1. Write a JUnit 5 test
2. Run the test
3. A contract JSON file is created
4. Run `./gradlew pactPublish`

### Expected:

- If success: `201 Created`
- If error: a detailed error message is presented

### Actual:
```
> Task :pactPublish FAILED
PUT JSON request failed with status HTTP/1.1 400 Bad Request
Publishing 'Android App-Some Api.json' ... Failed

FAILURE: Build failed with an exception.

* What went wrong:
One or more of the pact files were rejected by the pact broker

```

However, publishing the exact same JSON to the exact same broker using cURL works just fine:
```
curl -X "PUT" "https://.../pacts/provider/Some%20Api/consumer/Android%20App/version/0.0.1
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{...}'

Response: 201 Created
```

### Configuration
`build.gradle` (app level)
```
pact {
  publish {
    pactDirectory = 'app/target/pacts'
    pactBrokerUrl = 'https://...'
    pactBrokerUsername = '' // no authentication
    pactBrokerPassword = '' // no authentication
  }
}
...
testImplementation 'au.com.dius:pact-jvm-consumer-junit5:4.0.10'
```
`build.gradle` (project level)
```
plugins {
  id "au.com.dius.pact" version "4.1.2"
}
```
Do you have an idea of what may be needed for the publish task to work?

An issue related to missing error messages: https://github.com/DiUS/pact-jvm/issues/291

**Comment by uglyog** [comment]
4.1.7 has been released with this fix

**Comment by borwoj** [comment]
4.1.7 solved the issue, thanks!
