### ISSUE TITLE
How can I suppress the provider's UserAgent

### ISSUE THREAD

**Issue by DerKnecht** [DiUS/pact-jvm#1161]
I have the following scenario:
My provider does react based on the User-Agent sent by the Consumer.
Now there is a special case where no User-Agent is sent.

The problem is:
This test fails on the Provider's side, because the UserAgent seems to be automatically set, if it's empty:
`2020-07-06T17:29:37,853 [main] DEBUG o.a.h.i.c.Wire http-outgoing-3 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_231)"`
This, of course, results in a test failure.

Is it somehow possible to force the Provider to set a specific user agent or suppress this behaviour?

**Comment by tinexw** [comment]
Hi @DerKnecht,

> My provider does react based on the User-Agent sent by the Consumer.
What exactly do you mean be react? Does it return a different format? Execute different functionality? Both?

Could you provide more details on the framework/technologies you use? Also, what does the pact file look like that you run the provider against? 

Using Spring Boot and Junit5 for example, the following interaction results in an empty `User-Agent` being passed:
```
    {
      "description": "A request for an existing user",
      "request": {
        "method": "GET",
        "path": "/users/1",
        "headers": {
          "User-Agent": ""
        }
      },
      "response": {
        "status": 200,
        "body": {}
      }
    }
```

**Comment by DerKnecht** [comment]
Am am working on a legacy project with java 1.8 and pact-jvm-provider-junit_2.12 version 3.6.11.
By "react" I mean that the provider will provide a different json response or http request depending on the UserAgent.
e.g.
- When the user agent cannot be parsed or is not given, the provider will return a 400 bad request
- When the user agent is correct, the version in the user agent is checked and a json will be responded which says if there is an update available or not
In most cases a json will be returned.

I think I will try to upgrade to a newer pact version and see if that fixes my problem.

**Comment by DerKnecht** [comment]
It seems like I had a bug in my test. I'm not sure how I fixed it, but now it works.
