### ISSUE TITLE
PactDslJsonBody is not allowing me to create an array without name 

### ISSUE THREAD

**Issue by Dattasaisukumar** [DiUS/pact-jvm#1163]
Hi 
       My Response body is like 
[
  {
    "id": 54365477,
    "name": "Wils",
    "phone": "+1-416-345-3456"
  }
]
I am trying to use PactDslJsonBody for response body like this 

.body(new PactDslJsonBody()
	                		.array()
	                		.object()
	                		.numberValue("id", 54365477)
	                		.closeObject()
	                		.closeArray()).toPact
It is showing error stating can not initiate PACT . 
Can you please tell me how can we do this ?

**Comment by anto-ac** [comment]
I think this will help you:

https://github.com/DiUS/pact-jvm/tree/master/consumer#root-level-arrays-that-match-all-items

For these questions, I'd recommend Slack, as you'd get a wider audience and often a quicker reply.

**Comment by Dattasaisukumar** [comment]
> I think this will help you:
> 
> https://github.com/DiUS/pact-jvm/tree/master/consumer#root-level-arrays-that-match-all-items
> 
> For these questions, I'd recommend Slack, as you'd get a wider audience and often a quicker reply.

Hi 
            I have texted in slack also :)
