### ISSUE TITLE
Verification results are published even though not all interactions were verified

### ISSUE THREAD

**Issue by tinexw** [DiUS/pact-jvm#1166]
When using JUnit 5 in combination with `@FilteredPact`, the verification results are **always** published even if not all interactions were verified. See also discussion in [this PR](https://github.com/DiUS/pact-jvm/pull/1165#issuecomment-656290908).

Right now to me it looks like this is just not implemented for JUnit 5. I will look into it.

**Comment by uglyog** [comment]
4.1.7 has been released
