### ISSUE TITLE
Matching working for x-www-form-urlencoded encoded bodies

### ISSUE THREAD

**Issue by ChuanChuanLaw** [DiUS/pact-jvm#118]
Hi,

I am using Groovy and need to post body in application/x-www-form-urlencoded format.

Can we please have matching working for  x-www-form-urlencoded encoded bodies?

Thanks.

Chuan

**Comment by bethesque** [comment]
We need some pact-specifications so it matches the Ruby impl.

**Comment by uglyog** [comment]
@bethesque does the ruby version handle form encoded bodies?

**Comment by bethesque** [comment]
Yup.
https://github.com/bethesque/pact-support/blob/master/lib/pact/shared/form_differ.rb
https://github.com/bethesque/pact-support/blob/master/spec/lib/pact/shared/form_differ_spec.rb


On Wed, May 13, 2015 at 7:39 PM, Ronald Holshausen <notifications@github.com
> wrote:

> @bethesque <https://github.com/bethesque> does the ruby version handle
> form encoded bodies?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DiUS/pact-jvm/issues/118#issuecomment-101594857>.
>



-- 
Bethany Skurrie
Software Developer

DiUS Computing Pty. Ltd.


*where ideas are engineered *Phone: +61 3 9008 5400
Mobile: +61 415 413 713

www.dius.com.au

This email is intended solely for the use of the addressee and may contain
information that is confidential or privileged. If you receive this email
in error please notify the sender and delete the email immediately.

**Comment by uglyog** [comment]
For context: https://groups.google.com/forum/#!topic/pact-support/OwatX-_LdKo

**Comment by uglyog** [comment]
URL encoded FORM POST requests now include the parameters in the body.
