### ISSUE TITLE
Kotlin dsl example of modifying request before verifying provider through gradle plugin

### ISSUE THREAD

**Issue by ashishkujoy** [DiUS/pact-jvm#1181]
Hi in [docs](https://github.com/DiUS/pact-jvm/tree/master/provider/gradle) under section `Modifying the requests before they are sent` it was mention we can modify request. I tried that in Kotlin build.gradle.kts 

```kotlin
pact {
    serviceProviders {
        register("SomeService-Provider") {
            protocol = "http"
            host = "localhost"
            port = "443"
            requestFilter = {req->
                req.addHeader('Authorization', 'OAUTH eyJhbGciOiJSUzI1NiIsImN0eSI6ImFw...')
            }
            hasPactsFromPactBroker(
                pactBrokerUrl = System.getenv("PACT_BROKER_BASE_URL")
            )
        }
```
On running gradle i am getting error with `cannot infer type of req`

Could you please provide me a working example for kotlin dsl

**Comment by Badya** [comment]
According to kotlin compiler msg: `cannot infer type of req`
You just need to specify `req` type explicitly:
```kotlin 
requestFilter = { req : HttpRequest ->
    req.addHeader('Authorization', 'OAUTH eyJhbGciOiJSUzI1NiIsImN0eSI6ImFw...')
}
```
