### ISSUE TITLE
Docs upgrade

### ISSUE THREAD

**Issue by elliottmurray** [DiUS/pact-jvm#1189]
Most of these are urls to github pages that won't resolve on Docosaurus. Also you have some relative paths (e.g. ../junit5) that are broken. In that case probably junit5 or /implementation_guides/jvm/provider/junit5.

Without spending some time looking at this I wasn't sure which ones were in github jvm and docs.pact.io

- Page path = /implementation_guides/jvm/consumer:
   -> link to /consumer/junit/src/test/java/au/com/dius/pact/consumer/junit/WildcardKeysTest.java

- Page path = /implementation_guides/jvm/consumer/groovy:
   -> link to /consumer/groovy/src/test/groovy/au/com/dius/pact/consumer/groovy/WildcardPactSpec.groovy
   -> link to ../../provider/gradle#publishing-pact-files-to-a-pact-broker (resolved as: /implementation_guides/provider/gradle)

- Page path = /implementation_guides/jvm/consumer/junit:
   -> link to src/test/java/au/com/dius/pact/consumer/examples/ExampleJavaConsumerPactRuleTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/examples/ExampleJavaConsumerPactRuleTest.java)
   -> link to src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactMultiProviderTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactMultiProviderTest.java)
   -> link to src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderHttpsTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderHttpsTest.java)
   -> link to src/test/java/org/apache/http/client/fluent/InsecureHttpsRequest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/org/apache/http/client/fluent/InsecureHttpsRequest.java)
   -> link to src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderHttpsKeystoreTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderHttpsKeystoreTest.java)
   -> link to src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderWithMultipleFragmentsTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderWithMultipleFragmentsTest.java)
   -> link to ../java8 (resolved as: /implementation_guides/jvm/java8)
   -> link to src/test/java/au/com/dius/pact/consumer/WildcardKeysTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/WildcardKeysTest.java)
   -> link to ../../provider/gradle#publishing-pact-files-to-a-pact-broker (resolved as: /implementation_guides/provider/gradle)
   -> link to src/test/java/au/com/dius/pact/consumer/junit/v3/ExampleMessageConsumerTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/junit/v3/ExampleMessageConsumerTest.java)

- Page path = /implementation_guides/jvm/consumer/junit5:
   -> link to src/test/java/au/com/dius/pact/consumer/junit5/ArticlesTest.java (resolved as: /implementation_guides/jvm/consumer/src/test/java/au/com/dius/pact/consumer/junit5/ArticlesTest.java)
   -> link to src/test/groovy/au/com/dius/pact/consumer/junit5/MultiTest.groovy (resolved as: /implementation_guides/jvm/consumer/src/test/groovy/au/com/dius/pact/consumer/junit5/MultiTest.groovy)

- Page path = /implementation_guides/jvm/provider/junit:
   -> link to src/test/java/au/com/dius/pact/provider/junit/StateAnnotationsOnInterfaceTest.java (resolved as: /implementation_guides/jvm/provider/src/test/java/au/com/dius/pact/provider/junit/StateAnnotationsOnInterfaceTest.java)
   -> link to ../spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java (resolved as: /implementation_guides/jvm/spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java)
   -> link to ../junit5#modifying-the-requests-before-they-are-sent (resolved as: /implementation_guides/jvm/junit5)

- Page path = /implementation_guides/jvm/provider/junit5:
   -> link to ../junit/ (resolved as: /implementation_guides/jvm/junit/)
   -> link to src/test/java/au/com/dius/pact/provider/junit5/StateAnnotationsOnAdditionalClassTest.java (resolved as: /implementation_guides/jvm/provider/src/test/java/au/com/dius/pact/provider/junit5/StateAnnotationsOnAdditionalClassTest.java)

- Page path = /implementation_guides/jvm/provider/junit5spring:
   -> link to ../junit5 (resolved as: /implementation_guides/jvm/junit5)

- Page path = /implementation_guides/jvm/provider/spring:
   -> link to ../junit (resolved as: /implementation_guides/jvm/junit)
   -> link to ../junit5 (resolved as: /implementation_guides/jvm/junit5)

- Page path = /implementation_guides/jvm/readme:
   -> link to consumer/junit/src/test/clojure/au/com/dius/pact/consumer/junit/example_clojure_consumer_pact_test.clj (resolved as: /implementation_guides/jvm/consumer/junit/src/test/clojure/au/com/dius/pact/consumer/junit/example_clojure_consumer_pact_test.clj)
   -> link to consumer/groovy/src/test/groovy/au/com/dius/pact/consumer/groovy/messaging/PactMessageBuilderSpec.groovy (resolved as: /implementation_guides/jvm/consumer/groovy/src/test/groovy/au/com/dius/pact/consumer/groovy/messaging/PactMessageBuilderSpec.groovy)

**Comment by tinexw** [comment]
@uglyog I was going to look into this but saw that you already made a commit a while back. Is this already resolved?

**Comment by uglyog** [comment]
@tinexw Yes, I updated all the items raised above. I hope I did not miss any, but I'll close this issue for now.
