### ISSUE TITLE
Gradle PactVerify: Provider bug of converting null to string

### ISSUE THREAD

**Issue by ChuanChuanLaw** [DiUS/pact-jvm#119]
Hi,

I have the following scenario:

The Actual JSON looks like:

"complete": {
"certificateUri": "http://storage.stg.livemarket.com.au/carfacts_certs/150513/abcrdu05.pdf",
"issues": {
"idNotFound": { }
},
"nevdis": {
"body": null,
"colour": null,
"engine": null,

My PACT file looks like this:

   "complete" : {
          "certificateUri" : "http://storage.stg.livemarket.com.au/carfacts_certs/150513/abcrdu05.pdf",
          "issues" : {
            "idNotFound" : { }
          },
          "nevdis" : {
            "body" : null,
            "colour" : null,
            "engine" : null,

But when I run gradle pactVerify, my test fails due to:

  $.body.complete.nevdis.body -> Expected 'null' but received null

   Diff:

   @9
           "nevdis": {
   -            "body": "null",
   +            "body": null,
               "colour": null,

The PACT file has "body" : null, but not sure why the Provider test output suggest that it is generated as "body" : "null". I am wondering is it because above "body" : null is an empty JSON structure like below?

"issues" : {
            "idNotFound" : { }
          },
 "nevdis" : {
            "body" : null,
            "colour" : null,
            "engine" : null,

Please advice.

Thank you very much.

Cheers,

Chuan

**Comment by uglyog** [comment]
This issue is now fixed in version 2.2.3
