### ISSUE TITLE
How to verify the timestamp where it's  Long value

### ISSUE THREAD

**Issue by stephenwang1011** [DiUS/pact-jvm#1195]
Here is the response, I want to verify this "timestamp", how can I do?
`timestamp()` 
timestamp function, I think cannot resolve my question.
![image](https://user-images.githubusercontent.com/3350356/91114909-91f13b80-e6bb-11ea-9492-07fb412668c8.png)

**Comment by stephenwang1011** [comment]
Now   I using numberType(name,Number) instead

**Comment by uglyog** [comment]
Closing this issue as `numberType` is the correct function to use.
