### ISSUE TITLE
Add ability to auto publish pact files to broker

### ISSUE THREAD

**Issue by ruairitobrien** [DiUS/pact-jvm#120]
Currently when generating a pact file, the step to publish that file to a broker is up to the developer. I use gradle for example an create a task to do it. 

It would be useful to have this functionality available in the library to avoid having users repeat this effort.

Ideally we could configure the broker URL and have an action available to publish a pact somewhere along the build pipeline.

My particular use case has been in gradle so writing a groovy plugin for it is very simple and I can provide that but perhaps a more generic solution for the entire pact-jvm can be investigated too.

**Comment by uglyog** [comment]
I've added a gradle task to publish all the pact files in a directory.
