### ISSUE TITLE
Pact file is not generated (Android, Gradle Wrapper)

### ISSUE THREAD

**Issue by borwoj** [DiUS/pact-jvm#1204]
```
au.com.dius:pact-jvm-consumer-junit5:4.0.10
au.com.dius:pact-jvm-consumer-java8:4.0.10
au.com.dius.pact 4.1.7
Gradle 6.1.1
```
Running JUnit5 consumer tests within IntelliJ (Android Studio) generates the Pact file just fine and outputs it to `app/target/pacts`.

However, running the same tests from command line using `./gradlew clean testSomeBuildVariantUnitTest` does not generate anything.

How can one run unit tests from command line in order to have the file created?

Thanks

**Comment by uglyog** [comment]
@borwoj please don't mix major versions of the Pact-JVM libraries. IntelliJ must be resolving the dependencies differently and using the same version.

**Comment by borwoj** [comment]
Thanks, downgraded to 
``` 
au.com.dius:pact-jvm-consumer-junit5:4.0.10
au.com.dius:pact-jvm-consumer-java8:4.0.10
au.com.dius.pact 4.0.10
```
but that did not help.

**Comment by uglyog** [comment]
You need to confirm that `./gradlew clean testSomeBuildVariantUnitTest` is running your unit tests. Check the test output report to see what tests are running. Tests normally run from the `test` task, which the `check` depends on.

**Comment by borwoj** [comment]
@uglyog Thank you for the follow up. I can 100% confirm that the exact same unit tests, including Pact annotated tests, are being run from IntelliJ and the command line, with the missing Pact file being the only difference. If I intentionally make some Pact test fail, the build will fail in both cases and will point to that test.

As for the specific command, I follow this document: https://developer.android.com/studio/test/command-line
Tried both
```
./gradlew test
```
to test all the variants and
```
./gradlew testSomeBuildVariantUnitTest
```
for the specific variant.

**Comment by uglyog** [comment]
Check for a `build/pacts` directory. Gradle generates output files into build, not target

**Comment by borwoj** [comment]
Ah of course, bingo! I was checking the `app/target/pacts` path only. Thanks a lot @uglyog! 🙇
