### ISSUE TITLE
Contract testing with encrypted response

### ISSUE THREAD

**Issue by ashishkujoy** [DiUS/pact-jvm#1206]
Hi team, I am working on a project where we get encrypted responses from providers. I am using pact-jvm-provider-gradle plugin version 4.0.3 for writing the contract tests. Could you please let us know how we can leverage the pact to check the contract after decryption of the response?

**Comment by uglyog** [comment]
There is no callback mechanism to change the response. Pact tests are for verifying that interactions conform to a contract. The contract should be valid whether the response is encrypted or not.

You will need to setup your tests with encryption disabled and then use other types of tests to verify that the appropriate encryption is applied.

**Comment by ashishkujoy** [comment]
@uglyog In our case the actual provider does not run those test and so can't really turn off encryption. We are using pact jvm provider gradle plugin to verify pact against their stable environment. So the only option available to us is somehow intercept the encrypted response and decrypt it before pact verify response body. In docs, it was mention that we can add a filter to update outgoing request, if pact jvm provider gradle plugin can provide us similar functionality to intercept response from provider, that would solve our problem.

**Comment by uglyog** [comment]
There is no current way to modify the response.

**Comment by uglyog** [comment]
One way to do it is to use a proxy that can decrypt the response body.

**Comment by ashishkujoy** [comment]
@uglyog Thanks for the suggestion.
