### ISSUE TITLE
Provider not publishing verification results to Pact URL

### ISSUE THREAD

**Issue by varsha72** [DiUS/pact-jvm#1211]
Hi Team, I am getting following issue when running provider pact test cases, I mean the test cases is passing but thr results are not getting published, could  anyone look into the issue please.

Skipping publishing verification results for source UrlSource(url=pacturl, pact=null)

jars that I am using are 
testCompile group: 'au.com.dius', name: 'pact-jvm-provider', version: '4.0.10'
    testCompile group: 'au.com.dius', name: 'pact-jvm-provider-gradle', version: '4.0.10'
     testCompile 'au.com.dius:pact-jvm-provider-junit5:4.0.9'
    testCompile 'au.com.dius:pact-jvm-provider-junit:4.0.10'
    testCompile('org.junit.jupiter:junit-jupiter-api:5.5.2')
   testCompile('org.junit.jupiter:junit-jupiter-engine:5.5.2')

**Comment by ashishkujoy** [comment]
@varsha72 make sure you have "pact.verifier.publishResults" system property set to "true" .

An example for that in gradle kotlin dsl.
```kotlin
tasks.withType<Test> {
    useJUnitPlatform()
    systemProperties(
        "pact.verifier.publishResults" to "true"
    )
}
```

**Comment by varsha72** [comment]
yes I have set @ashishkujoy , but when do we get pact = null
**_Skipping publishing verification results for source UrlSource(url=pacturl, pact=null)_**

**Comment by ashishkujoy** [comment]
You are using pact broker for storing and managing pacts or some other source like s3 or something else. Because pact jvm publish report only when you have pact broker as your pact source. 
I am not sure but this might be a reason.
Reference.
https://github.com/DiUS/pact-jvm/blob/4250577abe4feb0ae7b46a146c60d312322c2802/provider/src/main/kotlin/au/com/dius/pact/provider/VerificationReporter.kt#L70

**Comment by varsha72** [comment]
@ashishkujoy , I am using pact url and it goes like dis, 
**_@PactUrl(urls = "http://pact url/provider/provider_name/consumer/consumer_name/latest")_**
if I pass d only pact url (e.g htpp://pacturl) without consumer and provider names, then I am getting error saying provider name is null

**Comment by ashishkujoy** [comment]
Yep that creates an uses an instance of `UrlsSource` that might be the reason why pact result are not getting published.

The way i pact jvm is by providing these information from system properties.
```kotlin
tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events = mutableSetOf(FAILED, PASSED, SKIPPED)
        showExceptions = true
        showCauses = true
    }
    systemProperties(
        "pactbroker.auth.username" to System.getenv("PACT_BROKER_USERNAME"),
        "pactbroker.auth.password" to System.getenv("PACT_BROKER_PASSWORD"),
        "pactbroker.host" to System.getenv("PACT_BROKER_HOST"),
        "pactbroker.port" to System.getenv("PACT_BROKER_PORT"),
        "pact.verifier.publishResults" to "true"
    )
}
```
And then use it in test like this. And after all test my pact result get publish to pact broker automatically.

```kotlin
@ExtendWith(SpringExtension::class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, properties = ["server.port=8080"])
@Provider("My-Provider")
@PactBroker(consumers = ["My-Consumer"])
@ActiveProfiles("test")
class ProviderTest {
    @BeforeEach
    fun setUp(context: PactVerificationContext) {
        context.target = HttpTestTarget("localhost", 8080)
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun `verify response`(context: PactVerificationContext) {
        context.verifyInteraction()
    }
    @State("Some consumer state")
    fun stateChange() {}
}
```

**Comment by varsha72** [comment]
@ashishkujoy , it worked...thanks a lot :)
