### ISSUE TITLE
Issue on pending test - doc has the wrong version 

### ISSUE THREAD

**Issue by achi2211** [DiUS/pact-jvm#1214]
As per [doc](https://docs.pact.io/implementation_guides/jvm/provider/junit#pending-pact-support-version-410-and-later)
to enable pending pact you need version 4.1.0 and later but 4.1.1 has an issue that was fixed on 4.1.3
The issue is basically that tests are marked as pending but the build fails anyway. 
Please update the doc and replace 4.1.3 and later instead of 4.1.0. 
You can replicate this just enabled the pending pact  (enablePendingPacts = "true") in version 4.1.1 you will see in the log the tests as [pending] but will break the build anyway.

**Comment by uglyog** [comment]
Docs been updated
