### ISSUE TITLE
how to set provider version in CI/CD to CI_COMMIT_SHA and how can we provide pact version from gradlew command line

### ISSUE THREAD

**Issue by varsha72** [DiUS/pact-jvm#1226]
Hi Team,
  
 I have implemented provider side test cases with junit5 but would like to 

   1.execute add the test cases to CI/CD, how do I set d provider version to CI_COMMIT_SHA

  2. created a gradle task to run the test cases, provided the **_pact.provider.tag_** and **_pact.verifier.publishResults_**  in gradle task but **would like to set pact.provider.version from gradle command line, which I am not able to do**

  3. I ran the pact tests without setting d provider version, tested for negative scenario(where d pact tests fails) I see that the results are not getting published from CI/CD even if I set the pact.verifier.publishResults to true, but whereas the same code works on local.

and what are the exact dependencies we need to use for junit5 and spring
 
FYI : I tried gradle task_name -Dpact.provider.version=version_name
gradle task_name -Dpact.provider.version='version_name'
gradlew task_name -Dpact.provider.version=version_name
gradlew task_name -Dpact.provider.version='version_name'

nothing worked, it took d default value 0.0.0

**Comment by ashishkujoy** [comment]
Hi @varsha72 

This is not really a pact jvm problem, gradle does not pass the system properties added from command line to test task. 

As workaround you will need to explicitly set system property in test task. Below is a code snippet to do that.

```kotlin
tasks.withType<Test> {
    useJUnitPlatform()
    System.getProperties().forEach {
        systemProperties[it.key as String] = it.value
    }
}
```

Do so will make those system property available to pact. Then you can run your tests.
`gradle clean test -Dpact.provider.version="2.0.2"`

**Comment by varsha72** [comment]
Thank you @ashishkujoy , it worked.
