### ISSUE TITLE
How do we create a pact for Multipart file upload using POST

### ISSUE THREAD

**Issue by tarakesh-nv** [DiUS/pact-jvm#123]
We have a scenario where we need to upload a file using post. Is there an option in pact jvm to pass file input in .body()? Is there an example? How do we go about it?

**Comment by uglyog** [comment]
Pact currently only supports text formats. If you need to post a binary body, we could implement it but it would have to be base64 encoded in the pact file.

The other option is with mime multipart bodies (like from a FORM POST with a file selection). 
Currently there is no direct support for creating a multipart body. I can update the DSL and provider verifiers to handle them, but in the meantime you can create the bodies yourself and set the body as a string.

You will have to set the content type to include the boundary marker in the body, i.e.

    Content-Type: multipart/form-data; boundary=5aa569203ce8f671

The `MultipartEntityBuilder` from Apache HTTP components can generate the content type with the boundary marker and bodies.

**Comment by vishwt** [comment]
Thanks! I'll explore and get back to you.

**Comment by radubutnaru** [comment]
We are in a similar situation where we would like to use Pact for a service provider accepting mime multipart bodies. Support for multipart matching would definitely be useful.

**Comment by radubutnaru** [comment]
We went for the full string body matching as a workaround, however we are a bit limited by the fact that there are no regex request matching rules for string bodies. 

Given that the MIME multipart boundary string is usually randomly generated, it is a bit hard to match exactly...

Any other ideas? Thank you.

**Comment by uglyog** [comment]
I have been thinking about this, and it does not make sense to have matchers in this case. What you probably want to do is confirm that a file was included with the body, i.e., the contents are not empty.

Are you using the JUnit DSL?

**Comment by radubutnaru** [comment]
Yes, we're using the JUnit DSL. The provider service accepts POST multipart/form-data, with multiple parts being sent, one of which is the uploaded file. Ideally, we should be able to match/verify each part independently. For the uploaded file part, simply confirming that a file was included should be OK.

**Comment by aniket-21** [comment]
any pointers to example of file upload?

**Comment by aniket-21** [comment]
Can we have this enhancement implemented please?

**Comment by uglyog** [comment]
I've managed to do this with a pact between JS and JVM. The interaction on the consumer side is setup as

```json
{
  "method": "POST",
  "path": "/promotion-groups/a_group_id/product-promotions",
  "headers": {
    "Content-Type": "multipart/form-data; boundary=----WebKitFormBoundary1bvPHrYmtx0UNv2e"
  },
  "body": "------WebKitFormBoundary1bvPHrYmtx0UNv2e\r\nContent-Disposition: form-data; name=\"file\"; filename=\"476.csv\"\r\nContent-Type: text/csv\r\n\r\ndata\r\n------WebKitFormBoundary1bvPHrYmtx0UNv2e--\r\n"
}
```

where `data` is the actual file data.

**Comment by uglyog** [comment]
Support for matching multi-part file uploads has now been added.
