### ISSUE TITLE
Move ConsumerPactBuilder from consumer-junit to consumer module for use in projects not using JUnit

### ISSUE THREAD

**Issue by flosell** [DiUS/pact-jvm#124]
I'm working on a Java Project using TestNG.

We found that the `ConsumerPactBuilder` and its related classes together with `PactFragment.runConsumer` would be enough to make pact-jvm work for us. 

However, the fact that those classes are currently in `pact-jvm-consumer-junit` makes for a messy dependency. 

Would it make sense to move `ConsumerPactBuilder` and the rest of the DSL somewhere else? Maybe to `pact-jvm-consumer`?

**Comment by uglyog** [comment]
Great idea. Moved to the consumer project.
