### ISSUE TITLE
pact-jvm-server rejects (supposedly) valid interaction create request

### ISSUE THREAD

**Issue by timoreimann** [DiUS/pact-jvm#128]
I cannot get pact-jvm-server to accept a fairly simple `/create` request. Here's what I did:

I compiled the [latest master branch](https://github.com/DiUS/pact-jvm/tree/961a2e03afb45dcbcc87c85db8fa427fed4922e0) of the project against Scala 2.11 and made sure that the server was started listening on port 29999:

```
$ pact-jvm-server/build/2.11/install/pact-jvm-server_2.11/bin/pact-jvm-server_2.11
starting unfiltered app at 127.0.0.1 on port 29999
press enter to stop server:
```

The following interaction create request seems legitimate to me. However, the server returns an error claiming that I missed either the state or the body:

```
$ curl http://localhost:29999/create?state=none -X POST -d '{ "provider": { "name": "Provider" }, "consumer": { "name": "Consumer" }, "interactions": [ { "description": "A GET request against the producer", "request": { "method": "get", "path": "/producer", "headers": { "Content-Type": "application/json" } }, "response": { "status": 200, "headers": { "Content-Type": "application/json" } } } ], "metadata": { "pactSpecificationVersion": "1.0.0" } }'
{
  "error" : "please provide state param and pact body"
}
```

I added some debugging log statements to the code and reran the request. It does really look like the state cannot be retrieved properly from the request. All examples I found though used a query parameter to pass the state, which is what I did.

Additionally, it seems to be that the state actually isn't processed:  After passing it to the [create method](https://github.com/DiUS/pact-jvm/blob/961a2e03afb45dcbcc87c85db8fa427fed4922e0/pact-jvm-server/src/main/scala/au/com/dius/pact/server/Create.scala#L19), the related variable isn't touched anymore.

**Comment by uglyog** [comment]
This issue is now fixed. I have been using the server in one of my projects and was able to confirm the fix.

**Comment by timoreimann** [comment]
@uglyog: Thanks, appreciated. Will give it a test run myself later the day.

One thing I am still wondering though is that the state is apparently not used inside the `create` method. Or am I missing something?

**Comment by uglyog** [comment]
I can't work it out either. It looks like it is not used.

**Comment by timoreimann** [comment]
@uglyog: Alright. Maybe the unused state issue should be the matter of another ticket.

Anyway, `/create` requests work for me as well now. Thanks!
