### ISSUE TITLE
Upgrade to scala-logging Library

### ISSUE THREAD

**Issue by abo64** [DiUS/pact-jvm#131]
We cannot really use pact-jvm due to your usage of the obsolete (dead would probably be the more appropriate description) [scalalogging](https://github.com/typesafehub/scalalogging) library.
Is it possible to upgrade to [scala-logging](https://github.com/typesafehub/scala-logging)?

**Comment by uglyog** [comment]
Sure, I'll add in a hyphen for you.

**Comment by uglyog** [comment]
I'm unable to update the project as there is no scala-logging artifact for scala 2.10. There is only one for 2.11.

**Comment by abo64** [comment]
Hmm, you've got a point here. Well then, I have to find some way around my problems.
But please remember this issue once you abandon Scala 2.10.

Thanks,
Achim.

**Comment by uglyog** [comment]
What problems are you having? As far as I can see, it is just a rename of the repository and a different base package.

**Comment by abo64** [comment]
Our (gradle) projects all use the new scala-logging library. So far we did not manage to avoid the conflicts resulting.
But perhaps I have to just try harder and dive deeper into gradle's dependency management or so.

**Comment by uglyog** [comment]
It is only 3 classes, so I could inline them and that should not cause a conflict with your project

**Comment by abo64** [comment]
That sounds like a great idea.
Thanks so much!

**Comment by uglyog** [comment]
Logging in-lined, should not conflict with your project now.

**Comment by abo64** [comment]
Again, thanks a lot!

**Comment by uglyog** [comment]
version 2.2.6 released with this fix

**Comment by maxant** [comment]
Please see https://github.com/DiUS/pact-jvm/issues/401
