### ISSUE TITLE
Doco for regular expressions in bodies?

### ISSUE THREAD

**Issue by bethesque** [DiUS/pact-jvm#134]
Someone was asking on twitter, but I couldn't find the doco for regexps in the Java one, haven't checked the other ones yet.

**Comment by uglyog** [comment]
There is an example in the Groovy DSL: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-groovy#body-dsl
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-groovy%2Fsrc%2Ftest%2Fgroovy%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2Fgroovy%2FPactBuilderTest.groovy
In Java DSL:
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2FREADME.md#building-json-bodies-with-pactdsljsonbody-dsl

**Comment by uglyog** [comment]
Apart from that, there is none.

**Comment by uglyog** [comment]
I've updated the documentation about the path expressions: https://github.com/DiUS/pact-jvm/wiki/Matching#matching-rules
