### ISSUE TITLE
Upgrade specs2 to 3.x?

### ISSUE THREAD

**Issue by freewind** [DiUS/pact-jvm#135]
I use `specs2 3.4` in my project with `pact-jvm-provider-specs2`, it will report some compilation error.

Sample code:

```
import org.specs2.execute.Result
import org.specs2.specification.{Example, Fragment, Fragments}
import au.com.dius.pact.provider.specs2.ProviderSpec

class MyPactRunnerSpec extends ProviderSpec {

  override def is: Fragments = {
    //...
  }

}
````

Compilation error:

```
overriding method is in trait SpecificationStructure of type => org.specs2.specification.core.SpecStructure;
[error]  method is has incompatible type
[error]   override def is: Fragments = {
[error]                ^
[error] one error found
[error] (test:compileIncremental) Compilation failed
```

Are we going to upgrade it?

**Comment by uglyog** [comment]
Is specs2 3 backwardly compatible with specs2 2? Or will it break things? I'm assuming it will force people to upgrade their builds?

**Comment by uglyog** [comment]
In relation to this issue: [#20](https://github.com/DiUS/pact-jvm/issues/20#issuecomment-118436991)

**Comment by uglyog** [comment]
I've upgraded Specs2 to version 3.6.4, hopefully it will work for you.

**Comment by uglyog** [comment]
Version 3.0.4/2.2.15 has been released with Specs2 graded
