### ISSUE TITLE
Any example how to use the feilds in matching rules defined in Pact Json file

### ISSUE THREAD

**Issue by Mikuu** [DiUS/pact-jvm#139]
Hello, 

I'm new to Pact and using the Pact_JVM, when verify the pact for provider, I found in responseMatchingRules or requestMatchingRules, we can define the rules how Pact should verify the response or request against the actual result, but I'm not sure how many and fields are there can be used and what's the usage of each one of them, e.g. "match", "regex", "min". I can guess the meaning from some of the text of this three, but also would like to know the exact usage, e.g. how the "match" works, and how many other fields could be used.

Is there any documents tell something about it, or could you please provide some example?
thank you.

e.g.

"responseMatchingRules":{
          "$.body.id":{
                "regex":"[0-9]+"
           },
          "$.body.name":{
                "match":"type"
           }
}

**Comment by uglyog** [comment]
There is not currently much documentation on the new matching mechanism. You can find test cases here: https://github.com/bethesque/pact-specification/tree/version-2/testcases

A groovy consumer test example: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-groovy/src/test/groovy/au/com/dius/pact/consumer/groovy/PactBodyBuilderTest.groovy

**Comment by uglyog** [comment]
I've updated the documentation about the path expressions: https://github.com/DiUS/pact-jvm/wiki/Matching#matching-rules

**Comment by Mikuu** [comment]
@uglyog, thanks for your update in the documentation, it is great!
