### ISSUE TITLE
Support for json arrays on root level of body.

### ISSUE THREAD

**Issue by stefan-lz** [DiUS/pact-jvm#141]
With using the groovy pact consumer there is no way, when using the withBody() dsl & matchers, to declare a json array on the root body. While I've heard of this being a bad idea for API design, it should still be supported.

I've tried looking at JsonBuilder as an example, it can build a root level array in a few different ways, seen [here](http://docs.groovy-lang.org/latest/html/gapi/groovy/json/JsonBuilder.html#call%28java.util.List%29) and [here](http://docs.groovy-lang.org/latest/html/gapi/groovy/json/JsonBuilder.html#call%28java.util.Collection,%20groovy.lang.Closure%29), but they don't feel like the right fit for the PactBodyBuilder, so I've come up with my own pretty basic solution.

It involves the keyword 'rootJsonArray' in the dsl.

    withBody() {
      rootJsonArray maxLike(10) {
        id identifier
          lineItems minLike(1) {
            id identifier
              amount numeric
              productCodes eachLike { code string('A100') }
          }
      }
    }

commit is here: :boom: stefan-lz/pact-jvm@7bd807fc689b35da0bf833d4a827e15d53938b4a

I was also toying around with the idea of something like another dsl method similar to maxLike/minLike.

    withBody() {
      orders rootJsonArray maxLike(10) {
        id identifier
          lineItems minLike(1) {
            id identifier
              amount numeric
              productCodes eachLike { code string('A100') }
          }
      }
    }

but failed to get anything working quickly.

**Comment by uglyog** [comment]
Got arrays working by extending `withBody` to accept an array:

```groovy
withBody([
    1, 2, 3
])
```

generates

```json
[
    1,
    2,
    3
]
```

and 

```groovy
withBody([
        {
          id identifier(1)
          name 'item1'
        }, {
          id identifier(2)
          name 'item2'
        }
])
```

generates

```json
[
    {
        "id": 1,
        "name": "item1"
    },
    {
        "id": 2,
        "name": "item2"
    }
]
```

**Comment by uglyog** [comment]
It has to have the brackets,

```groovy
withBody [
    1, 2, 3
]
```

generates a compiler error

**Comment by uglyog** [comment]
This now works:

```groovy
withBody eachLike {
        id identifier(1)
        name 'item1'
}
```

**Comment by stefan-lz** [comment]
Cool, that seems like a nice fit to the DSL. I'll have a play tonight and check it out.

**Comment by LoudRobed** [comment]
Was this ever done for the Java DSL? Or rather, is there a way to do it with the Java DSL? I want to specify that the payload of a post request can be an arbitrarily long list of strings like ["a", "b", ...] but I cant' find a way to do it.

**Comment by uglyog** [comment]
I thought this was supported, but I can't seem to find the implementation.

**Comment by uglyog** [comment]
Find it, but it was only implemented for arrays on objects: https://github.com/DiUS/pact-jvm/issues/256#issuecomment-222295887

I'll re-open that issue.
