### ISSUE TITLE
PactRule should use free port

### ISSUE THREAD

**Issue by C-Otto** [DiUS/pact-jvm#142]
Currently, one has to specify the port both when defining the `PactRule` and when building the URL used by the client. Without `PactRule` the `ConsumerPactTest` both takes care to find a free port, and provides the URL using this port.

**Comment by uglyog** [comment]
Host and port are now optional

**Comment by C-Otto** [comment]
Perfect!

**Comment by C-Otto** [comment]
I get `connection refused` when using the new `PactProviderRule` (and changing the `@Pact` methods to use `PactDslWithProvider`). Do I need to do more magic than connecting to localhost:port, where port is what `rule.getConfig().port()` gives me?

**Comment by uglyog** [comment]
No, it should default to localhost and a random port. You can use `rule.getConfig().url()` to get the full URL.

Have a look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2Fsrc%2Ftest%2Fjava%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2FPactRuleWithRandomPortTest.java for an example test.
