### ISSUE TITLE
Allow array matchers to work when root of the body is an array

### ISSUE THREAD

**Issue by batasha** [DiUS/pact-jvm#145]
Currently, array matchers assume that there is an object at the root of the body rather than an array, eg. 
```
{
  "values": [
    {
      "clearedDate": "07/22/2015",
      "amount": 15.0
    },
    {
      "clearedDate": "07/22/2015",
      "amount": 15.0
    }
  ]
}
```
I would like to be able to use this feature when the root of the body is an array, eg.
```
[
    {
      "clearedDate": "07/22/2015",
      "amount": 15.0
    },
    {
      "clearedDate": "07/22/2015",
      "amount": 15.0
    }
]
```
Here's the link to the corresponding Google thread: https://groups.google.com/forum/#!topic/pact-support/T1VhZrm4OJg

**Comment by batasha** [comment]
In my case I'm using the JUnit consumer, but it looks like someone posted a similar issue specifically for groovy: https://github.com/DiUS/pact-jvm/issues/141

**Comment by uglyog** [comment]
Thanks for that.

#141 is related, but more to do with the Groovy DSL not supporting array bodies at all.

**Comment by uglyog** [comment]
I've added a static method to PactDslJsonArray to help. You can use it like:

```java
PactDslJsonArray.arrayEachLike()
            .date("clearedDate", "mm/dd/yyyy")
            .stringType("status")
            .realType("amount")
            .closeObject();
```

This will create an array matcher you can use as the root of the body.

**Comment by batasha** [comment]
Thanks so much for looking into this! I noticed the matchers were missing from the arrayEachLike method, so I just put in a PR to fix that.
