### ISSUE TITLE
State Change URL for Provider States

### ISSUE THREAD

**Issue by vishwt** [DiUS/pact-jvm#149]
We're required to do some test data setup to keep provider in a desired state. However, I didn't find a way to mention the state change URL in pact-jvm. Is there an example?

**Comment by C-Otto** [comment]
I think this has to be added as part of your `pom.xml` (assuming you use Maven):

```
  <build>
        <plugins>
            <plugin>
                <groupId>au.com.dius</groupId>
                <configuration>
                    <serviceProviders>
                        <serviceProvider>
                            <consumers>
                                <consumer>
<stateChangeUrl>http://localhost:${env.PORT}/pactStateChange/v1.0</stateChangeUrl>
                                </consumer>
                            </consumers>
                        </serviceProvider>
                    </serviceProviders>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by uglyog** [comment]
If you're using gradle: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle#provider-states
For maven (as per @C-Otto comment) https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#provider-states
The original concept and ruby examples are here: https://github.com/realestate-com-au/pact/wiki/Provider-states

**Comment by vishwt** [comment]
How do we do it if we're using the spring mock mvc provider?

**Comment by uglyog** [comment]
What do you mean by 'spring mock mvc provider'?

**Comment by vishwt** [comment]
I understand that we can verify the provider tests from a host of providers like Gradle, Sbt, maven etc.
I'm using the provider for spring mvc https://github.com/realestate-com-au/pact-jvm-provider-spring-mvc and wanted to know how to define the state URL.

Can the above provider be used alongside Gradle/Maven? Not sure if I've understood it rightly.

**Comment by uglyog** [comment]
With pact-jvm-provider-spring-mvc, you use methods annotated with `@ProviderState` instead of a provider state change URL. It is described here: https://github.com/realestate-com-au/pact-jvm-provider-spring-mvc#runwithpactrunnerclass
