### ISSUE TITLE
Body options for Spec2 DSL

### ISSUE THREAD

**Issue by dspeele** [DiUS/pact-jvm#150]
It seems this question has been mostly answered in other issues (and in the code) but just to make sure I'm not missing anything- is there any way to ignore a field in the body of the response or match it using regex with the SPEC2 DSL or do I need to switch the the Junit DSL to accomplish this?

Thanks!

Dana

**Comment by uglyog** [comment]
The SPEC2 DSL probably needs to be updated, it hasn't been updated in about a year. I'll see if I can improve it for you, but I don't know SPEC2 very well, so I might need some help testing it.

**Comment by dspeele** [comment]
Fantastic! I'll be happy to test the heck out of it. Keep me posted.

Regards,

Dana

**Comment by uglyog** [comment]
Closing this as there have been a number of PRs that have improved the specs2 DSL.
