### ISSUE TITLE
PactRule: port not accessible

### ISSUE THREAD

**Issue by C-Otto** [DiUS/pact-jvm#151]
In 128c1b4063a7d5acfd2abcbac6dafbb44c8e34a6 you made the port specification optional. However, it is not possible to get the chosen port to use it in the tests.

**Comment by uglyog** [comment]
You can get the port with `rule.getConfig().port()`.

For a working example: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2Fsrc%2Ftest%2Fjava%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2FPactRuleWithRandomPortTest.java#L36

**Comment by C-Otto** [comment]
No, that just works for PactProviderRule, not for PactRule (as I said in this issue's title).

**Comment by uglyog** [comment]
Ok, I've exposed the mock provider config. `rule.getConfig().port()` should work now.

**Comment by C-Otto** [comment]
Thank you!
