### ISSUE TITLE
SBT requires json4s version 3.2.10

### ISSUE THREAD

**Issue by uglyog** [DiUS/pact-jvm#152]
Downgrade json4s to 3.2.10 to fix a error in the SBT plugin.

```
error: (*:verifyPacts) java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ScalaSigSymbol
```

**Comment by cjwebb** [comment]
I have recently stumbled upon this error message. Is there a currently published version of pact-jvm that fixes it?

**Comment by uglyog** [comment]
I'm not sure when the issue was introduced, or if it was an issue with the SBT all along. The SBT plugin has not been maintained for a while.

**Comment by renpillay** [comment]
I'm also encountering this issue.  Version 2.2.12, sbt 0.13.9

**Comment by jgordijn** [comment]
Any progress? Running into the same issue.
Plugin: 2.3.2
sbt 0.13.9

**Comment by uglyog** [comment]
I have removed the use of json4s library from pact-jvm. Version 2.4.0 should now work when run from SBT.
