### ISSUE TITLE
XmlBodyMatcher should honour DiffConfig.allowUnexpectedKeys

### ISSUE THREAD

**Issue by skalsi-atlassian** [DiUS/pact-jvm#153]
Right now, `XmlBodyMatcher` ignores `DiffConfig.allowUnexpectedKeys` and will always match XML bodies for all elements. This should be changed to allow ignoring unexpected keys in the actual output.

**Comment by uglyog** [comment]
Should this be extended to attributes as well?

**Comment by skalsi-atlassian** [comment]
In general: Aw thanks :)

I can't think of a reason why it shouldn't apply to attributes, but I defer to your judgement. Feel free to close. Thanks again.

**Comment by uglyog** [comment]
I think it should be consistent, so I'll add the check for attributes as well.

**Comment by dsiino** [comment]
I understand that `allowUnexpectedKeys` works if the consumer XML is empty and the actual has nodes. However, I would have thought that when the expected body has fewer nodes that the actual, it would not create a body mismatch. 
In `compareChildren`, the condition `expected.child.size != actual.child.size` generates a `BodyMismatch` even if the actual returns the expected nodes along with some extra nodes. 
I assume my understanding of the Postel's law is incorrect.
