### ISSUE TITLE
pact file with matchingRules vs responseMatchingRules

### ISSUE THREAD

**Issue by kmaddileti** [DiUS/pact-jvm#155]
Consumer is using au.com.dius:pact-jvm-consumer-groovy_2.10:2.2.12
Provider is using 'au.com.dius:pact-jvm-provider-gradle_2.11:2.2.1'

Consumer code snippet: 
willRespondWith(status: 201, headers: ['Content-Type': 'application/json;charset=UTF-8'])
            withBody {
                id guid
                text regexp(~/\w+/)
           }

This produces a pact file 

 "matchingRules" : {
 "$.body.id" : {
          "regex" : "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "$.body.text" : {
          "regex" : "\\w+"
        }

However, for the provider test to pass - the pact file should contain
 "responseMatchingRules" 

Once I edit the pact file manually, the test passes. I'm unsure if this is an error on the consumer or plugin?

Tried with both
"metadata" : {
    "pact-specification" : {
      "version" : "2.0.0"
    },
    "pact-jvm" : {
      "version" : "2.2.12"
    }
  }

and 

"metadata" : {
    "pact-specification" : {
      "version" : "2.0.0"
    },
    "pact-jvm" : {
      "version" : "3.0.1"
    }
  }

**Comment by uglyog** [comment]
"matchingRules" is the correct form. If you upgrade the version of the provider (to at least 2.2.3, but you may as well use 2.2.12), it will resolve this issue.

**Comment by kmaddileti** [comment]
Moving the provide from 2.2.1 -> 2.2.12 solved the problem. I was testing on the lower version due to some other issue that I was able to resolve separate. Thanks for the info!
