### ISSUE TITLE
Beautifing of pact request body can lead to error

### ISSUE THREAD

**Issue by knok16** [DiUS/pact-jvm#158]
During parsing request body of interaction, json body is beauitified (some whitespaces and line breaks are added):
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/scala/au/com/dius/pact/model/Pact.scala#L47

In case when server-side parser doesn't tolerate to whitespaces - request will fail.
For example we use [thrift](https://thrift.apache.org/) which is not able to parse json with whitespaces.

View should not interfere with model, so I suggest delete json "beautifing" and if it's needed for displaying add beautifing right before it.

Thanks

**Comment by uglyog** [comment]
Good point. But this does feel like an issue with Thrift because a pretty-printed JSON is still valid JSON. 

Do you encounter this error when validating a Pact?

**Comment by knok16** [comment]
I face this error when running pact against provider - provider can not parse request body that pact runner sent (due to whitespaces). Honestly, I think it is a thrift error (only if thrift doesn't declare own protocol that looks like json but without whitespaces), but I have googled a little and looks like straggle about "is whitesapces part of json" is common, and more tools can have the same behaviour as thrift.

So eliminate "beautifing" is good solution, that also can solve potentially problmes with another tools: also currently it breaks rule that "View should not interfere with model".

**Comment by uglyog** [comment]
Changing Pact.scala to not pretty-print the body may fix your issue (I'm going to implement that), but I feel it is only half the solution. I'm more inclined to have a flag to generate request and response bodies without whitespace regardless of how the body is persisted or stored internally.

Maybe something that can detect the `application/x-thrift+json` mime type as a non-whitespace body?

**Comment by uglyog** [comment]
I've gone through all the code, and it should now not add any whitespace to the bodies.

**Comment by uglyog** [comment]
Version 3.0.4 with this change has been released
