### ISSUE TITLE
Unable to have name like "10k-depreciation-bips" in JSON mathching body

### ISSUE THREAD

**Issue by ChuanChuanLaw** [DiUS/pact-jvm#165]
In Consumer test, I have the following:

withBody{
    
"10k-depreciation-bips" integer(-50)
}

When I run pactVerify, I get the following:

16:46:17.558 [DEBUG] [au.com.dius.pact.matchers.JsonBodyMatcher] compareValues:
Matcher defined for path List($, body, retail-egc)
16:46:17.566 [WARN] [au.com.dius.pact.matchers.Matchers$] Path expression $.body
.x-details.kmap.10k-depreciation-bips is invalid, ignoring: [1.23] failure: stri
ng matching regex `[$_\p{L}][$_\-\d\p{L}]*' expected but `1' found

And then, 

16:46:17.629 [DEBUG] [au.com.dius.pact.matchers.TypeMatcher$] comparing type of
9609 to Integer at List($, body, wholesale)

**Comment by uglyog** [comment]
released as part of 3.1.0
