### ISSUE TITLE
[pact-jvm-provider-maven] Ends Maven Process/LifeCycle Early

### ISSUE THREAD

**Issue by schwartzalexj** [DiUS/pact-jvm#167]
Is there a way in pact-jvm-provider-maven to prevent it from ending the maven lifecycle early on failure? I have pre-integration and post-integration tasks that need to be done regardless of whether the pact verification succeeds or not. Specifically, terminating the server I started.

**Comment by uglyog** [comment]
It might be that it is throwing the wrong exception on failure. I'll change it to throw a MojoFailureException and hopefully that will result in the post integration tasks still running but the build will still be a failure.

**Comment by uglyog** [comment]
This has been released, could you test it?
