### ISSUE TITLE
Allow maven plugin to run all pacts that belong to a provider

### ISSUE THREAD

**Issue by kmaddileti** [DiUS/pact-jvm#168]
Maven provide plugin provides ability to run pacts from file/dir or a URL. However, this requires updating the provider pom.xml everytime a new consumer publishes a new pact.

When using pact broker, maven plugin should provide ability to retrieve all pacts that belong to a service and run them 

In addition, some capability to filter the list of retrieved pacts would add even more flexibility.

https://groups.google.com/forum/#!topic/pact-support/AQC0vYifRnU

**Comment by uglyog** [comment]
The maven plugin has been updated to fetch pacts from a pact broker if a `pactBrokerUrl` is configured. It already has the ability to filter the list. See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#filtering-the-interactions-that-are-verified for information on how to do that.

**Comment by uglyog** [comment]
Docs on using this feature is now here: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#verifying-pact-files-from-a-pact-broker-version-311231
