### ISSUE TITLE
Junit consumer dsl does not allow specifying state for every interaction

### ISSUE THREAD

**Issue by kmaddileti** [DiUS/pact-jvm#169]
Junit consumer currently does not appear to allow setting the provider state using call to given() for every interaction. 

Per this discussion, it seems to be a bug.

https://groups.google.com/forum/#!topic/pact-support/-Kk_OxvcJQY

**Comment by uglyog** [comment]
Consumer DSL has been re-factored to bring it in-line with other DSLs. You are able to set the state before any request now.

**Comment by kmaddileti** [comment]
Thanks for the fix, looks like 3.1.1 is available on central, will check it out and update the issue.

**Comment by kmaddileti** [comment]
Checked with 3.1.1 & works as expected.
