### ISSUE TITLE
Pact Behavior in CI/CD Pipeline for Provider Tests

### ISSUE THREAD

**Issue by pozitron-collab** [DiUS/pact-jvm#1757]
Hello,

I have a query regarding Pact behavior in our CI/CD pipeline when executing provider tests. In our provider tests, we specify a target base URL, and Pact makes HTTP requests to that base URL. Typically, this is done when the application is hosted somewhere, and we explicitly specify the host URL.

When running the provider application locally, we have the ability to mock external dependencies and database calls, allowing Pact to make HTTP calls to the locally running application.

Now, my question relates to the execution of provider tests within a CI/CD pipeline. I'm interested in understanding how and where Pact makes the HTTP call during this process. Specifically, I'm wondering if there's a way for Pact to validate a contract when the provider application is not running anywhere. Or is it mandatory to start the application in an environment for Pact to successfully verify the contract?

Additionally, our requirement is to perform contract validation before the deploy step. In other words, we want to ensure that the recent changes comply with all consumer expectations before deploying the provider service. Could you provide insights into how this can be achieved within the Pact framework?

Thank you for your assistance.

**Comment by YOU54F** [comment]
> Is there a method to eliminate dependencies and launch the application (both in Java Spring Boot and Golang)? We are open to mocking external API and database calls for this purpose.

yes, you mention it below

> When running the provider application locally, we have the ability to mock external dependencies and database calls, allowing Pact to make HTTP calls to the locally running application.

It entirely depends on how you build your application, but this is the most preferable way to test your consumer and provider (prior to deployment)

>Please note that we aim to utilize Pact as a 'Safe as Provider' approach. This means that whenever a service undergoes a deployment, we intend to retrieve all its consumer contracts from the Pact broker and subsequently replay each contract within its CI pipeline, all of which should occur before the deployment step.

Related to this point, all of the Pact documentation and guides point towards this approach, although the Pact's wouldn't need to be replayed at the time of deployment, as they will have already been pre-verified when the consumer contract is either newly published, or has changed from its original publication. 

Providers will utilise webhooks to trigger provider builds against the newly published/changed contract

https://docs.pact.io/pact_broker/webhooks#the-contract-requiring-verification-published-event

which means that at the point of deploying the software to an environment, you are just querying a result and not triggering a test run. Testing is performed pre-deployment of software to an environment

I'd suggest running through the pact nirvana guide or pact workshop to get a feel for the recommended flow.

https://docs.pact.io/pact_nirvana
