### ISSUE TITLE
Support basic auth when using hasPactsFromPactBroker

### ISSUE THREAD

**Issue by georgepapas** [DiUS/pact-jvm#176]
Our pact broker has basic auth.  Following links to actual pacts results in 401 responses from the broker.

It would be nice to have basic auth creds passed along transparently if they exist as part of the initial broker URL, or access to headers as part of the config. i.,e. something like

```
      hasPactsFromPactBroker('https://user:password@my-pact-broker') { consumer ->
        stateChange = url('http://localhost:8080/tasks/pactStateChange')
      }
```
or
```
      hasPactsFromPactBroker('https://my-pact-broker') { headers, consumer ->
        headers.Authorization = 'foo:password'
        stateChange = url('http://localhost:8080/tasks/pactStateChange')
      }
```

**Comment by uglyog** [comment]
I like the second option. But it would need to be:

```groovy
      hasPactsFromPactBroker('https://my-pact-broker') { headers, consumer ->
        headers.Authorization = 'basic Zm9vOnBhc3N3b3Jk' // Base64 encoded
        stateChange = url('http://localhost:8080/tasks/pactStateChange')
      }
```

It might be better to just expose the client used to make the connection, but it might not be available at the point the Closure is executed.

**Comment by uglyog** [comment]
Looking at the code, the closure is executed after all the pacts have been fetched.

The best I can do without a big refactor, is something like:

```groovy
      hasPactsFromPactBroker('https://my-pact-broker', authentication: ['basic', 'user', 'password']) { consumer ->
        stateChange = url('http://localhost:8080/tasks/pactStateChange')
      }
```

**Comment by georgepapas** [comment]
That should work...

**Comment by uglyog** [comment]
I've added the basic auth as per the example above, but I'm unable to test it

**Comment by georgepapas** [comment]
Ok, cool. we can test it, has it been released?

**Comment by uglyog** [comment]
No, I'm a bit hesitant to release it with something that is not verified as working

**Comment by uglyog** [comment]
I'm going to try test it against an authenticated website, hopefully I can get the auth to work and then get a 404.

**Comment by uglyog** [comment]
this has been released, so you can give it a test

**Comment by georgepapas** [comment]
Hi Ron,

Gave this a go, looks like the closure is configured OK, but when the files are downloaded, it appears the auth is not used.  Here is a stack trace.

```
Caused by: groovy.json.JsonException: Unable to process url: https://my-server/pacts/provider/Service/consumer/Consumer/version/0.1.0-51
	at au.com.dius.pact.model.PactReader.loadFile(PactReader.groovy:149)
	at au.com.dius.pact.model.PactReader.loadPact(PactReader.groovy:22)
	at au.com.dius.pact.provider.ProviderVerifier.loadPactFileForConsumer(ProviderVerifier.groovy:83)
...
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://my-server/pacts/provider/Service/consumer/Consumer/version/0.1.0-51
```

**Comment by uglyog** [comment]
That should be fixed now. I tested it with an nginx reverse proxy in front of a pact broker.
