### ISSUE TITLE
Enhance ConsumerGroup.pactFileLocation to support filtering files

### ISSUE THREAD

**Issue by georgepapas** [DiUS/pact-jvm#177]
We have a scenario where we'd like to include  .gitkeep in the pactFileLocation folder.  The way ProviderInfo searches for files means that everything is treated as a pact, even folders...

**Comment by uglyog** [comment]
do something like:

```groovy
    hasPactsWith('manyConsumers') {
            pactFileLocation = file('path/to/pacts')
            include = '*.json'
    }
```

**Comment by uglyog** [comment]
Looking at the Groovy APIs, it will be easier with a regex:

```groovy
    hasPactsWith('manyConsumers') {
            pactFileLocation = file('path/to/pacts')
            include = /.*\.json$/
    }
```

**Comment by uglyog** [comment]
Implemented the include, with the default being `/.*\.json$/`

**Comment by uglyog** [comment]
This has been released, so you can give a go

**Comment by georgepapas** [comment]
Thanks Ron,

Looks good.

Cheers
