### ISSUE TITLE
multi-valued headers

### ISSUE THREAD

**Issue by bankras** [DiUS/pact-jvm#179]
I need to simulate a multi valued response header. At this moment I am unable to to this, because the `PacDslResponse` only allows a `Map<String, String>`. The value gets overwritten due to the duplicate key. Maybe the headers could be a `Map<String, List<String>>`?

for example:
my provider responds with two `WWW-Authenticate` headers. One with a Basic realm and one with a OAuth realm.

**Comment by bethesque** [comment]
You should be able to comma separate them, if the order is reliable.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

"Multiple message-header fields with the same field-name MAY be present in
a message if and only if the entire field-value for that header field is
defined as a comma-separated list [i.e., #(values)]. It MUST be possible to
combine the multiple header fields into one "field-name: field-value" pair,
without changing the semantics of the message, by appending each subsequent
field-value to the first, each separated by a comma. The order in which
header fields with the same field-name are received is therefore
significant to the interpretation of the combined field value, and thus a
proxy MUST NOT change the order of these field values when a message is
forwarded."

Beth


On Mon, Nov 9, 2015 at 8:27 PM, Roald Bankras <notifications@github.com>
wrote:

> I need to simulate a multi valued response header. At this moment I am
> unable to to this, because the PacDslResponse only allows a Map<String,
> String>. The value gets overwritten due to the duplicate key. Maybe the
> headers could be a Map<String, List<String>>?
>
> for example:
> my provider responds with two WWW-Authenticate headers. One with a Basic
> realm and one with a OAuth realm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DiUS/pact-jvm/issues/179>.
>



-- 
Bethany Skurrie
Software Developer

DiUS Computing Pty. Ltd.


*where ideas are engineered *Phone: +61 3 9008 5400
Mobile: +61 415 413 713

www.dius.com.au

This email is intended solely for the use of the addressee and may contain
information that is confidential or privileged. If you receive this email
in error please notify the sender and delete the email immediately.

**Comment by bankras** [comment]
Hi Beth

Thanks for the response. I've seen that too and have tried to implement that. The consumer side works fine with it. Although my http client does not recognise the separate values itself, it was relative easy to split the header.

When I read RFC2616 sec 14.47:
`User agents are advised to take special care in parsing the WWW- Authenticate field value as it might contain more than one challenge, or if more than one WWW-Authenticate header field is provided, the contents of a challenge itself can contain a comma-separated list of authentication parameters.`

It seems to stress that it allow to work with "more than one" lines, but that either side should take special care. Unfortunately, as http client and server are just passing the headers along. It's up to the common developer to take care of it.

However, We're not in control of the security layer of the provider. And that is adding multiple www-authenticate header fields. So now my producer build is failing because
`includes headers
        "WWW-Authenticate" with value "Basic realm="basic-realm",OAuth realm="oath-realm"" (FAILED)`

Do you know another way I can validate my contract?

**Comment by uglyog** [comment]
What is the actual comparison output for the header? It should have been listed out in the failure summary.

**Comment by bankras** [comment]
Failures:

    0) Verifying a pact between {consumer} and {provider} - Initial request Given Unauthenticated client returns a response which includes headers "WWW-Authenticate" with value "Basic realm="protected-area",OAuth realm="{oath-realm-name}""
          Expected header 'WWW-Authenticate' to have value 'Basic realm="protected-area",OAuth realm="{oath-realm-name}"' but was 'OAuth realm="{oath-realm-name}"'

    1) Verifying a pact between {consumer} and {provider} - authentication request Given Unauthenticated client returns a response which has status code 302
      assert expectedStatus == actualStatus
             |              |  |
             302            |  401
                            false

**Comment by uglyog** [comment]
Looks like the HTTP library pact is using is only returning one of the
values. You could use a regular expression that matches both. Have a look
at
https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#matching-on-headers-version-222

An expression like Basic realm="protected-area"|OAuth
realm="{oath-realm-name}" may work.

**Comment by bankras** [comment]
That would work, except that the error occurs in the provider validation. Following is my fragment:

    Map<String, String> headers = new HashMap<>();
    headers.put("WWW-Authenticate", "Basic realm=\"protected-area\",OAuth realm=\"realm-name\"");

    provider.given("Unauthenticated client")
        .uponReceiving("Initial request")
        .method("GET")
        .path("/")
    .willRespondWith().status(401).headers(headers).toFragment();

**Comment by bankras** [comment]
I just noticed you can do a matchHeader on the response as well. Let me check.

**Comment by bankras** [comment]
fixed it. although I had to provide an example value
