### ISSUE TITLE
matchNoHeader

### ISSUE THREAD

**Issue by bankras** [DiUS/pact-jvm#180]
It would be great if I could validate that a specific header is not present.
For example: when initiating an authentication flow
1. Request endpoint without Authorization header
2. Respond with status 401 and WWW-Authentication headers
3. Request endpoint with Authorization header
4. Authentication successful

**Comment by uglyog** [comment]
Unfortunately, due to that Pact follows Postel's law for matching requests and responses, we are unable to determine when something is not there. See https://github.com/realestate-com-au/pact/wiki/Matching-gotchas#you-cannot-expect-a-field-to-not-be-present-in-a-response for more information.
