### ISSUE TITLE
Comparing against null

### ISSUE THREAD

**Issue by venksub** [DiUS/pact-jvm#183]
If I expect a certain field to have a null value, how can I write a matching expression for it? I tried using stringValue("some_field", null) but doesn't work.

**Comment by venksub** [comment]
Code like this works:	
	
JSONObject body = (JSONObject)pactBody.getBody();
body.put("some_field", JSONObject.NULL);

**Comment by uglyog** [comment]
I'll look at why stringValue("some_field", null) is not working, but I'll also add a nullValue method.

**Comment by uglyog** [comment]
I've updated the Java DSL so that `stringValue("some_field", null)` works, and I have also added an explicit `nullValue("some_field")` method.
