### ISSUE TITLE
Use with pact-consumer-js-dsl

### ISSUE THREAD

**Issue by ichyr** [DiUS/pact-jvm#186]
As I understand those 2 libraries use the same pact-specification v.2.0.

So the question is:

Can I use the mock and provider infrastructure from this library **pact-jvm** but use the consumer code from [**pact-consumer-js-dsl**](https://github.com/DiUS/pact-consumer-js-dsl) ?

Sorry if the question is not supposed to be put there.

**Comment by uglyog** [comment]
In theory you can. But the mock servers require different setup (in the may that the pacts are passed to the newly started mock server). The pact-consumer-js-dsl assumes the behaviour of the ruby mock server. But the setup has only a small difference.

Once the mock servers are running with the correct pacts, the behaviour is all the same.

I was thinking of adding some configuration to pact-consumer-js-dsl to allow it to work with either mock server. It might be better to raise an issue in that project.

**Comment by bethesque** [comment]
The flexible matching won't work, pact JS uses the Ruby way of serialising
regular expressions between itself and the mock service. They only get
converted to pact spec v2 format when the pact is written to the file.


On Tue, Nov 24, 2015 at 9:38 AM, Ronald Holshausen <notifications@github.com
> wrote:

> In theory you can. But the mock servers require different setup (in the
> may that the pacts are passed to the newly started mock server). The
> pact-consumer-js-dsl assumes the behaviour of the ruby mock server. But the
> setup has only a small difference.
>
> Once the mock servers are running with the correct pacts, the behaviour is
> all the same.
>
> I was thinking of adding some configuration to pact-consumer-js-dsl to
> allow it to work with either mock server. It might be better to raise an
> issue in that project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DiUS/pact-jvm/issues/186#issuecomment-159090209>.
>



-- 
Bethany Skurrie
Software Developer

DiUS Computing Pty. Ltd.


*where ideas are engineered *Phone: +61 3 9008 5400
Mobile: +61 415 413 713

www.dius.com.au

This email is intended solely for the use of the addressee and may contain
information that is confidential or privileged. If you receive this email
in error please notify the sender and delete the email immediately.

**Comment by ichyr** [comment]
@bethesque but in the page of the JS pact consumer version there are words:

*The Javascript DSL is compatible with v2 of the pact-specification and supports type based matching, flexible array lengths, and regular expressions (read more below).*

So you saying that the resulting json ( that is supposed to be v2 compatible) can't be used in the pact-jvm?

**Comment by uglyog** [comment]
Damn ruby is always so far behind ;-)

What @bethesque is staying is that the JS consumer DSL talks V1 versions of pacts with the ruby mock server, which then converts them to V2 versions just before writing them to the pact file.

So the JS consumer DSL needs to be updated to generate V2 pact requests, and also changed to work with the JVM mock server.

**Comment by uglyog** [comment]
Closing this and marking it as unsupported
