### ISSUE TITLE
java.lang.NullPointerException when @PactFolder has an invalid path - pact-jvm-provider-junit

### ISSUE THREAD

**Issue by stefan-lz** [DiUS/pact-jvm#187]
Use @PactFolder with a resource path that does not exist:
 
    @PactFolder("xyz")
    class PactAcceptanceTest {
    ..
    ..
    }

When the test is run I get a junit initializationError with:

    java.lang.NullPointerException
	at au.com.dius.pact.provider.junit.loader.PactFolderLoader.load(PactFolderLoader.java:46)

**Comment by uglyog** [comment]
Wow, you think the Java File class would throw an exception if the directory does not exist!

**Comment by stefan-lz** [comment]
Well its easy enough to figure out I guess, but a FileNotFoundException
(with path) would be nicer.

**Comment by houdini68** [comment]
@uglyog:Why did you close this issue ? It is even worse. On our Jenkins servers, the path that references to the class has a space. I know it is not clever. In this case even if the path does exist, a NullPointerException is returned. Test fails. Build is unstable! That the directory does not exist, it is under my control and I can correct it. But that the directory does exist (ok there is a space in it) and that the test fails and the build is unstable is not acceptable. We should retrieve the path using another method that supports white spaces and that returns an exception that explains the problem (FileNotFoundException) and no NPE. My 2 cents.

**Comment by uglyog** [comment]
@houdini68 The issue was closed because a fix was committed (160eb66) and released with version 3.2.0 and there was no response after a few months, so the assumption was it is not longer an issue. If this is not the case, Github has an awesome feature just for this condition: Reopen issue.

**Comment by houdini68** [comment]
@uglyog **You are are right!** I will have a look to what was commited and give a feedback. Thanks a lot.
