### ISSUE TITLE
the 'real' number type does not seem to be matching correctly?

### ISSUE THREAD

**Issue by stefan-lz** [DiUS/pact-jvm#189]
I've created a pact file with real number matching, it looks something like this:

        {
          "provider" : {
            ...
          },
          "consumer" : {
            ...
          },
          "interactions" : [ {
            ...
            },
            "response" : {
              "status" : 200,
              "headers" : {
                "Content-Type" : "application/json"
              },
              "body" : {
                "transactions" : [ {
                  "cost" : 5.244065989E7,
                  ...
                } ]
              },
              "matchingRules" : {
                "$.body.transactions[*].cost" : {
                  "match" : "real"
                },
                ...
              }
            }
          } ],
          "metadata" : {
            "pact-specification" : {
              "version" : "2.0.0"
            },
            "pact-jvm" : {
              "version" : "2.2.7"
            }
          }
        }

With a response like:

    {
      "accountId": {
         ...
      },
      "transactions": [
        {
          ...
          "cost": 52440659.89,
        }
      ]
    }

Yet I get a mismatch for this, and other kind of numbers:

    BodyMismatch - Expected 39833354.42000000178813934326171875 to be a real number
    BodyMismatch - Expected 100 to be a real number
    BodyMismatch - Expected 100 to be a real number
    BodyMismatch - Expected 100 to be a real number
    BodyMismatch - Expected 52440659.89000000059604644775390625 to be a real number
    BodyMismatch - Expected 8613019.69 to be a real number
    BodyMismatch - Expected 44422888.75 to be a real number

Aren't all these valid real numbers?
As a workaround I've switched the matching to 'number' instead.

**Comment by uglyog** [comment]
That is interesting. What version are you using?

The real matcher checks the type is Float, Double or BigDecimal. The number matcher just checks the type is a Number. These are based on the Java class. But as JSON only has doubles, they aren't that valuable.

**Comment by uglyog** [comment]
It could be the JSON parser is returning a different Java type than those.

**Comment by bethesque** [comment]
Using "real" makes it incompatible with Ruby/.net. I thought we just had "number"? Or something.

**Comment by stefan-lz** [comment]
Yeah now thinking about it, JSON only has a concept of a number, not integers or reals. So reals would be validating that the number has a decimal point? Maybe they are more useful in XML or something - I'm happy to leave it with numeric checking.

Ron:  Version is "au.com.dius:pact-jvm-provider-junit_2.11:2.4.0"

**Comment by uglyog** [comment]
I did a quick test, and Groovy will convert whole numbers into an Integer,
and anything with a decimal point to a BigDecimal. Scala does something
similar, but to a Scala Int or Double. So the real vs integer is a valid
check.

The issue is that Scala has it's own classes that wrap the primitive
values, so that is why the real check was failing. But I have removed the
Scala parser in favour of the Groovy one, so the check should work with the
next release.

**Comment by uglyog** [comment]
Looks like the 3.2.0/2.4.0 refactor is not working with numbers. See #192

**Comment by uglyog** [comment]
Found the issue. Scala has it's own BigDecimal class (go figure), so since I removed json4s it now will be parsed to a java.math.BigDecimal

**Comment by uglyog** [comment]
BTW, I renamed the matcher to be 'decimal' instead of 'real' ('real' matcher is still there), as the intent was to check for numbers with a decimal place. The 'number' matcher will match both integers and decimals.
