### ISSUE TITLE
Implement V3 pact spec for JVM consumer DSLs

### ISSUE THREAD

**Issue by euan-tilley** [DiUS/pact-jvm#190]
To take advantage of the v3 pact spec can the jvm consumer dsl implement the new version.

**Comment by uglyog** [comment]
I've added a status page so you can see what has been implemented https://github.com/DiUS/pact-jvm/wiki/Status-of-implementation-of-pact-specification-versions

**Comment by uglyog** [comment]
3.5.0-rc.1 has been released.

**Comment by uglyog** [comment]
3.5.0 has now been released.
