### ISSUE TITLE
pact-jvm-provider-gradle_2.11:3.2.0 bug?

### ISSUE THREAD

**Issue by ChuanChuanLaw** [DiUS/pact-jvm#192]
Just upgraded Provider to version pact-jvm-provider-gradle_2.11:3.2.0.

(1) Not working for numbers

Got the following errors:

      $.body.Prices.PriceDAP -> Expected 5001 to be an integer
      $.body.Prices.Price -> Expected 5001 to be an integer
      $.body.Prices.SearchPrice -> Expected 5001 to be an integer
      $.body.GeoLocation.Latitude -> Expected -37.825039 to be a real number
      $.body.GeoLocation.Longitude -> Expected 144.971512 to be a real number
      $.body.Seller.GeoLocation.Latitude -> Expected -37.821293 to be a real num
ber
      $.body.Seller.GeoLocation.Longitude -> Expected 144.95576 to be a real num
ber
      $.body.Seller.Finance.0.Rate -> Expected 10.74 to be a real number
      $.body.Specification.GreenhouseRating -> Expected 7 to be a real number
      $.body.Specification.OverallGreenStarRating -> Expected 3.5 to be a real n
umber
      $.body.Specification.FuelCombined -> Expected 7.4 to be a real number
      $.body.Specification.Power -> Expected 104 to be a real number
      $.body.Specification.YearlyCosts.0.Amount -> Expected 9226.7159 to be a re
al number
      $.body.Specification.YearlyCosts.1.Amount -> Expected 2484 to be a real nu
mber

The errors does not seem to be correct. 

5001 indeed is an integer, 144.971512 is a real number.

(2) Not working for empty list 

Also, looks like it is not able to compare empty array like SubFeatures ([]).

Error below is thrown:

$.body.Features.0.SubFeatures -> Expected List() to have minimum 1

**Comment by ChuanChuanLaw** [comment]
Also, looks like it is not able to compare empty array like SubFeatures ([]).

Error below is thrown:

$.body.Features.0.SubFeatures -> Expected List() to have minimum 1

**Comment by uglyog** [comment]
I've fixed the real number matcher. In the mean time, you can use the basic number matcher (numeric).

As for the empty list, use eachLike which accepts an empty list.
