### ISSUE TITLE
Feature - Use SBT plugin with pact broker json

### ISSUE THREAD

**Issue by renpillay** [DiUS/pact-jvm#195]
At the moment, it seems the SBT plugin requires local Pact JSON files. We'd like to be able to run pact tests, as provider, against json files stored in a pact broker. The maven plugin has support for this, but it seems (?) that the sbt plugin does not.

**Comment by uglyog** [comment]
I want to completely rewrite the SBT plugin to have the same behaviour as the maven and gradle plugin.

**Comment by emdem** [comment]
@uglyog is there a branch yet? and if so need any help? we are really keen to use the sbt plugin to do testing for some scala apps

**Comment by uglyog** [comment]
@emdem I haven't started any work on the SBT plugin yet. I could use some help, as I do not have much SBT knowledge.

The main work required is to setup the SBT configuration and map that to what is required by the [PactVerifier](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider%2Fsrc%2Fmain%2Fgroovy%2Fau%2Fcom%2Fdius%2Fpact%2Fprovider%2FProviderVerifier.groovy) class which does the verification. For an example, the Maven plugin has the configuration defined as Pojos that are populated from the configuration in the POM file. All it needs to do is setup the PactVerifier based on the maven config and then call out to the PactVerifier from the maven task. We would need to do something similar for SBT.

If you can look at how the maven plugin is configured (https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-maven%2FREADME.md#2-define-the-pacts-between-your-consumers-and-providers) and are able to create an SBT plugin configuration that works well with the SBT para-dimes, that would be awesome.

For an example.

maven: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-maven%2Fsrc%2Fmain%2Fgroovy%2Fau%2Fcom%2Fdius%2Fpact%2Fprovider%2Fmaven%2FPactProviderMojo.groovy
For Leiningen: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-lein%2Fsrc%2Fmain%2Fclojure%2Fau%2Fcom%2Fdius%2Fpact%2Fprovider%2Flein%2Fverify_provider.clj

**Comment by uglyog** [comment]
I've release version 2.4.4 which includes a new task in the SBT plugin (`pactVerify`) that has support for fetching pacts from a pact broker.
