### ISSUE TITLE
pact-provide-junit is missing @Consumer annotation

### ISSUE THREAD

**Issue by scho** [DiUS/pact-jvm#197]
I really like the idea of having a JUnit PactRunner. What is missing though in my opinion, is a `@Consumer` annotation to specify the consumer. Together with `@PactBroker` and `@Provider`, it would be all you need to specify a certain pact.

In our current custom implementation of what `pact-provide-junit` does, we specify the consumer as well in order to have one test class per consumer/producer pair.

The main advantage is, that the producer build does not fail, unless it explicitly adds the corresponding test class. After than, breaking pact changes will make the build fail of course.

What do you think? Is this a reasonable enhancement?

**Comment by IschenkoArtem** [comment]
Hi, I'm from the team that worked on `pact-jvm-provider-junit`. 
We have already implemented functionality to run tests for specific consumers, but using system properties (with maven command line parameters). It allows to use approach described here: https://github.com/bethesque/pact_broker/wiki/How-to-ensure-backwards-compatibility-by-tagging-pacts . 

Command line parameters are more flexible than annotations, that helps us to configure CI properly. We are planning to open-source it in the near future. Would that work for you?

**Comment by scho** [comment]
I am not sure if it would work. We have one unit test class per consumer/provider pair. It's totally fine for us to specify the consumer per annotation. The current workaround would be, to point to the specific pact with the `@PactUrl` annotation. But then we need to write the PactBroker url all the time. It would be better in my opinion to use `@Consumer`, `@Provider` and `@PactBroker`.

**Comment by uglyog** [comment]
Closing this as PR #218 was merged
