### ISSUE TITLE
QueryMismatch when POSTing body with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by tanob** [DiUS/pact-jvm#198]
I'm trying to use Pact to verify my authentication service receives "username" and "password" via POST, with Content-type "application/x-www-form-urlencoded", here's the fragment using "pact-jvm-consumer-junit":

``` java
    @Pact(provider = AUTHENTICATION_SERVICE, consumer = DUMMY_AUTHENTICATION_CONSUMER)
    public PactFragment customerDoesNotExist(PactDslWithProvider builder) throws UnsupportedEncodingException {
        return builder
                .given("customer does not exist")
                    .uponReceiving("Request to authenticate")
                        .method("POST")
                        .path("/authentication-service/authenticate")
                        .body("username=unknown%40example.com&password=foobar", APPLICATION_FORM_URLENCODED.getMimeType())
                    .willRespondWith()
                        .status(404)
                .toFragment();
    }
```

Then my test uses a simple HTTP client to POST these values:

``` java
    @Test
    @PactVerification(fragment = "customerDoesNotExist")
    public void customerDoesNotExist() throws Exception {
        HttpResponse response = authenticateRequestWith(Form.form()
                .add("username", "unknown@example.com")
                .add("password", "foobar")
                .build());

        assertThat(response.getStatusLine().getStatusCode()).isEqualTo(404);
    }

    private HttpResponse authenticateRequestWith(List<NameValuePair> formParams) throws IOException {
        return Request
                    .Post(authenticationServiceURL())
                    .bodyForm(formParams, null)
                    .execute()
                    .returnResponse();
    }
```

And the test fails with the following:

```
au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:
Request to authenticate:
    QueryMismatch(password,,foobar,Some(Unexpected query parameter 'password' received),$.query.password)
    QueryMismatch(username,,unknown@example.com,Some(Unexpected query parameter 'username' received),$.query.username)

The following requests were not received:
Interaction: Request to authenticate
    in state customer does not exist
request:
    method: POST
    path: /authentication-service/authenticate
    query: null
    headers: [Content-Type:application/x-www-form-urlencoded]
    matchers: [:]
    body: username=unknown%40example.com&password=foobar

response:
    status: 404 
    headers: [:] 
    matchers: [:] 
    body: null
    at au.com.dius.pact.consumer.PactProviderRule$1.evaluate(PactProviderRule.java:132)
```

Looks like the reason for that is because of `Conversions`'s `toQuery`:
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/scala/au/com/dius/pact/model/unfiltered/Conversions.scala#L58 

`request.parameterNames` attribute joins query and body params:
https://github.com/unfiltered/unfiltered/blob/0.9.0/netty/src/main/scala/bindings.scala#L40

I think the correct behavior would be look only into the `queryParams`.

**Comment by uglyog** [comment]
What the underlying HTTP server code does is detects that the content type is a application/x-www-form-urlencoded form post, and exposes the query parameters from the body instead of the query string.

Just try using query parameters in the expectation. I think that should work.

```java
    @Pact(provider = AUTHENTICATION_SERVICE, consumer = DUMMY_AUTHENTICATION_CONSUMER)
    public PactFragment customerDoesNotExist(PactDslWithProvider builder) throws UnsupportedEncodingException {
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", APPLICATION_FORM_URLENCODED.getMimeType());
        return builder
                .given("customer does not exist")
                    .uponReceiving("Request to authenticate")
                        .method("POST")
                        .path("/authentication-service/authenticate")
                        .query("username=unknown%40example.com&password=foobar")
                        .headers(headers)
                    .willRespondWith()
                        .status(404)
                .toFragment();
    }
```

**Comment by tanob** [comment]
@uglyog that "works" in the sense it passes the test but I don't think it is the correct behavior. What if my service doesn't look the parameters from the query string but only from the body? How do I specify that distinct behavior with Pact JVM?

In other words, the generated Pact contract JSON should have a "body" specified, not a "query". This different behavior doesn't exist in Pact-ruby, I've just tried this and it works:

```ruby
      authentication_service.given("customer does not exist").
        upon_receiving("Request to authenticate").
        with(method: :post,
             path: '/authentication-service/authenticate',
             body: 'username=unknown%40example.com&password=foobar',
             headers: {'Content-type' => 'application/x-www-form-urlencoded'}).
        will_respond_with(
          status: 404)
```

**Comment by uglyog** [comment]
This is not by design, it comes from the underlying HTTP library (netty) that is being used. It might even be a JVM HTTP implementation behaviour. We discovered it via an issue that was previously raised: #118

**Comment by tanob** [comment]
@uglyog https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/scala/au/com/dius/pact/model/unfiltered/Conversions.scala#L58

in the `toQuery` method there's a call to `request.parameterNames`, this code is in Pact JVM. The `parameterNames` attribute of `HttpRequest` is from the library called "unfiltered", see source code for that attribute:

https://github.com/unfiltered/unfiltered/blob/0.9.0/netty/src/main/scala/bindings.scala#L72

see that `parameterNames` calls `params`, defined here:
https://github.com/unfiltered/unfiltered/blob/0.9.0/netty/src/main/scala/bindings.scala#L40

You can see that `params` looks to both `queryParams` and `bodyParams`.

Said all that, the `toQuery` method in the Pact JVM shouldn't be calling `parameterNames`, it should only call `request.queryParams`.

**Comment by uglyog** [comment]
ok, thanks for that.

**Comment by uglyog** [comment]
A side effect of this change is that the body will be compared as text as there is no matcher other than JSON and XML at the moment. This means that if the parameters are the same but in a different order, the verification will fail. The Query string matcher works on key-value pairs.

I'm thinking of making this switch-able so people can decide how they want this handled.

**Comment by uglyog** [comment]
A side effect of implementing the new mock server is that this is no longer an issue. I'll add a matcher for x-www-form-urlencoded bodies to complete this.
