### ISSUE TITLE
Specify version in gradle for pact publish

### ISSUE THREAD

**Issue by shavo007** [DiUS/pact-jvm#200]
Hi,

Is there a way to specify the version when publishing the pact?

Example:

```
 publish {
        pactBrokerUrl = 'https://pactbroker.com'
version = 1.0.0
    }
```

I do not want to use the version from gradle.properties.

Thanks,
Shane.

**Comment by uglyog** [comment]
I could implement that as an override to the project version. At the moment it uses `project.version`.

**Comment by shavo007** [comment]
That would be cool mate. As we want to align pact with our API versioning, not the versioning of our artifact that is deployed to  s3.

Thanks,
Shane.

**Comment by uglyog** [comment]
Version override has now been added.

**Comment by shavo007** [comment]
hi @uglyog , thanks for that.

What release is this in to test it out?

**Comment by uglyog** [comment]
This will be in the next release, which I'll push out to maven central by the weekend at the latest

**Comment by shavo007** [comment]
Cheers mate.

**Comment by uglyog** [comment]
This has been released with version 3.2.2

**Comment by shavo007** [comment]
Hi @uglyog . Thanks for putting that change in.

I updated to the latest version but have a syntax error with my version.

```

plugins {
    id "au.com.dius.pact" version "3.2.2"

}


   publish {
        version = 1.0.0
        pactBrokerUrl = 'https://pactbroker-ptest-01-web-elb-1767914713.ap-southeast-2.elb.amazonaws.com'
    }

```

build.gradle': 254: unexpected token: 0 @ line 254, column 23.
           version = 1.0.0
                                 ^

It complains about the last zero. Any clue!?

My gradle wrapper version is 2.4

**Comment by thetrav** [comment]
Looks like it should be a string...  there's no valid numeric type with multiple decimal places

``` version = "1.0.0" ```

might work better

**Comment by shavo007** [comment]
fantastic. thanks for the help

**Comment by shavo007** [comment]
Out of interest, in github how would i know what version this enhancement was made in?

**Comment by thetrav** [comment]
https://github.com/DiUS/pact-jvm/releases

However that relies on it either being mentioned in the release notes, or you looking at the code for the linked commit

**Comment by shavo007** [comment]
Cheers for the help guys. Working seamlessly in our CI.
