### ISSUE TITLE
pact-jvm-provider junit @PactBroker add an optional parameter to specify protocol

### ISSUE THREAD

**Issue by GeorgeSimon** [DiUS/pact-jvm#205]
Hello, we are using pact testing in a Pivotal Cloud Foundry environment where all services and the Pact Broker are running under SSL. I would like to be able to optionally specify the protocol, for example:
@PactBroker(host="host.of.pact.broker.com", port = 80, protocol="https")

**Comment by uglyog** [comment]
I've added protocol to both @PactBroker and HttpTarget

**Comment by uglyog** [comment]
This has been released with version 3.2.2
