### ISSUE TITLE
Avoid hard coding host in @PactBroker

### ISSUE THREAD

**Issue by JasonH74** [DiUS/pact-jvm#208]
To avoid having hard-coded host names in the @PactBroker annotation, can you implement the ability to inject the host name from an environment variable or properties file?

**Comment by uglyog** [comment]
That sounds like a useful feature. Would system properties work (i.e. can be set with -Dpact.broker.url=xxx)?

**Comment by JasonH74** [comment]
Yes that seems like a good place to configure it.




On Fri, Jan 29, 2016 at 6:27 PM -0800, "Ronald Holshausen" <notifications@github.com<mailto:notifications@github.com>> wrote:


That sounds like a useful feature. Would system properties work (i.e. can be set with -Dpact.broker.url=xxx)?

-

**Comment by uglyog** [comment]
This has been released with version 3.2.3
