### ISSUE TITLE
integerType generating numbers larger than integer.

### ISSUE THREAD

**Issue by Hazz223** [DiUS/pact-jvm#209]
Hi,

We've had this problem:
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (9,915,470,985) out of range of int

And followed where this is coming from; the PactDslJsonBody class.

    /**
     * Attribute that must be an integer
     * @param name attribute name
     */
    public PactDslJsonBody integerType(String name) {
        return integerType(name, Long.parseLong(RandomStringUtils.randomNumeric(10)));
    }

This looks like it will generate numbers that are 10 digits long (2,147,483,647 max value), which means pretty often it will generate numbers that are larger than integers.

Is this the intended behavior, or is this an issue?

**Comment by uglyog** [comment]
That was totally arbitrarily chosen, I'll reduce it to 9 digits so it fits within 32 bit integer dynamic range.

**Comment by Hazz223** [comment]
Thanks for the fast response!

**Comment by uglyog** [comment]
This has been released with version 3.2.3
