### ISSUE TITLE
3.2.0 Issue with request body definition

### ISSUE THREAD

**Issue by georgepapas** [DiUS/pact-jvm#212]
When defining a POST body request body expectation like this

```
withBody {
  fooInBar '1234'
}
```

Pact correctly matches the request.  However, when defining a request body like this...
```
withBody {
  fooAsBar '1234'
}
```
pact never matches the request. Note the change of property name from foo**In**Bar to foo**As**Bar. Not sure what is happening when using 'As' in the property name I can never get a match...

**Comment by uglyog** [comment]
You do manage to find the strange ones ;-)

**Comment by georgepapas** [comment]
lol, i know .. :(

**Comment by uglyog** [comment]
Are you able to provide debug logs?

**Comment by georgepapas** [comment]
Will try to create a test project...

**Comment by georgepapas** [comment]
I've created this repo which has test cases that demonstrate the issue

https://github.com/georgepapas/pact-issue-212

Looks like when digits are used in the pact body expectation, there is no match, but when alpha characters, things are ok.

**Comment by uglyog** [comment]
I'm not getting the same failures. I did get a failure because the content type was defaulting to `text/plain` instead of `application/json`. I fixed that, and the tests in pact-issue-212 all pass.

**Comment by georgepapas** [comment]
Thanks, has this been released?

**Comment by georgepapas** [comment]
Ignore my last comment, just saw release notes...

**Comment by georgepapas** [comment]
Thanks Ron.

**Comment by uglyog** [comment]
That is the 2.x version, 3.x might be released tomorrow

**Comment by georgepapas** [comment]
Cheers

**Comment by georgepapas** [comment]
Is there a way to override the content type headers in a test in the mean time?

**Comment by uglyog** [comment]
yes

```groovy
      withBody(mimeType: 'application/json;charset=UTF-8') {
        priceAsCents regexp(~/\d{4}/, foo.priceAsCents)
      }
```

**Comment by georgepapas** [comment]
Tops, thanks

**Comment by uglyog** [comment]
But it looks like I might have the release done today
