### ISSUE TITLE
PactDslJsonBody - can not create an object without name

### ISSUE THREAD

**Issue by nikolayg** [DiUS/pact-jvm#217]
I am trying to create a PactDslJsonBody instance, which matches JSON with the following form:
```json
{
  "array": [
       {
          "id": 1,
          "description": "Some Description",
       },
       {
          "id": 2,
          "description": "Some Other Description",
       }
   ]
}
```
My code is something like:
```java
PactDslJsonBody body = new PactDslJsonBody()
.minArrayLike("array", 1)
    .object() // Throws exception
        .integerType("id")
        .stringType("description") 
    .closeObject()
.closeObject().closeArray() // Close the array
```
The problem is that PactDslJsonBody.object always throws and exception and advises to use object(String name).

How can I create an object, without a name that will match the provided Json sample?

**Comment by nikolayg** [comment]
Putting the objects' values directly ins the array element (without surrounding with object-closeObject) resolved the problem.

**Comment by uglyog** [comment]
Yeah, minArrayLike automatically starts an object definition as a convenience so you don't need to call object(). Maybe the docs need to be more explicit?

**Comment by nikolayg** [comment]
Yes, perhaps an example in the doc would make it more clear.

**Comment by mattiasmgn** [comment]
I don't understand this: "Putting the objects' values directly ins the array element (without surrounding with object-closeObject) resolved the problem."
Can you post code that shows it instead of explaining in text?

**Comment by uglyog** [comment]
I assume he meant this:

```java
PactDslJsonBody body = new PactDslJsonBody()
.minArrayLike("array", 1)
    // .object() // should be removed
        .integerType("id")
        .stringType("description") 
    .closeObject()
.closeObject().closeArray() // Close the array
```

**Comment by mattiasmgn** [comment]
Would it be possible to generate the PactDslJsonBody in the same way you can create a java class from json like this?
http://pojo.sodhanalibrary.com/

**Comment by uglyog** [comment]
Yes, it would be possible.

**Comment by goelshubham1509** [comment]
Is there a tool to auto-generate the PactDSL body for a given JSON?

**Comment by uglyog** [comment]
I have not seen one. Someone once mentioned that they were going to create one (a few years ago), but I can't recall where they got with that. A Google search turned up https://github.com/remondis-it/pact-consumer-builder, which builds it from Java objects.
