### ISSUE TITLE
There is no way to undo state set after a test is completed.

### ISSUE THREAD

**Issue by ShaneDelmore** [DiUS/pact-jvm#220]
It would be nice to be able to call a state change event to setup state for a test, run the test, then call a revert of some sort to tear down the temporary state needed for the previously completed test.

**Comment by uglyog** [comment]
I'm thinking of using the same state change URL, but just include an `action=teardown` for the tear down call after the test is run.

**Comment by ShaneDelmore** [comment]
That sounds very useful.

**Comment by uglyog** [comment]
Implemented and published updated version
