### ISSUE TITLE
pact-jvm set up problem.

### ISSUE THREAD

**Issue by ashishk29** [DiUS/pact-jvm#222]
I am trying to set-up the pact-jvm project to my local but after configuring the project from Git, I got many issues in import and other functions that it is not resolved. Below are the few examples but I am getting in many files in places.

1. In ConsumerPactBuilder.java file , import au.com.dius.pact.model.RequestResponseInteraction; is not resolved.
2. In TestRun.java file "au.com.dius.pact.model.MockProviderConfig" is not resolved.

Is there any issue and or it's still in development phase? Please suggest if I need to follow any additional steps.

**Comment by uglyog** [comment]
You mentioned import. Is this in Eclipse? Looks like the classpath is not being setup correctly.

**Comment by ashishk29** [comment]
Thanks for quick response!!

Yes, It's in eclipse. I checkout the project from GIT repository. Since it's a gradle version, so all the dependency should be automatically resolved. But unfortunately it did not happen.

**Comment by uglyog** [comment]
It works ok in Intellij. I'll have to check what Eclipse is doing.

**Comment by ashishk29** [comment]
Ok. meanwhile I will try with Intellij. Thanks for your effort.

**Comment by uglyog** [comment]
I have not been able to get the project to work in Eclipse. Even after installing the Gradle, Groovy and Scala plugins, following the guide at https://docs.gradle.org/current/userguide/eclipse_plugin.html.

Pact-JVM is written in multiple languages (Java, Scala, Groovy and Clojure). I don't think Eclipse can handle that, or it will be complex to get it work.

**Comment by ashishk29** [comment]
Alright, but I want to learn it. I have already spend some time with Intellij but could not configured successfully. I will try it again and will ask you if I would unable to set-up it. 

Thanks Again !!

**Comment by uglyog** [comment]
With IntelliJ, you need to select 'File | New | Project from Existing Sources ...' , select the directory you cloned the project to, and then Gradle from the 'Import project from external model' option. Just go with the defaults from there on.

**Comment by ashishk29** [comment]
It start working with IntelliJ. Closing this issue.

Thanks.

**Comment by artamonovkirill** [comment]
@uglyog, after doing as you proposed, I still can't run my tests in Intellij:
```
Information:Kotlin: kotlinc-jvm 1.2.31 (JRE 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
Information:Modules "pact-jvm-matchers_2.12_main", "pact-jvm-pact-broker_main", "pact-jvm-model_main" were fully rebuilt due to project configuration/dependencies changes
Information:13-6-18 20:10 - Compilation completed with 84 errors and 16 warnings in 28 s 738 ms
...
Error:(12, 31) not found: type BodyMatcher
class JsonBodyMatcher extends BodyMatcher with StrictLogging {
...
```
I presume there's something with my Kotlin setup, but as I'm new to Kotlin, I can't tell what exactly is wrong.
Any hints?
Thank you in advance.

**Comment by uglyog** [comment]
@artamonovkirill did you create the project as per https://github.com/DiUS/pact-jvm/issues/222#issuecomment-198218627 ?

**Comment by artamonovkirill** [comment]
@uglyog, yep, that's what I did.
Also, it builds fine with gradle (command line).

**Comment by artamonovkirill** [comment]
@uglyog, that did the trick, thank you!
