### ISSUE TITLE
HttpTarget out-of-the-box producer doesn't allow path expressions

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#227]
HttpTarget out-of-the-box producer doesn't allow path expressions.

HttpTarget constructor only allows you to set protocol, host and port but it doesn't allow you to set the `path` of the application. If your application is running in different context rather than root (`/`) then you cannot use it (basically you need to implement your own Target). 

I think that the best way to proceed would be modify this method:

```
 private ProviderInfo getProviderInfo() {
        final ProviderInfo providerInfo = new ProviderInfo();
        providerInfo.setPort(port);
        providerInfo.setHost(host);
        providerInfo.setProtocol(protocol);

      final List<FrameworkMethod> methods = testClass.getAnnotatedMethods(TargetRequestFilter.class);
      if (testClass != null && !methods.isEmpty()) {
          providerInfo.setRequestFilter((Consumer<HttpRequest>) httpRequest -> methods.forEach(method -> {
            try {
              method.invokeExplosively(testTarget, httpRequest);
            } catch (Throwable t) {
              throw new AssertionError("Request filter method " + method.getName() + " failed with an exception", t);
            }
          }));
        }

        return providerInfo;
    }
```

and also add a new constructor which takes a URL as a parameter.

I can provide PR about this.

**Comment by uglyog** [comment]
So what you are looking for is a base path that is prefixed to all HTTP requests made during the test run?

**Comment by lordofthejars** [comment]
Well in my example I have one docker image and the server is deployed in a base path (basically WAR file is called starwars.war so the base is `/starwars`). 

Then the REST endpoints are in `/rest/......` so the gateway class makes a connection to the endpoint with something like `WebTarget peopleTarget = client.target(planetsUrl).path("rest/planet/orbital/average");` were `planetsUrl` can be `http://localhost:8080/starwars` or `http://dockerHost:9090/starwars` or whatever.

Obviously the test on the consumer looks like:

```
return builder
                .given("planets aggregator")
                .uponReceiving("Planets average calculation")
                    .path("/rest/planet/orbital/average")
                    .method("GET")
```

Since the `clientUrl` changes depending on where it is deployed, maybe it could be even `http://localhost:8080/starwars-SNAPSHOT` but what it doesn't change is the REST URL part.

But then let's look at producer part, if you want to use the default `HttpTarget`, you get the problem that you can only specify the protocol `http`, the port `8080` and the host `localhost`, but you cannot add the path which in my case is `starwars`.

What I have done is copy paste the `HttpTarget` class and add one constructor https://gist.github.com/lordofthejars/b76b4138304c66259b10 but If you agree I could send a PR in the `HttpTarget` class so everyone can use the same.

**Comment by uglyog** [comment]
That will definitely be helpful for others. A pull request would be awesome, but if you don't have the time I could sort it out for you.

**Comment by lordofthejars** [comment]
No worries, I have always time to contribute to open source community.  :) More discussions coming in next hours

**Comment by lordofthejars** [comment]
I close the issue since it has been merged the change.
