### ISSUE TITLE
unable to run http://localhost:29999/create?state=NoUsers with pact-jvm-server

### ISSUE THREAD

**Issue by anurag0249** [DiUS/pact-jvm#231]
Hi ,

I am facing problem to execute an example on pact-jvm-server.
I have started pact-jvm server and its listening on port 29999 and GET call of " http://localhost:29999" giving JSON "{"ports": []}" in response.
I am using Postman for executing POST call http://localhost:29999/create?state=NoUsers
but I am not getting what will be perfect JSON for above post request.

**Comment by uglyog** [comment]
What response are you getting? Are you getting an invalid JSON response?

Also, could you let us know how you where running the server (via archive bundle, docker, etc.) and could you provide debug logs?

**Comment by anurag0249** [comment]
Thanks Uglyog ,

I am getting 500 Internal server error.

yes , I am running server from archive bundle by executing "pact-jvm-server_2.11.bat" but I also added pact-jvm-consumer-junit_2.11-3.2.5.jar into server lib.

I have attached the debug log.
[DebugLog.txt](https://github.com/DiUS/pact-jvm/files/191364/DebugLog.txt)

**Comment by uglyog** [comment]
Fixed the issue and I released an updated version (3.2.6)

**Comment by anurag0249** [comment]
I think another regression issue occurred . No build directory created into pact-jvm-server after update and build. Please verify.
