### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by anurag0249** [DiUS/pact-jvm#235]
Hi,

when I am trying to building pact-jvm from cmd by using command "gradlew.bat build". It is failing, Error is given below .
Please let me know how can I fix this.

:pact-jvm-consumer_2.11:compileTestScala
:pact-jvm-consumer_2.11:processTestResources UP-TO-DATE
:pact-jvm-consumer_2.11:testClasses
:pact-jvm-consumer_2.11:test

au.com.dius.pact.consumer.PrettyPrinterSpec > header mismatch FAILED
    org.specs2.reporter.JUnitPrinter$$anon$1
au.com.dius.pact.consumer.PrettyPrinterSpec > path mismatch FAILED
    org.specs2.reporter.JUnitPrinter$$anon$1
au.com.dius.pact.consumer.PrettyPrinterSpec > body mismatch FAILED
    org.specs2.reporter.JUnitPrinter$$anon$1
44 tests completed, 3 failed
:pact-jvm-consumer_2.11:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pact-jvm-consumer_2.11:test'.
> There were failing tests. See the report at: file:///E:/pact_testing/junit/pact-jvm/pact-jvm-consumer/build/2.11/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 55.549 secs

**Comment by uglyog** [comment]
I've never run the build on windows. I'll need to setup a VM to find out what is happening.

**Comment by anurag0249** [comment]
I don't think its OS dependent issue. I am getting same error when building pact-jvm in intellij IDE.
As you can see in screenshot.
![buildfail](https://cloud.githubusercontent.com/assets/12272785/14099884/e059169a-f5a6-11e5-844e-92c27e4dae4e.PNG)

**Comment by uglyog** [comment]
That test works on Linux and OSX, so it must be a windows specific failure. It might be due to windows line endings.

**Comment by uglyog** [comment]
Don't know why it was failing, but it seems to be an issue with specs2. I converted it to a spock groovy test, and it passes ok.

**Comment by anurag0249** [comment]
Still build fail, Please see attached screen
![buildfail](https://cloud.githubusercontent.com/assets/12272785/14104821/e33453c0-f5c4-11e5-9799-5c7f8fe08acf.PNG)

**Comment by uglyog** [comment]
All good now, travis CI build is passing: https://travis-ci.org/DiUS/pact-jvm/builds/119204532

**Comment by anurag0249** [comment]
Good,  But fail somewhere else now,
Please see screen.
![buildfail](https://cloud.githubusercontent.com/assets/12272785/14105338/9dfff94a-f5c8-11e5-93c3-625440e62448.PNG)

**Comment by uglyog** [comment]
You need to install maven to build the maven plugin.

**Comment by anurag0249** [comment]
but as per stack trace it's looking for mvn.bat into "pact-jvm-provider-maven" .
Error :  Caused by: java.io.IOException: Cannot run program "mvn.bat" (in directory "D:\pact\pact-jvm\pact-jvm-provider-maven"): CreateProcess error=2, The system cannot find the file specifi
ed


![buildfail](https://cloud.githubusercontent.com/assets/12272785/14106217/6547a1a2-f5cd-11e5-9925-444d2d673806.PNG)

**Comment by uglyog** [comment]
The maven bin directory needs to be in the path. If the maven you downloaded does not have a `mvn.bat` in the
bin directory, just copy or rename `mvn.cmd` to `mvn.bat`.

```
C:\Users\Ronald\pact-jvm>
C:\Users\Ronald\pact-jvm>set PATH=%PATH%;C:\Users\Ronald\apache-maven-3.3.9\bin

C:\Users\Ronald\pact-jvm>mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:41:47+11:00)
Maven home: C:\Users\Ronald\apache-maven-3.3.9\bin\..
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_77\jre
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

C:\Users\Ronald\pact-jvm>mvn.bat --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:41:47+11:00)
Maven home: C:\Users\Ronald\apache-maven-3.3.9\bin\..
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_77\jre
Default locale: en_AU, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by anurag0249** [comment]
Thanks Ronald, 
It's working after setup environment variable PATH properly.
