### ISSUE TITLE
Please brief the flow of pact provider jvm junit.

### ISSUE THREAD

**Issue by ashishk29** [DiUS/pact-jvm#246]
I would like to understand the flow of Pact-jvm-provider-junit. I have explored the example of ContractTest and it's fine but suppose if we need to verify the new pact file (.json) then where should I write the verification code? If we have multiple pact files with different format then how we can verify the pact files?

Please brief high level so that I can move further. Thanks!

**Comment by uglyog** [comment]
Pact-jvm-provider-junit allows you to validate pact files via a JUnit test. You don't write the verification code, the Pact-jvm-provider-junit does that. You just define the source of the pact files (URLs, directories on disk or pact files stored in a pact broker), and the target to validate the requests against (currently on HttpTarget has been implemented).

You're test class is responsible for making sure your provider is started before and torn down afterwards. You can use the standard JUnit `@Before` and `@After` annotated methods for that.

**Comment by ashishk29** [comment]
Thanks Ronald,

I was exploring HTTPTarget and found It is comparing actualResponse with interaction.getResponse() and interaction response is what defined into pact json(contract.json) but I am not getting how jetty server returning actual response. is it already defined there? could you brief about how other request /data ,/second will work ?

**Comment by uglyog** [comment]
I'm not sure I understand this statement: _but I am not getting how jetty server returning actual response_

This is how jetty will work. If you make a HTTP request to a running jetty server, it will return an HTTP response.

I think what you are trying to ask is how do you get your provider to be running for the test, and this depends on how your provider is implemented. Is it a web application, or are you using a micro-service framework like SpringBoot or DropWizard?

The Pact-jvm-provider-junit library will make each request it finds in all the pact files provided and compare the actual response back from the running provider based on the HttpTarget annotation. It will then report back on all the requests made and fail the test if any did not match.
