### ISSUE TITLE
integerType generating numbers larger than integer. #209 fix in version 3.2.3 can't be run in project using Java 1.7

### ISSUE THREAD

**Issue by ajhcpt** [DiUS/pact-jvm#247]
In my project we are still running Java 1.7. It seems like the jars for version 3.2.3 are compiled using java 1.8, so when trying to run with this version I get this error:

An exception or error caused a run to abort: au/com/dius/pact/consumer/TestRun : Unsupported major.minor version 52.0 
java.lang.UnsupportedClassVersionError: au/com/dius/pact/consumer/TestRun : Unsupported major.minor version 52.0

Which is the latest version that was still compiled with Java 1.7 and could it get this fix (#209) included?

**Comment by uglyog** [comment]
Use the 2.x branch, it is compiled with Java 1.6. The current version is 2.4.8, which includes this fix (it was fixed in version 2.4.5)

**Comment by ajhcpt** [comment]
Awesome! thanks.
