### ISSUE TITLE
Ignore body when validating

### ISSUE THREAD

**Issue by Hazz223** [DiUS/pact-jvm#248]
I've got a consumer that when requesting something by ID from a provider, I expect a 404 returned when it doesn't exist. I don't care about the body, purely the status code.

However, in version 2.4.8, I get an issue where the pact test fails, as it expects no body, but one is returned. This doesn't happen in previous versions of the library.

Is there a way around this?

**Comment by uglyog** [comment]
In Pact we distinguish between an empty body (meaning the body must be empty) and a missing body (meaning the body is not important). I can't see any change made in 2.4.8 that would have changed this.

Normally this is achieved by not defining the body in the consumer test, i.e. if using JUnit

```java
    ...
    .willRespondWith()
        .status(404);
```

This should create a Pact interaction where the body is not included (have a look at your pact json files).

```json
    "response": {
        "status": 404
    }
```

**Comment by lplotni** [comment]
Using the **3.2.9** version and following setup 
```java
 .willRespondWith()
    .status(201)
    .toFragment()
```
 I'm getting  
```javascript 
"response": { 
    "status": 201, 
    "body": null
}
```
Shouldn't it be the following?
```javascript 
"response": { 
    "status": 201
}
```

**Comment by uglyog** [comment]
Yes it should. I'll investigate.

**Comment by uglyog** [comment]
Confirmed as a defect.

**Comment by uglyog** [comment]
The generated JSON should now not include the missing body.

**Comment by uglyog** [comment]
Version 3.2.10 has been released with the fix.

**Comment by Hazz223** [comment]
Thanks for this. I'll give it a go!

**Comment by alonpeer** [comment]
This issue seems to still exist in `PactFragmentBuilder`. 
When running [ExamplePactSpec](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-specs2/src/test/scala/au/com/dius/pact/consumer/specs2/ExamplePactSpec.scala#L27), you would expect to get a pact json with no `body` field, but in fact you get `"body": ""`.
