### ISSUE TITLE
How to get RequestResponseInteraction from Pact class

### ISSUE THREAD

**Issue by kumarSC** [DiUS/pact-jvm#249]
Hi @uglyog ,

We have been using Pact (2.4) for running the provider test as below,
```
      List<Pact> pacts = pbl.load("Test Service"); 

        for (Pact pact : pacts) {
            for (Interaction i : pact.getInteractions()) {
                try {
                    i.getDescription();
                    target.testInteraction(i);
```
We recently updated to version(3.2.4) and realized that `testInteraction()` method expects object of type `RequestResponseInteraction`, there is no public method to convert `Interaction i` to type `RequestResponseInteraction`, Could you please suggest a workaround/fix?

**Comment by uglyog** [comment]
`Interaction` is now an interface, and `RequestResponseInteraction` is the implementation. Just cast it if you are not using message pacts, otherwise just do a `instanceof` check.

E.g.,

```
List<Pact> pacts = pbl.load("Test Service"); 

        for (Pact pact : pacts) {
            for (Interaction i : pact.getInteractions()) {
                try {
                    i.getDescription();
                    RequestResponseInteraction rri = (RequestResponseInteraction) i;
                    target.testInteraction(rri);
```
