### ISSUE TITLE
The JVM version does have an eachLike matcher, but it assumes an array of objects. It won't currently work with an array of strings. 

### ISSUE THREAD

**Issue by nnarendravijay** [DiUS/pact-jvm#256]
Looks like Ruby has the support from the documentation from the following page to assert for a few elements in an array using each_like(). Reference: https://github.com/realestate-com-au/pact/wiki/v2-flexible-matching

How can I achieve this in Java ?

For example:

```
PactDslJsonBody body = new PactDslJsonBody()
    .stringType("preference")
    .stringType("subscriptionId")
    .array("types").stringType().eachLike("abc", "def").closeArray().asBody();
```

The above doesn't work though. The JVM version does have an eachLike matcher, but it assumes an array of objects. It won't currently work with an array of strings

**Comment by uglyog** [comment]
Although not as elegant as your example, I was able to extend the `eachLike` method to handle arrays of values that are not objects.

This example:

```java
PactDslJsonBody body = new PactDslJsonBody()
      .stringType('preference')
      .stringType('subscriptionId')
      .eachLike('types', PactDslJsonRootValue.stringType('abc'), 2);
```

generates the following JSON:

```json
{
  "types":["abc","abc"],
  "preference":"CLSSvnSComcUHKmXFhCK",
  "subscriptionId":"gYamPCZqxpyynNIEiMpH"
}
```

and the following matchers:

```json
{
  ".types": {"min": 0, "match": "type"},
  ".types[*]": {"match": "type"},
  ".subscriptionId": {"match": "type"},
  ".preference": {"match": "type"}
}
```

**Comment by uglyog** [comment]
Released fix with versions 3.2.8/2.4.10

**Comment by aniket-21** [comment]
This doesn't work for me in Java

**Comment by uglyog** [comment]
Re-opening to extend this behavior to root level arrays.

**Comment by uglyog** [comment]
@aniket-21 what behaviour are you experiencing?

**Comment by aniket-21** [comment]
here is the issue @uglyog , https://github.com/DiUS/pact-jvm/issues/385

**Comment by aniket-21** [comment]
I tried fixing it for java but then it broke the groovy implementation, so I closed the PR

**Comment by metaflow** [comment]
@uglyog I am also struggling with arrays of string
```
DslPart request = new PactDslJsonBody()
  .eachLike("keywords", PactDslJsonRootValue.stringType("foo"), 1);
```
produces `..."body": { "keywords": [ "\"foo\"" ] }...` (note escaped qoutes). Should I open different issue for that?

**Comment by aniket-21** [comment]
@metaflow, #385 is raised for the same issue you are facing

**Comment by uglyog** [comment]
Released 3.3.9 with the updated eachLike methods

**Comment by jaideeprana** [comment]
I have use-case where I'm expecting PactDslJsonRootValue to contain one value as string and another one as an integer.
Here's the example:

`"someArray": [
      "some value that is a string",
     1
]`

I'm not able achieve this using eachLike and PactDslJsonRootValue.

**Comment by uglyog** [comment]
LambdaDsl issue is tracked in #701
