### ISSUE TITLE
matchingRules for "null or <Type>"

### ISSUE THREAD

**Issue by surpher** [DiUS/pact-jvm#261]
A provider is returning either `{ ... "totals" : null ... }` if there is no data available, or `{ ... "totals" : 8724.76 ... }` when there is data available. 
When writing withBody {} DSL, the regex() doesn't work as it deals with strings and numeric() doesn't work either.

An option to either have a null or a type would be beneficial. 

Reasoning behind this is in finance. Given you are budgeting and your budget sums down to 0, and is returned as "totals" : 0. Given you are not budgeting at all, the value is returned as `"totals" : null` (and not null as a string i.e.: `"totals" : "null"`)

**Comment by uglyog** [comment]
I can implement a decimalOrNull matcher, but this will only work on the JVM version. The other problem is the DSLs generate random examples when the example value is null, so you will never be able to generate a null example.

It would probably be better to implement something like `or(decimal, nullValue)` that extends the V3 matcher proposal  https://github.com/pact-foundation/pact-specification/tree/version-3#allow-arrays-of-matchers-to-be-defined-against-a-matcher-path

**Comment by surpher** [comment]
The `or(decimal, nullValue)` would look much better imo.

**Comment by ian-ellis** [comment]
@uglyog I can see you are working on a beta for 3.5 that will implement the V3 Spec. Will this feature be in the 3.5 release? I really need to be able to test for a string or null value. We have control of the API but changing it would break legacy versions of our app.

Also when using the 3.5.0-beta.3 all my type matchers fail because they try to do an exact match rather than a type match.

**Comment by uglyog** [comment]
The V3 changes provide the mechanism to implement this, but the DSLs will need to be updated and a null matcher implemented.

Can you provide more information (logs, example test case) of the type matchers not working?

**Comment by ian-ellis** [comment]
@uglyog Here is what I'm doing in regards to the type matchers failing

My **Pact Builder**: https://gist.github.com/ian-ellis/a5efb25fe7f6b9076b04c1e3309fe3cb
Produces this pact file in **V2**, which **passes**: https://gist.github.com/ian-ellis/4a67cae80aac9e2230086a6deda9c9ef 
Produces this pact file in **V3**: https://gist.github.com/ian-ellis/d70400ee3a42ae8deaae051d19c69b57 
which **fails** with this error message: https://gist.github.com/ian-ellis/cf68c822639469894edef3a15b4af0ab

Let me know if you need any more details.

As for updating the DSL and implementing a null matcher, is this something that would be provided by project or implemented by the user?

**Comment by uglyog** [comment]
Thanks for that.

It will be implemented by the project.

**Comment by lippea** [comment]
Just wanna to show interest to the feature of "null or <Type>", not only for number, but also for string

**Comment by welcor** [comment]
We have the same issue - interestingly enough, we have two fields that are mutually exclusive ("current owner" and "day of deletion") where always will send either one or the other as null. 
Currently, we handle this through checking two different resources, with their own pactbuilder.

**Comment by uglyog** [comment]
V3 implementation has been released (v3.5.x) that supports this feature.
