### ISSUE TITLE
v3.2.1+ Mock server seems to ignore withHeaders('Content-Type' : 'application/vnd.api+json')

### ISSUE THREAD

**Issue by surpher** [DiUS/pact-jvm#263]
In Groovy version 3.2.7 (using Gradle), when writing a test as 

            uponReceiving('a request for')
            withAttributes(method: 'get',
                    path: '/profitLossReport',
                    query: ['reportBreakdown': someQuery],
                    headers: reportingHeader
            )
            willRespondWith(
                    status: 200,
                    headers: ['Content-Type': 'application/vnd.api+json']
            )

            withBody (mimetype: 'application/vnd.api+json) {}

The mock server always returns `application/json`.

**Comment by uglyog** [comment]
Hmm, I wonder if it is the period that is causing it to not match.

**Comment by surpher** [comment]
It's case sensitive it seems. The following worked.

`withBody([mimeType: 'application/vnd.api+json']) {
                data {}
}`

**Comment by uglyog** [comment]
Yeah, Groovy is case sensitive for map keys.
