### ISSUE TITLE
au.com.dius:pact-jvm-provider-maven_2.11:verify not using regex but actual values

### ISSUE THREAD

**Issue by musk** [DiUS/pact-jvm#264]
I have create the following json from my consumer test and when running the verify via maven against my provider I always get a mismatch on the id. 
My expectation is that verify should use the regex and not the actual example value from the consumer test. 
Is this a defect in the maven plugin?
# Verify Output

<code><pre>1) Verifying a pact between consumer and provider - a request for resource temp returns a response which has a matching body
      $.body.display_name -> Expected 'Temp Unlimited' but received 'Temp Display Name'
      $.body.id -> Expected '121343' but received '19281'

```
  Diff:

  @1
  -    "display_name": "Temp Unlimited",
  -    "id": "121343",
  +    "display_name": "Temp Display Name",
  +    "id": "19281",
      "name": "TEMP",</pre></code>
```
# Consume Test

<code><pre>
 protected PactFragment createFragment(PactDslWithProvider builder) {
        return builder.uponReceiving("a request for resource temp")
                .path("/resource/temp").method("GET")
                .willRespondWith().status(200).body(
                        new PactDslJsonBody()
                                .stringMatcher("id", "[0-9]+", "121343")
                                .stringMatcher("shortname", "\w+", "temp")
                                .stringMatcher("name", "(\s|\w)+", "TEMP")
                                .stringMatcher("display_name", "(\s|\w)+", "Temp Unlimited"))
                .toFragment();
    }
</pre></code>
# consumer-provider.json

<code><pre>{
    "provider": {
        "name": "provider"
    },
    "consumer": {
        "name": "consumer"
    },
    "interactions": [
        {
            "providerState": null,
            "description": "a request for resource temp",
            "request": {
                "method": "GET",
                "path": "/resource/temp",
                "body": null
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json; charset=UTF-8"
                },
                "body": {
                    "display_name": "Temp Unlimited",
                    "id": "121343",
                    "name": "TEMP",
                    "shortname": "temp"
                },
                "matchingRules": {
                    "$.body.display_name": {
                        "regex": "(\s|\w)+"
                    },
                    "$.body.shortname": {
                        "regex": "\w+"
                    },
                    "$.body.id": {
                        "regex": "[0-9]+"
                    },
                    "$.body.name": {
                        "regex": "(\s|\w)+"
                    }
                }
            }
        }
    ],
    "metadata": {
        "pact-specification": {
            "version": "2.0.0"
        },
        "pact-jvm": {
            "version": "3.2.7"
        }
    }
}</pre></code>

**Comment by uglyog** [comment]
It should be using the regular expression. Are you able to enable debug logs when running the provider verification. The logs will have the reason why the regex matcher is not being used.

**Comment by musk** [comment]
Tried running with -X but the output does not give clear identification of the problem. How do I enable more detailed logging.

**Comment by uglyog** [comment]
When running with -X you should see output like the following:

```
Verifying a pact between sampleconsumer and sampleprovider
  [Using file src/test/resources/sample-pact.json]
  Given many activities exist
         WARNING: State Change ignored as there is no stateChange URL
[DEBUG] State Change: "many activities exist" -> true
  a request for activities
[DEBUG] Verifying via request/response
[DEBUG] Making request for provider au.com.dius.pact.provider.maven.Provider(null, null, null):
[DEBUG]         method: GET
        path: /activities
        query: null
        headers: [Accept:application/json]
        matchers: null
        body: au.com.dius.pact.model.OptionalBody(MISSING, null)
[DEBUG] Received response: HTTP/1.1 200 OK
[DEBUG] Response: [statusCode:200, headers:[content-type:application/json, connection:keep-alive, transfer-encoding:chunked], contentType:application/json, data:{"activities":[{"name":"Fred","description":100}]}]
[DEBUG] Found a matcher for application/json -> Some((application/.*json,au.com.dius.pact.matchers.JsonBodyMatcher@244418a))
[DEBUG] compareLists: Matcher defined for path List($, body, activities)
[DEBUG] comparing List(Map(description -> 100, name -> Fred)) with minimum 2 at List($, body, activities)
[DEBUG] compareValues: Matcher defined for path List($, body, activities, 0, description)
[DEBUG] comparing type of 100 to 'f_UXcxIXYhgqtxjiPumRiCo9C5JNDX' at List($, body, activities, 0, description)
[DEBUG] compareValues: Matcher defined for path List($, body, activities, 0, name)
[DEBUG] comparing type of 'Fred' to 'hx55sbvMPk1kF-9' at List($, body, activities, 0, name)
    returns a response which
      has status code 201 (FAILED)
      includes headers
        "Content-Type" with value "application/json" (OK)
      has a matching body (FAILED)
```

You want to look for lines like:

```
[DEBUG] compareValues: Matcher defined for path List($, body, activities, 0, name)
[DEBUG] comparing type of 'Fred' to 'hx55sbvMPk1kF-9' at List($, body, activities, 0, name)
```

This is showing that in my example a matcher is being used for `$.body.activities[0].name`.

**Comment by davecroman** [comment]
I had this issue as well and found that it's a problem with pact-jvm version mismatch between the consumer and the provider. My consumer tests were using version 2.5.0 while my provider was using 3.3.8. When I updated the consumer tests dependency to use 3.3.8, I got rid of the issue.

**Comment by chris-fa** [comment]
Hi, could you explain "running with -X"?  I'm running them by doing a right-click in my PactProviderTest class, and then "Run PactProviderTests" on IntelliJ.  Where should I put the -X?

**Comment by uglyog** [comment]
The `-X` parameter is for Maven. When running from the IDE, you just need to ensure that debug level logging is enabled by making sure that the logback JARs are on the test classpath.
