### ISSUE TITLE
404 on README

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [DiUS/pact-jvm#267]
The link to `pact-jvm-consumer-groovy-v3` is currently a 404 on the README for master

```
My Consumer interacts with a Message Queue

As part of the V3 pact specification, we have defined a new pact file for interactions with message queues. For an implementation of a Groovy consumer test with a message pact, have a look at pact-jvm-consumer-groovy-v3.
```

**Comment by uglyog** [comment]
`pact-jvm-consumer-groovy-v3` was merged with `pact-jvm-consumer-groovy`, so I'll remove the link from the readme.

**Comment by uglyog** [comment]
I have corrected the link, it now points to the actual example test. Thanks for raising that.
