### ISSUE TITLE
Multiple tags specified re-using first tag for @PactBroker in pact-jvm-provider-junit

### ISSUE THREAD

**Issue by hmcgowan** [DiUS/pact-jvm#283]
If I run the provider tests against a pact-broker using a "prod" tag then I get the results I expect (all pass).
@PactBroker(host = <hostname>, port = "80", tags={"prod"} )

If I run against a "dev" tag I also work fine (expect one failure). 
@PactBroker(host = <hostname>, port = "80", tags={"dev"} )

If I run with both tags, I expect to see one failure but they all pass
@PactBroker(host = <hostname>, port = "80", tags={"prod", "dev"} )

Looking at the output I see that when it tries the second retrieval of pacts from the broker, it's doing a get request using the wrong url for the specified tag (full output below)
Console shows this:
>> Loading pacts from pact broker for provider omega_provider and tag **dev**
Then this:
>> GET /pacts/provider/omega_provider/latest/**prod** HTTP/1.1
But I expect to see this:
>> GET /pacts/provider/omega_provider/latest/**dev** HTTP/1.1

So whichever tag is set first in the list of tags is reused for the second request. 

I'm using the docker-latest of pact-broker and this version of the provider. I'm seeing the same behavior back to 3.2.4 when the tags were added to the PactBroker annotation

            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-provider-junit_2.11</artifactId>
            <version>3.2.8</version>
            <scope>test</scope>

Holler if there's any additional information you need

=== full console output ===

12:22:30.018 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 0; route allocated: 0 of 100; total allocated: 0 of 200]
12:22:30.029 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 0; route allocated: 1 of 100; total allocated: 1 of 200]
12:22:30.031 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://qa-pact-broker.dev.aws.lcloud.com:80
12:22:30.039 [main] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to qa-pact-broker.dev.aws.lcloud.com/10.253.113.9:80
12:22:30.043 [main] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 0:0:0:0:0:0:0:1:49465<->10.253.113.9:80
12:22:30.044 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request GET /pacts/provider/omega_provider/latest/prod HTTP/1.1
12:22:30.044 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
12:22:30.044 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> GET /pacts/provider/omega_provider/latest/prod HTTP/1.1
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: application/hal+json
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: qa-pact-broker.dev.aws.lcloud.com:80
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_45)
12:22:30.046 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "GET /pacts/provider/omega_provider/latest/prod HTTP/1.1[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/hal+json[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: qa-pact-broker.dev.aws.lcloud.com:80[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_45)[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
12:22:30.046 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
12:22:30.167 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
12:22:30.167 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/hal+json[\r][\n]"
12:22:30.167 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 535[\r][\n]"
12:22:30.167 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Status: 200 OK[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Tue, 05 Jul 2016 17:22:30 GMT[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: Webmachine-Ruby/1.4.0 Rack/1.3[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Powered-By: Phusion Passenger 4.0.58[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
12:22:30.170 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"_links":{"self":{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacts/provider/omega_provider/latest/prod","title":"Latest pact versions for the provider omega_provider with tag 'prod'"},"provider":{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacticipants/omega_provider","title":"omega_provider"},"pacts":[{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacts/provider/omega_provider/consumer/gopher_consumer/version/0.0.103","title":"Pact between gopher_consumer (v0.0.103) and omega_provider","name":"gopher_consumer"}]}}"
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/hal+json
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 535
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Status: 200 OK
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Tue, 05 Jul 2016 17:22:30 GMT
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: Webmachine-Ruby/1.4.0 Rack/1.3
12:22:30.173 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Powered-By: Phusion Passenger 4.0.58
12:22:30.177 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
12:22:30.180 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80] can be kept alive indefinitely
12:22:30.180 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 1; route allocated: 1 of 100; total allocated: 1 of 200]
12:22:31.034 [main] DEBUG a.c.d.p.p.j.loader.PactBrokerLoader - Loading pacts from pact broker for provider omega_provider and tag dev
12:22:31.035 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
12:22:31.035 [main] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
12:22:31.035 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 1; route allocated: 1 of 100; total allocated: 1 of 200]
12:22:31.035 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 0; route allocated: 1 of 100; total allocated: 1 of 200]
12:22:31.035 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request GET /pacts/provider/omega_provider/latest/prod HTTP/1.1
12:22:31.035 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
12:22:31.035 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> GET /pacts/provider/omega_provider/latest/prod HTTP/1.1
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: application/hal+json
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: qa-pact-broker.dev.aws.lcloud.com:80
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_45)
12:22:31.035 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
12:22:31.035 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "GET /pacts/provider/omega_provider/latest/prod HTTP/1.1[\r][\n]"
12:22:31.035 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept: application/hal+json[\r][\n]"
12:22:31.035 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: qa-pact-broker.dev.aws.lcloud.com:80[\r][\n]"
12:22:31.035 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
12:22:31.035 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_45)[\r][\n]"
12:22:31.036 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
12:22:31.036 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/hal+json[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 535[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Status: 200 OK[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Tue, 05 Jul 2016 17:22:31 GMT[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: Webmachine-Ruby/1.4.0 Rack/1.3[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Powered-By: Phusion Passenger 4.0.58[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
12:22:31.102 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"_links":{"self":{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacts/provider/omega_provider/latest/prod","title":"Latest pact versions for the provider omega_provider with tag 'prod'"},"provider":{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacticipants/omega_provider","title":"omega_provider"},"pacts":[{"href":"http://qa-pact-broker.dev.aws.lcloud.com/pacts/provider/omega_provider/consumer/gopher_consumer/version/0.0.103","title":"Pact between gopher_consumer (v0.0.103) and omega_provider","name":"gopher_consumer"}]}}"
12:22:31.102 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
12:22:31.102 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/hal+json
12:22:31.102 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 535
12:22:31.102 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: keep-alive
12:22:31.103 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Status: 200 OK
12:22:31.103 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Tue, 05 Jul 2016 17:22:31 GMT
12:22:31.103 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: Webmachine-Ruby/1.4.0 Rack/1.3
12:22:31.103 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Powered-By: Phusion Passenger 4.0.58
12:22:31.103 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
12:22:31.103 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80] can be kept alive indefinitely
12:22:31.103 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://qa-pact-broker.dev.aws.lcloud.com:80][total kept alive: 1; route allocated: 1 of 100; total allocated: 1 of 200]INFO [2016-07-05 12:22:37,173] [Thread-1] org.eclipse.jetty.util.log:? Logging initialized @36364ms

**Comment by uglyog** [comment]
That's not good, I'll look into it. Thanks for the info.

**Comment by uglyog** [comment]
Fix has been released with 3.2.9

**Comment by hmcgowan** [comment]
Works great on my side. Thanks for the quick fix!
