### ISSUE TITLE
pact-jvm-provider-maven fails to parse response when using pactBrokerUrl

### ISSUE THREAD

**Issue by mikjonsson** [DiUS/pact-jvm#287]
1. I'm using a setup as described in https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#verifying-pact-files-from-a-pact-broker-version-311231
2. When executing mvn au.com.dius:pact-jvm-provider-maven_2.11:verify it fails with:

> Execution default-cli of goal au.com.dius:pact-jvm-provider-maven_2.11:3.2.10:verify failed: Expected a HAL+JSON response from the pact broker, but got 'application/hal+json;charset=utf-8'.

The same project executes the tests successfully when I explicitly point to a contract in the broker using and configuring for pactUrl instead.

There's a chance I'm missing something else, in which case I'd be very grateful for assistance.

**Comment by uglyog** [comment]
Hmm, it's not handling the charset. I'll fix that.

**Comment by uglyog** [comment]
Fix released with version 3.2.12
