### ISSUE TITLE
Randomly generated matcher value does not match regex

### ISSUE THREAD

**Issue by alonpeer** [DiUS/pact-jvm#288]
I'm using `PactDslJsonBody` in Scala with the specs2 consumer. I'm trying to use a digit matcher like so:

```scala
val body = new PactDslJsonBody().stringMatcher("foo", """bar\d+""")
```

At runtime I get the following error:

```
...
[error]   CAUSED BY au.com.dius.pact.consumer.InvalidMatcherException: Example "bard" does not match regular expression "bar\d+"
[error]   au.com.dius.pact.consumer.dsl.PactDslJsonBody.stringMatcher(PactDslJsonBody.java:259)
[error]   au.com.dius.pact.consumer.dsl.PactDslJsonBody.stringMatcher(PactDslJsonBody.java:273)
...
```

I can currently bypass this by forcing a specific value:

```scala
val body = new PactDslJsonBody().stringMatcher("foo", """bar\d+""", "bar123")
```

However I prefer using the random values, so I can use this with arrays and get different values for each element.

**Comment by uglyog** [comment]
The library that generates the random value from the regex is ignoring the slash, so it is generating values for `bard+`. Use `bar[0-9]+` in the mean time.

**Comment by alonpeer** [comment]
Right, I forgot to mention that `[0-9]+` also works for me.
I'll take a look at that library code, maybe I can fix it there.

**Comment by uglyog** [comment]
The class to look at is https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer/src/main/java/nl/flotsam/xeger/Xeger.java

**Comment by alonpeer** [comment]
Hmm looks like this library isn't supported anymore. 
I will look into integrating an alternative library, such as this: https://github.com/mifmif/Generex

**Comment by uglyog** [comment]
👍
