### ISSUE TITLE
'No service providers are configured' when using gradle pactPublish 

### ISSUE THREAD

**Issue by carwinz** [DiUS/pact-jvm#290]
when I run `./gradlew pactPublish` I get the error `No service providers are configured`

my build.gradle contains

    pact {
        publish {
            pactDirectory = 'build/pacts'
            pactBrokerUrl = 'http://my-pact-broker'
        }
    }

I'm guessing the error is related to pactVerify, but in this case I'm just trying to use pactPublish after generating pacts via JUnit

The error occurs with pact-jvm-provider-gradle_2.11:3.2.10; it worked with 3.2.6

**Comment by uglyog** [comment]
The check for no providers is only done now if the pactVerify task is being run.
