### ISSUE TITLE
gradle pactPublish doesn't give any reason for failures

### ISSUE THREAD

**Issue by carwinz** [DiUS/pact-jvm#291]
If there is an error while running `./gradlew pactPublish`, the output doesn't say what the problem is

This happens:
- when the version number is incorrect (e.g. 1.0-SNAPSHOT)
- when the service name is too similar to another name in the pact broker

Output looks like:

    :pactPublish
    Publishing consumer-service-provider-service.json ... :pactPublish FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':pactPublish'.
    > groovyx.net.http.HttpResponseException: Bad Request
    

It should say that the version is wrong or name is incorrect

**Comment by carwinz** [comment]
Error occurs in `pact-jvm-provider-gradle_2.11:3.2.6`

**Comment by uglyog** [comment]
I could have a look, but the pactPublish task is just the messenger. If the pact broker does not give an indication of the problem, there is not much I can do.

**Comment by uglyog** [comment]
Ok, looks like we do get some error message back, I'll report it back to the console.

**Comment by uglyog** [comment]
The output now looks like:

```console
:pactPublish
Publishing sample-pact.json ... FAILED! 400 Bad Request - Consumer version number '1.0-SNAPSHOT' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1
Publishing sample-pact3.json ... FAILED! 400 Bad Request - Consumer version number '1.0-SNAPSHOT' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1
Publishing sample-pact2.json ... FAILED! 400 Bad Request - Consumer version number '1.0-SNAPSHOT' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1
Publishing v3-message-pact.json ... FAILED! 400 Bad Request - Consumer version number '1.0-SNAPSHOT' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1
:pactPublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
One of more of the pact files were rejected by the pact broker

```
