### ISSUE TITLE
pact-jvm-provider-gradle - Validating number of data on array.

### ISSUE THREAD

**Issue by pedrro** [DiUS/pact-jvm#297]
Hi guys, i'm creating tests using the plugin of pact-jvm-provider for gradle. On pact-broker I have a pact with this body:

```
"body" : [ {
        "name" : "apmHpkclFKdJLAbCNdyS",
         "address" : "apmHpkclFKdJLAbCNdyS"
      } ]
```

So, when I run the request on provider, the request responde me the same body, but, with 2 objects inside array
```
"body" : [ {
        "name" : "apmHpkclFKdJLAbCNdyS",
         "address" : "apmHpkclFKdJLAbCNdyS"
      },
 {
        "name" : "apmHpkclFKdJLAbCNdyS",
         "address" : "apmHpkclFKdJLAbCNdyS"
      } ]
```

And it's giving me an error:

>       $.body -> Expected a List with 1 elements but received 2 elements

So, my question is: **Should pact-jvm-provider validate how much data has inside the array?** In my opinion it should only validate the fields on array, not the length. How can avoid it?

**Comment by uglyog** [comment]
With arrays, it validates that the size is the same. There is a way of specifying a like match, which means that we don't care how many items there are as long as they all correctly match.

You can find more info about using like matchers here: 

- For Java: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#ensuring-all-items-in-a-list-match-an-example-220
- For Groovy: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-groovy/README.md#ensuring-all-items-in-a-list-match-an-example-220

**Comment by pedrro** [comment]
Thanks @uglyog, the example to generate a body with multiple objects works, but, about the behaviour of eachLike(), do you think that it's correct? In provider, it should not care about the quantity of object on body, should just validate about type of each fields on each objects... I would like to know your opinion about this, 😄

**Comment by uglyog** [comment]
That will be different for different people. Some people may need to specify the array size (think of logitude and latitude as an array with two values). Some may need to ensure that the array is never empty, or has a minimum or maximum size.

We use the example to base the matching on, and then have the matchers be able to extend it.

**Comment by pedrro** [comment]
Sure, got it! Thanks for support
