### ISSUE TITLE
Array examples not accepting unnamed items

### ISSUE THREAD

**Issue by AlyGryf** [DiUS/pact-jvm#299]
I have a consumer pact body that includes GeoJSON e.g. 
 `"coordinates": [ 
              [  
                    [  
                       -7.55717,  
                       49.766896  
                    ],
                    [
                        -7.557159,
                        49.766807
                    ]
          ]
]`

A response could hold any number of coordinates so I want to use eachLike() or minArrayLike(). 
`	.object("geometry")
					.stringType("type")
					.array("coordinates")
						.array()
							.minArrayLike(0)
								.decimalType() //unsupported
								.decimalType() //unsupported
                                                                .closeObject()
							.closeArray()
						.closeArray()
					.closeArray()
				.closeObject();`

However, neither of these methods allows the use of unnamed example items, so the above insists on using decimalType(String) which GeoJSON does not provide. As I can use unnamed types outside these methods I don't see why I can't use them inside the eachLike/minArrayLike/maxArrayLike functions

As a work around I tried leaving the coordinates array empty for Postel's law, but I ran into this issue [#298](https://github.com/DiUS/pact-jvm/issues/298)

**Comment by uglyog** [comment]
I see your problem. I'll add a new set of methods to allow you to define arrays of arrays with the each/min/max matchers.

**Comment by uglyog** [comment]
I added `eachArrayLike` methods and was able to replicate the GeoJSON structure with:

```groovy
new PactDslJsonBody()
      .stringType('type', 'FeatureCollection')
      .eachLike('features')
        .stringType('type', 'Feature')
        .object('geometry')
          .stringType('type', 'Point')
          .eachArrayLike('coordinates')
            .decimalType(-7.55717)
            .decimalType(49.766896)
            .closeArray()
          .closeArray()
        .closeObject()
        .object('properties')
          .stringType('prop0', 'value0')
        .closeObject()
        .closeObject()
      .closeArray()
```

This generated the following JSON:

```json
{
  "features": [
    {
      "geometry": {
        "coordinates": [[-7.55717, 49.766896]],
        "type": "Point"
      },
      "type": "Feature",
      "properties": { "prop0": "value0" }
    }
  ],
  "type": "FeatureCollection"
}
```

**Comment by AlyGryf** [comment]
That's brilliant, thank you!
