### ISSUE TITLE
MessagePactBuilder.withContent Only Receive PactDslJsonBody but Not DslPart

### ISSUE THREAD

**Issue by cosineyan** [DiUS/pact-jvm#301]
In our case, the body of a message is a json array. We have to use PactDslJsonArray for arrayEachLike. Is it possible to support this requirement?

**Comment by uglyog** [comment]
I've updated it to take a `DslPart` as the parameter.

**Comment by cosineyan** [comment]
Great. When will the fix be released by the way?

**Comment by uglyog** [comment]
Already released https://github.com/DiUS/pact-jvm/releases/tag/3_2_12

**Comment by cosineyan** [comment]
Thanks a lot.
