### ISSUE TITLE
Groovy consumer test does not report the real reason behind failure

### ISSUE THREAD

**Issue by carwinz** [DiUS/pact-jvm#304]
When running a consumer test and the closure passed into PactBuilder.run() throws an exception, the exception is caught and the test fails, but the real reason is not printed in the console. 

The exception ends up in PactMismatch.userError, but PactMismatch.toString() does not print it out.

Example:

```
import au.com.dius.pact.consumer.PactVerified$
import au.com.dius.pact.consumer.VerificationResult
import au.com.dius.pact.consumer.groovy.PactBuilder
import org.junit.Test

class SwallowingUserErrorPactTest {

    @Test
    def void 'create a person'() {
        def myService = new PactBuilder()
        myService {
            serviceConsumer 'some consumer'
            hasPactWith 'some provider'
            uponReceiving 'a request to create a person'
            port 1234
            withAttributes(
                    method: 'post',
                    path: '/person',
            )
            willRespondWith(
                    status: 200
            )
        }
        VerificationResult result = myService.run() {
            throw new RuntimeException('this is not reported')
        }
        assert result == PactVerified$.MODULE$
    }
}
```

The output is 

```
assert result == PactVerified$.MODULE$
       |      |                |
       |      false            Pact verified.
       Pact verification failed for the following reasons:

       The following requests were not received:
       Interaction: a request to create a person
...
```

but there is no mention of 'this is not reported'

**Comment by uglyog** [comment]
This is a problem with the way JUnit handles failure, by throwing an exception. In this case, there are two exceptions that are being raised, a RuntimeException from your test code, and a Pact verification exception because the mock service did not get the requests that it expected. Only a single exception can get thrown, so the Pact library is favouring the verification exception as the more important one and the runtime exception is being lost.

Then to complicate things even more, the assert in your spock test is throwing an AssertionFailed exception, so we now have 3 protential failures with individual exceptions, and only one can get thrown to fail the test.

**Comment by lagershins** [comment]
@uglyog if the issue is that only a single exception can be thrown, wouldn't it be possible to wrap all the root cause exceptions into a single exception and throw that? It could then print out the messages from all the root causes providing as much detail to the user as possible.

**Comment by uglyog** [comment]
We can wrap everything into a single exception, and this is probably what I'm going to do unless I can think of a better way. The main problem is going to be a lot of error output coming from up to 3 different exceptions.

**Comment by uglyog** [comment]
I've started working on a new mock server implementation, and I've updated the test framework to display the error in the following form (still WIP so it will be improved in time):

```
java.lang.AssertionError: Pact Test function failed with an exception, possibly due to Mismatches(mismatches=[PartialMismatch(mismatches=[QueryMismatch(status,good,bad,Some(Expected 'good' but received 'bad' for query parameter 'status'),$.query.status.0)])])
```

**Comment by uglyog** [comment]
For your test, the output is a little bit ugly, but it is all there:

```
Assertion failed: 

assert result == PactVerificationResult.Ok.INSTANCE
       |      |                            |
       |      false                        au.com.dius.pact.consumer.PactVerificationResult$Ok@2bf5dc88
       Error(error=java.lang.RuntimeException: this is not reported, mockServerState=ExpectedButNotReceived(expectedRequests=[	method: post
       	path: /person
       	query: [:]
       	headers: [:]
       	matchers: [:]
       	body: au.com.dius.pact.model.OptionalBody(MISSING, null)]))
```
