### ISSUE TITLE
Groovy consumer: match array of strings

### ISSUE THREAD

**Issue by carwinz** [DiUS/pact-jvm#308]
Similar to #256, but for the groovy consumer. Can we match a list of strings?

Something like:
    
    willRespondWith(...)
    withBody {
        permissions eachLike(3) { ->
            'GRANT'
         }
    }

which would generate json like

    "permissions": ['GRANT', 'GRANT', 'GRANT']

and matchers like

    ".permissions": {"min": 0, "match": "type"},
    ".permissions[*]": {"match": "type"}

**Comment by uglyog** [comment]
I've implemented it without the need for the closure (they map to objects). Also, the second matcher in your example is not necessary as they cascade.

So, for 

```groovy
withBody {
        permissions eachLike(3, 'GRANT')
}
```

will generate the following JSON

```json
{
    "permissions": ["GRANT", "GRANT", "GRANT"]
}
```

and matchers

```json
{
    "$.body.permissions": {"match": "type"}
}
```

and now you can even get more fancy

```groovy
withBody {
        permissions eachLike(3, regexp(~/\w+/))
        permissions2 minLike(2, 3, integer())
        permissions3 maxLike(4, 3, ~/\d+/)
}
```

**Comment by carwinz** [comment]
Looks good! Thanks @uglyog
