### ISSUE TITLE
Publish all versions to https://plugins.gradle.org/plugin/au.com.dius.pact

### ISSUE THREAD

**Issue by rcaval** [DiUS/pact-jvm#310]
Hi, we are still using java 1.7 and only pact 2.x is compatible with java 7.
We can successfully generate pact files using pact 2.4.14, but we cannot use is in our gradle pactVerify step since only 2.2.12 is published to plugins.gradle.org.

Our current problem is that the decimal matcher was introduced after 2.2 and we cannot use it in our verification step.
the stacktrace snipped looks like this:

```
     Request Failed - decimal (of class java.lang.String)
scala.MatchError: decimal (of class java.lang.String)
	at au.com.dius.pact.matchers.Matchers$.matcher(Matchers.scala:61)
	at au.com.dius.pact.matchers.Matchers$.domatch(Matchers.scala:49)
	at au.com.dius.pact.matchers.JsonBodyMatcher.compareValues(JsonBodyMatcher.scala:128)
	at au.com.dius.pact.matchers.JsonBodyMatcher.compare(JsonBodyMatcher.scala:55)
```

Is it possible to publish other versions to the gradle plugin portal?
Is there any other workaround (other than generating our pact files with 'real' instead of 'decimal')?

**Comment by uglyog** [comment]
Sure, I'll push the latest 2.x version.

**Comment by uglyog** [comment]
2.4.14 is now available from the gradle plugin portal
