### ISSUE TITLE
Consumer's JSON request matching failed when content type starts with application/json

### ISSUE THREAD

**Issue by phantomread1** [DiUS/pact-jvm#315]
Hi,

I've been playing with the consumer pact test and I noticed the JSON request matching  is failed when the content type is not strictly application/json. Our client and server communicate using json-rpc so the content type set by the json rpc client is **application/json-rpc** rather than application/json.

In this case, it seems pact-jvm's consumer does not recognize the content type and will treat the request as String hence a String comparison is done which consequently causes the matching failed. 

Is there a way we can enhance the pact-jvm to accept aplication/json-rpc and treat it as json content ? perhaps using a startsWith sort of check will do?

Thanks

**Comment by uglyog** [comment]
I'll add `application/json-rpc` to the list.

**Comment by phantomread1** [comment]
thanks, the consumer I've been using is **pact-jvm-consumer-junit**

**Comment by uglyog** [comment]
Released with version 3.3.1
