### ISSUE TITLE
BodyMismatch behaviour change when using JSON DSL in version 3.5.0-beta.2

### ISSUE THREAD

**Issue by phantomread1** [DiUS/pact-jvm#320]
Hi,

Since the issue https://github.com/DiUS/pact-jvm/issues/315 was resolved in 3.5.0-beta.2, I noticed there is a behaviour change when matching using JSON DSL.

Previously, a DSL defintion like below, would match types only (I think), e.g. any String ID, String method would result in a match. 
` DslPart requestDSL = new PactDslJsonBody()
        .stringType("id")
        .stringType("method")
        .stringType("jsonrpc", "2.0")
        .array("params")
        .stringType("QIZ")`

A request with id='any string" and method='any string" will be a match.

However, when I switch to version 3.5.0-beta.2
I got the following errors:

`au.com.dius.pact.consumer.PactMismatchException: Pact verification failed for the following reasons:
Search criteria is AKL to WLG:
    BodyMismatch - Expected 'AHMtUMgQiojtURTRUnRT' but received 'fixed'
    BodyMismatch - Expected 'UoNIWQxkXLaJdxyuaPBf' but received 'getPricesByTravelDate'
    BodyMismatch - Expected '2016-01-02' but received '2011-01-02'
`
It seems the body matching now requires the request to match not only the type but also the actual **example value.** 

I have rolled back to the previous version and it works fine (with temp hack of setting content type to application/json)

**Comment by uglyog** [comment]
Hmm, that's not good! Looks like we have a regression, I'll try to diagnose it. How are you verifying your pacts?

**Comment by phantomread1** [comment]
I am using the ConsumerPactTest.

It fails the verification in this method:

` @Override
  protected PactFragment createFragment(PactDslWithProvider builder)`

**Comment by uglyog** [comment]
I was unable to reproduce this. The example test I created is https://github.com/DiUS/pact-jvm/blob/v3-spec/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/Defect320Test.java but it passes.

**Comment by phantomread1** [comment]
@uglyog Hi, I think you somehow fixed this in 3.3.1. I run this in 3.3.1 and it works fine. It was broken in 3.5.0-beta.2. Anyway good it is fixed now. thanks
