### ISSUE TITLE
[Reports] Allow dynamic reporters

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#321]
In class https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider/src/main/groovy/au/com/dius/pact/provider/reporters/ReporterManager.groovy#L20 you can see that if reporter name is not set an exception is thrown. Why not instead of throwing an exception, we don't try first to treat that value as fully qualified class name and instantiate it as custom reporter?

**Comment by uglyog** [comment]
That's a really good idea.

**Comment by lordofthejars** [comment]
Ok, I will provide a PR soon

**Comment by uglyog** [comment]
Released with version 3.3.1
