### ISSUE TITLE
pact-jvm-provider-lein :state-change-url throws an exception because of incorrect type

### ISSUE THREAD

**Issue by gregmcaree** [DiUS/pact-jvm#322]
Following error occurs when using :state-change-url as String and as URL

1) As string
:state-change-url "https://localhost:3000/example" 
throws "java.lang.String cannot be cast to java.net.URL". 

2) As URL
So on trying to use URL for 
:state-change-url (-> (URL.) 
                                 "http://localhost:3000/example") 
throws "clojure.lang.PersistentList cannot be cast to java.net.URL"

**Comment by uglyog** [comment]
With this fix, you can use the string form.

**Comment by uglyog** [comment]
This has been released with version 3.3.2
