### ISSUE TITLE
support specifying the provider port at runtime

### ISSUE THREAD

**Issue by staekblw** [DiUS/pact-jvm#325]
Because multiple project share the same build node, so we need use a random port for the service provider. So it would be nice if pact jvm gradle can support specifying the provider port at runtime just like it support specifying the provider host at runtime.

**Comment by alonpeer** [comment]
I guess this could be done. But I'd like to suggest another approach which we do in my org. We run our provider service in a docker container, and use `--expose` to expose the static port in which its running. This way you can run as many containers as you want on the same build node, without collisions.

**Comment by uglyog** [comment]
This has been released with version 3.3.2
