### ISSUE TITLE
[Question] Provider-Driven Contracts

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#327]
Hello, I have next question regarding Pact and Provider-Driven Contracts. Let me explain the scenario first:

Sometimes the provider needs to define the contract, for example suppose a security service. Probably the contract in this case will be defined by security team, then any service (consumer) that wants to for example log into the system, or encrypt any data would need to follow this contract. Also probably it will be the case that at time of defining the contract, there will be no consumer developed yet, so the question is how to proceed with this use case?

Let me share my vision of what should be and then let's discuss if it is possible or not:

1) Provider team should be able to define the contract using PactBuilder
2) This Pact builder should be bundled inside a (`jar`) so any consumer can downloaded and use it.
3) Provider should be able to convert this Pact Builder object into a Pact json file so it can validate by himself that he is meeting the contract other consumers are going to follow.

I think that: 

Point 1) is easy, in fact it is already supported.

Point 2) it is supported somehow since consumer test part (in case for example of JUnit) you can call inside @Pact method any other static method defined inside the `jar` created by Provider team

Point 3) I don't know if it is easy to convert a PactBuilder to Pact json file. If it is easier then provider could use an special PactLoader which loads a JAR file in classpath, gets the PactBuilder, converts to Pact Json format to finally execute as usually the provider tests (using `Target`)

Probably it would require some other minor modifications, for example in these kind of tests you don't need to specify any specific consumer since all the consumers must follow the same contract.

WDYT?

**Comment by uglyog** [comment]
I think it is achievable. Is there an reason you would not just bundle the pact files into the JAR?

For a similar approach (but using Swagger) see https://bitbucket.org/atlassian/swagger-request-validator

**Comment by lordofthejars** [comment]
In theory would be always a jar file since what I think it is important is to be able to reuse the contract defined as `PactBuilder` into consumer part. So consumers don't need to create the stubs simply they can reuse the ones defined by provider. The only thing is that in this case, when consumer runs the test, it doesn't need to publish the contract (because he is not the owner of the contract), so we need a way to take a PactBuilder object and to a `.toContract()` so it can be called from provider side, publish it and use it during running test phase.

**Comment by uglyog** [comment]
I think that sharing the pact JSON files is better, as there are lots of supported ways of sharing them (Pact Broker, URLs, S3 buckets) and they are not JVM specific.

The PactBuilder just provides a fluent DSL for constructing a Pact model class, which is what gets serilaised into the Pact JSON file. On the consumer side, the test could just load the Pact JSON back into a Pact model and use that.

**Comment by lordofthejars** [comment]
Exactly, this is what I don t know if it is currently supported

**Comment by uglyog** [comment]
There are two classes, PactReader and PactWriter for converting between Pact models and Pact JSON. The consumer test support will need to be altered slightly to support this.
