### ISSUE TITLE
JSON DSL's response exact matching

### ISSUE THREAD

**Issue by phantomread1** [DiUS/pact-jvm#332]
Hi,

I am not sure if this is by design but the JSON DSL's response matching seems not to match the exact value when replaying it at provider side. E.g.

`new PactDslJsonBody()
        .stringType("jsonrpc", "2.0")
        .stringType("id", "fixed")
        .eachLike("result")
        .stringValue("serviceClass", "ECONOMY")`

For the above code, I was expecting the response MUST contain a string field serviceClass with value "ECONOMY" to be able to match as I am using stringValue not stringType.  The API also indicates the stringValue matches the value specified. 

I am talking about replaying the generated pact file at the provider side. It passed the test even though the value in the actual response for field serviceClass is not ECONOMY.

I also noticed in the generated pact file, there is no matching rule defined for stringValue. 

Thanks

**Comment by uglyog** [comment]
The matchers cascade, so what is happening is the `eachLike` method is adding a wildcard matcher to all elements of the array, and this is propagating to all attributes of the objects in the array.

There is a [specification change to deal with this](https://github.com/pact-foundation/pact-specification/tree/version-3#add-an-equality-matcher) but it has not been implemented yet.

**Comment by phantomread1** [comment]
Thanks, any idea when will this going to be patched in ?

**Comment by uglyog** [comment]
The equality matcher was added to 3.5.0-beta.2, but the body DSLs still need to be updated to use it. I'll add it to the next version (which will be 3.5.0-beta.3), which hopefully I can get out in the next week or two.

**Comment by phantomread1** [comment]
Thanks, 

just to remind that version 3.5.0-beta.2 may have a regression problem which I've mentioned in the below issue. 
https://github.com/DiUS/pact-jvm/issues/320
