### ISSUE TITLE
Provide states with dynamic values

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#333]
Hello, today I have been working with Pact in provider side with states (`@State`) and I have found one enhancement that could be interesting and it is provide a way to set dynamic values, something like it is done in Cucumber JVM.

So the idea is that you could do something like:

In *consumer* side:

```java
return builder
            .given("user Alex is on database")
            .uponReceiving("ExampleJavaConsumerPactTest test interaction")
                .path("/")
                .method("GET")
....
```

Nothing new in consumer side but then in *provider* side:

```java
@State("user (\\w+) is on database")
public void toDatabaseState(String name) {
  System.out.println("Insert " + name + "user to database"); 
}

...
```

What do you think? Also we could support list using `(.*)` to get a comma separated list elements: https://cucumber.io/docs/reference/jvm#java

What do you think? I can provide a PR as well.

**Comment by uglyog** [comment]
There is also a V3 extention which improves this by adding key value pairs https://github.com/pact-foundation/pact-specification/tree/version-3#allow-multiple-provider-states-with-parameters

**Comment by lordofthejars** [comment]
Ah right, this is supported in 3.5.beta 2
