### ISSUE TITLE
Consumer test with multiple PactFragments and multiple test-methods only records interactions on one of the fragments

### ISSUE THREAD

**Issue by chellgren** [DiUS/pact-jvm#338]
We are testing a Consumer using the method described here:
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderWithMultipleFragmentsTest.java

The test works fine and the PactProviderRule is behaving exactly as defined in the PactFragments used by the separate methods. 

However the resulting json-file recording the interactions with the PactMock only has the recordings of interactions as used by one of the @PactVerification annotated test-methods? We can see that the run writes the pact file once for each test-methods. I think it would have to gather the interactions as generated by both test-methods before it attempts to write the json-file otherwise it overwrites the previous methods results?

**Comment by uglyog** [comment]
This has been released with version 3.3.2

**Comment by aniket-21** [comment]
Is this issue back in 3.3.5?

**Comment by uglyog** [comment]
You'll need to tell me, I did not put it back.

**Comment by aniket-21** [comment]
I tried with 3.3.5 and interaction of only one fragment was recorded in pact file

**Comment by aniket-21** [comment]
Would you be able to check his @uglyog ? I am facing this issue on 3.3.3 as well

**Comment by aniket-21** [comment]
ok I got the issue now, if expectMismatch == true then the interaction is not recorded. Is it expected?

**Comment by uglyog** [comment]
Yes, the interaction is never recorded if there is a mismatch. The `expectMismatch` value just stops the test from failing.
