### ISSUE TITLE
JSON representation of matchingRules in Specification V3

### ISSUE THREAD

**Issue by momoendo** [DiUS/pact-jvm#340]
I ran the tests of the pact-jvm-consumer-junit project and the created pact json files contain matchers described as this:

```
"matchingRules": {
  "$.headers.Location": {
    "regex": "http(s)?://\\w+:\\d+//some-service/user/\\w{36}$"
  }
```

with pact-specification version 3.0.0

According to https://github.com/pact-foundation/pact-specification/tree/version-3 the usage of JsonPath notation was dropped for matcher keys in Version 3. Is there a reason pact-jvm still uses V2 to store the matchers in the pact-file?

**Comment by uglyog** [comment]
The change to matching rules was introduced in 3.5.0-beta.2. The 3.3.x versions only support the message pacts from V3.
