### ISSUE TITLE
AmqpTarget and @PactFolder don't play well with each other

### ISSUE THREAD

**Issue by andreschaffer** [DiUS/pact-jvm#341]
Running a message pact verification test with the AmqpTarget and @PactBroker works fine, but it throws an error if using @PactFolder instead.
Debugging the code it seems the method getProviderInfo of the AmqpTarget sets the provider consumers with their names only (pactFile value is missing) and further down the execution the ProviderVerifier will throw an error when executing the method loadPactFileForConsumer with a consumer with null pactFile.

**Comment by uglyog** [comment]
I have removed that bit of code, because the PactRunner has already loaded all the pact files from the annotations before this. It was then loading them a second time, and as you discovered, causing a later failure.
