### ISSUE TITLE
Problems with Pact for Service returning just a Number (Version 3.3.3 and 3.5.0)

### ISSUE THREAD

**Issue by maxant** [DiUS/pact-jvm#348]
I have a service which returns just a number, like 12345678.

Here is the consumer test:

    @RunWith(WeldJunit4Runner.class)
    @WeldConfiguration 
    public class FachnummerServiceConsumerTest {

      @Inject
      Service service;

      @Test
      public void test() throws IOException {
        PactDslJsonRootValue responseJson = PactDslJsonRootValue.integerType(12345678);

        PactFragment pactFragment = ConsumerPactBuilder
                .consumer("ServiceConsumer")
                .hasPactWith("ServiceProvider")
                .uponReceiving("createNumber")
                  .path("/pathToService")
                  .query("param1=73&param2=1")
                  .body((String)null)
                  .method("POST")
                .willRespondWith()

                  .status(201)
                  .body(responseJson)
                  .headers(headers("Content-Type", "text/plain"))
                .toFragment();

          MockProviderConfig config = MockProviderConfig.createDefault();
          VerificationResult vResult = pactFragment.runConsumer(config, (c) -> {

            //reconfigure our integration service so that it calls the PACT server which runs locally
        service.restClient.getRequestConfiguration().setBaseUrl(c.getScheme()+"://"+c.getHostname()+":"+c.getPort() + "/rest");

            //when
            String number = service.getNumber();

            //then
            assertEquals("12345678", number);
            //assertTrue(fachnummer.matches("[0-9]*"));
        });

        if (vResult instanceof PactError) {
            throw new RuntimeException(((PactError)vResult).error());
        }
        assertEquals(ConsumerPactTest.PACT_VERIFIED, vResult);
    }
}

This test passes and creates the following pact:

    {
        "provider": {
            "name": "ServiceProvider"
        },
        "consumer": {
            "name": "ServiceConsumer"
        },
        "interactions": [
            {
                "description": "createNumber",
                "request": {
                    "method": "POST",
                    "path": "/rest/",
                    "query": "parameter1=73&parameter2=1",
                    "body": null
                },
                "response": {
                    "status": 201,
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "body": "12345678",   <--- THIS LINE IS PROBLEMATIC IN 3.3.3
                    "matchingRules": {
                        "$": {               <-- THIS LINE APPEARS PROBLEMATIC IN 3.5.0-Beta2
                            "matchers": [
                                {
                                    "match": "integer"
                                }
                            ]
                        }
                    }
                }
            }
        ],
        "metadata": {
            "pact-specification": {
                "version": "2.0.0"
            },
            "pact-jvm": {
                "version": "3.5.0-beta.2"
            }
        }
    }

See the comments in the pact for the two problems that I have.

3.3.3 Error:

    returns a response which
      has status code 201 (OK)
      includes headers
        "Content-Type" with value "text/plain" (OK)
      has a matching body (FAILED)

    Failures:

    0) createNumber returns a response which has a matching body
      / -> mismatch

      Diff:

      @0
      -12345678
      +670015005301
      
    java.lang.AssertionError: 
    0 - / -> mismatch

	at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:84)
	at au.com.dius.pact.provider.junit.target.HttpTarget.testInteraction(HttpTarget.java:121)
	at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:181)
	at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:141)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:101)
	at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

With 3.5.0-beta2: crashes with an exception in groovy code with an array out of bounds exception in MatchingRules.groovy:

      void fromV2Map(Map map) {
        map.each {
          def path = it.key.split('\\.')        <-- since the pact contains just "$", there is no "." => no element 1 for below
          if (it.key.startsWith(DOLLAR_BODY)) {
            if (it.key == DOLLAR_BODY) {
              addV2Rule(BODY, DOLLAR, it.value)
            } else {
              addV2Rule(BODY, DOLLAR + it.key[6..-1], it.value)
            }
          } else if (it.key.startsWith('$.headers')) {
            addV2Rule('header', path[TWO], it.value)
          } else {
            addV2Rule(path[1], path.size() > TWO ? path[TWO] : null, it.value)    <-- Element 1 does not exist!
          }
        }
      }

**Comment by uglyog** [comment]
Thanks for the report. I'll fix the 3.5.0-beta2 version. 

When you run it with version 3.3.3, can you confirm that you are using that version in the consumer test? Version 3.3.+ does not support the newer V3 format pact files.

**Comment by uglyog** [comment]
I see the problem, it's the content type.

    "Content-Type" with value "text/plain" (OK)

The matchers only get applied to JSON and XML. I'll look at adding regex matchers for plain text, but if you can the content type to `application/json` it should resolve your problem.

**Comment by maxant** [comment]
Changing the response content-type (on the provider side) to application/json works when combined with `PactDslJsonRootValue.integerType()`, for example: https://github.com/maxant/pactexamples/blob/master/src/test/java/ch/maxant/tullia/pactexamples/EventsRepositoryPrimitiveConsumerTest.java
