### ISSUE TITLE
Better debugging support for pact-jvm-provider-junit

### ISSUE THREAD

**Issue by BenSayers** [DiUS/pact-jvm#354]
This request is for the use case of pact-jvm-provider-junit runner combined with the pact broker.

When it cannot find any pact files it returns an error saying that no pact files were found. This results in developers needing to figure out where the problem is. Did they upload the pact file to the broker? Has it been tagged properly? Have they configured pact-jvm-provider-junit to point to the right broker and tag?

To help answer these questions quickly it would help if when an error occurred more verbose details were returned, the most important being the full URL the library is using to try and retrieve the pacts.

**Comment by uglyog** [comment]
You will now get an exception like the following:

    au.com.dius.pact.provider.broker.NotFoundHalResponse: 404 Not Found response from the pact broker (URL: 'http://localhost:1234', LINK: 'http://localhost:1234/pacts/provider/Activity Service2/latest')

**Comment by BenSayers** [comment]
Awesome, I'll give it a go when this ships.

**Comment by uglyog** [comment]
3.3.4 has been released

**Comment by BenSayers** [comment]
Just tried it out, thats a big improvement, thanks!
