### ISSUE TITLE
Update PactBrokerLoader to work with basic auth

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [DiUS/pact-jvm#360]
At the moment it doesn't appear to be possible to use `PactBrokerLoader`/`@PactBroker` with a basic auth protected pact broker.  These could be added as a username and password field on the `@PactBroker` annotation, and if present could be added to the request in `PactBrokerLoader` by calling `URIBuilder::setUserInfo`.

**Comment by uglyog** [comment]
Ah, yeah, good catch. I might look at adding a `@PactBrokerAuth` annotation.

**Comment by uglyog** [comment]
Basic auth is now supported via a new annotation:

```java
@PactBroker(host = "${pactbroker.url:localhost}", port = "1234", tags = {"latest", "prod", "dev"},
  failIfNoPactsFound = false, authentication = @PactBrokerAuth(username = "test", password = "test"))
```

The username and password fields also support the expressions (like the host in the example above)

**Comment by cah-andrewfitzgerald** [comment]
sweet.

Thanks!

**Comment by uglyog** [comment]
3.3.4 has been released

**Comment by cah-andrewfitzgerald** [comment]
Still having some issue. When it gets down to `PactReader::loadPactFromUrl` options.authentication is empty.
![screen shot 2017-01-04 at 10 51 11 am](https://cloud.githubusercontent.com/assets/13521755/21648467/22875cbe-d26c-11e6-8352-adaa775c37e1.png)
This is my broker annotation
![screen shot 2017-01-04 at 10 52 25 am](https://cloud.githubusercontent.com/assets/13521755/21648472/2553516e-d26c-11e6-8e24-6cce9b7b3804.png)

**Comment by uglyog** [comment]
Hmm, apologies about that. I tested it locally using a docker container, and it seemed to be working. I must have missed something.

**Comment by uglyog** [comment]
Ok, I tested the initial query against the broker. Not the actual loading, which your PR has fixed. Sorry about that.
