### ISSUE TITLE
pact-jvm-provider-maven tag support

### ISSUE THREAD

**Issue by kevinkilroy** [DiUS/pact-jvm#364]
Is it possible when using the pactBrokerUrl option of the maven plugin to only fetch pacts that match a particular tag?

Thanks

**Comment by uglyog** [comment]
Should be possible, it may only require an option added to the maven plugin.

**Comment by uglyog** [comment]
I've added both tag and basic auth support to the maven plugin.

**Comment by uglyog** [comment]
Version 3.3.5 has been released with this change
