### ISSUE TITLE
Expected List but received Map on JsonArray body

### ISSUE THREAD

**Issue by vbaidak** [DiUS/pact-jvm#366]
Hi!

I faced with an issue after upgrading **pact-jvm-consumer-junit_2.11** from version **2.4.10** to version **3.3.4**. Everything worked well before update, but after update the pact verification fails.

Here is a sample output of the REST api:
```
[
  {
    "@type": "Organization"
  },
  {
    "@type": "Organization"
  }
]
```

This is my pact test DSL:
```java
DslPart agenciesAlike = new PactDslJsonArray()
				.eachLike(2)
				.stringMatcher("@type", "Organization", "Organization")
				.closeObject()
                                .closeArray();
```

This is what has been generated:

```
"response": {
    "status": 200,
    "headers": {
        "Content-Type": "application/json"
    },
    "body": [
        [
            {
                "@type": "Organization"
            },
            {
                "@type": "Organization"
            }
        ]
    ],
    "matchingRules": {
        "$.body[0][*]['@type']": {
            "regex": "Organization"
        },
        "$.body[0]": {
            "min": 0,
            "match": "type"
        }
    }
}
```

And here is the output of the pact verification:
`
Expected List List(Map(@type -> Organization), Map(@type -> Organization)) but received Map Map...
`

Am I doing something wrong?
Thanks!

**Comment by uglyog** [comment]
You have a double array in the generated JSON, because `new PactDslJsonArray()` defines an array and so does `eachLike`.

What you want is something like:

```java
PactDslJsonArray.arrayEachLike(2)
  .stringMatcher("@type", "Organization", "Organization")
  .closeObject()
```

**Comment by vbaidak** [comment]
Thanks! That helps
