### ISSUE TITLE
[Consumer][V3] withContent method is confusing for Message queues while writing consumer tests

### ISSUE THREAD

**Issue by aniket-21** [DiUS/pact-jvm#367]
In below pact builder, **withContent()** sounds like it is the data sent as request and not the one expected as response.  

return builder.given("SomeProviderState")
                      .expectsToReceive("a test message")
                      .withMetadata(metadata)
                      .withContent(body)
                      .toPact();

So far as per my understanding it maps to **.body()** of http response.
Also why does **withContent(DSLPart body)** only accepts DSLPart body while **.body(String)** accepts string

**Comment by uglyog** [comment]
With messages, there is no request or response, there is just the content of the message, hence the `withContent` method.

You are correct, there should be a `withContent` method that takes a `String` parameter.

**Comment by aniket-21** [comment]
@uglyog could you plz help me understand this. Over the qeueue, some consumer service puts a message, its read by provider service and acted upon and then provider may put back a message in the queue.

In this scenario what does withContent corresponds to?

**Comment by uglyog** [comment]
The component that creates the message and puts it on the queue is the provider, and the component that consumes the message from the queue is the consumer. Think of it in terms of a contract between two parties that are communicating over a message queue. If the consumer puts the message back, that does not change the contract.

In the Consumer test DSL, the `withContent` is used to specify the message content (what gets put on the queue).
