### ISSUE TITLE
AmqpTarget missing on pact-jvm-provider-junit 3.5.0-beta.2

### ISSUE THREAD

**Issue by zwant** [DiUS/pact-jvm#368]
I'm trying to get a simple test for consumer & producer up and running in a Messaging Queue scenario with pact-jvm-provider-junit and pact-jvm-consumer-junit.
I tried running 3.3.4 where AmqpTarget exists, but the consumer part seems to generate a message format which doesn't play nicely with JSON data comparisons. This code:
```
PactDslJsonBody body = new PactDslJsonBody()
        .stringValue("name", "value1")
        .numberValue("value", 1);

    Map<String, String> metadata = new HashMap<String, String>();
    metadata.put("contentType", "application/json");

    return builder.given("SomeProviderState")
        .expectsToReceive("a test message")
        .withMetadata(metadata)
        .withContent(body)
        .toPact();
```

Produces a pact-file like:
```
{
    "description": "a test message",
    "metaData": {
        "contentType": "application/json",
        "Content-Type": "application/json; charset=UTF-8"
    },
    "contents": "{name=value1, value=1}",
    "providerState": "SomeProviderState"
}
```

The contents then fail my provider tests, as it's doing the comparison wrong.
This very simple test:
```
@PactVerifyProvider("a test message")
  public String verifySimpleMessage() throws Exception {
    ExampleThing thing = new ExampleThing();
    thing.name = "value1";
    thing.value = 1;

    return DummyEventHandler.exampleThingToJson(thing);
  }
```
fails with 
```
java.lang.AssertionError: 
0 - $.body -> Expected '{name=value1, value=1}' but received Map(name -> value1, value -> 1)
```

Upgrading to 3.5.0-beta.2 I get much better pact-file output from my consumer, but the AmqpTarget class doesn't exist so I can't test my producer. The 3.5.0-beta.2 pact-file for the same code as above is:
```
{
    "description": "a test message",
    "contents": {
        "name": "value1",
        "value": 1
    },
    "providerState": "SomeProviderState"
}
```

Should AmqpTarget exist in the 3.5-branches, or is there another way of doing these tests in 3.5 that I'm missing?

**Comment by uglyog** [comment]
Hmm, the 3.3.4 pact file has invalid JSON, so that is why the provider test is failing.

```
   "contents": "{name=value1, value=1}"
```

should be

```
   "contents": "{\"name\": \"value1\", \"value\": 1}"
```

I'll have a look to see why that is happening.

As to 3.5.0-beta.2, it is branched off master so should have all the same classes.

**Comment by uglyog** [comment]
AmqpTarget was added in commit b56db8770830, which is after the 3.5.0-beta.2 release. It will be in 3.5.0-beta.3, which will be released as soon as the generator implementation is completed.

**Comment by zwant** [comment]
Thanks a lot!
So to unblock myself and explore testing MQ interactions with pact-jvm, what are my options?
Was the 3.3.4 pact file with invalid JSON a regression, so that I can go for an older version? Or will I have to wait for new releases of either 3.5.x or 3.3.x ?

**Comment by uglyog** [comment]
Yes it was a regression, possibly introduced in version 3.3.0, but the AmqpTarget was introduced in 3.3.2.

I should be able to get a new 3.3.x version out soon, the 3.5.x will take a little longer.

**Comment by uglyog** [comment]
Closing this as v3.5.x has been released.
