### ISSUE TITLE
[Pact-jvm-consumer-junit] In case of multi providers, pact file for only one provider is generated

### ISSUE THREAD

**Issue by coding-yogi** [DiUS/pact-jvm#371]
Setup:
Two providers defined with MessagePactProviderRule
Consumer is same in this case
Pact defined for consumer with every provider

When the tests are ran for all the providers, pact file for only of the provider gets generated

**Comment by uglyog** [comment]
[Defect371Test](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/v3/Defect371Test.java) is an example of a message pact test with multiple providers. It works with the fix I implemented.
