### ISSUE TITLE
Unable to specify multiple providers in gradle.build

### ISSUE THREAD

**Issue by xytrams** [DiUS/pact-jvm#372]
I have 2 different providers with the same consumer. I'm trying the following configuration in gradle.build: 

pact {

    serviceProviders {

  		provider-1 {
             //All the provider properties are optional, and have sensible defaults (shown below)
            			protocol = 'http'
            			host = 'localhost'
            			port = 8080
            			path = '/'

             //Again, you can define as many consumers for each provider as you need, but each must have a unique name
            			hasPactWith('consumer-1') {

            				// currently supports a file path using file() or a URL using url()
            				pactFile = file('src/test/consumer-pacts/consumer-1-provider-1.json')

            			}
            }
        
		provider-2 {
             //All the provider properties are optional, and have sensible defaults (shown below)
            			protocol = 'http'
            			host = 'localhost'
            			port = 8080
            			path = '/'

             //Again, you can define as many consumers for each provider as you need, but each must have a unique name
            			hasPactWith('consumer-1') {

            				// currently supports a file path using file() or a URL using url()
            				pactFile = file('src/test/consumer-pacts/consumer-1-provider-2.json')

            			}        
		}

    }

my plugin version: id "au.com.dius.pact" version "3.3.6"

It is either a bug or I can't find the correct way to specify more than 1 provider. 

Error I get:

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: au/com/dius/pact/provider/gradle/PactPlugin : Unsupported major.minor version 52.0
> au/com/dius/pact/provider/gradle/PactPlugin : Unsupported major.minor version 52.0

**Comment by uglyog** [comment]
The 3.x versions of pact jvm require Java 8. Refer to https://github.com/DiUS/pact-jvm#supported-jdk-and-specification-versions for more info.
