### ISSUE TITLE
Using PACT 3.5.0-beta.2, verification failed.

### ISSUE THREAD

**Issue by shrutiujjwal** [DiUS/pact-jvm#373]
Verifying a pact between Notification_receiver and Notification_sender
  [Using file resources/Notification_receiver-Notification_sender.json]
  Given SomeProviderState
         WARNING: State Change ignored as there is no stateChange URL
  in case of message is not from case-exchange origin
    generates a message which
      **Verification Failed - Failed to invoke provider method 'testPublisherNotificationContract'**

What is the meaning of this failure?

**Comment by uglyog** [comment]
The Pact verifier tried to invoke the method `testPublisherNotificationContract` to get the message contents to verify, but an exception was raised.

If you enable the display of the stacktrace, you'll see what exception was raised. You can do this with the `pact.showStacktrace` property.

**Comment by shaship04** [comment]
Verifying a pact between PED_A2CO_MERCHANT_CONFIG_REQUEST
  [Using File ../pacts/PED_A2CO_MERCHANT_CONFIG_REQUEST-PED.json]
  Given Merchant-Config
  create
{"TimeStamp":"2023-02-07T23:04:58.676+05:30","message":"[Controller id=0] Processing automatic preferred replica leader election","Thread":"controller-event-thread","Level":"INFO"}
    generates a message which
      Verification Failed - Failed to invoke provider method 'verifySuccessMessageEvent'
      
      i am not getting the exact steps and what is this error mean? could you please help why this exception occured.
