### ISSUE TITLE
numberValue does not match doubles with decimal value 0

### ISSUE THREAD

**Issue by flaviuratiu** [DiUS/pact-jvm#380]
Hi.
I have a 0 value coming on the response as a double: 0.0

I'm trying to validate it in a contract test with:
`.willRespondWith().status(200).matchHeader("Content-Type", "application/json;charset=UTF-8").body(new PactDslJsonBody().object("freePackageTemplate").numberValue("billingAmount", 0).closeObject())`

I've also tried with: `.numberValue("billingAmount", 0.0)`

But I get the following error:

`$.body.freePackageTemplate.billingAmount -> Expected 0 but received 0`

I've also tested with 1.0 coming on the response. The same behavior can be noticed.

The validation `.numberValue("billingAmount", 1.1)` passes though if the value on the response is 1.1 

Tested with version 3.3.6 of pact-jvm-consumer-junit_2.11

**Comment by uglyog** [comment]
That error message is not useful at all!

**Comment by flaviuratiu** [comment]
Indeed it's not. Or are you saying you need more details for investigating?

**Comment by uglyog** [comment]
I was refering to `$.body.freePackageTemplate.billingAmount -> Expected 0 but received 0`

But this does need more investigating, or at least display the types so we can see what the problem is. It looks like the matcher is not being applied, and it is doing an equality comparison with different types.

**Comment by uglyog** [comment]
Use `numberType("billingAmount", 0)` to match by type.

What framework are you using? I'm assuming that the `0.0` value is being returned as a BigDecimal and that is why it is not matching.

**Comment by LinghaoYu** [comment]
Got the same problem here. I am using pact-jvm-provider-maven_2.12 version 3.5.2. In the contract json, the expected number is 0.0, for instance 
```
 "feature_coefficients": {
            "subdivision_missing": 0.0,
            "addressline_leftout": -0.9795832395929132,
            "city_unmatched50": -4.388086346734725,
            "geo_exact": 0.0,
```
Then when the plugin verifies this contract, it complains that` $.feature_coefficients.subdivision_missing -> Expected 0 but received 0.0`. It seems 0.0 is automatically parsed to be 0, which is not expected

**Comment by LinghaoYu** [comment]
Hi @uglyog thanks for your help. This is not the problem of the plugin but the problem of the contract broker. The contract we upload to the broker has 0.0, but the same contract that is downloaded from the broker has 0. This issue can be closed.
