### ISSUE TITLE
Rename AmqpTarget

### ISSUE THREAD

**Issue by fitzoh** [DiUS/pact-jvm#383]
`AmqpTarget` seems to imply that it is only usable with AMQP, when there is nothing preventing it from being used to test kafka or other non-AMQP message providers.

a name of `MessageTarget` or something similar would make the intended usage more clear.

**Comment by uglyog** [comment]
Good point, I use it to test lambda functions.

**Comment by uglyog** [comment]
Done

**Comment by anto-ac** [comment]
Should this not be renamed for JUnit5 too?
