### ISSUE TITLE
eachLike doesn't seem to generate proper o/p in Java

### ISSUE THREAD

**Issue by aniket-21** [DiUS/pact-jvm#385]
below is my DSL
   ```
   .object("dataStorePathInfo")
            .stringMatcher("basePath", String.format("%s/%s/training-data/[a-z0-9]{20,24}", CUSTOMER, TRAINING))
             .eachLike("fileNames", PactDslJsonRootValue.stringType("abc.txt") ,1)
   .closeObject()
```

o/p generated is as follows

```
"dataStorePathInfo": {
    "basePath": "acctestcustomer/acctesttraining/training-data/l0at879y7786mv5z30g1",
    "fileNames": [
         "\"abc.txt\""
    ]
}
```

I was expecting file name in o/p to be just **"abc.txt"** and not **"\\"abc.txt\\""**

**Comment by petenattress** [comment]
Hi, I've hit this issue also - just to add that it appears to affect all the array matching methods (e.g. `minArrayLike`, `maxArrayLike`, etc)

**Comment by tomreay** [comment]
Am also hitting this issue, it seems to stem from https://github.com/DiUS/pact-jvm/commit/17554aaaa99a0d2751cdee75b2af218fb72b5342

**Comment by uglyog** [comment]
Released 3.3.9 with this fix

**Comment by aniket-21** [comment]
Great, let me check

**Comment by metaflow** [comment]
3.3.9 version works for me! Thank you!
