### ISSUE TITLE
`@VersionedPactUrl` should blow up if nothing to filter

### ISSUE THREAD

**Issue by tjheslin1** [DiUS/pact-jvm#386]
If there is nothing to filter (_e.g. ${app.version}_) when using `@VersionedPactUrl`, this is a sign that you should either be using the default `@PactUrl` or you have temporarily replaced the tokens with hard coded values to test locally.

`@VersionedPactUrl` blowing up is a safe reminder of this and I have found this to cause issues in the past.

**Comment by tjheslin1** [comment]
Please assign this to myself as I don't have permission to do so.

**Comment by uglyog** [comment]
Good catch, that should throw an exception.

**Comment by tjheslin1** [comment]
I will work on this.
