### ISSUE TITLE
Can't match Json value in request body with stringType

### ISSUE THREAD

**Issue by Altoyyr** [DiUS/pact-jvm#387]
I try to match a certain value in my Json-Body on POST against any string value.
`nonce` is a generated random value and I do not know it before running the test.
```
PactDslJsonBody jsonBody = new PactDslJsonBody()
		.stringType("username", "error")
		.stringType("password", "password")
		.stringType("scope", "content")
		.stringType("grant_type", "password")
		.stringType("nonce");

return builder
		.uponReceiving(description)
		.path("/auth")
		.headers(defaultHeaders)
		.method("POST")
		.body(jsonBody)
		.willRespondWith()
		.status(statusCode)
		.body(responseBody);
```

But I get a PactMismatchException

```
BodyMismatch({"password":"error","grant_type":"password","scope":"content","nonce":"UhlniLvYTyZgepVgyYOV","username":"error"},{"password":"error","grant_type":"password","scope":"content","nonce":"e92f850834014847ab249bea44eea89c","username":"error"},None,/)
```

I can see that the `nonce` values are different, but I thought the point of using `stringType(String name)` is to not care about the actual value?

I am using version 2.5.0-beta.0.
Thank you in advance

**Comment by uglyog** [comment]
The `nonce` values you are seeing are the random generated values provided when you don't give an example. They will not matter as long as they are strings.

But the main problem seems to be that the bodies are being treated as strings and not JSON. Can you check what the value of the `Content-Type` header is?

**Comment by Altoyyr** [comment]
This was actually caused by using `stringValue` and `stringType` incorrectly. 
This can be closed.
Sorry for the inconvenience.

**Comment by payals2387** [comment]
@Altoyyr : Can you elaborate how stringValue and stringType were used correctly versus incorrectly?
I am also bit confused how these both work.
