### ISSUE TITLE
Consumer Tests should have a return type

### ISSUE THREAD

**Issue by thetrav** [DiUS/pact-jvm#39]
`PactFragment` defines test as `=> Unit`

specs2 defines test functions as returning instances of `Result`

We should be able to do:

`def duringConsumerSpec[T](config: MockProviderConfig)(test: => [T]): VerificationResult[T] = {`

Which would allow slightly better test framework integration at the cost of some extra code in our library.

**Comment by uglyog** [comment]
This is no longer required.
