### ISSUE TITLE
Query match support

### ISSUE THREAD

**Issue by radubutnaru** [DiUS/pact-jvm#392]
I can see that Pact spec v3 [supports ](https://github.com/pact-foundation/pact-specification/blob/version-3/testcases/request/query/matches%20with%20regex.json) regex matching for request query params. We would like to have this functionality for one of our use-cases.

Are there plans to implement query matching support in the JUnit Consumer lib?

Thank you very much,
Radu.

**Comment by uglyog** [comment]
The matching implementation supports it, it just has not been added to the DSL.

**Comment by radubutnaru** [comment]
Sounds great. So should we expect for it to be added to the DSL anytime soon?

**Comment by uglyog** [comment]
yes, I will work on this in the near future.

**Comment by uglyog** [comment]
A `matchQuery` method has been added to the DSL to support query parameter matching.

**Comment by radubutnaru** [comment]
Works fine. Thank you!
