### ISSUE TITLE
Generated PACTs are stored with System default encoding

### ISSUE THREAD

**Issue by apf3l** [DiUS/pact-jvm#395]
When I try to generate PACT files with the letters ä, ü, ö and ß. The files are stored in system default encoding and not as expected in UTF-8, so these letters are displayed wrong. Is it possible to force UTF-8 for the json-file generation or is this an issue?

Tested Consumer: pact-jvm-consumer-junit_2.11 
Versions: 
- 3.5.0-beta.2
- 3.5.0-beta.3

Tested OSs:  
- Windows 7 SP1 64-bit 
    Fileformat: ANSI
- SUSE Linux Enterprise Server 12 SP2
    Fileformat: ASCII

**Comment by shashidesai** [comment]
Checked on Mac. Added ä to value in a field and it shows up as shown below.

`"response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": {
                    "field1": "**value\u00e4**"
                },
`

Consumer: 
pact-jvm-consumer-junit_2.11

Version:
3.5.0-beta.2

Tested OS:
macOS Sierra Version 10.12.3

Running a check on system default encoding, it shows as us-ascii:
`$ file -I test_consumer-test_provider.json`
`test_consumer-test_provider.json: text/plain; charset=us-ascii`

**Comment by uglyog** [comment]
Does this issue also occur with version 3.3.7?

**Comment by uglyog** [comment]
It was the Groovy JSON class that was encoding the non-ascii characters into the unicode escape sequences. I have switched to GSON, and the characters are now preserved.

As a side note, the unicode escapes are equivalent:

```
groovy:000> "value\u00e4"
===> valueä
groovy:000> "value\u00e4" == 'valueä'
===> true
```

it is just that they are not escaped correctly in the JSON file.
