### ISSUE TITLE
pact-jvm-consumer-junit - ConsumerPactTest - decimalType issue

### ISSUE THREAD

**Issue by shashidesai** [DiUS/pact-jvm#397]
Here is part of the class - the pact file generated does not have floating point in the pact when I use decimalType. 
`public class PactTest extends ConsumerPactTest {

    @Override
    protected PactFragment createFragment(PactDslWithProvider builder) {
        DslPart body = new PactDslJsonBody()
                .decimalType("time");

        PactFragment fragment = builder
                .uponReceiving("interaction with api")
                .path("/")
                .method("GET")
                .willRespondWith()
                .status(200)
                .body(body)
                .toFragment();

}`

part of the pact file generated:
` 
"body": {
                    "time": 2859673060
                }
`

`time` should be floating point number in the pact file when I use decimalType or did I understand it wrong ?

**Comment by uglyog** [comment]
It's using a BigDecimal under the covers, and as the random number has no decimal points the BigDecimal  is not outputting the decimal point with a zero. You can provide your own example value as the second parameter.

**Comment by shashidesai** [comment]
Thanks @uglyog
