### ISSUE TITLE
PactBrokerClient should be in common place

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#408]
Currently PactBrokerClient https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider/src/main/groovy/au/com/dius/pact/provider/broker resides on provider project. The problem is that PactBrokerClient does not only contains operations used by provider but also by the consumer (for example upload pacts) https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider/src/main/groovy/au/com/dius/pact/provider/broker/PactBrokerClient.groovy#L68 

I think that this part should be moved as module itself, for example `pact-jvm-pact-broker`

I can spend time on this refactor if you agree.

**Comment by uglyog** [comment]
You are correct, that should be moved to a shared module. I've been thinking about consolidating the modules in the project, so maybe a `pact-jvm-core` would be better.

**Comment by uglyog** [comment]
Now that I think of it, the pact broker code could be useful to others and can probably be pulled out of pact-jvm all together.

**Comment by lordofthejars** [comment]
Completely agree, for example for Maven/Gradle/Jenkins plugins. Currently I am using it in Algeron.

**Comment by uglyog** [comment]
Version 3.5.3 has been released with the PactBrokerClient in its own module

**Comment by lordofthejars** [comment]
Great thank you very much, tomorrow I'll work on Arquillian Algeron to use this decoupled version.
