### ISSUE TITLE
The requests and responses received by the mock server are not logged anywhere

### ISSUE THREAD

**Issue by uglyog** [DiUS/pact-jvm#41]
The Ruby version of pact has very good logging of requests and responses to help diagnose failures. While investigating issue #40 I could not find any logs to see what actually requests where received to work out why they did not match.

**Comment by moleske** [comment]
Hey there, we're trying to access the logs. Where can we find them? We're on 3.3.7

```
        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-consumer-junit_2.11</artifactId>
            <version>3.3.7</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer_2.11 -->
        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-consumer_2.11</artifactId>
            <version>3.3.7</version>
            <scope>test</scope>
        </dependency>
```

**Comment by moleske** [comment]
Found the answer at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/README.md

**Comment by colossatr0n** [comment]
> Found the answer at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/README.md

Here's the updated URL path: https://github.com/pact-foundation/pact-jvm/blob/master/consumer/junit/README.md#debugging-pact-failures

I had to log everything from `au.com.dius.pact` instead of just `au.com.dius.pact.consumer.UnfilteredMockProvider` in order to debug my issue.
