### ISSUE TITLE
Is there an easy way to create a PactFragment directly from a Pact model?

### ISSUE THREAD

**Issue by mingyangz1** [DiUS/pact-jvm#410]
I am trying to use PactReader to get a Pact model from a pact json file. Then I am trying to create a PactFragment in order to mock the service. If there are several interactions for the mock service, I know I can do something like "builder.uponReceiving().path().method()" to code it in hard way. But is there any easy way to create the PactFragment?

**Comment by uglyog** [comment]
The code is written to go the other way, PactFragment -> Pact model. But you could just use the PactFragment constructor, you just have to convert the interactions to a Scala Seq.

```java
List<RequestResponseInteraction> list = new ArrayList<>((List<? extends RequestResponseInteraction>) pact.getInteractions());
    PactFragment fragment = PactFragment.apply(pact.getConsumer(), pact.getProvider(),
      JavaConverters.asScalaBufferConverter(list).asScala().toSeq());
```
