### ISSUE TITLE
Array "min" not respected: Pact writing code on the consumer side is missing one of the rules

### ISSUE THREAD

**Issue by uglyog** [DiUS/pact-jvm#416]
The [* ].* rule is missing that says, match the contents of the array by type.

See https://github.com/pact-foundation/pact-provider-verifier/issues/8

**Comment by bethesque** [comment]
I've finally caved and I've updated the Ruby code to allow the `match: 'type'` rule to be specified on the parent, or on the child as `parent[*].*`.

**Comment by SchulteMarkus** [comment]
I am awaiting next release!
