### ISSUE TITLE
[pact-jvm-consumer-junit] Pact consumer performance

### ISSUE THREAD

**Issue by ndelacrz** [DiUS/pact-jvm#418]
This is really more of a question than an issue...

Is it normal that one consumer test takes several seconds to execute? 
Currently I am running the test via my machine's IDE (IntelliJ). [ windows 7 with intel i5 @2.60GHz with 8GB RAM]

And with 1 test, it takes between 5-15 seconds to execute. There was even one execution that took 30 seconds.

I currently have a very basic pact consumer based on the samples here:

```
        // Define the test data:
        String path = "/mypath/abc/";

        //Header data:
        Map<String, String> headerData = new HashMap<String, String>();
        headerData.put("Content-Type", "application/json");

        // Put as JSON object:
        JSONObject bodyExpected = new JSONObject();
        bodyExpected.put("name",myName);

        PactFragment pactFragment = ConsumerPactBuilder
                .consumer("test_consumer")
                .hasPactWith("test_provider")
                .uponReceiving("a request to get values")
                    .path(path)
                    .method("GET")
                .willRespondWith()
                    .status(200)
                    .headers(headerData)
                    .body(bodyExpected)
                .toFragment(); 

        MockProviderConfig config = MockProviderConfig.createDefault();
        VerificationResult result = pactFragment.runConsumer(config, new TestRun() {

            @Override
            public void run(MockProviderConfig config) {
                try {
                    new ProviderClient(config.url(),path).hello(bodyExpected);
                } catch (IOException e) {
                }
            }

        });
```

(I removed all the junit assertions to make sure it's not causing additional delays)

I was expecting the test to be as short as a normal Unit test. Currently on the same machine, 1 unit test takes less than 1 second to execute. So I am not sure if there is something I need to do on my pact consumer test ?

**Comment by uglyog** [comment]
Running your test on a powerful laptop takes 02.265 seconds. But there is quite a bit happening behind the scenes for this test to work. Firstly, a new mock server is started for every test. On my laptop this accounted for 0.6 seconds. Then 0.1 seconds seems to be the time that the request is received by the server. Then a further 0.1 seconds to compare the request with the expected one. Then another 0.5 seconds for the server to be shut down and the pact file written to disk.

So the largest amount of time seems to be starting the HTTP mock server and shutting it down again afterwards.

**Comment by uglyog** [comment]
Using a timer, it looks the the time for your test is measured as:

| Stage | Time (ms) |
|---------|---------------|
| Setup | 9 |
| Setup Fragment | 597 |
| Start of test function | 1326 |
| End of test function | 2225 |
| End of Test | 2464 |

**Comment by ndelacrz** [comment]
@uglyog thanks for the quick revert! :)

Do you have any ideas/suggestions how we can make further improvements?

**Comment by uglyog** [comment]
I was quite surprised that setting up the pact was 0.5 seconds. That can be improved. And I've started working on a new mock server that should be quicker to startup and shutdown.
