### ISSUE TITLE
does pact support rabbitMQ (Spring)?

### ISSUE THREAD

**Issue by Stobiecki94** [DiUS/pact-jvm#422]
Hi, pact seems to be great tool, for HTTP work correct and effectively.
 I want to use for AMQP protocol (rabbitMQ + Spring) - I made big research but there is nothing on the Internet about this, there is no single example for use and documentation about AMQP is limited to:
https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/test/java/au/com/dius/pact/provider/junit/AmqpTest.java
and
https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-junit#example-of-amqp-message-test

My questions:
1. does pact really support AMQP? (and is it possible to use with rabbitMQ and Spring)?
2. if yes, could someone show some example or provide description how to?

**Comment by uglyog** [comment]
AMQP support works at the code level, not at the protocol level. I have used it to test interactions between services that pass messages over Kafka, SQS and Kinesis. If you can call the code that generates and consume the messages, you can test that without requiring an actual message queue.

If you're using spring cloud, I'm assuming your message handler probably is annotation driven and your message producer is using a spring template. What I have done is get the spring classes to call a delegate that would either consume or produce the message, then I can verify those classes without all the spring stuff getting in the way.
