### ISSUE TITLE
pact verify mismatching due to array body

### ISSUE THREAD

**Issue by ndelacrz** [DiUS/pact-jvm#424]
more of a question... 

I'm trying to verify the pact contract against a provider service.
In my contract, my **expected response** contains an array of messages... for example, "Message1" and "Message2"
```
{
	"code": 123,
	"messages": 
		[
			"Message1 .....",
			"Message2 ....."
		]
}
```

However, I noticed that the provider service's response is not "fixed"... meaning the order of those messages are not always the same. Sometimes "Message1" is first, sometimes "Message2".

So sometimes I end-up with an error: (and sometimes no error. :P)
```
      $.body.messages.0 -> Expected 'Message1..' but received Message2...'

      $.body.messages.1 -> Expected 'Message2...' but received 'Message1...'
```

I am not quite sure if there is some matching method that could help me with this kind of situation?

**Comment by uglyog** [comment]
Is it important that you receive "Message 1 ..." as the first item, or only that you receive it?

**Comment by ndelacrz** [comment]
@uglyog I don't need them in specific order, as long as I receive them, it's fine.

**Comment by uglyog** [comment]
The DSL has an `eachLike` method to do this. See https://github.com/DiUS/pact-jvm/issues/433
