### ISSUE TITLE
pact-jvm-provider-maven : Error details not printed out during pact publishing

### ISSUE THREAD

**Issue by ndelacrz** [DiUS/pact-jvm#428]
In relation to https://github.com/pact-foundation/pact_broker/issues/98#issuecomment-300932409

To reproduce:
1. There is an existing pacticipant in the pact broker with a name "test_consumer1"
2. Publish a new pact contract with a pacticipant with name "test-consumer1"
3. Pact contract will not be published with this error:

```
[INFO] --- pact-jvm-provider-maven_2.11:3.3.6:publish (pact-publish) @ test-consumer1 ---
Publishing test-consumer1-test-provider1.json ... FAILED! 409 Conflict - This is the first time a pact has been published for "test-consumer1".
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.996 s
[INFO] Finished at: 2017-05-11T08:57:25+02:00
[INFO] Final Memory: 69M/458M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal au.com.dius:pact-jvm-provider-maven_2.11:3.3.6:publish (pact-publish) on project test-consumer1: One or more of the pact files were rejected by the pact broker -> [Help 1]
```

It would have been nice to see the error details why the pact contract was rejected.

**Comment by uglyog** [comment]
Agreed!

**Comment by ndelacrz** [comment]
On a slightly related note... is there some feature in the pact-jvm-provider-maven plugin that shows some report about the pact:verify results?

**Comment by uglyog** [comment]
There is a mechanism to generate either a JSON or Markdown file with the results, but there is no option with the maven plugin to enable it.

**Comment by ndelacrz** [comment]
thanks for the quick revert @uglyog 
could you let me know how to activate that?

**Comment by uglyog** [comment]
The Gradle plugin has the following options: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/README.md#verification-reports-versions-327249

A similar set of options need to be added to the Maven plugin and then set on the Verifier.

**Comment by bethesque** [comment]
Can we get the full message please? Someone else hit this problem again.

**Comment by uglyog** [comment]
PR's are welcome, @bethesque ;-)

**Comment by bethesque** [comment]
I'm feeling brave after my 6 month stint of Java. I can do it! I can do it!

**Comment by uglyog** [comment]
This has been fixed in later versions of the Maven plugin. Latest is 3.5.19.

**Comment by bethesque** [comment]
Thanks! And only yesterday I checked out pact-jvm on my client laptop to try and fix this myself (got stuck because of client maven repo settings)
