### ISSUE TITLE
Type Matching for a list of String

### ISSUE THREAD

**Issue by mingyangz1** [DiUS/pact-jvm#433]
I want to have a contract whose response body contains a key:value, and the value is a list of String, something like below
```
"body": {
    "object": [
        "object1",
        "object2",
        "object3"
    ],
}
```
I want to do a type matching to match any list of String. For example, if I get a response from a real server which has the following body
```
"body": {
    "object": [
        "item1",
        "item2",
    ],
}
```
I would like my tests pass. I don't find a good way to do a type match in such case. What is a good way to do such a type matching for a list of String?

**Comment by uglyog** [comment]
What language are you using to write your consumer tests?

**Comment by mingyangz1** [comment]
I am using Java. But I concern more on the provider tests. It would also be good if I could do some manual work if Java doesn't support that.

**Comment by uglyog** [comment]
It does support it, the answer is different depending on the DSL language used.

You can use the `eachLike` method on the DSL class to do this. See https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/README.md#ensuring-all-items-in-a-list-match-an-example-220

**Comment by mingyangz1** [comment]
Can you show me an example? I tried something like below
```
new PactDslJsonBody()
    .eachLike("objects", 1)
    .closeObject()
```
But I got following
```
"users": [
    {
                            
    }
]
```
It is not a list of String.

**Comment by uglyog** [comment]
For an example, look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer/src/test/groovy/au/com/dius/pact/consumer/PactDslJsonArrayMatcherSpec.groovy#L202

**Comment by mingyangz1** [comment]
I got it. Thanks so much!

**Comment by gks-96** [comment]
> It does support it, the answer is different depending on the DSL language used.
> 
> You can use the `eachLike` method on the DSL class to do this. See https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/README.md#ensuring-all-items-in-a-list-match-an-example-220

-> the link that you have shared is not working. Can you please point to the new working link?

**Comment by uglyog** [comment]
Updated link https://github.com/pact-foundation/pact-jvm/tree/master/consumer/junit#ensuring-all-items-in-a-list-match-an-example
