### ISSUE TITLE
Rewriting path for provider junit test / method visibility

### ISSUE THREAD

**Issue by metaflow** [DiUS/pact-jvm#438]
I am using pact-jvm-provider-junit with http target.
Imagine scenario when I am trying to test that I can upload some file to server and then download it by going to path provided by service.
My pact looks like:
```
.consumer("wget")
.hasPactWith("server")
.given("file uploaded")
.uponReceiving("get file")
.method("GET")
.matchPath("/.*", "/{file-path}")
.willRespondWith()
.status(200)
```
in test I have created a method
```
@State("file uploaded")
public void uploadFile() {}
```
which uploads file and retrieves URL corresponding to `{file-path}` above.
Now the question is: how can I make HttpTarget to replace {file-path} with real value?
1. It would be nice to have callback I can inject into client to update URIBuilder just before creating http request, but you might find it too specific. I am fine as I can make subclasses of `HttpTarget`, `ProviderClient` and  `ProviderClient` and change behavior.
2. Unfortunately almost all of methods of classes above are private and I have to copy (almost) whole classes to change behavior of one method. It would be nice to change methods visibility to private -> protected so it would be easier to extend classes.

**Comment by uglyog** [comment]
This type of scenario feels like it would be better tested with some other strategy, as a contract test probably has little benefit as all we are asserting is that a GET request was made.

But you may be able to modify the path with a request filter. See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-junit#modifying-the-requests-before-they-are-sent-version-323245

**Comment by metaflow** [comment]
It turned out that you can do that in `@TargetRequestFilter` method e.g.
```
string path;
@TargetRequestFilter
public void exampleRequestFilter(HttpRequest request) throws Exception {
    if (request instanceof HttpGet) {
        HttpGet get = (HttpGet) request;
        URIBuilder builder = new URIBuilder(get.getURI());
        if (path != null) {
            builder.setPath(builder.getPath().replace("{file-path}", path));
        }
        get.setURI(builder.build());
    }
}
```
