### ISSUE TITLE
reserved words in groovy used as json key

### ISSUE THREAD

**Issue by yekster** [DiUS/pact-jvm#440]
Any way to bypass reserved words defined as a key in json response body?

            willRespondWith(
                    status: 200)
            withBody {
                keys eachLike {
                    n regexp(alpha_num_regex, 'testValue123...')
//                    use ('testValue') //TODO not working properly bec 'use' is a method name
                }
            }

**Comment by uglyog** [comment]
Here you go:

```

**Comment by yekster** [comment]
Awesome! thank you @uglyog !
