### ISSUE TITLE
Can I include a customized property in contract files?

### ISSUE THREAD

**Issue by mingyangz1** [DiUS/pact-jvm#442]
I am trying to write a provider side test. In my test, I would like to first create a endpoint and then delete it. I will have a contract like the following:
```
 {
    "request": {
        "method": "POST",
        "path": "/examples"
     }
    "response": {
        "status": 201,
        "headers": {
            "Location": "123"
        }
    }
},
{
    "request": {
        "method": "DELETE",
        "path": "/examples/123"
    },
    "response": {
        "status": 201
    }
},
```
The `post` request will return a value `123` in response headers. But the value `123` will be changed each time I do a `post`. When I do `delete`, I like to change the path based on the `post` response. Is there a way to do that?

**Comment by uglyog** [comment]
What you're looking at doing is more behaviour testing. With Pact, each request is verified in isolation, so there is no way to pass information between the requests.

The current way of dealing with this is to use a defined provider state to setup the data correctly so the request can be made. So the delete request may have a state 'example 123 exists', etc.

**Comment by mingyangz1** [comment]
In my case, I need to do a `post /examples`, get a response `123`, and then test if doing a `delete /examples/123` works. But each time when I do a `post`, I will get a different response, maybe `456`, etc. So if the contract is fixed, then I cannot setup the data based on the contract.

Is there a way to modify the request's path before sending the request?

**Comment by uglyog** [comment]
You can try using a request filter.
