### ISSUE TITLE
Scala 2.12 version

### ISSUE THREAD

**Issue by ajhcpt** [DiUS/pact-jvm#445]
Hi, when will there be a release compatible with Scala 2.12?

Regards,
Andrew

**Comment by SanCoder-Q** [comment]
I have the same question.

**Comment by jcreixell** [comment]
+1

**Comment by BenjaminDebeerst** [comment]
I have been looking into this, and there is 4 dependencies that need an upgrade to be able to provide Scala 2.12 support as their current version don't have 2.12 support. This is:

* `com.typesafe.scala-logging:scala-logging` is currently at 3.4.0 and needs update to [at least 3.5.0](https://mvnrepository.com/artifact/com.typesafe.scala-logging/scala-logging_2.12)
* `net.databinder:unfiltered-netty-server` [currently has no scala 2.12 support](https://mvnrepository.com/search?q=net.databinder&p=1), but the project is active and 2.12 support is [in the making](https://github.com/unfiltered/unfiltered/blame/0.10.x/project/common.scala#L15)
* `net.databinder.dispatch:dispatch-core` is currently at 0.11.3 and needs update to [at least 0.12.0](https://mvnrepository.com/artifact/net.databinder.dispatch/dispatch-core_2.12)
* `io.gatling:jsonpath` is currently at 0.6.4 and needs update to [at least 0.6.8](https://mvnrepository.com/artifact/io.gatling/jsonpath_2.12)

I'll be working on PRs to update dependencies for those projects that do have Scala 2.12 support already.

**Comment by BenjaminDebeerst** [comment]
Contrary to what I wrote in my first comment, `unfiltered-netty-server` does have support for Scala 2.12 since version 0.9.0, and that version is already out. What I missed (and the reason why I didn't find it), is that the project group ID has been [renamed to `ws.unfiltered`](https://github.com/unfiltered/unfiltered/commit/91b81b318f0355c774f5c4130fb34b10f2f9fa1b). Versions 0.9.0 and 0.9.1 of the project have been released [under that new org name](https://mvnrepository.com/artifact/ws.unfiltered).

**Comment by uglyog** [comment]
Scala 2.12 version 3.5.4-rc.0 has been released

**Comment by kwark** [comment]
It looks like this is not working yet: I am getting following resolution problems

[warn] 	Note: Unresolved dependencies path:
[warn] 		au.com.dius:pact-jvm-model:3.5.4-rc.0
[warn] 		  +- au.com.dius:pact-jvm-matchers_2.12:3.5.4-rc.0
[warn] 		  +- au.com.dius:pact-jvm-consumer_2.12:3.5.4-rc.0 (XXXXXX)

So, it looks like jvm-matchers:3.5.4-rc0 depends on pact-jvm-model 3.5.4-rc.0 which does not exist. 
A 3.5.4 version does exist.

**Comment by uglyog** [comment]
Ah, yes, au.com.dius:pact-jvm-model:3.5.4 is the correct one.

Are you able to force the jar version, because I'll need to publish a new version to correct the dependency issue.

**Comment by kwark** [comment]
You can work around it by excluding the pact-jvm-model dependency and explicitly including the correct one in sbt:

```
libraryDependencies ++= Seq(
  "au.com.dius" %% "pact-jvm-consumer" % "3.5.4-rc.0" exclude("au.com.dius", "pact-jvm-model"),
  "au.com.dius" %% "pact-jvm-model" % "3.5.4"
)

```

**Comment by uglyog** [comment]
Closing this as master branch is now based on 2.12
