### ISSUE TITLE
Pact for SOAP 

### ISSUE THREAD

**Issue by suresh2000** [DiUS/pact-jvm#451]
Is pact framework supports SOAP?  if not is there plan for include in the future release?

**Comment by uglyog** [comment]
Pact can match XML documents, which SOAP messages are encoded as. But you will have to include rules for all the SOAP headers.

There is no plan to implement SOAP specific matching, but maybe someone will do so via a pull request.

**Comment by suresh2000** [comment]
Do you have some sample to exclude the SOAP Header

**Comment by hemantp2001** [comment]
We have a similar scenario where we have both SOAP services as well as REST services. It would be good if pact is available for both REST as well as SOAP. Do you provide any info or url for the rules to be configured to handle SOAP ?
