### ISSUE TITLE
failIfNoPactsFound = false only changes exception thrown

### ISSUE THREAD

**Issue by Nalha** [DiUS/pact-jvm#455]
Running my provider tests with the annotations:
```
@Provider("test_provider")
@PactBroker(failIfNoPactsFound = false, host = "localhost", port = "8080")
@RunWith(RestPactRunner.class)
```

throws this exception:
```
java.lang.Exception: Did not find any pact files for provider test_provider

	at org.junit.runners.model.InitializationError.<init>(InitializationError.java:38)
	at au.com.dius.pact.provider.junit.PactRunner.<init>(PactRunner.java:81)
```

While running it with failIfNoPactsFound = true throws this instead
```
u.com.dius.pact.provider.junit.loader.NoPactsFoundException: No consumer pacts were found for provider 'test_provider' and tag 'null'. (URL [])

	at au.com.dius.pact.provider.junit.loader.PactBrokerLoader.loadPactsForProvider(PactBrokerLoader.java:83)
```
Is there a way to disable the runner when pacts are missing or is this a broken feature?

**Comment by uglyog** [comment]
This is a broken feature.

**Comment by stemlaur** [comment]
Hello @uglyog, I encounter the same issue for the version 3.5.2, do you know what is the last version where this property `failIfNoPactsFound` feature was working ?

**Comment by uglyog** [comment]
There is a regression introduced in 2.4.1, so 2.4.0 should have the old behaviour.

This issue is on conflict with #188, so it needs to be fixed for both uses.

**Comment by uglyog** [comment]
I have deprecated the `failIfNoPactsFound` attribute and added a new `@IgnoreNoPactsToVerify ` annotation that can be added to the test class to control this behaviour.

**Comment by uglyog** [comment]
Version 3.5.3 has been released
