### ISSUE TITLE
'pact-jvm-consumer-junit_2.11', version: '3.4.0' throws  java.lang.NoSuchMethodError: au.com.dius.pact.model.MockProviderConfig.createDefault(Lau/com/dius/pact/model/PactSpecVersion;)

### ISSUE THREAD

**Issue by ricwal-richa** [DiUS/pact-jvm#456]
I am testing the 'swagger-request-validator-pact' library by atlassian. On running my consumer side tests I am getting following error -
11:13:45.235 [DEBUG] [TestEventLogger] com.cardinalhealth.SwaggerValidatorPactConsumerTestExample > testGetValidPet FAILED
**11:13:45.235 [DEBUG] [TestEventLogger]     java.lang.NoSuchMethodError: au.com.dius.pact.model.MockProviderConfig.createDefault(Lau/com/dius/pact/model/PactSpecVersion;)Lau/com/dius/pact/model/MockPr
oviderConfig;
11:13:45.235 [DEBUG] [TestEventLogger]         at au.com.dius.pact.consumer.PactProviderRule.<init>(PactProviderRule.java:51)
11:13:45.235 [DEBUG] [TestEventLogger]         at au.com.dius.pact.consumer.PactProviderRule.<init>(PactProviderRule.java:110)
11:13:45.235 [DEBUG] [TestEventLogger]         at com.atlassian.oai.validator.pact.ValidatedPactProviderRule.<init>(ValidatedPactProviderRule.java:33)**
............

On analyzing the problem further I realized that in the call to 'MockProviderConfig.createDefault' from 'PactProviderRule' class argument passed should be of type 'au.com.dius.pact.model.PactConfig' while it is currently trying to pass an enum value i.e au.com.dius.pact.model.PactSpecVersion

**Comment by ricwal-richa** [comment]
![pact model issue](https://user-images.githubusercontent.com/22143156/26948887-f7c8a784-4c65-11e7-90a6-ab91d2bb4d4e.png)

**Comment by uglyog** [comment]
Can you check all the pact libraries you are using have the correct version, because in the 3.4.x branch `MockProviderConfig` does have a method that takes a `PactSpecVersion` enum. It was introduced in 3.3.0.

See https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/groovy/au/com/dius/pact/model/MockProviderConfig.groovy#L36

**Comment by ricwal-richa** [comment]
Hi @uglyog,
Thanks for the response. I am using the pact version 3.4.0 (listed dependencies from my build file below)
dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.3.11'
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'com.atlassian.oai', name: 'swagger-request-validator-pact', version: '1.0.17'
    **compile group: 'au.com.dius', name: 'pact-jvm-provider-junit_2.11', version: '3.4.0'
    compile group: 'au.com.dius', name: 'pact-jvm-consumer-junit_2.11', version: '3.4.0'**
    compile 'org.apache.httpcomponents:fluent-hc:4.5.3'
    compile group:'com.github.rest-driver',name:'rest-client-driver',version:'1.1.45'
    compile group:'org.slf4j',name:'slf4j-api',version:'1.7.23'
    compile group:'org.slf4j',name:'slf4j-simple',version:'1.7.23'
    compile group:'commons-collections',name:'commons-collections',version:'3.2.1'
    compile group: 'io.rest-assured', name: 'rest-assured', version: '3.0.0'
    compile group: 'com.atlassian.oai', name: 'swagger-request-validator', version: '1.0.17'
}

The problem with 'PactProviderRule' class is that the reference call it is making to 'MockProviderConfig.createDefault' it is actually passing PactSpecVersion enum but 'MockProviderConfig.createDefault' is expecting the parameter type to be 'PactConfig'. (as shown in screenshot above).

'PactConfig' is not even present in au.dius.com:pact-jvm-model:3.4.0
It is present in au.dius.com:pact-jvm-model_2.11:3.2.6 (this library is getting automatically downloaded with above list of dependencies).
![pactconfig](https://user-images.githubusercontent.com/22143156/27087365-d6336eae-5022-11e7-8725-6c34855ab862.png)

**Comment by uglyog** [comment]
The issue is that pact-jvm-provider-junit_2.11:3.4.0 and pact-jvm-consumer-junit_2.11:3.4.0 depend on au.dius.com:pact-jvm-model:3.4.0 and will not work with au.dius.com:pact-jvm-model_2.11:3.2.6.

swagger-request-validator-pact is built against pact-jvm version 3.2.6, so it would be best to use that version. You could also try the latest in 3.2.x which is 3.2.13.
