### ISSUE TITLE
how to send MultipartFile in PactFragment

### ISSUE THREAD

**Issue by burakaraz** [DiUS/pact-jvm#462]
I am trying to put requestPart field in pact Fragment. Is there any way to put for MultiPartFile?

I need to put .part instead of .body I guess.
Pact:
public PactFragment createFragmentForFileManagementCreateFile(final PactDslWithProvider builder)
    {
        return builder
                .given(PROVIDER_FILEMANAGEMENT + CREATE_FILE)
                    .uponReceiving("POST createFile")
                    .path(FILE_MANAGEMENT_PATH)
                    .query(FILE_MANAGEMENT_QUERY)
                    .method(POST.name())
                    .body("anyFileData", MediaType.MULTIPART_FORM_DATA_VALUE)
                .willRespondWith()

Controller that I want to call:
@VersionedResource
    @RequestMapping(method = POST)
    public ResponseEntity<FileResource> createFile(
            @RequestPart final MultipartFile file,
            @RequestParam final String assetId,
            @RequestParam(required = false) final String properties
    ) throws IOException {

**Comment by uglyog** [comment]
Multi-part file uploads are a bit complicated, and are not supported directly. The main problem is that the boundary markers in the content header need to match what is in the body. See this comment: https://github.com/DiUS/pact-jvm/issues/123#issuecomment-105485349

**Comment by uglyog** [comment]
The Java DSL was updated to include a `withFileUpload` method, which will generate the correct headers and body.
