### ISSUE TITLE
pact-jvm-consumer-junit, provide ability to shuffle Strings in array

### ISSUE THREAD

**Issue by SchulteMarkus** [DiUS/pact-jvm#464]
I am using PactProviderRuleMk2 Junit-rule for generating test-data while pact-testing.
In my usecase, I am generating an JSON-array to test against. This array contains (among others) an "id"-field of type String (yes ...). 

Right now, the contained elements of my generated are the same, like this

    {"my-array":[{"id":"OHpRMRttzGoabqPfPzQt"},{"id":"OHpRMRttzGoabqPfPzQt"}]}

I would appreciate a way to build "my-array", so that the String-"id"-element has another value for each sub-child in "my-array". The output would be like this:

    {"my-array":[{"id":"asdfqwer"},{"id":"ghjktyui"}]}

I have implemented a test [Defect464Test](https://github.com/SchulteMarkus/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/Defect464Test.java) for demonstrating my issue.

**Comment by uglyog** [comment]
Version 3.5.0 does not have this issue.

**Comment by SchulteMarkus** [comment]
Indeed, closed for 3.5.*
