### ISSUE TITLE
Maven trimSnapshot configuration option doesn't work

### ISSUE THREAD

**Issue by dylanwatsonsoftware** [DiUS/pact-jvm#469]
Basically I'm trying to run:
`mvn pact:publish`

I have a SNAPSHOT version and have the `trimSnapshot` option set to true.

However, when running the command I still get:
`FAILED! 400 Bad Request - Consumer version number '1.0.0-SNAPSHOT' cannot be parsed to a version number. The expected format (unless this configuration has been overridden) is a semantic version. eg. 1.3.0 or 2.0.4.rc1`

For reference, I have a pom.xml something like the following:
```
    <groupId>com.myproject</groupId>
    <artifactId>super-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>

            <plugin>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-provider-maven_2.11</artifactId>
                <version>3.3.8</version>
                <configuration>
                    <pactBrokerUrl>http://server:8080</pactBrokerUrl>
                    <projectVersion>${project.version}</projectVersion>
                    <trimSnapshot>true</trimSnapshot>
                </configuration>
            </plugin>
```

**Comment by uglyog** [comment]
Use version 2.4.1, that contains the `trimSnapshot` option.
