### ISSUE TITLE
DSL method `or` inside `.object()` erroneously generate `AND` as combine rule

### ISSUE THREAD

**Issue by lucaong** [DiUS/pact-jvm#483]
Hello,
if I specify a JSON body like:

```java
builder.body(
  new PactDslJsonBody()
    .object("foo")
      .or("bar", 42, PM.numberType(), PM.nullValue())
    .closeObject()
).toPact();
```

It erroneously generate a JSON like the following:

```javascript
"body": {
  "foo": {
    "bar": 42
  }
},
"matchingRules": {
  "body": {
    "$.foo.bar": {
      "matchers": [
        {
          "match": "number"
        },
        {
          "match": "null"
        }
      ],
      "combine": "AND" // this should be "OR"!
    }
  }
}
```

Interestingly, if the `.or()` is outside of `.object()`, it works fine. For example, the following generate a correct JSON, combining clauses with `"OR"`:

```java
builder.body(
  new PactDslJsonBody()
    .or("bar", 42, PM.numberType(), PM.nullValue())
).toPact();
```

**Comment by lucaong** [comment]
I tried to give a brief look at it, but I could not find the source of the issue. The call to the `.or` method correctly creates a `MatchingRuleGroup` with `RuleLogic.OR` (in https://github.com/DiUS/pact-jvm/blob/1aa4833dd3303880e4624d419ab9c437c6dc2402/pact-jvm-consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslJsonBody.java#L1066), and the `matchingRuleGroup.toMap()` method works fine.

I suspect the issue might be with the way the matching rules are copied over to the parent object in the `closeObject()` DSL method, but I still could not isolate the bug. Any idea?

**Comment by uglyog** [comment]
You are correct, the OR value is not being copied over to the parent object.

**Comment by lucaong** [comment]
Thanks for the fast response and fix! :)

**Comment by uglyog** [comment]
Version 3.5.3 has been released
