### ISSUE TITLE
Spring provider default context path

### ISSUE THREAD

**Issue by Nalha** [DiUS/pact-jvm#485]
All our spring APIs have a default context path of /api and there doesn't seem to be a way to add these in the pact-jvm-provider-spring.

Traditional integration tests would simply ignore the context path but our consumers are hard coded to use it and therefore write it into our pacts.

Is there a way to make a custom spring context with this, configure the pact provider for it or is it a missing feature?

**Comment by uglyog** [comment]
Doesn't look like there is a way to set the context path at the moment, but it should not be too hard to do.

**Comment by uglyog** [comment]
You can use a request filter to remove the `/api` from the path. 

```java
    @TargetRequestFilter
    public void stripContextPathRequestFilter(HttpRequest request) throws URISyntaxException {
        String rawUri = request.getRequestLine().getUri();
        ((HttpRequestBase) request).setURI(new URI(rawUri.replaceFirst("/api/", "/")));
    }
```
