### ISSUE TITLE
Can't create a plain string response if content type is 'application/json'

### ISSUE THREAD

**Issue by bbarke** [DiUS/pact-jvm#486]
See gist:
https://gist.github.com/bbarke/8245deed6a8a5b96e52a3d0f3673141a

The problem I'm seeing:
If the response body is a simple string, I get a error saying:

```
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is 'h' with an int value of 104
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
hi
^
```

If the body has quotes surrounding the text, `JsonSlurper` will parse and run just fine, except it then contains quotes in the final result as seen in the gist

I can create a PR for this.

**Comment by uglyog** [comment]
The problem is that a simple string is not valid JSON. For plain text, you should use the `text/plain` content type.

**Comment by bbarke** [comment]
I think that is reasonable. Closing...
