### ISSUE TITLE
Root level string array

### ISSUE THREAD

**Issue by Nalha** [DiUS/pact-jvm#487]
I am using pact-jvm-consumer-junit and one of the calls I need to test is using a root level string array in its request.

I've looked around at examples and code to find a way to have eachLike behaviour on the root level array but it doesn't seem to be available.

**Comment by uglyog** [comment]
I've added 3 new methods to PactDslJsonArray for this:

```

**Comment by uglyog** [comment]
Version 3.5.3 has been released
