### ISSUE TITLE
Configurable differ/diff formatter based on content type

### ISSUE THREAD

**Issue by bethesque** [DiUS/pact-jvm#49]
Hi guys,

We have a team who wants to use the JVM pact with XML. How close are you to being able to configure the differ and diff formatter by content type?

**Comment by amarpotghan** [comment]
:+1:  We also have the same requirement! When are we expecting this issue to be closed?

**Comment by uglyog** [comment]
Currently, pact-jvm has been re-factored to support multiple different matchers based on mime type. Only a JSON matcher has been implemented, but other types can be easly added.

Do you require handling of XML (as was the original requirement), or something else?

**Comment by amarpotghan** [comment]
@uglyog yes, I require xml handling. I assume I need to write Xml-matcher by myself?

**Comment by uglyog** [comment]
If you feel up to doing a pull request, that would be great. But I can also implement one for you.

**Comment by amarpotghan** [comment]
@uglyog :+1: sure, anything will do :)

**Comment by bethesque** [comment]
Can you add test cases to the pact specification if/when you do Ron, so we can talk someone into doing the Ruby impl? (hint: it won't be me)

**Comment by mdjnewman** [comment]
I've just pushed a commit to https://github.com/mdjnewman/pact-jvm/commit/2cc1085e87c2f6bfec509d59ad6e00a969f90f4a that shows what we found while spending a day or so looking at adding XML support.

This commit isn't intended to be merged, we just wanted to show the approach we were thinking off. There are multiple problems with the commit (as covered in the commit message) but the [XmlBodyMatcher.scala](https://github.com/mdjnewman/pact-jvm/blob/2cc1085e87c2f6bfec509d59ad6e00a969f90f4a/pact-jvm-matchers/src/main/scala/au/com/dius/pact/matchers/XmlBodyMatcher.scala) might be useful.

**Comment by uglyog** [comment]
Thanks @mdjnewman. That's a step in the write direction.

The first thing that will make it better is to return a list of all the mismatches instead of just a single result. The way I'm reading the code is that it will report the first mismatch. Correct me if I'm mistaken.

**Comment by uglyog** [comment]
pull request #125 adds XML matching
