### ISSUE TITLE
PactDslJsonRootValue.stringType()  or stringMatcher  doesn't  work

### ISSUE THREAD

**Issue by yuqitao** [DiUS/pact-jvm#494]
bilud success only on the situations where the server response a string that is equal to the example string.
It seems that the stringMatcher doesn't work

**Comment by yuqitao** [comment]
a request to say Hello returns a response which has a matching body
      / -> mismatch

**Comment by bbarke** [comment]
Do you have an example pact file that produces this message?

**Comment by yuqitao** [comment]
Matcher for text plain #496   
I just saw it
what can I do to get this ? pact-jvm-consumer-junit_2.11   3.5.2 or lastest ?

**Comment by uglyog** [comment]
The next release will include it.

**Comment by yuqitao** [comment]
OK，thank you
