### ISSUE TITLE
Pact how to do contract testing by hitting the real service url

### ISSUE THREAD

**Issue by hemantp2001** [DiUS/pact-jvm#498]
hi,
In my application I am consuming a service and I want to generate a pact file by actually hitting the provider service url. Right now I notice that my current code is always going to Mock provider and then only Pact file is getting generated. This is due to the below PactproiderRule configuration
@rule
public PactProviderRule rule = new PactProviderRule("weatherprovider",
PactSpecVersion.V3, this);
My run test code is as below:
assertEquals(new WeatherService(rule.getConfig().url()).getMaxTemp().toString(),"{"MaxTemp":300.01}");

rule.getconfig() is always hitting mockprovider getconfig method.

Can someone please guide me on how to hit the real provider service url from my consuming application ?

**Comment by Nalha** [comment]
The whole idea of pact is to separate the consumer and provider with a contract, if you want to test the provider you should use a pact provider test and replay the contract afterwards.

**Comment by uglyog** [comment]
As @Nalha mentioned, the point of the PactProviderRule in a consumer test is to pretend to be the provider so you can test your code without having to have the provider running.

Have a look at the pact-jvm-provider modules for a number of ways of replaying the pact file against your actual provider.
