### ISSUE TITLE
pact-jvm-server complete 400

### ISSUE THREAD

**Issue by cotnic** [DiUS/pact-jvm#502]
Hello, I have a problem with pact-jvm-server requests. When I create the mock service with pact file it returns the correct response and creates the stub server. But when I call the POST request on /complete with port in body it always returns 400 even though it deletes the stub service. Has anyone an idea why this happens and how to fix it? I've tried it with Postman and also with a Maven plugin from my microservice, where the build fails because it gets 400 even though it again deletes the stub service on provided port in body. Any help would be appreciated.

**Comment by cotnic** [comment]
I'm doing this with the Docker image provided: uglyog/pact-jvm-server

If I try to execute over the URL I get the following response: 

`$ curl -v -d '{"port":20004}' localhost:8080/complete
* timeout on name lookup is not supported
*   Trying ::1...
* TCP_NODELAY set
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                             Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (::1) port 8080 (#0)
> POST /complete HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 14
> Content-Type: application/x-www-form-urlencoded
>
} [14 bytes data]
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Connection: keep-alive
< Content-Length: 613
<
{ [613 bytes data]
* Curl_http_done: called premature == 0
100   627  100   613  100    14  40866    933 --:--:-- --:--:-- --:--:--  598k{"error": "Pact verification failed for the following reasons:

The following requests were not received:
Interaction: catalogue test interaction
    in state None
request:
    method: GET
    path: /books/1
    query: null
    headers: null
    matchers: null
    body: au.com.dius.pact.model.OptionalBody(MISSING, null)

response:
    status: 200
    headers: [Content-Type:application/json]
    matchers: [body:[$.bookOrders:[combine:AND, matchers:[[match:type, min:0]]]]]
    body: au.com.dius.pact.model.OptionalBody(PRESENT, {"author":"J.K. Rowling","bookOrders":[],"description":"Books about a wizzard","id":1,"title":"Harry Potter"})"}
* Connection #0 to host localhost left intact`

**Comment by cotnic** [comment]
no response, closing

**Comment by uglyog** [comment]
Is this still an issue?
