### ISSUE TITLE
Allow specifying code in a scripting language that would be embedded in a pact file and run during provider verification

### ISSUE THREAD

**Issue by slugcat** [DiUS/pact-jvm#507]
Sometimes there are complex relations between requests and responses, or within responses.  Simple matching does not always suffice.  So define hooks at various levels (body, map, key+value) that would invoke a script and pass the thing (eg key and value) as objects in the scripting language.  It should be possible to pass the request (or fragments of the request) as well.  This would facilitate complex validations, and reduce the need for you to add ever more specific ways of validating.

**Comment by uglyog** [comment]
I have thought about this before. The main problem is that Pact is used across a lot of different languages, so the scripting language would need to work the same way across all of them.

JavaScript may be a good scripting language we could use for this, or maybe LUA. The other option would be to develop a simple scripting language and provide an implementation to all the language implementors.

This would have to be driven through the pact specification project.

**Comment by slugcat** [comment]
If there were a standard scripting language that could be used for arbitrary verification that worked with a standard test runner, then there wouldn't me much need to have more than one test runner.  Other facilities would just run this standard test runner.

I would strongly suggest a real, powerful scripting language with lots of resources behind it, javascript would be a good choice, LUA a bad choice and home-grown a really bad choice.

You are just the man to drive it!
