### ISSUE TITLE
Support for one query parameter multiple times

### ISSUE THREAD

**Issue by maxant** [DiUS/pact-jvm#509]
The service I am calling takes a query parameter named "nodeId". This parameter can have multiple values, so a request URL can look like this:

    http://localhost/path?nodeId=8&nodeId=20&nodeId=999

I tried to build the fragment like this:

            .matchQuery("nodeId", "^[0-9]{1,3}$", "8")
            .matchQuery("nodeId", "^[0-9]{1,3}$", "20")
            .matchQuery("nodeId", "^[0-9]{1,3}$", "999")

However I get the following error when running the consumer pact test:

    QueryMismatch(nodeId,List(999),List(8, 20, 999),Some(Expected query parameter nodeId with 1 values but received 3 values),$.query.nodeId)

While not quite that normal, HTTP allows you to provide the same query parameter multiple times, allowing a single service call to respond with multiple sets of data.

Is this supported and if not, please consider this a feature request :-)

**Comment by uglyog** [comment]
This is a defect. It should support multiple query parameter values. You also should only have to supply one matcher which should be applied to all the parameters.

**Comment by maxant** [comment]
I guess the API needs to be something like this:

    .matchQuery("nodeId", "^[0-9]{1,3}$", Arrays.asList("8", "20", "999"))

That way the JSON which the provider runs will be called with all three values.
