### ISSUE TITLE
Provide a PactDslResponse matchHeader with noRegexp?

### ISSUE THREAD

**Issue by ehmkah** [DiUS/pact-jvm#512]
Would it be possible to provide a method matchHeaderExact(header, example) to [PactDSLResponse](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer/src/main/java/au/com/dius/pact/consumer/dsl/PactDslResponse.java) that it is possible to add a header without a regexp?

My use-case: I like to test whether the expected media-type is returned from the server. I found a workaround to provide it like `.matchHeader("Content-Type", ".", "application/vnd.ehmkah.app-1.0+json")` which makes it difficult to read. Or is that the way I should do it with pact?

**Comment by uglyog** [comment]
The default is to match using equality. Just use `headers(Map<String, String> headers)` to set the exact headers that are required.

**Comment by ehmkah** [comment]
Ok. I thought that message should be used when I want to match ALL headers. But I am only interested in one header. I do not care for the others.

**Comment by uglyog** [comment]
It should be used to specify only the headers you want to match on (not all headers). You can set your single header value there.

**Comment by ehmkah** [comment]
I could change the documentation of this method to:

````
/**
 * Response headers to return.
* 
* Provide the headers you want to validate, other headers willl be ignored.
 *
 * @param headers key-value pairs of headers
*/
````

**Comment by ehmkah** [comment]
With the additional information the issue is closed for me.
