### ISSUE TITLE
Cannot update to au.com.dius:pact-jvm-consumer-junit_2.11:3.5.4

### ISSUE THREAD

**Issue by SchulteMarkus** [DiUS/pact-jvm#521]
au.com.dius:pact-jvm-consumer-junit_2.11:3.5.4 was released today¹.

When I update (from 3.5.3) to 3.5.4 in my pom.xml, I cannot build any more. Instead, following error occurs

    [ERROR] Failed to execute goal on project abc: Could not resolve dependencies for project xxx: Could not find artifact com.github.kittinunf.result:result:jar:1.1.0 -> [Help 1]

¹ https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22au.com.dius%22%20AND%20a%3A%22pact-jvm-consumer-junit_2.11%22

**Comment by uglyog** [comment]
Hmm, looks like `com.github.kittinunf.result:result` is not available in maven central, only on jcenter.

For the docs to add jcenter to your maven repos go to https://bintray.com/bintray/jcenter and click the 'Set me up' button.

I'll inline that library and raise an issue with the project.

**Comment by uglyog** [comment]
3.5.5 no longer depends on this library
