### ISSUE TITLE
Results are not published to pact broker when using @RunWith(FilteredPactRunner) with jvm-provider-junit

### ISSUE THREAD

**Issue by valemany** [DiUS/pact-jvm#522]
Note: It works fine when using the normal @PactRunner.

**Comment by uglyog** [comment]
Pushed a fix for the issue.

**Comment by bethesque** [comment]
I don't think this is a bug! Verification should only be considered complete when ALL the interactions in a pact are verified. Verifying only some does not give you confidence that the consumer/provider will work in real life.

**Comment by uglyog** [comment]
Sigh, trust @bethesque to open a can of worms ;-)

So how do we determine when the pact is verified if we can filter the interactions and these can run in separate tests, maybe even on separate build agents?

**Comment by uglyog** [comment]
We might have to track the results per interaction, and post that to the broker.

**Comment by bethesque** [comment]
I started off with big sky design that reported each interaction and it's status, and then dialled it back to the bare basics when I implemented it. So we can increase the complexity if need be.

How common is this "run the verifications in separate processes" thing?

**Comment by bethesque** [comment]
@valemany what is your use case for verifying with the filter?

**Comment by valemany** [comment]
Thanks for looking into this guys. 

I agree we should only see results when all pacts are verified. The reason why I use the FilteredPact is because it gives us the ability to run a single suite of test instead of running all the pacts. I think it would be good to have a number of total pacts and if I run the tests and total of number of pacts are verified then it means i ran the whole suite so I can get my results published, otherwise its fine not to publish results if I am only running a few tests if that makes sense.

**Comment by bethesque** [comment]
@valemany are you running filtered interactions in your CI, or just locally? I'd recommend only publishing the verification results from your CI, not when running on your local machine. You can see an example of how you might do this here (obviously you'd need to adapt it for the JVM) https://github.com/pact-foundation/pact_broker/wiki/Provider-verification-results

**Comment by valemany** [comment]
@bethesque 

We are using PactFiltered in both CI and Locally, because its part of the class annotation so you cant really use different runners locally and in CI without a code change. 

Let me give you more context on why we chose to use the FilteredPact as our default runner. 

When we where using the normal runner we had the following issue: 

One person created a new pact that was failing, he wanted to do full troubleshooting so he published it  (it was work in progress). Another person opened a PR including a new pact that was working, but his PR failed because the pact from the other person failed (because normal PactRunner runs everything) Thats what FilteredPact gives us, the ability to enable pacts when we feel they are ready and removes the dependency for other people wanting to publish pacts that are not yet working on the provider side for troubleshooting purposes.

**Comment by carlosmmelo** [comment]
In short:

We wanted to seperate the tests on multiple files instead of one big huge file like so:

![image](https://user-images.githubusercontent.com/5649650/29578264-ab611234-873c-11e7-8279-ced5977ff52c.png)


If you dont filter the patcs on each one of the files, its gonna run ALL the patcs from the broker on each file in the provider. Since we dont have ALL the tests on each file but rather the correspondent test per Controller for example (also better organized) then the "missing tests" are gonna be a false negative cause it didnt find them.

This is why the FilteredPact runner is useful for us.

**Comment by carlosmmelo** [comment]
I think the initial commit from @uglyog was ok, but to cover your concern @bethesque (which is very valid) I think @uglyog should add a safe check checking if ALL test from broker were executed (between the whole run/files) then publish, else exception or some warning saying we are missing tests from the broker.

**Comment by bethesque** [comment]
Ah! I think understand. You're choosing which pacts to run, not filtering interactions *within* a pact?

**Comment by carlosmmelo** [comment]
that is exactly right! @bethesque

**Comment by bethesque** [comment]
I agree, it makes perfect sense to publish the verifications for the (full) pacts that have actually been run.

**Comment by carlosmmelo** [comment]
for example, Given we have 8 tests in total:

### File number 1:
```
@PactFilter(["request 1", "request 2", "request 3","request 4"])
@RunWith(FilteredPactRunner)
@Provider("My_Provider")
@PactBroker(host = "{broker_ip}", port = "80")
@TestFor(APIController1)
```

### File number 2:
```
@PactFilter(["request 5", "request 6", "request 7", "request 8"])
@RunWith(FilteredPactRunner)
@Provider("My_Provider")
@PactBroker(host = "{broker_ip}", port = "80")
@TestFor(APIController_2)
```

**Comment by valemany** [comment]
@bethesque that is correct.

**Comment by martinreus** [comment]
We also have some provider tests which are separated in different Test Suites. This enables us to keep the suites as small as possible.

I would agree to the idea that, once all states of a Pact are tested, the Pact file should be considered as verified for a consumer<->provider

**Comment by nikitasharma2692** [comment]
When the code will be published on Maven ?

**Comment by bethesque** [comment]
I've just realised there has been some misunderstanding due to incorrect terminology. A pact is the entire file, where as an interaction is a request/response pair. One pact => many interactions. What you're asking is to split the execution of those interactions across many test files, and once they're all verified, to publish the results back to the broker.

**Comment by valemany** [comment]
Yes that is correct. Thanks.

**Comment by valemany** [comment]
@bethesque  "What you're asking is to split the execution of those interactions across many test files, and once they're all verified, to publish the results back to the broker." <= That works for me.

**Comment by valemany** [comment]
@uglyog what do you think ^ ?

**Comment by uglyog** [comment]
My concern is working out when all the interactions have been verified. If the tests are running distributed across different machines, we need to accumulate the results in a central place, and then publish them once we have checked that all interactions are verified. We can only do this by comparing the results against the original pact file, and then we need to combine them to publish.

This adds a lot of complexity.  We can reduce this somewhat by using the build directory as a temporary store, but then the tests have to run on the same machine.

**Comment by valemany** [comment]
` We can reduce this somewhat by using the build directory as a temporary store, but then the tests have to run on the same machine.` <= I think that would work for most ppl/cases. That definitely works for me and my team.

**Comment by CraigAtWork** [comment]
Hello, has there been any resolution on this thread? We have a similar configuration where we use the JUnit-based runner and we use @PactFilter to break our unit tests for each data state into separate classes.

With the above configuration, is there a mechanism to publish the results back to the broker?

**Comment by uglyog** [comment]
No progress on this issue to date.

**Comment by ngentse** [comment]
Hello, we have the same problem. 
Do anyone have a workaround for this?

**Comment by krutoystas** [comment]
We have the same problem too. We have 13 controllers in our project and we use pact-jvm. I think, it will be better to use RestPactRunner in several test classes with common controlling

**Comment by uglyog** [comment]
Version 3.6.5 has been released with this feature

**Comment by HiTAsm** [comment]
Hello, I'm using 3.6.5 version but this does not work. I'm using PactRunner as the FilteredPactRunner is deprecated.
Is there a flag or annotation to use in order to make this work or should it work natively in 3.6.5 ?

**Comment by uglyog** [comment]
@HiTAsm in what way does it not work?

**Comment by HiTAsm** [comment]
@uglyog, from what I understood from this thread is once we break our tests to multiple seperate classes where we filter on each of the states that we want to test, the pact would be considered as verified only and only if all the interactions are tested. 
In my use case, I have a test class where I filter on a particular state without testing the other states, once I run the test, the pact is considered as verified even though not all interactions within the pact were tested so I was expecting that the verification fails

**Comment by HiTAsm** [comment]
@uglyog, after upgrading to 3.6.13, the behaviour I described now works.
