### ISSUE TITLE
Multiple calls to provider which depend upon each other

### ISSUE THREAD

**Issue by maxant** [DiUS/pact-jvm#529]
We have a provider which is called multiple times. Each time it is called, the internal state changes. We are dealing with something like a case management system, and we want to write a test to check that a case can be moved through multiple states.

We have written a Pact Fragment which contains multiple interactions, i.e. multiple calls to "uponReceiving".

        PactFragment pactFragment = ConsumerPactBuilder
                .consumer("EventsConsumer1")
                .hasPactWith("EventsProviderNew")
                .given("InitialState")    <-- IMPORTANT 1
                .uponReceiving("Z")    <-- IMPORTANT 2
                .path("/all")
                .method("POST")
                .body("{\"someField\": \"asdf1\"}")
                .willRespondWith()
                .status(200)
                .body(body)

                .uponReceiving("A")    <-- IMPORTANT 3
                .path("/all")
                .method("POST")
                .body("{\"someField\": \"asdf2\"}")
                .willRespondWith()
                .status(200)
                .body(body)
                .toFragment();

So we are going to call the service first of all with "asdf1" and then again with "asdf2". It happens to be the same service method here, but it could be different ones.

The consumer test runs through fine and the Pact JSON is generated.

The problem that we have is twofold.

First of all, the order of the interactions is changed in the JSON. In Java we put the order as `uponReceiving("Z")` and then `uponReceiving("A")`, but in the JSON, A is listed first, causing the provider test to call the service in the wrong order.

**Can we rely on the ordering to be based upon the description?**

The second problem is that in the JSON both interactions have the state set to "InitialState", so when the second interaction is tested, it is based upon the initial state, rather than the state after the first interaction.

**Is this a bug?**

Here is the generated JSON:

	{
		"provider": {
			"name": "EventsProviderNew"
		},
		"consumer": {
			"name": "EventsConsumer1"
		},
		"interactions": [
			{
				"description": "A",   <-- IMPORTANT
				"request": {
					...
					"body": {
						"someField": "asdf2"
					}
				},
				"response": {
					"status": 200,
					...
				},
				"providerState": "InitialState"   <-- IMPORTANT
			},
			{
				"description": "Z",   <-- IMPORTANT
				"request": {
					...
					"body": {
						"someField": "asdf1"
					}
				},
				"response": {
					"status": 200,
					...
				},
				"providerState": "InitialState"   <-- IMPORTANT
			}
		],
		"metadata": {
			"pact-specification": {
				"version": "2.0.0"
			},
			"pact-jvm": {
				"version": "3.3.7"
			}
		}
	}

**Comment by uglyog** [comment]
Pact has been designed to test the different requests in isolation. See https://docs.pact.io/best_practices/consumer.html for more on this. Thus, there has never been any guarantee as to the order that requests will be validated. Each request should be able to be validated without requiring other requests to be done first. We have always tried to keep to verifying the contract and avoid behaviour testing.
