### ISSUE TITLE
Pact SBT returns exit code 0 when tests fail.

### ISSUE THREAD

**Issue by ShaneDelmore** [DiUS/pact-jvm#53]
I am using travis-ci for continuous integration and noticed that if I have a failure with "sbt test" then sbt exits with a non-zero code, causing my continuous integration service to notify me of a failed test, but if "sbt verifyPacts" has an error it exits with 0 and the continuous integrations tests pass when I would have liked them to fail.

**Comment by uglyog** [comment]
The SBT plugin has been updated (version 2.4.4) with a new verify task (`pactVerify`) that will return an error exit code if the verification fails.
