### ISSUE TITLE
upgrading pact jvm consumer to 3.5.4 gives java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by shailesh-waman** [DiUS/pact-jvm#531]
We tried upgrading the pact jvm-consumer version from 3.2.4 to 3.5.4

We are getting following error while generating pact json from consumer

```
java.lang.IllegalAccessError: tried to access method com.google.common.collect.Lists.cartesianProduct([Ljava/util/List;)Ljava/util/List; from class au.com.dius.pact.model.PactMerge
```

Another observation, we tried example [ExampleJavaConsumerPactRuleTest](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/examples/ExampleJavaConsumerPactRuleTest.java) , It executes successfully and generate pact json. However when same request is executed once again, it fails with the same error mentioned above.

**Comment by uglyog** [comment]
Can you check your dependencies. Versions 3.5.x depend on `pact-jvm-model`, while versions before v3.3.x depend on `pact-jvm-model_2.11`. It may be that your build is still pulling in the old model library.

**Comment by mouserd** [comment]
I had this same issue today and in the end it turned out that one of my compile dependencies had a transitive dependency for an older version of guava (version 18.0).

I'm not sure if this is the best approach but to get around it I explicitly specified that I needed version 19.0 of guava in my test compile dependencies.

Hope this helps!

**Comment by uglyog** [comment]
That could be it. Could you provide a dependency tree?

**Comment by scheuchzer** [comment]
Same here. I had to explicitly add guava 19.0 as a dependency. In my case this is because I'm using spring-cloud that uses guava 18.0. Same dependency mess I have with netty libraries. They're also part of some spring-cloud libs like eureka.

**Comment by shailesh-waman** [comment]
Sorry for the delayed response.

Same as @scheuchzer 
My project build was putting old dependencies which was conflicting with needed dependency (i.e. guava)
I explicitly specify dependencies for guava which fix this issue for me.

**Comment by uglyog** [comment]
I'm going to be removing guava, as well as some of the other dependencies which are causing issues.

**Comment by scheuchzer** [comment]
Great! Thanks

**Comment by kshrivastava-r7** [comment]
Hi, I have this issue too, and my app needs to be depend on guava 18.0.
Would you be releasing another version that would work with guava 18.0?

**Comment by uglyog** [comment]
The next version (3.5.8) has guava downgraded to 18. I'll release that version soon.
