### ISSUE TITLE
pact-jvm-provider-maven_2.11:3.5.4-jre7.0:Verification filure

### ISSUE THREAD

**Issue by jayanth1007** [DiUS/pact-jvm#533]
pact-jvm-provider-maven_2.11:3.5.4-jre7.0 failing with the following error, but works fine with pact-jvm-provider-maven_2.11:3.5.4. (Java 8 version)

[ERROR] Failed to execute goal au.com.dius:pact-jvm-provider-maven_2.11:3.5.4-jre7.0:verify (default) on project oep.store.service.impl: Execution default of goal au.com.dius:pact-jvm-provider-maven_2.11:3.5.4-jre7.0:verify failed: No signature of method: com.sun.proxy.$Proxy28.accept() is applicable for argument types: (groovy.json.internal.LazyMap) values: [[href:http://<BROKER_URL>/pacts/provider/<PROVIDER>/consumer/<CONSUMER>/version/<VERSION>, ...]]

**Comment by uglyog** [comment]
The commit I just pushed should fix this.
