### ISSUE TITLE
@IgnoreNoPactsToVerify doesnt work with tags

### ISSUE THREAD

**Issue by Nalha** [DiUS/pact-jvm#535]
Using pact_jvm_provider_spring:

@IgnoreNoPactsToVerify doesn't work if you list tags on @PactBroker

au.com.dius.pact.provider.junit.loader.NoPactsFoundException: No consumer pacts were found for provider 'MyService' and tag 'prod'. (URL [])

@RunWith(RestPactRunner.class)
@Provider("MyService")
@IgnoreNoPactsToVerify
@PactBroker(host = "example.com", port = "7500", tags = "dev,prod")

**Comment by uglyog** [comment]
This was due to an incorrectly handled exception, should be fixed now.
