### ISSUE TITLE
pact-jvm-model doesn't have 3.5.5-jre7.0 

### ISSUE THREAD

**Issue by cosineyan** [DiUS/pact-jvm#537]
Hi there,

When using Pact Jvm Provider_2.11 version 3.5.5-jre7.0, it has the compile dependency of pact-jvm-model 3.5.5-jre7.0. However this lib doesn't have 3.5.5-jre7.0 version in center maven repository. Could you help?

Regards,
Cosine

**Comment by uglyog** [comment]
Oops, let me publish that for you.

**Comment by uglyog** [comment]
pact-jvm-model 3.5.5-jre7.0 has now been published to maven central. It should be available in the next few hours.

**Comment by cosineyan** [comment]
Good. Thanks a lot.
