### ISSUE TITLE
Is there a way to load the broker properties from a configuration file ?

### ISSUE THREAD

**Issue by tal181** [DiUS/pact-jvm#539]
Is there a way to load the broker properties from a configuration file ?

**Comment by uglyog** [comment]
Depends on the build tool you are using. With Gradle it is possible.

**Comment by tal181** [comment]
what about maven ?

**Comment by uglyog** [comment]
Looks like Maven Surefire plugin does not support loading properties from a configuration file by default. There could be another plugin you could use, you will have to research this.
