### ISSUE TITLE
Spring Boot Provider support

### ISSUE THREAD

**Issue by thombergs** [DiUS/pact-jvm#547]
In my current project, we develop microservices with Spring Boot and use Pact for CDC tests between those microservices and between the microservices and an Angular UI. 

So, all of our providers are Spring Boot applications. We started off using [pact-provider-spring](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-spring) but quickly got into problems since we could not guarantee that the mocked Spring MVC environment produced the correct output. For example, the mock environment used a different JSON mapper, exception handler, [HandlerMethodArgumentResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/method/support/HandlerMethodArgumentResolver.html), ...).

Now, we could try to configure the mock environment accordingly, but that would mean if something changed in the real application configuration, it might be overlooked in the configuration of the mock environment. 

Thus, we decided to start up the real Spring Boot application in a provider test to remove those problems. We still mock away some things, but we start the real application.

It would be nice to have this Spring Boot support built-in. That would make it easier to adopt Pact in a Spring Boot microservice project. Perhaps with a custom `SpringBootTarget` that starts up a Spring Boot application and runs the pact requests against this application. 

Something along these lines:

```java
@RunWith(RestPactRunner.class)
@Provider("myAwesomeService")
@PactFolder("pacts")
public class ContractTest {

    @TestTarget
    public final SpringBootTarget target = new SpringBootTargetBuilder()
        .withApplicationClass(MyAwesomeApplication.class)
        .withConfigurationSource(MockConfiguration.class)
        .withProperty("spring.data.jpa.repositories.enabled", false)
        .withProperty("server.port", 8080)
        .build();

    private static MyAwesomeRepository repositoryMock = Mockito.mock(MyAwesomeRepository.class);

     @Configuration
     static class MockConfiguration {
         @Bean
         private MyAwesomeRepository repository(){
             return repositoryMock;
         }
     }
    
    @Before 
    public void before() {
        Mockito.reset(repositoryMock);
    }

    @State("default")
    public void toDefaultState() {
        when(repositoryMock.findOne(anyLong())).thenReturn(new MyEntity());
     }

}
```

I'd be glad to give it a try and provide a PR if you think this feature worthwhile. Our current workaround is halfway there already anyways.

**Comment by uglyog** [comment]
I've just created a `SpringRestPactRunner` that extends the default `PactRunner` to work with the Springboot test annotations.

**Comment by thombergs** [comment]
Is there a snapshot or nightly or beta build of 3.5.7 available through any maven repository? I'd very much like to try that feature in our project as soon as possible to give feedback.

**Comment by uglyog** [comment]
3.5.7 is available in maven central.

**Comment by thombergs** [comment]
This has been working for some time now, so I guess we can close the issue :). It even works in combination with `@PactFilter` (see #572 )
