### ISSUE TITLE
Underscore ("_") in the name of the key throwing error

### ISSUE THREAD

**Issue by sunitav** [DiUS/pact-jvm#548]
I have a response that has keys separated by underscore ("\_") 
When I try to generate a pact with stringType for these keys, I get the following error
<code>au.com.dius.pact.model.InvalidPathExpression: "_" is not allowed in an identifier in path expression "$.blah\_blah_type" at index 5</code>

Here's what my PactDslJsonBody looks like
``` return new PactDslJsonBody()
                    .stringType("blah_blah_type")
                    .date("blah_early_pull_date", "yyyy-MM-dd")
                    .date("blah_compliance_date", "yyyy-MM-dd")
                    .timestamp("created_date", "yyyy-MM-dd hh:mm:ss")
                    .object("blah_blah_id")
                        .numberType("blah_blah_number")
                        .numberType("blah_id")

``` 
If I convert it to string the Pact file gets generated but at the Provider end it matches the response literally instead of just matching the key and the data type of the value.

**Comment by sunitav** [comment]
Ok, I figured out that If I escape the \_ with \\ it does generate the matchers but doesn't read very well. I will close this for now.

**Comment by sunitav** [comment]
So in my code, for Pact version 3.0 if i escape the \_ it works upto pact file generation after which it fails at the provider end because it tries to match the key literally

**Comment by QMG-kazala** [comment]
Same here.....

**Comment by sunitav** [comment]
So @QMG-kazala what I did was remove the \\ in the pact file then it works fine.

**Comment by QMG-kazala** [comment]
@sunitavOf course it does :) But it's not a proper solution. This way you have to do it each time you want to regenerate and upload a pact file. Which also means no automatic regeneration and upload.... Not very sustainable...
Thx for the tip anyway :)

**Comment by uglyog** [comment]
Release 3.5.8 with the fix for this issue

**Comment by sunitav** [comment]
Thanks @uglyog will wait for 3.5.8 to be released.

**Comment by uglyog** [comment]
Sorry, my comment was a bit unclear :-D What I meant to say (or type) was that 3.5.8 has been released.

**Comment by QMG-kazala** [comment]
Was it? Mvnrepo seems to know nothing about it....
https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer-groovy_2.11 
https://mvnrepository.com/artifact/au.com.dius/pact-jvm-consumer-junit_2.11

**Comment by uglyog** [comment]
Oops, I had the jars ready for release but had not clicked the release button on oss.sonatype.org. They should be available now.

**Comment by QMG-kazala** [comment]
Emmmm, I still don't see v. 3.5.8..... :)
BTW, @uglyog many many thanks for all your work. Great job!

**Comment by uglyog** [comment]
Have a look at http://search.maven.org/#search%7Cga%7C1%7Cpact-jvm

**Comment by QMG-kazala** [comment]
You're absolutely right, new version is available already 👍  The fix works like a charm :)
Thank you for your quick response!  I'm honesty impressed by your work and handling everything. Thx again!

**Comment by uglyog** [comment]
Thank you for the kind words. Knowing that people appreciate it makes all the effort worth while.
