### ISSUE TITLE
No exampleclients.ConsumerClient

### ISSUE THREAD

**Issue by yuandanxu** [DiUS/pact-jvm#549]
I've added all pact related dependencies, but I didn't find ConsumerClient which is used in the example. May I know which package contains ConsumerClient? Thanks a lot.

		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer_2.11</artifactId>
			<version>3.5.5</version>
		</dependency>

		
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-provider_2.11</artifactId>
			<version>3.5.5</version>
		</dependency>

		
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-model</artifactId>
			<version>3.5.5</version>
		</dependency>

		
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-matchers_2.11</artifactId>
			<version>3.5.5</version>
		</dependency>

		
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-pact-broker</artifactId>
			<version>3.5.5</version>
		</dependency>

		
		<dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer-junit_2.11</artifactId>
			<version>3.5.5</version>
			<scope>test</scope>
		</dependency>

**Comment by yuandanxu** [comment]
Just realized the client is defined in the example, I will implement mine. Close the issue.

**Comment by NameYoung** [comment]
supplement : https://github.com/DiUS/pact-jvm/blob/3_5_14/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/exampleclients/ConsumerClient.java
