### ISSUE TITLE
.stringType() and .date() in PactDslJsonBody() not working

### ISSUE THREAD

**Issue by gtata** [DiUS/pact-jvm#553]
I am using pact-jvm-provider-junit_2.11 version 3.5.4 and the .stringType() and .date() is not working. It's pretty much acting like .stringValue() method. Here is an example:

                .body(
                		new PactDslJsonBody()
                		.minArrayLike("entities", 1)
	            				.object("entityKey")
	            					.stringValue("id", "CART1234")
	            					.stringType("type")
	            					.stringType("owner")
	            				.closeObject()
	            				.minArrayLike("entityStatus", 1)
	            						.stringType("entityVersion")
	            						.stringType("status")
	            						.date("statusDate", "yyyy-MM-dd'T'HH:mm:ss.SSSZ", new Date(System.currentTimeMillis()))
	            					.closeObject()
	            				.closeArray()
            				.closeObject()
                		.closeArray()
                     )

Which generates the following Json:

{
  "entities": [
    {
      "entityStatus": [
        {
          "entityVersion": "string",
          "statusDate": "2017-09-29T09:43:19.325-0400",
          "status": "string"
        }
      ],
      "entityKey": {
        "owner": "string",
        "id": "CART1234",
        "type": "string"
      }
    }
  ]
}

In my unit test, I create entityKey object as follows:

        EntityKeyDto expectedEntityKeyDto = new EntityKeyDto();
        expectedEntityKeyDto.setId("CART1234");
        expectedEntityKeyDto.setType("Shopping Cart");
        expectedEntityKeyDto.setOwner("Shopping Cart");

The following test fails:

 assertEquals(actualEntityKeyDto.getType(), "Shopping Cart");

ERROR message:
org.junit.ComparisonFailure: expected:<[string]> but was:<[Shopping Cart]>

**Comment by gtata** [comment]
Also wanted to mention that I'm using pact-jvm-consumer-junit_2.11 version 3.5.4

**Comment by gtata** [comment]
Nevermind, figured out my issue.

**Comment by Garame** [comment]
What was the solution for the problem you faced.? Please provide snippets and explain.

**Comment by uglyog** [comment]
I assume the issue is that `.stringValue("id", "CART1234")` will match the exact value, where `.stringType("id", "CART1234")` should have been used instead.

**Comment by gtata** [comment]
@Garame The problem was with the JUnit assertions.  [ . stringType("owner") ] was generating a json result set with "string" as the default value. But in my JUnit, I'd created an object with the value of "owner" field set to "gtata". So it was comparing the string value "gtata" to string value "string" generated by default and was failing. So I had to add a default value like .stringType("owner", "gtata") which allowed my JUnit to pass.
