### ISSUE TITLE
How to create the pact file for negative scenario?

### ISSUE THREAD

**Issue by nv195k** [DiUS/pact-jvm#559]
Here am sharing my fragment. I need to know how to handle for http status 503 for the api.

1. It is consumer side code, 
I need example for consumerservice and assertequals

**return builder
	.given("negative scenario")
	.uponReceiving("checking negative scenario")
	.path("/Services/error/query")
	.method("GET")
	.willRespondWith()
	.headers(headers)
	.status(503)
	.body(new PactDslJsonBody()
	.object("PolicyException")
	.stringType("MessageId", "POL0002")
	.stringType("Text", "User ID and/or Password Is Invalid")
	.closeObject())
	.toFragment();**

Please guide me on this.

**Comment by uglyog** [comment]
Not sure I understand the question. Did you try this and it didn't work?

**Comment by nv195k** [comment]
Yes, we facing issue. its not working

**Comment by uglyog** [comment]
Ok, you'll need to provide more information as to what is not working. What behaviour are you witnessing, and what where you expecting to happen?

**Comment by sr5613** [comment]
We are trying to test a scenario where the response status from the microservice is 503. Is it even possible?

**Comment by uglyog** [comment]
Yes it is, you can set the status to return to any valid HTTP status code. But beware that the HTTP client you are using may throw an exception if it receives a non-success status code (400+).

Can you kindly provide some information on what issues you are facing.
