### ISSUE TITLE
Form params are not sent to producers in 3.5.x

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#560]
I'm trying to write a Pact test for a POST endpoint that takes form parameters. When I write the consumer side of the test, it produces a pact file with the parameters encoded in the body field. However, the producer side fails. When I debug into the test with a breakpoint in my endpoint, I can see that all the parameters are null (parameters that come in as collections are empty). This appears to be a regression from 3.4.0. When I switch to that version of pact, I get non-null/non-empty parameters in my resources. Unfortunately, I can't use 3.4.0 because the annotations don't work for me.

I wrote a toy example. Here's the consumer side:
`private static final int PACT_TEST_PORT = 8080;
private static final String PACT_TEST_SERVER = "localhost";
private static ServerConfiguration FAKE_ZOO_CLIENT_SERVER = new ServerConfiguration(PACT_TEST_SERVER, PACT_TEST_PORT, "zoo-ws");

	/*
		Junit rule to tell pact to mock the service and record the interactions
	*/
	@Rule
	public PactProviderRuleMk2 mockProvider = new PactProviderRuleMk2("zoo_ws", PACT_TEST_SERVER, PACT_TEST_PORT, this);

	@Pact(consumer = "zookeeper")
	public RequestResponsePact createPact(PactDslWithProvider builder) throws ParseException
	{
		/*
			Define expected states and interactions including json matcher for response
		 */
		return builder
				.given("grizzly bear can be added to zoo")
					.uponReceiving("a POST request to add a grizzly bear named Bubbles")
						.path("/zoo-ws/animals")
						.method("POST")
						.headers(ImmutableMap.of("Content-Type", "application/x-www-form-urlencoded"))
						.body("type=grizzly+bear&name=Bubbles")
					.willRespondWith()
						.status(200)
						.headers(ImmutableMap.of("Content-Type", "application/json"))
						.body(expectedGrizzlyResponse())
				.toPact();
	}
	
	private DslPart expectedGrizzlyResponse()
	{
		/*
			Define Json Matcher for expected response for grizzly object
		 */
		return new PactDslJsonBody()
				.stringValue("animalType", "grizzly bear")
				.stringType("name", "Bubbles")
				.array("feedingLog")// we expect the feeding logs to be empty when you first add an animal
				.closeArray();
	}

	@Test
	@PactVerification
	public void verifyZooService() throws Exception
	{
		ZooClient fakeZooClient = new ZooClient(FAKE_ZOO_CLIENT_SERVER, new RequestMethodExecutorLive());
		
		Animal grizzly = fakeZooClient.saveAnimal("grizzly bear", "Bubbles");
		
		assertThat(grizzly.getAnimalType(), is("grizzly bear"));
		assertThat(grizzly.getName(), is("Bubbles"));
		assertThat(grizzly.getFeedingLog().size(), is(0));
	}`

Here's the pact file that generates:
`{
    "provider": {
        "name": "zoo_ws"
    },
    "consumer": {
        "name": "zookeeper"
    },
    "interactions": [
        {
            "description": "a POST request to add a grizzly bear named Bubbles",
            "request": {
                "method": "POST",
                "path": "/zoo-ws/animals",
                "headers": {
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "body": "type=grizzly+bear&name=Bubbles"
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": {
                    "feedingLog": [
                        
                    ],
                    "animalType": "grizzly bear",
                    "name": "Bubbles"
                },
                "matchingRules": {
                    "body": {
                        "$.name": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "grizzly bear can be added to zoo"
                }
            ]
        }
    ],
    "metadata": {
        "pact-specification": {
            "version": "3.0.0"
        },
        "pact-jvm": {
            "version": "3.5.5"
        }
    }
}`

And here's the producer side: 
`@RunWith(PactRunner.class)
@PactFolder("pact")
@Provider("zoo_ws")
@Consumer("zookeeper")
public class ZookeeperPactTest 
{
	@TestTarget
	public final Target target = new HttpTarget(8332);
	private Server server;
	private AnimalDao dao = mock(AnimalDao.class);
	
	private class AnimalResourceConfig extends ResourceConfig
	{
		public AnimalResourceConfig(AnimalResource resource)
		{
			this.register(resource);
		}
	}
	
	@Before
	public void setUpService() throws Exception
	{
		AnimalResource animalResource = new AnimalResource(dao);
		
		ServletContextHandler context = new ServletContextHandler();
		context.setContextPath("/zoo-ws");
		
		ServletContainer sc = new ServletContainer(new AnimalResourceConfig(animalResource));
		ServletHolder servletHolder = new ServletHolder(sc);
		context.addServlet(servletHolder, "/*");
		
		server = new Server(8332);
		server.setHandler(context);
		server.setStopAtShutdown(true);
		
		server.start();
	}
	
	@After
	public void tearDownService() throws Exception
	{
		server.stop();
	}
	
	@State("grizzly bear can be added to zoo")
	public void grizzlyIsAdded()
	{
		when(dao.saveAnimal("grizzly bear", "Bubbles")).thenReturn(new Animal("grizzly bear", "Bubbles"));
	}`

And the resource itself:
`@Path("/animals")
@Produces(MediaType.APPLICATION_JSON)
@AllArgsConstructor(onConstructor=@__({@Inject}))
public class AnimalResource 
{
	private final AnimalDao animalDao;
	
	@Path("{type}")
	@GET
	public Response getAnimal(@PathParam("type") String animalType)
	{
		return Response.ok(JsonUtils2.objToJson(animalDao.getAnimal(animalType))).build();
	}
	
	@POST
	public Response saveAnimal(@FormParam("type") String animalType, @FormParam("name") String animalName)
	{
		return Response.ok(JsonUtils2.objToJson(animalDao.saveAnimal(animalType, animalName))).build();
	}
}`

**Comment by uglyog** [comment]
Looks like the switch to using the Apache HTTP client has caused this issue. Should not be hard to fix.

**Comment by LoraVolkert** [comment]
Any ETA on when your fixes will be released? Thanks for working on this.

**Comment by uglyog** [comment]
I'll release it this week.

**Comment by uglyog** [comment]
3.5.9 has been released

**Comment by LoraVolkert** [comment]
Thanks!
