### ISSUE TITLE
Is it possible to publish from JUnit??

### ISSUE THREAD

**Issue by gtata** [DiUS/pact-jvm#561]
Hi,

This is not really a bug but more of an inquiry. Is it possible to publish to a pack broker from JUnit? I've searched around and I've not able to find anything with regards to that if it's available.

Thanks.

Gabsaga

**Comment by uglyog** [comment]
No, there is no JUnit publishing. Mostly, all the generated pacts get published in one go using the build tool plugin at the end of the test run.

**Comment by gtata** [comment]
Thanks uglyog. Well noted.
