### ISSUE TITLE
Tear Down methods for Provider States

### ISSUE THREAD

**Issue by gaurav517** [DiUS/pact-jvm#568]
Is it possible to have tear down methods for provider states. So I want to prepare some data for a state and after test run I run to cleanup the data, depending on the state.

Thanks..

**Comment by uglyog** [comment]
Yes you can. There is a flag to execute a tear-down for any state. If you're using Gradle, have a look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/README.md#teardown-calls-for-state-changes-version-325247-1.

**Comment by gaurav517** [comment]
Is it possible to do only with Junit? I am not using maven/gradle plugin on provider side.. I am using maven plugin on consumer side only to publish pacts..

**Comment by uglyog** [comment]
All the current supported ways of running verifications support this; JUnit, Gradle and Maven.
