### ISSUE TITLE
Provider state not showing up in pact broker

### ISSUE THREAD

**Issue by kinezu** [DiUS/pact-jvm#571]
I have a docker pact broker using https://github.com/DiUS/pact_broker-docker

When using the gradle plugin (https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle)  to push my pact file, the pact broker never gets/shows the provider state. Because of this, my provider never gets a state to work with.

I have a pact file that looks like

```
{
    "provider": {
        "name": "prov"
    },
    "consumer": {
        "name": "cons"
    },
    "interactions": [
        {
            "description": "a get request for users",
            "request": {
                "method": "GET",
                "path": "/api/users"
            },
            "response": {
                "status": 200,
                "body": {
                    "a" : "b"
                 }
            },
            "providerStates": [
                {
                    "name": "one user"
                }
            ]
        }
    ],
    "metadata": {
        "pact-specification": {
            "version": "3.0.0"
        },
        "pact-jvm": {
            "version": "3.5.8"
        }
    }
}
```

It works if I have it formatted like,

```"interactions": [
        {
            "description": "a get request for users",
            "provider_state" : "my state",
```

I am creating the pact in Java using

```
public RequestResponsePact createFragment(PactDslWithProvider builder) throws IOException {
    return builder
        .given("one user")
        .uponReceiving("a get request for users")
          .path("/api/users")
...
```

**Comment by kinezu** [comment]
My broker was expecting V2 formatting

@Rule
  public PactProviderRuleMk2 mockProvider = new PactProviderRuleMk2("prov", PactSpecVersion.V2,this);

**Comment by kzaporowski** [comment]
@sanketi you just need to specify PactSpecVersion.V2 when creating PactProviderRuleMk2 in your test suite. By default it uses V3, which adds "providerStates" array instead "providerState" field in pact json. It seems that pact broker is compatible with the latter only (but I didn't make a deep dive, that's only my assumption).
