### ISSUE TITLE
Pact DSL for java List of Map

### ISSUE THREAD

**Issue by alagesann** [DiUS/pact-jvm#573]
i have to create a pact dsl part to match the json to be serialized into the following java object:

List<Map<String, List<String>>> attributes = new ArrayList<>();

Currently i have following pact dsl part which is not working:

             .eachLike("attributes")
                .eachKeyMappedToAnArrayLike("sale")
                  .stringType("new sale")
                  .closeObject()
                .closeArray()
            .closeObject()
            .closeArray();

what's the issue in the above pact dsl? i am following this github page to implement that:

**Comment by uglyog** [comment]
`.eachLike("attributes")` will create a Map with a key called `attributes` and the value is a List, which is not what you want.

Use `PactDslJsonArray.arrayEachLike()` which creates the outer list.
