### ISSUE TITLE
Add eachArrayLike to Groovy DSL

### ISSUE THREAD

**Issue by QMG-kazala** [DiUS/pact-jvm#574]
As mentioned here:
https://stackoverflow.com/questions/42164666/pact-matcher-how-to-use-each-like-for-an-array-of-arrays-values
"eachLike in the Groovy DSL only supports arrays of objects. If you use the Java DSL, there is a eachArrayLike method that can help you."

Could we have eachArrayLike in Groovy DSL pls? 

BTW, why are java and groovy versions inconsistent? Are there more inconsistencies? It Groovy implementation always behind Java one? Is it "safer" to use Java DSL?

**Comment by uglyog** [comment]
The Java and Groovy DSLs are different implementations, Groovy provides much richer support for DSLs. Most of the methods in the Java one (like `closeObject()` and `closeArray()`) exist because of this, there is no equivalent in the Groovy DSL.

But this does mean that features asked for in one implementation might not get added to the other.

**Comment by uglyog** [comment]
Could you provide an example of your requirement, the one from the SO question is a bit confusing.

**Comment by QMG-kazala** [comment]
Example: 
A form with answers where an answer:
- can be a simple answer (questionId-answer object)
- can have more complicated structure. In particular **"answer" can be an array of arrays, each consisting of multiple simple answers**. In simpler scenario all inner arrays have a fixed "list" of answers (fixed set of question ids). In more complicated scenario inner-arrays can consist of variable number of answers (different set of question ids for each inner array).

Example form json (made up obviously :) so pls forgive me if it doesn't make much sense):
```
answers: [
{questionId:"name", answer: "James"},
{questionId:"surname", answer:"Bond"},
{questionId:"books", answer: [
  [
       {questionId:"title", answer: "AAAAA"},
       {questionId:"author", answer: "A.A."},
       {questionId:"co_author", answer: "A.A.2"},
       {questionId:"isbn", answer: "978-3-16-148410-0"}
   ],
  [
       {questionId:"title", answer: "BBBB"},
       {questionId:"author", answer: "B.B."}
   ]
]}
//more answers here
]
```

Currently it's impossible to define requirements for "answer" field for "books" question. The only viable way is to provide a hardcoded example of the inner array, if I'm not mistaken. That gives us a Closure that looks like this:
```
{
answers minLike(1) {
  questionId string("books")
  answer eachLike( [
       {
        questionId "title"
        answer "BBBB"
       },
       {
       questionId "author"
        answer "B.B."
       },
  ] }
}
```
and is far from perfect :( Among other problems it's impossible to use matchers for sub-answers. It also forces our provider do deliver the exact response we've hardcoded. 

Having eachArrayLike() in Groovy DSL and being able to define requirements for unordered lists with multiple elements (https://github.com/DiUS/pact-jvm/issues/506 , https://github.com/pact-foundation/pact-specification/issues/38) would be AWESOME. Having both would allow us to define all our requirements in 1 pact test 🏆 🏆 🏆  Looking forward to this :D 

Hope above example makes sense for you and I didn't make any mistakes building example json and example Closure :) Thx!

**Comment by uglyog** [comment]
I've implemented support of using `eachLike` with arrays at the root level. Next I'll see if I can get your example working.

**Comment by QMG-kazala** [comment]
Great news! Thank you :)

**Comment by uglyog** [comment]
With this change you will be able to do something like

```groovy
{
answers minLike(1) {
  questionId string("books")
  answer eachArrayLike {
        questionId string("title")
        answer string("BBBB")
  }
}
```

**Comment by uglyog** [comment]
Version 3.5.9 has been released

**Comment by QMG-kazala** [comment]
Thx, works great! :)
