### ISSUE TITLE
MockMvc needs the servletPath set, but there is no way with MockMvcTarget to set this

### ISSUE THREAD

**Issue by olejkavn** [DiUS/pact-jvm#580]
I have feign client with name like: /SomeService/somePath
and controller with @RequestMapping("/somePath")
also on service side i have application.properties file with property: server.contextPath=/SomeService

Need to add posibility to set servletPath to MockMvc via MockMvcTarget

**Comment by uglyog** [comment]
With this change, you can do `target.setServletPath("/SomeService");` in the test setup.

**Comment by uglyog** [comment]
Version 3.5.9 has been released
