### ISSUE TITLE
OR functionality is not working

### ISSUE THREAD

**Issue by ravichandrasurabhi** [DiUS/pact-jvm#583]
I'm using 3.3.4/2.11. Is this version supports my requirement or Please suggest me the exact version. 

.or("valueC", null, PM.date(), PM.nullValue())

It's showing error at PM.

**Comment by uglyog** [comment]
You need to use version 3.5.x, the latest being 3.5.9 at the moment.

**Comment by ravichandrasurabhi** [comment]
Thanks we will try
