### ISSUE TITLE
AND/OR condition in pact file

### ISSUE THREAD

**Issue by soumilkrishna** [DiUS/pact-jvm#585]
I need to implement AND/OR condition in pact file. From DiUS wiki I got below code. When I pasted this code to eclipse,  class "PM" is not able to import. Also I am not able to call "and", "or" in the statement.
I am using pact-jvm-consumer-junit_2.11-3.3.9.jar.
Does below code is from groovy? 
How can I get AND/OR implementation in Java ?

DslPart body = new PactDslJsonBody()
          .numberValue('valueA', 100)
          .and('valueB', 'AB', PM.includesStr('A'), PM.includesStr('B'))
.or('valueC', null, PM.date(), PM.nullValue())

**Comment by uglyog** [comment]
Use version 3.5.9, then you can write equivalent code in Java.
