### ISSUE TITLE
Clarification on PACT - CONTRACT TESTING

### ISSUE THREAD

**Issue by ravichandrasurabhi** [DiUS/pact-jvm#587]
Here are we validating the response or the request also ?. For PUT and POST operation mainly.
If request also can you please provide me the example.

**Comment by uglyog** [comment]
I am unable to work out what exactly you are asking.

**Comment by ravichandrasurabhi** [comment]
I mean exactly in Contract Testing, as per my understanding we need to validate the response. But here my question is for POST or PUT operation we need to send request in a body. So, can we validate request ?

**Comment by uglyog** [comment]
You can validate both the request and responses for PUT and POST requests (in fact for any HTTP verb). The requests are validated in the consumer test, and the responses are validated when verifying the provider.
