### ISSUE TITLE
PACT to verify Status code 206 or 400

### ISSUE THREAD

**Issue by ravichandrasurabhi** [DiUS/pact-jvm#589]
I'm trying to verify the PACT with status code 400 but i'm unable to generate a PACT because of its failing due to mocked server

**Comment by uglyog** [comment]
I doubt this is failing due to mocked server. More likely, it is failing due to the HTTP client you are using will throw an exception when it receives a 400+ response.

**Comment by ravichandrasurabhi** [comment]
Yes, exactly how to over come it

**Comment by uglyog** [comment]
You need to handle the exception in your test code.

**Comment by ravichandrasurabhi** [comment]
Any example which helps me, I tried it but unable to achieve it.

**Comment by uglyog** [comment]
Here you go: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/PactConsumer400Test.java
