### ISSUE TITLE
Expected List(Map) but received Map(Map) on JsonArray body

### ISSUE THREAD

**Issue by fw0037** [DiUS/pact-jvm#594]
**Here is a sample output of the REST api:**
[
  {
    "lableid": 0,
    "lableName": "服务配置",
    "quantity": 225
  },
  {
    "lableid": 1,
    "lableName": "设备配置",
    "quantity": 220
  },
  {
    "lableid": 2,
    "lableName": "计算",
    "quantity": 223
  },
  {
    "lableid": 3,
    "lableName": "站点分配",
    "quantity": 222
  },
  {
    "lableid": 4,
    "lableName": "目录结构(MO)",
    "quantity": 229
  },
  {
    "lableid": 5,
    "lableName": "资源服务",
    "quantity": 226
  },
  {
    "lableid": 6,
    "lableName": "基础数据服务",
    "quantity": 227
  },
  {
    "lableid": 7,
    "lableName": "其他",
    "quantity": 210
  }
]

**This is my pact test DSL:**
DslPart responseBody = new PactDslJsonArray().eachLike(8).stringMatcher("lableid","[0-9]")
        		.stringMatcher("lableName", "\\w+")
        		.stringMatcher("quantity", "[0-9]+")
        		.closeObject()
                .close();

**Comment by fw0037** [comment]
**This is what has been generated:**
0) Verifying a pact between GetLableList_Consumer_v1 and ApiManager_Provider - generateAccessToken returns a response which has a matching body
      $.body.0 -> Type mismatch: Expected List List(Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635), Map(lableName -> _, lableid -> 7, quantity -> 1635)) but received Map Map(lableName -> 服务配置, lableid -> 0, quantity -> 55)
      $.body -> Expected a List with 1 elements but received 8 elements

      Diff:

      @1
      -    [
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        },
      -        {
      -            "lableName": "_",
      -            "lableid": "7",
      -            "quantity": "1635"
      -        }
      -    ]
      +    {
      +        "lableName": "\u670d\u52a1\u914d\u7f6e",
      +        "lableid": 0,
      +        "quantity": 225
      +    },
      +    {
      +        "lableName": "\u8bbe\u5907\u914d\u7f6e",
      +        "lableid": 1,
      +        "quantity": 230
      +    },
      +    {
      +        "lableName": "\u8ba1\u7b97",
      +        "lableid": 2,
      +        "quantity": 223
      +    },
      +    {
      +        "lableName": "\u7ad9\u70b9\u5206\u914d",
      +        "lableid": 3,
      +        "quantity": 222
      +    },
      +    {
      +        "lableName": "\u76ee\u5f55\u7ed3\u6784(MO)",
      +        "lableid": 4,
      +        "quantity": 229
      +    },
      +    {
      +        "lableName": "\u8d44\u6e90\u670d\u52a1",
      +        "lableid": 5,
      +        "quantity": 226
      +    },
      +    {
      +        "lableName": "\u57fa\u7840\u6570\u636e\u670d\u52a1",
      +        "lableid": 6,
      +        "quantity": 227
      +    },
      +    {
      +        "lableName": "\u5176\u4ed6",
      +        "lableid": 7,
      +        "quantity": 210
      +    }
      ]

**Comment by fw0037** [comment]
Am I doing something wrong?
Thanks!

**Comment by uglyog** [comment]
This ` new PactDslJsonArray().eachLike(8)` is creating an array of arrays. Use the static methods.

See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#root-level-arrays-that-match-all-items-version-2211 for more info

**Comment by fw0037** [comment]
Thanks.
I changed the my Pact test DSL to : 
 DslPart responseBody = new PactDslJsonArray().arrayEachLike().stringMatcher("lableid","[0-9]")
        		.stringMatcher("lableName", "[A-Za-z0-9()\\u4E00-\\u9FFFh]+")
        		.stringMatcher("quantity", "[0-9]+")
        		.closeObject()
                .close();
       
        return builder.uponReceiving("generateAccessToken")
                .matchPath(BASE_PATH + URL_PATH)
                .method("GET")
                .willRespondWith()
                .headers(headers)
                .status(200)
                .body(responseBody)
                .toPact();
Then it was success.
