### ISSUE TITLE
Gradle plugin has trouble with spaces in the name of consumer/provider pairs

### ISSUE THREAD

**Issue by TimothyJones** [DiUS/pact-jvm#599]
A change introduced in version `3.5.7` prevents uploading pacts where the consumer/provider names contain spaces:

```
:pactPublish
Publishing API Test Consumer-Coffee Ordering Provider.json ... FAILED! 400 Bad Request - 
  consumer.name: does not match API Test Consumer name in path 
  ('API%20Test%20Consumer')., provider.name: does not match Coffee Ordering 
  Provider name in path ('Coffee%20Ordering%20Provider').
:pactPublish FAILED
```

This issue is still present in the current release of `3.5.10`.

## To reproduce

Clone [this repository](https://github.com/DiUS/dius-mentor_boris_coffee-api):

```
git clone git@github.com:DiUS/dius-mentor_boris_coffee-api.git
```

Then set up and build the project:
```
export pactBrokerAccount=<some account>
export pactBrokerUsername=<some user>
export pactBrokerPassword=<some password>

cd dius-mentor_boris_coffee-api/test-consumer
./gradlew build
```

At this point, publishing should work:
```
./gradlew pactPublish
```
Then, change line 11 of `build.gradle` to read:
```
  id 'au.com.dius.pact' version '3.5.10'
```
Re-running the publish step:
```
./gradlew pactPublish
```
results in failure with the error message at the top of this report.

`3.5.6` seems to be the last non-failing version, which means the problem was introduced by some change in `3.5.7`

## Workaround

Downgrade to `3.5.6`

**Comment by TimothyJones** [comment]
Copying the comment from above, since it didn't appear here:

> This is the commit that causes #599 - `halClient.uploadJson(uploadPath, pactText)` already does escaping, and so some characters may be double escaped - possibly anything that isn't a slash(?).
>
> A fix would need to still escape slashes in provider/client names, but not double escape other characters. Changing `uploadJson` to not do escaping would fix this issue, but I'm not sure if it would cause others.

Happy to look into a PR.

**Comment by uglyog** [comment]
The fix should be as easy as `halClient.uploadJson(uploadPath, pactText, false)`

**Comment by TimothyJones** [comment]
I agree. It looks like perhaps `version` should be encoded as well?

Would you like me to make a PR?

**Comment by uglyog** [comment]
Yes, please!
