### ISSUE TITLE
Gradle plugin: Prevent broker publication?

### ISSUE THREAD

**Issue by TimothyJones** [DiUS/pact-jvm#602]
Is there a way to prevent pact verification status from being published to a broker? It's useful to have pact verification of pull requests in CI, but it's not always appropriate for the results to be published back to the broker.

**Comment by uglyog** [comment]
You sure can. Set the system property `pact.verifier.publishResults` to `false`

**Comment by TimothyJones** [comment]
Aha, thanks! Was that added in 3.5.7?

**Comment by uglyog** [comment]
Yes it was.

**Comment by uglyog** [comment]
From 3.5.18, publishing is disabled unless `pact.verifier.publishResults` is set to `true`
