### ISSUE TITLE
java8 dsl does not properly manage min/maxArrayLike

### ISSUE THREAD

**Issue by ohubaut** [DiUS/pact-jvm#605]
The Java8 dsl simply delegate method such as `minArrayLike` to the underlying object, which will internally create a new array. 
But, as there is no `closeArray` method on LambdaDslObject, the array remain unclosed.
Moreover, as the newly created array is not exposed, it is not possible to provide any specification for the given array.
The solution would be to use a similar mechanism as for `array` and `object` method and force a last argument to be the Consumer of that array. Some convenience method without the Consumer could also be provided, which would properly close the internal array immediately.

**Comment by eatdrinksleepcode** [comment]
I have just run into this as well. Do I understand correctly that this means that there is no way using the Java8 DSL to specify an array with an unknown number of items? Is the only choice to fall back to the standard java DSL?

**Comment by ohubaut** [comment]
I have written a pull request that should fix the issue. Feel free to review it (works on my machine 😁) #611
