### ISSUE TITLE
How to include an array of Strings in PactDslJsonBody()

### ISSUE THREAD

**Issue by preethips89** [DiUS/pact-jvm#606]
The JSON Schema is as below:
{
"breakpack": {
      "type": "string",
      "enum": [
        "YES",
        "NO",
        "ONLY"
      ]
    }, 
"containerType": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "enum": [
          "PALLET",
          "RACK",
          "CARTON",
          "ANY"
        ]
      }
    },
    "conveyability": {
      "type": "string",
      "enum": [
        "CONVEYABLE",
        "NONCONVEYABLE",
        "BOTH"
      ]
    }
}

I have the Sample json example as below where containerType accepts an array of Strings.
{
  "breakpack": "YES",
  "containerType": ["PALLET", "CARTON"],
  "conveyability": "CONVEYABLE"
}
 
Please let me know how to include the containerType as part of the PactDslJsonBody() to get the pact generated for an array of Strings with root element as containerType.

expectedResult = (PactDslJsonBody) new PactDslJsonBody()
				.stringMatcher("breakpack", "YES|NO|ONLY","YES")				.stringMatcher("conveyability","CONVEYABLE|NONCONVEYABLE|BOTH","CONVEYABLE");

**Comment by uglyog** [comment]
Use `minArrayLike("containerType", 1, PactDslJsonRootValue.stringMatcher("PALLET|RACK|CARTON|ANY", "PALLET"))`

**Comment by preethips89** [comment]
Hi, Thank you for the response. I tried the same as you mentioned.
minArrayLike method has the following implementations only in DslPart which i have imported.
public abstract PactDslJsonBody minArrayLike(Integer size);
public abstract PactDslJsonBody minArrayLike(String name, Integer size, int numberExamples);
public abstract PactDslJsonBody minArrayLike(Integer size, int numberExamples);
Since these are not in sync with the minArrayLike("containerType", 1, PactDslJsonRootValue.stringMatcher("PALLET|RACK|CARTON|ANY", "PALLET")), It is giving me error.
Please let me know if I need to use a specific version to get this method implementation.

I am using the following in pom.xml

                 <dependency>
			<groupId>au.com.dius</groupId>
			<artifactId>pact-jvm-consumer-junit_2.11</artifactId>
			<version>3.3.9</version>
			<scope>test</scope>
		</dependency>

**Comment by uglyog** [comment]
Upgrade to 3.5.10 or later

**Comment by amentagit** [comment]
How do we solve the same problem with LambdaDsl object ?

**Comment by uglyog** [comment]
LambdaDsl issue is tracked in #701

**Comment by sidharthasubudhi** [comment]
How can I build JSON PACT for below JSON body:
[
    {
        "id": 1,
        "firstName": "George",
        "lastName": "Franklin",
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "telephone": "6085551023",
        "pets": [
            {
                "id": 1,
                "name": "Leo",
                "birthDate": "2010/09/07",
                "type": {
                    "id": 1,
                    "name": "cat"
                },
                "owner": 1,
                "visits": []
            }
        ]
    }
]
It is starting with array []. There can be many objects{} inside the array.
I tried this:
 .body(new PactDslJsonBody()
                        .minArrayLike("",1) //no name for the array.
                        .integerType("id",1)
                        .stringValue("firstName", "George")
                        .stringValue("lastName", "Franklin")
                        .stringValue("address", "aaa")
                        .stringValue("city", "vvv")
                        .stringValue("telephone", "121323")
                        .minArrayLike("pets",1)
//                        .object()
                            .integerType("id",1)
                            .stringType("name","Leo")
                            .stringType("birthDate","2010/09/07")
                            .integerType("owner",1)
                            .object("type")
                                .integerType("id",1)
                                .stringType("name","Cat")
                            .closeObject()
                        .object()
                        .integerType("owner",1)
                        .array("visits")
                        .closeArray()
                .closeArray())
                .toPact();

**Comment by anto-ac** [comment]
@sidharthasubudhi It is explained here: https://github.com/DiUS/pact-jvm/tree/master/consumer/junit#root-level-arrays-that-match-all-items

**Comment by sidharthasubudhi** [comment]
@anto-ac thanks for the help. Issue got resolved.
I need more info. 
1. Can we send an attachment along with certain JSON body in a request if yes how to do that?
2. Can we expect an attachment from a response, if yes, how to do that?

**Comment by anto-ac** [comment]
@sidharthasubudhi I'd recommend asking those questions on Slack.
