### ISSUE TITLE
Discrepancies in generated pact across pact-jvm-consumer-junit_2.11 versions

### ISSUE THREAD

**Issue by BenDave** [DiUS/pact-jvm#636]
Hi,

We are upgrading our consumer dependencies from `pact-jvm-consumer-junit_2.11`  version `3.3.4` to  version `3.5.11`.

At the moment, we need the upgrade to be seamless, i.e. we need the generated pacts with version `3.5.11` to be identical to the pacts generated by version `3.3.4`. 

We can achieve this by ensuring that the pacts produced by version `3.5.11` are generated using pact `DSL 2.0.0` instead of `DSL 3.x.x.` We do this by specifying `PactSpecVersion.V2` when instantiating our `PactProviderRuleMk2`.

This works wonder ... except that the pacts generated by `pact-jvm-consumer-junit_2.11`  version `3.5.11` have an additional validation element as follows:

 `pact-jvm-consumer-junit_2.11`  version `3.3.4` with pact DSL 2.0.0. generates:
```
                "matchingRules": {
                    "$.path": {
                        "regex": "/entity"
                    }
                }

```
 `pact-jvm-consumer-junit_2.11`  version `3.5.11` with pact DSL 2.0.0. generates:
```
                "matchingRules": {
                    "$.path": {
                        "match": "regex",
                        "regex": "/entity"
                    }
                }

```
This is a problem for us, is there a way to ensure that the generated pacts are identical ?

**Comment by uglyog** [comment]
The values from before `3.5.x` where incorrect, missing the `"match": "regex"` which was clarified in the spec. This was corrected in the later versions to make it consistent with other language implementations.

Going forward, the latter example is how all the pacts should be stored.

**Comment by BenDave** [comment]
OK, I guess the best way for us to achieve the consistency required is to fork your repo and revert to the former schema, until our code base is ready to migrate to the latest version. Thanks for your help ...
