### ISSUE TITLE
Be able to generate pacts when consumer client code fails

### ISSUE THREAD

**Issue by wandrewni** [DiUS/pact-jvm#640]
My team would like to use our pact tests to verify that our client code is correct, but we would also like to be able to generate and publish the pacts before we have finished implementing the client code.  During the period where our client code does not work, we currently aren't able to publish the pacts because our client code sends the incorrect body to the mockServer.

We are currently able to accomplish this in our Ruby code as described in the documentation here: https://docs.pact.io/documentation/usage_ruby.html -- at Step 5, we have a spec that runs our client code & generates the pact file -- even though the spec fails because we have not finished implementing the client code.

Is it possible to have this feature introduced into the pact-jvm-consumer-junit module?

**Comment by uglyog** [comment]
I've had a chat to the maintainer of the Ruby version, and it seems that that behavior is a defect. If the spec fails, the pact should not be written. This may be changed in a future version of Pact-Ruby.

I could add a property that can be set to enable this behavior.

**Comment by bethesque** [comment]
I don't understand how the pacts can be written. I've just created a build that shows that they aren't https://travis-ci.org/pact-foundation/pact-ruby-e2e-example/builds/343266614

**Comment by bethesque** [comment]
I believe the passing interactions are written, but not the failing ones. Could this be what you are talking about?

**Comment by bethesque** [comment]
You can see the passing interactions written to the pact file here, but the failing ones are not https://travis-ci.org/pact-foundation/pact-ruby-e2e-example/builds/343267328

I think this may be a case of misused terminology. A "pact" is a file made up of many "interactions" (request/response pairs). You want the passing _interactions_ to be written to the pact file.

**Comment by bethesque** [comment]
I would suggest that you just disable your failing tests and then the pact should be written.

**Comment by wandrewni** [comment]
Hmm.  Maybe I'm not understanding the intended use of these tests.  We are trying to have the tests both verify our client code is doing the correct thing as well as generate the pacts to facilitate independent development for the provider & consumer.

We generally try to work out the pacts as early as possible in our development workflow, which is typically before either the provider or consumer has begun to implement their code.  We had imagined we could set up the pact tests to generate the documentation & have them linked to stubs of the client code, so that they would also serve as acceptance tests of sorts for that code...

It seems like in order to accomplish these two things, we'll need to run the tests for each interaction twice -- once with the in-progress client code (expected to fail until we implement correctly), and then once with posting the expected request for that interaction so that the pacts will be generated.  Then as we implement consumer code for interactions, we can remove the extra test as the consumer code itself will generate the pact.

It seems like our workflow/use case doesn't quite fit the paradigm?

**Comment by bethesque** [comment]
>We are trying to have the tests both verify our client code is doing the correct thing as well as generate the pacts to facilitate independent development for the provider & consumer.

This is exactly what pact is designed for, no misunderstanding there. 

When you say "client code" what do you mean exactly? Generally, we'd recommend creating a client _class_ for the service (eg. `AnimalServiceClient`) and using pact to unit test _just_ that client class. That means there is barely any code that needs to be written in the client to get the pact created. Is this what you are already doing? Or are you trying to test the full consumer stack in your pact tests?

**Comment by wandrewni** [comment]
Ah, that makes sense.  We were imagining writing more than just the client class for the service, and I do see that if you just make that class, it's a fairly trivial amount of code to get the pact created.  Thanks for the explanation!

**Comment by wandrewni** [comment]
What you've written above helps makes clearer how the pact tests should fit in your application.  I think the part that confused us was Step 5:

> Running the AnimalServiceClient spec will generate a pact file in the configured pact dir (spec/pacts by default). Logs will be output to the configured log dir (log by default) that can be useful when diagnosing problems.
>
>Of course, the above specs will fail because the Animal Service client method is not implemented, so next, implement your provider client methods.

We assumed from the first sentence that the pacts would be written regardless of whether the spec fails/passes -- maybe something could be tweaked there to make that clearer?

**Comment by bethesque** [comment]
Ah! You are right, that statement is a LIE. I shall correct it.

**Comment by bethesque** [comment]
I have removed the lie! https://github.com/pact-foundation/pact.io/commit/d86d21cbd2844a36a7534492a490f1aee4ec4d7d

Please have a read when you have a moment and let me know if that is clearer.

**Comment by wandrewni** [comment]
Much clearer!

**Comment by wandrewni** [comment]
no longer a desirable feature from our end
