### ISSUE TITLE
pact file is created wrongly "['[200]']": when passed  .array("200") , expecting "200": format

### ISSUE THREAD

**Issue by skmeesala** [DiUS/pact-jvm#641]
Hi Team,
i am very new to the concept , please help on issue .. here I am trying to create pact file for  response body

    "responseTime": "281",
    "timestamp": "Fri jan 16 21:13:32 IST 2017",
    "products": [
        {
            "productid": "10",
            "productdata": [],
            "productlist": {
                "200": [
                    {
                        "attribute": "cos1",
                        "isAvailable": "Y"
                    },
                    {
                        "attribute": "cos2",
                        "isAvailable": "N"
                    },
                    {
                        "attribute": "cos3",
                        "isAvailable": "Y"
                    },
                    {
                        "attribute": "cos5",
                        "isAvailable": "N"
                    }
                ]
            }
        }
    ]

body i am using to create pactFile for the above response as  below, 
Issue on my pact file .array("200")   is generated as "['[200]']":   it must be "200":

	.stringType("responseTime")
	.stringType("timestamp")
	.array("products")
			.object()	
				.stringType(productid)
				    .array("productdata")
	                            .closeArray()
			      .object("productlist")
				   .array("200")
						.object()
						    .stringType("name")
						    .stringType("isAvailable")								
						.closeObject()	
						.object()
						    .stringType(name)
						    .stringType(isAvailable)								
						.closeObject()
						.object()
						    .stringType(name)
						   .stringType(isAvailable)								
						.closeObject()
						.object()
					            .stringType("name")
						    .stringType("isAvailable")								
						.closeObject()
				.closeArray()
                          .closeObject()

on Console:

$.body.products.0.productlist -> Expected ['200']=List(Map(attribute -> uchiqBbbnPQWqxfBzOrQ, isAvailable -> nIzMirtjdAvViaUrDVco)) but was missing

        Diff:

        {
        -    "['200']": [
        +    "200": [
                {
        -            "attribute": "uchiqBbbnPQWqxfBzOrQ",
        -            "isAvailable": "nIzMirtjdAvViaUrDVco"
        +            "attribute": "Site Management Option",
        +            "isAvailable": "Y"
        +        },
        +        {
	-            "attribute": "uchiqBbbnPQWqxfBzOrQ",
        -            "isAvailable": "nIzMirtjdAvViaUrDVco"
        +            "attribute": "Dial Backup Type",
        +            "isAvailable": "N"
        +        },
        +        {
	-            "attribute": "uchiqBbbnPQWqxfBzOrQ",
        -            "isAvailable": "nIzMirtjdAvViaUrDVco"
        +            "attribute": "Hub Catcher",
        +            "isAvailable": "Y"
        +        },
        +        {
        -            "attribute": "uchiqBbbnPQWqxfBzOrQ",
        -            "isAvailable": "nIzMirtjdAvViaUrDVco"
        +            "attribute": "ISDN Bandwidth",
        +            "isAvailable": "N"
                }

**Comment by uglyog** [comment]
Can you check what version of Pact-JVM you are using? I don't get this issue with 3.5.12.

**Comment by skmeesala** [comment]
Thank you for responding...

i am using - 3.3.9

**Comment by skmeesala** [comment]
It worked with 3.5.12.. Thank you
