### ISSUE TITLE
withFileUpload regex does not allow charset to be specified

### ISSUE THREAD

**Issue by holly-cummins** [DiUS/pact-jvm#645]
We're using the new `withFileUpload` method in the JUnit DSL, and it's almost working really well. The only issue is that our client (Feign) is setting a charset as part of the content-type header, between the mime type and the boundary. Would it be possible to adjust the MULTIPART_HEADER_REGEX to include an optional charset?

**Comment by uglyog** [comment]
Done

**Comment by holly-cummins** [comment]
That was impressively fast - thanks!
