### ISSUE TITLE
Pact consumer tests' execution hangs after reaching 200 connection limit of mockServer

### ISSUE THREAD

**Issue by a-ster** [DiUS/pact-jvm#658]
When running the pact consumer tests, the execution hangs after completing 200 tests (we got 222 tests to run). It seemed a bit odd that it'll stop after 200 tests but found this in the console:

![image](https://user-images.githubusercontent.com/28387803/38064280-b09fd7ca-3359-11e8-96d7-3e047928149c.png)

I was able to trace this to the mockServer. It doesn't seem to close the connection after each test. Is there a way to close the connection after each test? Thanks!

**Comment by uglyog** [comment]
Are you running the 222 tests in the same test class, or as part of a suite of tests?

**Comment by a-ster** [comment]
It's a suite of tests. We have around 32 test classes and test execution hangs at the 30th class (where the 201st test is located).

![image](https://user-images.githubusercontent.com/28387803/38224901-46313eb0-3746-11e8-90ac-cb7efdbc0c9f.png)

**Comment by uglyog** [comment]
Thanks, I'll look into this. It might be related to #342, in that the `PoolingHttpClientConnectionManager` is creating a new connection for every test, while each test class gets it's own mock server.

**Comment by a-ster** [comment]
Thanks, I’ll try this out. I’m not using the
PoolingHttpClientConnectionManager in the tests, and I have observed the
connection starting when I step into runConsumerTest(pact, config,
mockServer -> {}  even before it reaches the code inside {}. I thought I
saw the PoolingHttpClientConnectionManager Being used in the mockServer
which is why I mentioned I was able to trace the issue to the mockServer.

Thanks again!

**Comment by uglyog** [comment]
Hmm, now that you mention it, there is a bootup check run from that function. I'll check to see if that is using the PoolingHttpClientConnectionManager.

**Comment by uglyog** [comment]
I think this is the culprit: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer/src/main/kotlin/au/com/dius/pact/consumer/MockHttpServer.kt#L200

I'll fix that function to use a better connection manager.

**Comment by uglyog** [comment]
Fix has been released with version 3.5.18
