### ISSUE TITLE
Getting a "No such property: providerVersion" when executing mvn pact:verify on JDK6 project

### ISSUE THREAD

**Issue by jaspreetParhar** [DiUS/pact-jvm#662]
Hello iam trying to use the pact-jvm-provider-maven_2.10 plugin version: 2.4.19 for a jdk 6 project.
When iam trying to run mvn pact:verify iam getting following error:

**Failed to execute goal au.com.dius:pact-jvm-provider-maven_2.10:2.4.19:verify (default-cli) on project mbconnect.sbb.cpd.ws: Execution default-cli of goal au.com.dius:pact-jvm-provider-maven_2.10:2.4.19:verify failed: No such property: providerVersion for class: au.com.dius.pact.provider.ProviderVerifier** 

I tried to find a similar failure on inet but there was nothing. Please can you help me.

Thanks in advance.

**Comment by uglyog** [comment]
Ok, looks like a commit was missed when back-porting the fixes from the 3.5.x version.

I'll cherry-pick the associated commits for you, and release a new version.

**Comment by jaspreetParhar** [comment]
Thank you very much for the fix.

**Comment by uglyog** [comment]
First have to get the build passing, and then do a release. ;-)

I am unable to test on JDK 6, so you will need to verify it.

**Comment by jaspreetParhar** [comment]
Iam on it ;) will let you know in a while.

**Comment by jaspreetParhar** [comment]
Hello soo I tried to build the plugin but getting following error!!!

![image](https://user-images.githubusercontent.com/15687935/38538025-3b002d7a-3c92-11e8-86f6-f10567b15288.png)

**Comment by uglyog** [comment]
Can you have a look at the test report to see why that test is failing?

**Comment by jaspreetParhar** [comment]
Hello following test PactBodyBuilderSpec is failing. 
This is the caused by message which I am seeing. 
au.com.dius.pact.consumer.groovy.PactBodyBuilderSpec.Guard Against Field Names That Don't Conform To Gatling Fields(PactBodyBuilderSpec.groovy:414)

**Comment by jaspreetParhar** [comment]
I have noticed an other problem as well au.com.dius.pact.model.PactFragment does not exists and this cause errors too.

**Comment by uglyog** [comment]
I'm not getting any errors about missing PactFragment. I have got the build passing, so I can do a release.

**Comment by jaspreetParhar** [comment]
Hello soo I am able to get the build passing if I am changing the version from 2.4.20 --> 2.4.19 in the build.gradle file direct under the root pact-jvm project. 
Otherwise Iam getting following error:

![image](https://user-images.githubusercontent.com/15687935/38677827-abf4fa28-3e5f-11e8-9c8e-0c9b6c37a6e4.png)

**Comment by uglyog** [comment]
I have released 2.4.20 with this fix.

**Comment by jaspreetParhar** [comment]
Thank you !!!
