### ISSUE TITLE
Pact Broker Client fails to publish verification back to Pact Broker when HTTPS

### ISSUE THREAD

**Issue by oswaldquek** [DiUS/pact-jvm#667]
It seems the PactBrokerClient (https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-pact-broker/src/main/kotlin/au/com/dius/pact/pactbroker/PactBrokerClient.kt) fails to publish the verification back to the pact broker when it's an HTTPS POST call to the pact broker. i see the following in my test logs
```
[a.c.d.p.p.ProviderVerifier] - Failed to publish verification results - Connect to localhost:1234 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused) 
```
I currently think it's a problem with the underlying apache httpclient as it somehow tries to route the request to localhost:1234.
FYI i've tested with a unit test publishing the verification to a locally running pact broker on http and it works.

As a workaround I've overridden the au.com.dius.pact.provider.junit.InteractionRunner which works:
```
public class PayInteractionRunner extends InteractionRunner {

    private Optional<String> verificationUrl = Optional.empty();
    private String username;
    private String password;

    public PayInteractionRunner(TestClass testClass, Pact<? extends Interaction> pact, PactSource pactSource) throws InitializationError {
        super(testClass, pact, pactSource);
        if (pact.getSource() instanceof BrokerUrlSource) {
            verificationUrl = Optional.of(((BrokerUrlSource) pact.getSource()).getAttributes().get("pb:publish-verification-results").get("href").toString());
            PactBrokerAuth authentication = testClass.getAnnotation(PactBroker.class).authentication();
            password = authentication.password();
            username = authentication.username();
        }
    }

    @Override
    public void reportVerificationResults(Boolean allPassed) {
        verificationUrl.ifPresent(url -> {
            CredentialsProvider provider = new BasicCredentialsProvider();
            provider.setCredentials(AuthScope.ANY, new UsernamePasswordCredentials(username, password));
            HttpClient httpClient = HttpClientBuilder.create().setDefaultCredentialsProvider(provider).build();

            try {
                System.out.println("Publishing verification results...");
                HttpPost request = new HttpPost(url);
                StringEntity stringEntity = new StringEntity("{\"success\":\"false\",\"providerApplicationVersion\":\"1.0.1\"}");
                request.addHeader("Content-Type", "application/json");
                request.setEntity(stringEntity);
                httpClient.execute(request);
                System.out.println("Verification results published successfully.");
            } catch (Exception e) {
                System.out.println("Exception caught: " + e.getMessage());
                System.out.println("Verification results published unsuccessfully");
            }
        });
    }
}
```

**Comment by uglyog** [comment]
Ok, I will look into this. It should be sending the results back to the server the pact was fetched from.

**Comment by oswaldquek** [comment]
Great, thanks!

**Comment by uglyog** [comment]
I am unable to replicate this, and it seems HTTP vs HTTPS makes no difference. However, I can see from your interaction runner and the default one is the default one does not use the source passed into the runner's constructor, but the source associated to the pact. Maybe in your case the source associated with the pact file is being overwritten.

I will change the interaction runner, but as it is working for me, I am unable to confirm whether this will make a difference.

**Comment by oswaldquek** [comment]
hmm it still doesn't work for me. I think you should disregard my interaction runner - it's only there as my workaround because the pact broker client fails to publish to the pact broker using https. It's no biggie as I already have a workaround, so feel free to close the issue as you're unable to duplicate it.

**Comment by uglyog** [comment]
I'm going to have to revert the changes, as it has impacted some other people
