### ISSUE TITLE
multiple .query() doesn't works

### ISSUE THREAD

**Issue by valera7979** [DiUS/pact-jvm#677]
Hi! My code is next:
`....method("PUT")
.query("recursive=true")
.query("some=true")`

when I try to make pact with next url in request

`String url = String.format("Http://localhost:%d/repository/upload?recursive=true&dsome=true");`

I get next error 

> java.lang.AssertionError: Pact Test function failed with an exception, possibly due to Mismatches(mismatches=[PartialMismatch(mismatches=[QueryMismatch(recursive,,true,Some(Unexpected query parameter 'recursive' received),$.query.recursive)])])

always the first parameter in the queries falls for error

I try next code and it works:

`....method("PUT")
				.matchQuery("recursive", "true")
				.matchQuery("somee", "true")`

But why multiple queries don`t work properly?
Thanks

**Comment by uglyog** [comment]
`.query()` is for the whole query string, so use `.query("recursive=true&some=true")`

**Comment by valera7979** [comment]
Thanks a lot.
