### ISSUE TITLE
Spring provider can not send tags to broker after validation

### ISSUE THREAD

**Issue by niek1414** [DiUS/pact-jvm#678]
Is it currently possible to publish the current version tag of the provider after a pact file from the broker is validated?
It now defaults to `0.0.0`. Seems related to #200 for gradle and #0abaf38 for the Maven-Provider. Is there something similar for the Spring-Provider?

**Comment by uglyog** [comment]
The Spring provider support is an extension of the JUnit 4 runner. These use the Java system property `pact.provider.version` for the version of the provider.

**Comment by niek1414** [comment]
Ah i see, Thanks.
Nice project!
