### ISSUE TITLE
@DefaultRequestValues .headers works only for first request

### ISSUE THREAD

**Issue by valera7979** [DiUS/pact-jvm#680]
Hi. My code is next:

`@DefaultRequestValues`
	public void defaultRequestValues(PactDslRequestWithoutPath request) {
		request.headers("Content-Type", "application/json").method("GET");
	}

code fragment to create pact:

return builder.given("status200")
				.uponReceiving("Get object")
					.path(PATH)
				.willRespondWith()
					.status(200)
				.uponReceiving("Download")
					.headers("Content-Type", "application/json")
					.path(PATH2)
					.matchQuery("source_filename" , "[\\S\\s]+[\\S]+", FILENAME)
				.willRespondWith()
					.status(200)

as you can see I added .headers("Content-Type", "application/json") because without it the header absent in pact and providers tests do not pass.

Thanks.

**Comment by uglyog** [comment]
3.5.17 has been released with this fix
