### ISSUE TITLE
Automatically create a `PactDslJsonBody` from a Java object

### ISSUE THREAD

**Issue by thombergs** [DiUS/pact-jvm#683]
Currently, to define the body of a message within a Java consumer test, we have to do the following: 

```java
new PactDslJsonBody()
  .stringType("firstName", "Zaphod")
  .stringType("lastName", "Beeblebrox"))
  .toPact();
```

This is quite cumbersome, especially for large objects (which are not unusual). 

Is there a way to automatically create a `PactDslJsonBody` from a given Java object?

If not, consider this a feature request :). 

Implementing a mapper that does this seems easy enough, and I'd gladly give it a try.

**Comment by uglyog** [comment]
Should be able to do this.

**Comment by oswaldquek** [comment]
@thombergs you could use the jackson's ObjectMapper to write a json string of your body?

**Comment by thombergs** [comment]
Yes, didn't think of this.

**Comment by thombergs** [comment]
@oswaldquek Actually, just providing a JSON string doesn't suffice for our use case, since we want to use the "like" matchers (i.e. we don't want to match the exact JSON, but just that the types of the JSON fields are correct).

**Comment by oswaldquek** [comment]
@thombergs yeah, true that. we're using the json pact (according to the pact specification https://github.com/pact-foundation/pact-specification/tree/version-3) directly: https://github.com/alphagov/pay-publicapi/pull/177. personally i'm not a huge fan of java dsls. that might help you.

**Comment by schuettec** [comment]
We build a lib for that. It creates calls on `PactDslJsonBody` from a Java Bean. Matcher are used by default. But you can configure it very flexible.
@thombergs https://github.com/remondis-it/pact-consumer-builder :)

**Comment by uglyog** [comment]
Closing this

**Comment by pfichtner** [comment]
@thombergs even if this is a quite old issue, perhaps still relevant or otherwise just for reference: 
please check https://github.com/pfichtner/pacto
Any feedback welcome!
