### ISSUE TITLE
SpringRestPactRunner doesn't appear to call destroyMethod on Spring beans

### ISSUE THREAD

**Issue by darrengreaves** [DiUS/pact-jvm#699]
I have a Pact test using `SpringRestPactRunner` that passes when I run it standalone.
Elsewhere in my app I have a `@Bean` annotation with a `destroyMethod` parameter to control my HazelcastInstance.

```
    @Bean(destroyMethod= "shutdown")
    public HazelcastInstance hazelcastInstance() {
        LOGGER.info("Starting Hazelcast");
        return Hazelcast.newHazelcastInstance(config());
    }
```

In my other functional tests I can see in the logs that Hazelcast starts and stops correctly.

However, in my pact test Hazelcast is never shut down - this causes my Maven build to fail as the next test tries to start Hazelcast and the application fails with an exception at that point as it's already running.

My thinking is that when I use the `SpringRestPactRunner` it's not calling the `destroyMethod` from the `@Bean` annotation.

**Comment by darrengreaves** [comment]
Hi.

That test already has an `@After` method.

**Comment by darrengreaves** [comment]
Hi, is there anything else I can try to get this resolved please?

**Comment by uglyog** [comment]
By default the application context is destroyed when the test JVM exits, but you can now use the `@DirtiesContext` Spring test annotation to change that to be after the test class or after each test method.

**Comment by uglyog** [comment]
3.5.19 has been released with this fix

**Comment by darrengreaves** [comment]
Thanks, this has fixed the issue.
