### ISSUE TITLE
There is no implementation for Array of strings (or) array of integers in LambdaDsl and in PactDsl for pact jvm

### ISSUE THREAD

**Issue by habhilash** [DiUS/pact-jvm#701]
`{
"Conditions":[
               "conditionA",
               "conditionB",
               "conditionC"
            ]
}`

Consider above example, and there is no implementation to use **eachArrayLike()**, **minArrayLike()**, **maxArrayLike()** in order to generate generalized array of strings using LambdaDSL or PactDSL.

Referred to [](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-java8/src/test/java/io/pactfoundation/consumer/dsl/LambdaDslJsonArrayTest.java#L270) and such use case is not found and no implementation is found in **LamdaDslObject.java** and **LambdaDslJsonBody.java** and **LambdaDslJsonArray.java** classes

@uglyog

**Comment by uglyog** [comment]
Fix has been released with version 3.5.18

**Comment by biergit** [comment]
I would like to be able to add different values inside the example array. How to do that?
