### ISSUE TITLE
MockMvcTarget executes controller under test 2 times.

### ISSUE THREAD

**Issue by CraigAtWork** [DiUS/pact-jvm#706]
At line 68 in MockMvcTarget.kt, the code 0.rangeTo(runTimes) executes the controller under test 2 times since runTimes defaults to 1, and the execution goes from 0 to 1.

Is this the intended behavior?

A consequence is that we cannot verify number of executions of a mocked business service without creating a +1 fudge number in the verify() assertion.

The alternative is to call setRunTimes(0) when the MockMvcTarget is initialized, but this could be a point of confusion in the test code.

**Comment by uglyog** [comment]
3.5.19 has been released with this fix
