### ISSUE TITLE
@State("default") is not executed when running mvn pact:verify

### ISSUE THREAD

**Issue by AdrianKrebs** [DiUS/pact-jvm#712]
When I run my provider-test locally, everything works fine.
When I get my pact from the pact broker and run mvn pact:verify, the preconditions specified in my @State("default") method are not executed.
I have not specified any stateChange URL in the POM since I just want to run the default state method.

Consumer Pact File:
`{
    "provider": {
        "name": "GoalProvider"
    },
    "consumer": {
        "name": "GoalConsumer"
    },
    "interactions": [
        {
            "description": "retrieving goal data",
            "request": {
                "method": "GET",
                "path": "/goals"
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json; charset=UTF-8"
                },
                "body": [
                    {
                        "person": {
                            "firstName": "Herbert",
                            "lastName": "Panter"
                        },
                        "description": "stop smoking"
                    }
                ],
                "matchingRules": {
                    "body": {
                        "$[0].description": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].person.firstName": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].person.lastName": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "header": {
                        "Content-Type": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "application/json;\\s?charset=(utf|UTF)-8"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "default"
                }
            ]
        }
    ],
    "metadata": {
        "pact-specification": {
            "version": "3.0.0"
        },
        "pact-jvm": {
            "version": "3.5.17"
        }
    }
}`

Provider-Test:
```

@Provider("GoalProvider")
@PactFolder("pacts")
@ActiveProfiles("test")
@ExtendWith({ SpringExtension.class, WiremockResolver.class,
		WiremockUriResolver.class })
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
class GoalProviderPactTest {

	@Autowired
	GoalRepository goalRepository;
	@Autowired
	PersonRepository personRepository;

	@TestTemplate
	@ExtendWith(PactVerificationInvocationContextProvider.class)
	void pactVerificationTestTemplate(PactVerificationContext context) {
		context.verifyInteraction();
	}

	@BeforeEach
	void before(PactVerificationContext context) throws MalformedURLException {
		context.setTarget(new HttpTestTarget("localhost", 8099, "/"));
	}

	@State("default")
	public void toDefaultState() {
		// Prepare service before interaction that require "default" state
		Goal g = new Goal();
		Person p = createPerson();
		g.setAmount(new BigDecimal("10"));
		g.setPurpose(PaymentPurpose.GREENPEACE);
		g.setDeadline(LocalDateTime.now());
		g.setDescription("stop smoking");
		g.setStatus(GoalStatus.SET);
		g.setPerson(p);
		goalRepository.saveAndFlush(g);
	}

	@NotNull
	private Person createPerson() {
		Person p = new Person();
		p.setFirstName("Hans");
		p.setLastName("Panter");
		p.setStripeCustomerId("123");
		p.setEmail("test@test.com");
		return p;
	}
}
````
And with no data I get: "Expected a List with 1 elements but received 0 elements"

What am I doing wrong?

**Comment by rholshausen** [comment]
Unit tests are not run by the `pact:verify` task, they are run as part of the test phase by the Maven surefire plugin.

**Comment by AdrianKrebs** [comment]
Ok so I misunderstand a few points:
- I want to pull/push my pacts to/from the broker. This works fine with the pact maven plugin.
- What is best practice to run the pacts in the CI pipeline? When should I run `pact:verify` to pull the pacts from the broker? Can the unit test do this itself?
Thanks a lot!

**Comment by rholshausen** [comment]
Unit tests with the `@PactBroker` annotation will fetch the pacts from the broker.
