### ISSUE TITLE
[Provider-Maven] Build now fails if there is no pact to verify

### ISSUE THREAD

**Issue by AlexTess** [DiUS/pact-jvm#713]
I've recently upgraded pact to 3.5.18 (for features I needed) and noticed that now the build fails if there is no pact to verify. 
"No pact files were found for provider XXXX"

I find this problematic as provider may not know when new contracts will be published by consumer to be verified, so having the provider pact-verify always active, regardless if there is contract to verify at this stage, is preferable (than commenting the verify until contracts are published). I don't really believe it should be a build failure condition. 

What is the reasoning behind this? is it possible to change this back to previous behavior ?

Thanks ! :)

**Comment by uglyog** [comment]
Are you running the verification tests with Gradle, Maven or JUnit?

**Comment by AlexTess** [comment]
Using Maven plugin.

**Comment by uglyog** [comment]
That was by accident, not design. The reason that the default behaviour is to fail when there are no pacts to verify is to avoid any false positives. If the project is mis-configured (say the provider name is misspelt or the pact directory name is incorrect) and no pacts are found, then if the build passes everyone could assume that the provider has been verified, when it has not.

But I will add an option to explicitly turn off this behaviour.

**Comment by uglyog** [comment]
3.5.19 has been released with this fix

**Comment by AlexTess** [comment]
Thanks !
