### ISSUE TITLE
PACT does not work with java modules

### ISSUE THREAD

**Issue by tgdchmi2** [DiUS/pact-jvm#714]
Trying to make PACT-JVM working under Java 9 / 10 with modules does not work because there are the same packages / classes in different JARs. Could you please fix your JARs and dependencies to make PACT work with the new Java module system?

**Comment by uglyog** [comment]
💯 need to do this. The good news is that I have started cleaning up the packages for version 4.0, but it will be a little while before that version is available for use.

**Comment by tgdchmi2** [comment]
Sounds good. Thank you very much.

**Comment by TomRK1089** [comment]
Not just that there are split packages - but also the transient dependencies on Scala modules mean that automatic module names cannot be extracted from those JARs, meaning they will not be added to the module-path.

**Comment by efenderbosch** [comment]
I see 4.0 had a recent beta release. Is this ready for use, or should we wait for a milestone release or final release?

**Comment by uglyog** [comment]
It should be ok to use (no Scala or Clojure support as yet). But JUnit 4 and 5 should work, as well as Gradle and Maven.

It is a rewrite of all the Scala code to Kotlin, so there may be issues. Also, there may be some big changes before the full 4.0 release.

**Comment by uglyog** [comment]
Closing this as 4.0 has been released (current in 4.0.6)
