### ISSUE TITLE
Catch and ignore exception if a command line option is provided

### ISSUE THREAD

**Issue by delitescere** [DiUS/pact-jvm#718]
I'd like to be able to `lein auto pact-verify` (using the [lein-auto](https://github.com/weavejester/lein-auto) plugin) against a running system.

In the [plugin](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-lein/src/main/clojure/leiningen/pact_verify.clj), it would be nice to catch the exception thrown by the [provider](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-lein/src/main/clojure/au/com/dius/pact/provider/lein/verify_provider.clj#L75). I assume this is happening to ensure a non-zero exit code (and there's better ways to do that), nonetheless, it would be nice to have a "normal" exit that doesn't also kill the `auto` task.

Perhaps a `lein auto pact-verify --swallow-exceptions` with some change in the plugin [code](https://github.com/DiUS/pact-jvm/blob/866209a67710822f8533435853f18c1324076327/pact-jvm-provider-lein/src/main/clojure/leiningen/pact_verify.clj#L21) like:

```clojure
(let [parsed-args (parse-args args)
      verifier (LeinVerifierProxy. project parsed-args)]
  (try
    (verify/verify verifier (-> project :pact))
    (catch RuntimeException e
      (when-not (contains? parsed-args '--swallow-exceptions) (throw e)))))
```

**Comment by uglyog** [comment]
Wow, somebody is actually using that plugin! :-D

What should the behaviour be with an exception when run via the auto plugin? Should it just print the error to the console?

Looks like the auto plugin does catch `clojure.lang ExceptionInfo`, so maybe wrapping exceptions in that would work.

**Comment by delitescere** [comment]
Hehe.

Yes, just print out, because you're expecting to make a fix, save, and the `auto` re-runs.

**Comment by delitescere** [comment]
Making a PR now...

**Comment by delitescere** [comment]
I was going to do a PR but there's no instructions on how to actually build or verify the beast, and I don't use gradle or groovy, so... 👎

**Comment by uglyog** [comment]
I have the same problem, I don't use lein so I can't test it. But 3.5.19 has been released with this fix.
