### ISSUE TITLE
Can't set pact.verifier.publishResults to true with Maven

### ISSUE THREAD

**Issue by DerKnecht** [DiUS/pact-jvm#724]
Hello,

since an update I get the following warning:
`[main] WARN  au.com.dius.pact.provider.junit.InteractionRunner - Skipping publishing of verification results (pact.verifier.publishResults is not set to 'true')`
As I found this [#publishing-verification-results-to-a-pact-broker-version-354](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#publishing-verification-results-to-a-pact-broker-version-354) I tried to set the property in the pom.xml in property-section, via the properties-maven-plugin and via command line (Dpact.verifier.publishResults=true), but nothing of that worked for me. I could not figure out how to set it to true.

Any ideas?

Edit: This may be a duplicate of: https://github.com/DiUS/pact-jvm/issues/538
As I use Annotations (@PactUrl) and there is no Annotation like PactBrokerUrl there may be another chance? I need an url like: `"http://" + Constants.PACTBROKERHOST + ":" + Constants.PACTBROKERPORT + "/pacts/provider/" + PROVIDER + "/consumer/" + CONSUMER+ "/version/" + PACTVERSION`

**Comment by rholshausen** [comment]
The JUnit tests run by the surefire Maven plugin. You need to get it to set the property, as per http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

**Comment by SnewsButton** [comment]
I struggled with this too. After some searching, I found that the value of 'true' the verifier seeks is the string "true" rather than the boolean `true` (see [ProviderVerifier.kt](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider/src/main/kotlin/au/com/dius/pact/provider/ProviderVerifier.kt)). I think this is kinda tricky.

However, even still I am getting the following error:

```
[main] INFO au.com.dius.pact.provider.ProviderVerifier - Skipping publishing verification results for source FileSource(file=target/pacts/consumer-provider.json, pact=null)
```

**Comment by uglyog** [comment]
JVM properties are always strings. How can you supply any other type of value?

**Comment by SnewsButton** [comment]
I think I erred because of my general jvm unfamiliarity. Rather than setting the property through maven (which I do now), I initially set pact.verifier.publishResults to true (the boolean rather than a string as it would expect) programatically. So
```
Properties prop = System.getProperties();
prop.put("pact.verifier.publishResults", true);
System.setProperties(prop);
```
would not register as 'true', but this would: 
```
prop.put("pact.verifier.publishResults", "true");
```
This is probably just my own error.

**Comment by DerKnecht** [comment]
Okay, this is what I have now: 
```
...
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${mvn-surefire-plugin.version}</version>
				<configuration>
					<systemProperties>
						<property>
							<pact.verifier.publishResults>true</pact.verifier.publishResults>
						</property>
					</systemProperties>
				</configuration>
			</plugin>
...
```

I tried to debug it:
```
final Properties sysProp =  System.getProperties();
System.out.println("pact.verifier.publishResults:" +  sysProp.get("pact.verifier.publishResults"));
```

But the outcome is: `pact.verifier.publishResults:null`

What's wrong here?

**Comment by Norman-else** [comment]
@DerKnecht According to your last comment:
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemProperties>
                        <property>
                            <pact.verifier.publishResults>true</pact.verifier.publishResults>
                        </property>
                    </systemProperties>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*Tests.java</include>
                        <include>**/*TestCase.java</include>
                        <include>**/*Spec.java</include>
                    </includes>
                </configuration>
            </plugin>
```

That still not work for me. Could you please help me?

**Comment by Norman-else** [comment]
> ublishing verification results to a Pact Broker. So even if you set it to true, it has no use without a broker.

```
        <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemProperties>
                        <property>
                            <pact.verifier.publishResults>"true"</pact.verifier.publishResults>
                        </property>
                    </systemProperties>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*Tests.java</include>
                        <include>**/*TestCase.java</include>
                        <include>**/*Spec.java</include>
                    </includes>
                </configuration>
            </plugin>
```

This is my configuration but still not works no matter I change the value to `'true'` or `true` or `"true"`.

**Comment by uglyog** [comment]
@Norman-else what version of Pact-JVM are you using?

**Comment by Dattasaisukumar** [comment]
Hi even I am also not able to publish the results after verifying . I am getting error as publish is not set to true. 

I am using this pulgin 

<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M5</version>
				<configuration>
					<systemProperties>
						<property>
							<pact.verifier.publishResults>true</pact.verifier.publishResults>
						</property>
					</systemProperties>
				</configuration>
			</plugin>

and my other dependency details are 


<dependency>
    <groupId>au.com.dius</groupId>
    <artifactId>pact-jvm-provider-junit</artifactId>
    <version>4.0.10</version>
</dependency>

<plugin>
				<groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-provider-maven</artifactId>
                <version>4.0.10</version>
				</plugin>

Can anyone please help me on this. I am able to do the verification sucessfully. I want to publish my results into PACT BROKER back

**Comment by uglyog** [comment]
@Dattasaisukumar just check https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html, `systemProperties` is deprecated and you should use `systemPropertyVariables` which has a different form.
