### ISSUE TITLE
JUnit5 TestResultAccumulator does not publish verification results

### ISSUE THREAD

**Issue by nwholloway** [DiUS/pact-jvm#736]
I saw [Issue 694](694) had a fix for publishing verification results, so I tried with 3.5.19.  I found that for my project the verification results were not published.

Results for pacts are accumulated in the map `testResults`.  Unfortunately, the value for `pact.hashCode()` changes, so results for a pact are split across multiple entries.

The attached screenshot shows a test with 13 interactions where the results are split across 4 map entries.  You can see the same object identity is reported in all 4 keys.

![image](https://user-images.githubusercontent.com/1571880/42875570-05374e0c-8a7c-11e8-8700-402ac99b670a.png)

My investigation of what might be contributing to the change in hash code has the following chain:

* RequestResponsePact.iteractions
* RequestResponseInteraction.response
* Response.matchingRules

Initially `matchingRules` is an empty list, but after the pact interaction is validated, the list has two entries:
* "header" -> "Category(name=header, matchingRules={})"
* "body" -> "Category(name=body, matchingRules={})"

Other pact interactions are not mutated, and `matchingRules` remains an empty list.

**Comment by shashidesai** [comment]
I am facing the same issue. i am using the gradle plugin `id "au.com.dius.pact" version "3.5.19"`
So when I run `gradle clean pactVerify -Dpact.verifier.publishResults=true` - pactVerify runs fine but I don't see the last verified column in the pact broker being updated.

**Comment by uglyog** [comment]
Verification results will only be published if the tests are not filtered and the Java system property `pact.verifier.publishResults` is set to `true`.

**Comment by uglyog** [comment]
Oh, sorry, just re-read your description, and I understand the issue now.

I'll update the accumulator to use a deterministic hash which will not change.

**Comment by uglyog** [comment]
Released 3.5.20 with this fix

**Comment by uglyog** [comment]
Thanks for digging into this. The JUnit 4 module has the same issue.
