### ISSUE TITLE
Help with the "PKIX path building failed" when working with provider endpoint as https

### ISSUE THREAD

**Issue by aricalee** [DiUS/pact-jvm#741]
Dear
   I'm using pact-JVM-example with grade plugin 3.5.19. when the provider endpoints has https://..., I got the error like "Request Failed - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException:
 unable to find valid certification path to requested target" when run packVerify.

May I know if any tips on how to configure the self signed certification in this case with gradle?

Thanks so much!

**Comment by uglyog** [comment]
Refer to the docs here: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle#enabling-insecure-ssl-version-228

**Comment by aricalee** [comment]
@uglyog  Thanks so much for your help. Just a quick question, if the access to the provide needs a root certificate, should I install the certificate on the PACT broker server? Say, if I setup my PACT broker server with DIUS...I have no way to install my certificate on it?

Thanks

**Comment by aricalee** [comment]
The issue has been solved. Close it. Thanks @uglyog  so uch.

**Comment by AnuragkAnkur** [comment]
@uglyog the url is not found :
: https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-gradle#enabling-insecure-ssl-version-228

Can you please redirect us to the latest URL ?

I am having a similar issue with my Maven project. The provider is an Https endpoint and I am not sure how to configure the ssl context using the HttpTarget class. 

Your help will be really appreciated . 

Thanks

**Comment by uglyog** [comment]
@AnuragkAnkur -> https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-gradle#enabling-insecure-ssl

**Comment by AnuragkAnkur** [comment]
@uglyog Many thanks for the reference . However i am also looking for a way to provide/pass custom SSL context though coding or annotation when using pact-jvm-provider dependency and not from build.gradle or pom.xml . 

Also is there a way to intercept Response object like we have @TargetRequestFilter to intercept Request Object? 

I have also opened a separate issue ticket for it . 
https://github.com/DiUS/pact-jvm/issues/900

**Comment by ahajizade** [comment]
@uglyog the url is not found:
 https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-gradle#enabling-insecure-ssl

**Comment by uglyog** [comment]
URL is now https://github.com/pact-foundation/pact-jvm/tree/master/provider/gradle#enabling-insecure-ssl
