### ISSUE TITLE
Neither query params nor form params are sent when both are specified in the same request

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#745]
I have an endpoint I'm testing that looks like this:

`@POST
    @Path("/byCreators")
    @Consumes(APPLICATION_FORM_URLENCODED)
    @Produces(APPLICATION_JSON)
    public Response queryForSnacksByMultipleCreators(@QueryParam("floor") Integer floor, @FormParam("creator") List<String> creator)`

The consumer side Pact test for it has this fragment:
`public class GetSnacksOnFloorByCreatorsTest extends AbstractPactTestForDonutsWs {
    @Pact(provider = "donuts-ws", consumer = "donuts-consumer")
    public RequestResponsePact querySnacksByCreatorsFragment(PactDslWithProvider builder) {
        return builder.given("there exists a donuts entry on floor 6 with creator Loren")
                .uponReceiving("a request to find donuts on floor 6 brought by Loren")
                .method("POST")
                .path("/donuts/byCreators")
                .headers("Accepts", APPLICATION_JSON)
                .matchQuery("floor", "[5-9]", "6")
                .body(new QueryBuilder().addCreators("Loren").createFormParams(), X_WWW_FORM_URLENCODED)
                .willRespondWith()
                .status(200)
                .matchHeader("Content-Type", APPLICATION_JSON)
                .body(
                        newJsonArray(
                                        rootArray ->
                                                rootArray.object(
                                                        getSnackJsonResponseFragment(
                                                                defaultSnack.but().setCreator("Loren").setLocation(new Location(6, "north kitchen")).build())))
                                .build())
                .toPact();
    }`

That results in the following section in my Pact file: 

`{
            "description": "a request to find donuts on floor 6 brought by Loren",
            "request": {
                "method": "POST",
                "path": "/donuts/byCreators",
                "headers": {
                    "Accepts": "application/json",
                    "Content-Type": "application/x-www-form-urlencoded"
                },
                "query": {
                    "floor": [
                        "6"
                    ]
                },
                "body": "creator=Loren",
                "matchingRules": {
                    "query": {
                        "floor": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "[5-9]"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "path": {
                        
                    },
                    "header": {
                        
                    },
                    "body": {
                        
                    }
                }
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": [
                    {
                        "creator": "Loren",
                        "quantity": 5,
                        "created": "2018-07-31T13:41:14.768",
                        "description": "donuts",
                        "location": {
                            "floor": 6,
                            "room": "north kitchen"
                        },
                        "id": 1,
                        "lastModified": "2018-07-31T13:41:19.768"
                    }
                ],
                "matchingRules": {
                    "header": {
                        "Content-Type": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "application/json"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "body": {
                        "$[0].id": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].created": {
                            "matchers": [
                                {
                                    "match": "timestamp",
                                    "timestamp": "yyyy-MM-dd'T'HH:mm:ss.SSS"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].lastModified": {
                            "matchers": [
                                {
                                    "match": "timestamp",
                                    "timestamp": "yyyy-MM-dd'T'HH:mm:ss.SSS"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].creator": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].quantity": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].description": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].location.floor": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].location.room": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "there exists a donuts entry on floor 6 with creator Loren"
                }
            ]
        }`

The empty body in the matchingRules in the request seems a little suspect.

When I put together the provider test, I got an empty list for the creators and a null for the floor.

Don't ask me why anyone would want to combine formparams and queryparams in the same request. I'm modeling this after someone else's existing contract, and was able to reproduce the pact issue in both the original project and this toy donuts project.

I'm happy to provide more of the donuts code if it helps. Thanks for looking into this.

**Comment by uglyog** [comment]
Version 3.5.21 has been released
