### ISSUE TITLE
pact-jvm fat jar

### ISSUE THREAD

**Issue by nikroth** [DiUS/pact-jvm#747]
As mentioned in another case (#439) the dependency tree for pact-jvm is quite large, and can often cause conflicts.  Is it possible to create a fat jar option that can be called upon for those of us that might be interested in shading the project?  

For those who aren't interested in the shaded jar, they can continue using the non-shaded releases.  For those who are interested, they would be importing it into the test scope, so there would be no increase in their own artifact size.  And they would get the benefit of not having to worry about transitive dependency conflicts.

Thanks!

**Comment by LoraVolkert** [comment]
One of our teams had some Pact tests at one time, but had to delete them because the version of groovy they were using conflicted with the version in Pact. :(

**Comment by uglyog** [comment]
I'll create a pact-jvm-all jar with the next release.

**Comment by quincy** [comment]
Thanks @uglyog, this will be really helpful.

**Comment by uglyog** [comment]
Version 3.5.21 was published including all dependencies other than the build plugin jars.

**Comment by LoraVolkert** [comment]
Dumb question maybe. What's the artifact id for the fat jar, so we can use it in our pom files?

**Comment by uglyog** [comment]
https://search.maven.org/artifact/au.com.dius/pact-jvm/3.5.21/pom

**Comment by LoraVolkert** [comment]
This is great! Can we do this for the provider side and the java8 library as well?

**Comment by uglyog** [comment]
A fat jar with all the provider code, and one with just the java 8 consumer module?

**Comment by LoraVolkert** [comment]
Yep.
