### ISSUE TITLE
PactDslResponse#uponReceiving returns `PactDslRequestWithPath` but does not reuse path

### ISSUE THREAD

**Issue by usr42** [DiUS/pact-jvm#748]
Hello,

if you specify multiple interactions for one given state, the second call to `uponReceiving()` (`PactDslResponse#uponReceiving`) returns a `PactDslRequestWithPath`.
So, you don't have to specify the path anymore.

Following minimal example shows what I mean:
```java
ConsumerPactBuilder
    .consumer("consumer")
    .hasPactWith("provider")
        .given("state")
            .uponReceiving("request1")
                .path("/path")
            .willRespondWith()
            .uponReceiving("request2")
            // Don't add already same path again
            .willRespondWith()
    .toPact()
```

I would expect, that the second request reuses the path of the first one (`"/path"`), but instead the path of the second request is `"/"`

From my perspective it would be even cleaner if `PactDslResponse#uponReceiving` would return a `PactDslRequestWithoutPath`, so the user has to specify the path again, which makes it more explicit and the behavior becomes more obvious.
But this would then be a breaking change. So, it is a tradeoff.

### Test to reproduce

Here is a minimal test in Kotlin to reproduce the bug:
```kotlin
import au.com.dius.pact.consumer.ConsumerPactBuilder
import au.com.dius.pact.consumer.dsl.PactDslResponse
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class PactBugTest {
    private val requestDescription = "request2"
    private val path = "/path"

    @Test
    fun reproduceBug() {
        val pactWithExplicitPath = pactWithResponse()
            .uponReceiving(requestDescription)
                // Add same path again
                .path(path)
            .willRespondWith()
            .toPact()

        val pactWithImplicitPath = pactWithResponse()
            .uponReceiving(requestDescription)
                // Don't add same path again
            .willRespondWith()
            .toPact()

        println()
        
        assertThat(pactWithExplicitPath).isEqualTo(pactWithImplicitPath)
    }

    private fun pactWithResponse(): PactDslResponse {
        return ConsumerPactBuilder
            .consumer("consumer")
            .hasPactWith("provider")
            .given("state")
            .uponReceiving("request1")
            .path(path)
            .willRespondWith()
    }
}
```

### Version details

- au.com.dius:pact-jvm-consumer_2.12:3.5.19

If there are more questions or you need more data, please ask.

**Comment by uglyog** [comment]
Version 3.5.21 has been released
