### ISSUE TITLE
newJsonArrayMinMaxLike does not respect type matchers, forcing stricter match

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#749]
I want to test that my producer returns a certain number of an object in a given scenario, but I don't want to have to specify every single aspect of the objects since a) that's a lot of code, b) it's potentially fragile due to ordering issues, and c) I'd like to leave some flexibility for the producer. Seems like a perfect place to use newJsonArrayMinMaxLike and some type matchers. But when I use this and implement a test on the producer side that doesn't match the examples, but does match the matchers, it fails.

Here's an example:

`@Pact(provider = "donuts-ws", consumer = "donuts-consumer")
    public RequestResponsePact getAllDonutsFragment(PactDslWithProvider builder) {
        return builder.given("there are two snack entries")
                .uponReceiving("a request for all available donuts")
                .method("GET")
                .path("/donuts")
                .willRespondWith()
                .status(200)
                .matchHeader("Content-Type", APPLICATION_JSON)
                .body(
                        LambdaDsl.newJsonArrayMinMaxLike(2, 2, rootArray -> rootArray.object(getSnackJsonResponseFragment(defaultSnack.but().setId(1).build())))
                                .build())
                .toPact();
    }`

The getSnackJsonResponseFragment uses type matchers, not value matchers:

`<T extends LambdaDslObject> Consumer<T> getSnackJsonResponseFragment(Snack snack) {
        return snackObject -> {
            snackObject.numberType("id", snack.getId());
            snackObject.timestamp("created", "yyyy-MM-dd'T'HH:mm:ss.SSS", Date.from(snack.getCreated().atZone(ZoneId.systemDefault()).toInstant()));
            snackObject.timestamp("lastModified", "yyyy-MM-dd'T'HH:mm:ss.SSS", Date.from(snack.getLastModified().atZone(ZoneId.systemDefault()).toInstant()));
            snackObject.stringType("creator", snack.getCreator());
            snackObject.numberType("quantity", snack.getQuantity());
            snackObject.stringType("description", snack.getDescription());
            snackObject.object(
                    "location",
                    locationObject -> {
                        locationObject.numberType("floor", snack.getFloor());
                        locationObject.stringType("room", snack.getRoom());
                    });
        };
    }`

This results in the following in the pact file:
`{
            "description": "a request for all available donuts",
            "request": {
                "method": "GET",
                "path": "/donuts"
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": [
                    {
                        "creator": "loren",
                        "quantity": 5,
                        "created": "2018-08-03T14:51:49.796",
                        "description": "donuts",
                        "location": {
                            "floor": 6,
                            "room": "south kitchen"
                        },
                        "id": 1,
                        "lastModified": "2018-08-03T14:51:54.796"
                    },
                    {
                        "creator": "loren",
                        "quantity": 5,
                        "created": "2018-08-03T14:51:49.796",
                        "description": "donuts",
                        "location": {
                            "floor": 6,
                            "room": "south kitchen"
                        },
                        "id": 1,
                        "lastModified": "2018-08-03T14:51:54.796"
                    }
                ],
                "matchingRules": {
                    "header": {
                        "Content-Type": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "application/json"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "body": {
                        "$": {
                            "matchers": [
                                {
                                    "match": "type",
                                    "min": 2,
                                    "max": 2
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].id": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].created": {
                            "matchers": [
                                {
                                    "match": "timestamp",
                                    "timestamp": "yyyy-MM-dd'T'HH:mm:ss.SSS"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].lastModified": {
                            "matchers": [
                                {
                                    "match": "timestamp",
                                    "timestamp": "yyyy-MM-dd'T'HH:mm:ss.SSS"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].creator": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].quantity": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].description": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].location.floor": {
                            "matchers": [
                                {
                                    "match": "number"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$[0].location.room": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "there are two snack entries"
                }
            ]
        }`

But when I implement my producer state like this, I get failures:
`@State("there are two snack entries")
    public void getAllSnacksTest() {
        when(mockSnackDao.loadCurrentSnacks(any(LocalDateTime.class), any(), anyInt(), anyString(), anyString(), anyInt(), anyInt(), anyString()))
                .thenReturn(
                        Lists.newArrayList(
                                defaultSnack.but().setQuantity(5).setDescription("donuts").setCreator("Nikki").setLocation(new Location(6, "south kitchen")).build(),
								defaultSnack.but().setDescription("Hostess Fruit Pies").build()));
    }`

It's angry because the second entry's quantity is 1, not 5; its description is Hostess Fruit Pies, not donuts; and the timestamps are different by a matter of seconds. These are all things that should match the type matchers.

**Comment by LoraVolkert** [comment]
There's also a much bigger, uglier error message above those ones which is complaining that the list as a whole doesn't match.

**Comment by LoraVolkert** [comment]
By the way, we would not mind contributing to the repository for some of the issues we've opened, but we've had some difficulty getting the project to build. Do you have a guide for getting things set up?

**Comment by uglyog** [comment]
There are a few defects contributing to this. Starting with the verifier, the type matchers are not cascading correctly (it should default to the type matcher at `$`). Then the DSL is only defining the matchers on the fields on the first item (`$[0].quantity` instead of `$[*].quantity`).

**Comment by uglyog** [comment]
Version 3.5.21 has been released
