### ISSUE TITLE
Pact:verify doesnt print out the tag name in the verification results

### ISSUE THREAD

**Issue by amitojduggal** [DiUS/pact-jvm#754]
Description: 
I am running the pact verifications against a pact broker for 2 tags, master and develop.

when i see the results after the execution ,the log says

Verifying a pact between A and B
[from Pact Broker https://xyz.com.au/pacts/provider/A/consumer/B/version/0.0.33]
OK

Verifying a pact between A and B
[from Pact Broker **https://xyz.com.au/pacts/provider/A/consumer/B/version/0.0.33**]
FAILED

it doesnt give us the tag url and just gives out the version, i dont come to know which of the tagged branch is having the failure. cause both look the same , the pact broker url should have /tag/version in it as well.

**Comment by uglyog** [comment]
Version 3.5.21 has been released
