### ISSUE TITLE
pact-jvm-provider-spring bug parsing Content-Type Header when it's a regex?

### ISSUE THREAD

**Issue by chris-fa** [DiUS/pact-jvm#756]
Here's my Pact interaction definition for my endpoints (all endpoints have the same problem)
```json
...
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "matchingRules": {
          "$.headers.Content-Type": {
            "match": "regex",
            "regex": "application\\/json"
          },
          ...
        }
...
```

I'm using `pact-jvm-provider-spring`:

```gradle
testCompile group: 'au.com.dius', name : 'pact-jvm-provider-spring_2.12', version: '3.5.20'
```

The endpoints are defined with:
```java
@RestController
@RequestMapping(value = "/my/api/resource")
public class MyResourceController {
  @ResponseBody
  @ResponseStatus(value = HttpStatus.OK)
  @RequestMapping(path = "", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
  public ResponseEntity<MyResource> getResources(...
```

And when verifying the pact, this is the result
```
Failures:

0) a resources request returns a response which includes headers "Content-Type" with value "application/json; charset=utf-8"
      Expected 'application/json;charset=UTF-8' to match 'application\/json'
```

This is the first time I'm integrating Pact on a Java project. It looks like the Pact framework isn't doing a regex match here?  Those values match.

Is this a bug, or maybe I missed some configuration?

PS: I also made a quick NodeJS mock project to see if maybe I did something wrong in the pacts, but it is verifying it with no problem.

### Update 1
Have tried **manually** updating the pact to the following, with **no** luck:

```
"$.headers.Content-Type": {
  "match": "regex",
  "regex": "application\/json"    <--  only one `\`
},
```

And also to the following, which **worked, but this is not really what I need**, since it breaks the consumer.

```
"$.headers.Content-Type": {
  "match": "regex",
  "regex": "application\/json;charset=UTF-8"    <--  matching the whole thing
},
```

So maybe this is indeed a bug?

**Comment by uglyog** [comment]
It probably works in Node because Javascript regular expressions behave differently than with the JVM. The regex needs to match the entire string, so you need at least

```json
"$.headers.Content-Type": {
  "match": "regex",
  "regex": "application\\/json.*"
}
```

**Comment by chris-fa** [comment]
Thanks, this was helpful. Would be cool if we could follow just 1 regex type for all pact implementations
