### ISSUE TITLE
Provider tests are not failing when consumer changes the response body field names

### ISSUE THREAD

**Issue by basiaBB** [DiUS/pact-jvm#759]
Hi,

I have a consumer written with pact-js and provider with pact-jvm.

The contract has following matching rules:

        "matchingRules": {
          "$.body": {
            "min": 3
          },
          "$.body[*].*": {
            "match": "type"
          },
          "$.body[*].url": {
            "match": "regex",
            "regex": "^https?:\\/\\/.*"
          },
          "$.body[*].target.link": {
            "match": "regex",
            "regex": "^(TEST1|TEST2|TEST3)$"
          },
          "$.body[*].target.ids": {
            "min": 1
          },
          "$.body[*].target.ids[*].*": {
            "match": "type"
          },
          "$.body[*].contentType": {
            "match": "regex",
            "regex": "^(image\\/jpeg|image\\/png)$"
          },
          "$.body[*].width": {
            "match": "type"
          }
        }

When I changed the field name in the contract ie. width->height, provider tests are still passed.

**Comment by uglyog** [comment]
When you renamed width to height, did you also rename the field in the body, or just the matching rule?

**Comment by basiaBB** [comment]
@uglyog, could you help with that?

**Comment by uglyog** [comment]
I'll need more information before I can help you, particularly a pact file, the debug logs from running the provider verification and information on how you are running the provider verification.

**Comment by uglyog** [comment]
I've managed to replicate the problem, so there is no need for the logs.

**Comment by uglyog** [comment]
3.5.22 has been released with this fix
