### ISSUE TITLE
pact-jvm-provider and pact-jvm-java8 fat jars

### ISSUE THREAD

**Issue by LoraVolkert** [DiUS/pact-jvm#760]
In #747, you provided a shaded jar for the pact jvm consumer library, for which I'm very grateful. However, one of the team's we were hoping this would solve some problems for is a provider, rather than a consumer. Could you provide shaded jars for that library and the java8 one, too?

**Comment by uglyog** [comment]
The shaded jar contains all the consumer libraries, including the Java 8 one. It also contains all the provider ones excluding the build plugins.

Which provider library are you wanting?

**Comment by LoraVolkert** [comment]
That's funny. Is this what the maven dependency for the fat jar is supposed to be?
`<dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm</artifactId>
            <version>${pact.version}</version>
			<type>pom</type>
            <scope>test</scope>
        </dependency>`

**Comment by LoraVolkert** [comment]
Ok. Do the import statements need to change when we use the fat jar? Because when I tried using the fat jar on a project with provider side tests in place of the pact-jvm-provider-junit_2.12 library, it couldn't find any of the pact classes I was trying to import. I got errors like "package au.com.dius.pact.provider.junit does not exist," and when I tried deleting the old import statements and running "fix imports" on the file, it couldn't find a package in the fat jar library that contained them.

**Comment by uglyog** [comment]
Ok, I'll have a look as it should have those packages in it.

**Comment by uglyog** [comment]
I've checked the latest version, and after unpacking the JAR file I can see the class files in there. It must be your project setup. Are you using IntelliJ or Eclipse?

**Comment by uglyog** [comment]
It is the `all` classifier that you are missing.

```
<dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm</artifactId>
            <version>3.5.24</version>
            <scope>test</scope>
            <classifier>all</classifier>
        </dependency>
```

**Comment by LoraVolkert** [comment]
That works. We'll get people using it.
