### ISSUE TITLE
[JVM] Question: array or null

### ISSUE THREAD

**Issue by dbonari** [DiUS/pact-jvm#761]
Hi,

I have the following json:
`"Balance": [
            {
                "AccountId": "22289",
                "CreditDebitIndicator": "Credit",
                "CreditLine": [
                    {
                        "Included": true,
                        "Amount": {
                            "Amount": "1000.00",
                            "Currency": "GBP"
                        },
                        "Type": "Pre-Agreed"
                    }
                ]
            },
            {
                "AccountId": "31820",
                "CreditDebitIndicator": "Debit",
                "CreditLine": null
            }
        ]`
How can I define a matcher for CreditLine array that will accept a null?
My current implementation looks like this:
`DslPart balancesArray = new PactDslJsonBody()
            .minArrayLike("Balance", 1)
                .stringType("AccountId")
                .or("CreditDebitIndicator", PM.stringType(), PM.stringMatcher("Debit"), PM.stringMatcher("Credit"))
                .minArrayLike("CreditLine", 0)
                    .booleanType("Included")
                    .stringType("Type")
                    .object("Amount", amountObject)
                .closeArray()
            .closeArray();`

pactSpecification.version: 3.0.0
pact-jvm.version: 3.5.21

**Comment by uglyog** [comment]
The `.or` method only works with primitive attributes, not arrays. The best way of doing something like this is to have two tests, one with a list set and one with a null value.
