### ISSUE TITLE
Junit5 support for pact messaging

### ISSUE THREAD

**Issue by antoniq** [DiUS/pact-jvm#762]
Hi there,

I have looked at the new Junit5 extension which is great. Are you planning to add support for messaging? Currently, one is required to define the contract:

@Pact(provider="test_provider", consumer="test_consumer")
    public RequestResponsePact createPact(PactDslWithProvider builder) { }

it would be great for msg support:

@Pact(provider="test_provider", consumer="test_consumer")
    public MessagePact createPact(MessagePactBuilder builder) { }

**Comment by uglyog** [comment]
Yes, just needs to be implemented.

**Comment by uglyog** [comment]
3.5.22 has been released with this feature

**Comment by antoniq** [comment]
Great! Thanks for the quick response @uglyog 👍
