### ISSUE TITLE
Question: safe to re-use DslPart in multiple tests? (Junit)

### ISSUE THREAD

**Issue by wandrewni** [DiUS/pact-jvm#766]
I know that pre #619 reusing a DslPart in multiple interactions would result in extra `$` appearing in the `matchingRules` field of the produced pacts -- is it now safe & supported to reuse a DslPart in multiple interactions?

**Comment by uglyog** [comment]
Yes, it should be fine to fine to do that now.

**Comment by wandrewni** [comment]
Thanks!
