### ISSUE TITLE
Pact Provider Exception when no pacts to verify

### ISSUE THREAD

**Issue by AlexTess** [DiUS/pact-jvm#768]
Hello,

I'm implementing Pact Provider Junit5 and I'm facing this issue whenever there is no pacts available to verify for this provider (when there is, it works like a charm). 
I'm using version 3.5.21.

This is the implementation :
```
@Provider("myprovider")
@PactBroker(host="${pact.broker.host}", port = "${pact.broker.port}",tags = "${pact.broker.tag}")
@IgnoreNoPactsToVerify
public class PactVerifyITTest {

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void testTemplate(Pact pact, Interaction interaction, HttpRequest request, PactVerificationContext context) {
        context.verifyInteraction();
 }
```

And the exception raised when not pacts are available: 

```
...
16:11:11.110 [main] DEBUG org.apache.http.wire - http-outgoing-1 << "{"_links":{"self":{"href":"http://192.168.99.100:30003/pacts/provider/myprovider/latest/dev","title":"Latest pact versions for the provider myprovider with consumer version tag 'dev'"},"provider":{"href":"http://192.168.99.100:30003/pacticipants/myprovider","title":"myprovider"},"pb:pacts":[],"pacts":[]}}"
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.1 200 OK
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Content-Type: application/hal+json;charset=utf-8
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Content-Length: 322
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Connection: keep-alive
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Status: 200 OK
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Date: Tue, 11 Sep 2018 14:10:53 GMT
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << X-Content-Type-Options: nosniff
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << Server: Webmachine-Ruby/1.5.0 Rack/1.3
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << X-Pact-Broker-Version: 2.23.3
16:11:11.110 [main] DEBUG org.apache.http.headers - http-outgoing-1 << X-Powered-By: Phusion Passenger 5.1.11
16:11:11.110 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
16:11:11.111 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://192.168.99.100:30003] can be kept alive indefinitely
16:11:11.111 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-1: set socket timeout to 0
16:11:11.111 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://192.168.99.100:30003][total kept alive: 1; route allocated: 1 of 5; total allocated: 1 of 10]

org.junit.platform.commons.util.PreconditionViolationException: No supporting TestTemplateInvocationContextProvider provided an invocation context
```

Did I miss something possibly? or is it an issue ? 
Thanks

**Comment by uglyog** [comment]
This is a problem with JUnit 5. The pact library is doing the correct thing, but then as there are no pacts, there is no JUnit 5 context values. The templated method in your test needs four parameters.

To support this we would have to create dummy values when there are no pacts and the annotation is present.

**Comment by stengvac** [comment]
Suggstion: Make (in Kotlin case) parameters nullable so pact lib can pass nulls?

Test modification:

`
    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider::class)
    fun testTemplate(context: PactVerificationContext? = null) {
        context?.verifyInteraction()
    }

    @BeforeEach
    fun before(context: PactVerificationContext? = null) {
        context?.apply {
           target = myTestTarget
        }
    }
` 
Will there still be problem with context values?

**Comment by FRosner** [comment]
Did anybody figure out a workaround for that issue?

**Comment by matioly** [comment]
I am getting the same problem here.

**Comment by uglyog** [comment]
I've tried injecting null values if there are no pacts to verify, but that still fails as JUnit5 considers a null as not providing the parameter and the tests fail with `No ParameterResolver registered for parameter ...`

**Comment by aaron-hooper** [comment]
Any update on this? Perhaps returning a dummy object?

**Comment by ahsankarimbhai** [comment]
@uglyog Any timeline on when this could be resolved. Or any workaround for this?

**Comment by uglyog** [comment]
Current behaviour after #1007 is to thrown an UnsupportedOperationException when there are no pact files

**Comment by uglyog** [comment]
One way to do this is to return false from the supportsTestTemplate method, which will make JUnit5 skip this test template when there are no pact files.

**Comment by uglyog** [comment]
The dummy test works. It is driven by adding the `@IgnoreNoPactsToVerify` annotation to the test class.

**Comment by uglyog** [comment]
Version 4.0.7 has been released with this change

**Comment by ahsankarimbhai** [comment]
@uglyog I've tried to test with 4.0.7 with `@IgnoreNoPactsToVerify` annotation. I get NullPointerException on `PactVerificationContext`. It looks like `context` variable is still set to null when there are no pacts found in pact broker.

```@IgnoreNoPactsToVerify
@ExtendWith(SpringExtension.class)
@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
)
@Provider("invalid-provider")
@PactBroker(
	host = "${pact.broker.host}",
	port = "${pact.broker.port}",
	tags = "${pact.consumer.tag}",
	authentication = @PactBrokerAuth(username = "${pact.broker.username}", password = "${pact.broker.password}")
)
public class ProviderTests {

    @LocalServerPort
    private int serverPort;

	@BeforeEach
	void setupTestTarget(PactVerificationContext context) {
		System.out.println(context);  // this returns null
		context.setTarget(new HttpTestTarget("localhost", serverPort, "/"));
	}```

**Comment by uglyog** [comment]
@ahsankarimbhai the context will be null when there are no pacts, because the context is created from the pact files. Just check for not null before using the context.

**Comment by ahsankarimbhai** [comment]
> @ahsankarimbhai the context will be null when there are no pacts, because the context is created from the pact files. Just check for not null before using the context.

Got it! thanks. It works for me now after checking for null value.

**Comment by fragonib** [comment]
Bad news :( It doesn´t work when template method has algo an `HttpRequest` parameter

```
    @TestTemplate
    @ExtendWith(PactVerificationSpringProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context, HttpRequest request) throws ProtocolException {
        removeContextFromRequestPath(request);
        context.verifyInteraction();
    }
```

Any thoughts?
