### ISSUE TITLE
Provide Body Content on AssertionError

### ISSUE THREAD

**Issue by thombergs** [DiUS/pact-jvm#770]
Given a request / response interaction in a pact that only expects a HTTP status code without a body. 

When I create a Provider Test with pact-jvm and the HTTP status doesn't match the one from the pact, I get the following output:

```
java.lang.AssertionError: 
0 - assert expectedStatus == actualStatus
           |              |  |
           204            |  400
                          false
```

I get a Bad Request (400). But the log output doesn't help me to identify why the request is bad. When the status code doesn't match, I would like to see the HTTP Body in the log, because it will most likely contain a more detailed error message (or an error JSON object).

**Comment by uglyog** [comment]
The entire response is logged out at debug log level. If you enable debug level logging you should see it.
