### ISSUE TITLE
when will  "values injected from the provider state" for PactBuilder.groovy be available ? 

### ISSUE THREAD

**Issue by geekybaiyi** [DiUS/pact-jvm#773]
hi 
the  PR  https://github.com/DiUS/pact-jvm/commit/0205868b3f741216937b3647bfa7f7ede1af2c5b  
doesn't seem to be included in the latest release  `pact-jvm-consumer-groovy_2.12-3.5.22`

I  got  the following error when trying to use `fromProviderState('foo', 'bar')`

```
MissingMethodException: No signature of method: au.com.dius.pact.consumer.groovy.PactBuilder.fromProviderState() is applicable for argument types: (java.lang.String, java.lang.String) 
```

The PR was merged in July and  `pact-jvm-consumer-groovy_2.12-3.5.22` was released in Sept .. I thought it should include this feature but not.. 
Will this be released soon ?  
thx

**Comment by uglyog** [comment]
I moved that to the 3.6.0 release, as I felt it required too fix a change and I didn't want to impact the stability of the 3.5.x branch. I'm hoping to get 3.6.0 out in the next few weeks.

**Comment by uglyog** [comment]
3.6.0-rc.0 has been released with this feature
