### ISSUE TITLE
Please upadate examples in Readme for pact-jvm provider

### ISSUE THREAD

**Issue by kefasb** [DiUS/pact-jvm#774]
I am trying to use Pact with Spock on the provider side and I am trying to use pact-jvm-provider for this. The examples included in Readme are out of date. They use an outdated api. There is currently no constructor for ProviderClient which takes Request as second argument. Furthermore there is no request() method in Interaction interface. Could you provide example that will work with version 3.5.22?

**Comment by kefasb** [comment]
I figured it out. I have something like:
`    def "Pact"() {
        final verifier = new ProviderVerifier()
        when:
        final Map result = verifier.verifyProvider(serviceProvider)

        then:
        StringJoiner errors = new StringJoiner("\n")
        if (result.size() > 0) {
            int id = 0;
            result.each { k, v ->
                ++id
                errors.add(id.toString()).add(k.toString()).add(v.toString())
            }
        }

        assert errors.length() == 0
    }`
1. Is there a better method to present the result?

2. How to make provider state change?

**Comment by kefasb** [comment]
Again I found out the state change
```
        serviceProvider.hasPactWith("Consumer", {
            pactSource = new File(...)
            stateChange = { providerState ->
                if (providerState.name == "name1") {
                    doSth1()
                } else if (providerState.name == "name2") {
                    doSth2()
                }
            }
        }
```
I have still the questions :)
1. Is there a better method to present the result?
2. Is there a better way to handle stateChanges?
3. How to set pactSource to a directory?

**Comment by uglyog** [comment]
I have updated the examples in README. If you want to see how to use the verifier, have a look at the other implementations. The [JUnit HTTP target](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/main/kotlin/au/com/dius/pact/provider/junit/target/HttpTarget.kt) and [Gradle verify task](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-gradle/src/main/groovy/au/com/dius/pact/provider/gradle/PactVerificationTask.groovy) might be good ones to look at.
