### ISSUE TITLE
3.5.22 - pactVerify is not updating the "Last Verify" status in PACT Broker

### ISSUE THREAD

**Issue by contactsai123** [DiUS/pact-jvm#775]

**Comment by contactsai123** [comment]
[logs.txt](https://github.com/DiUS/pact-jvm/files/2408593/logs.txt)
[build.zip](https://github.com/DiUS/pact-jvm/files/2408596/build.zip)

Am using gradle 4.4 and am trying to publish the verification results in PACT broker. Attached is my build.gradle / error logs:

While am able to publish the pact files in the broker and able to see the dependency graphs, 'Last Verified' shows blank after running the pactVerify method. I saw some documentation around 'pact.verifier.publishResults=true' and tried to pass as gradle parameter, but I got an error message saying:

FAILURE: Build failed with an exception.

What went wrong: Your project is misconfigured, was expecting a 'pact' configuration in the build, but got a String with value '' instead. Make sure there is no property that is overriding 'pact'.
the gradle command I run is:

      ./gradlew test pactPublish 
      ./gradlew pactVerify -Ppact.verifier.publishResults=true
Please let me know what am I missing, the pact.verifier.publishResults is not accepted

**Comment by uglyog** [comment]
This is a duplicate of #738. Can you check that issue to see if it resolves your problem.

**Comment by contactsai123** [comment]
When I run the command:
./gradlew pactVerify

The verification gets completed but the results are not uploaded to PactBroker. 
Skipping publishing of verification results as it has been disabled (pact.verifier.publishResults is not 'true')

So I ran this command:
./gradlew pactVerify -Ppact.verifier.publishResults=true

Now, I get this error:
org.gradle.internal.exceptions.LocationAwareException: Your project is misconfigured, was expecting a 'pact' configuration in the build, but got a String with value '' instead. Make sure there is no property that is overriding 'pact'.] 

I had checked issue #738 and added project.version="2.0.1" in the Provider properties in build.gradle but it didn't resolve.
Also, I see a similar issue logged in the issue# 254

**Comment by contactsai123** [comment]
The issue was due to invalid build.gradle file:

Per comments by Ronald in [StackOverflow](https://stackoverflow.com/questions/52442700/unable-to-publish-the-last-verified-status-in-pact-broker):

The first thing is your Gradle config is invalid. There should only be one pact block. You have two. Remove the inner one with the publish block in it (but leave the publish block :-D).

Resolution: Changed it to one pact block and now the results are published to the broker!
