### ISSUE TITLE
java8 DSL: how to use eachKeyLike with a value that is not an object/array

### ISSUE THREAD

**Issue by abendt** [DiUS/pact-jvm#778]
I'm trying to describe this structure:

```
{
  "offer": {
    "prices": {
      "DE": 1620
    },
    "shippingCosts": {
      "DE": {
        "cia": 300
      }
    }
}
```

I want to specify that the object can contain some String -> Number mappings. The actual values can vary and should not be fixed.

using the old DSL (with Kotlin) I came up with:

```
   val body = PactDslJsonBody()
                .`object`("offer")
                .`object`("prices")
                .eachKeyLike("DE", PactDslJsonRootValue.numberType(1620))
                .closeObject() // prices
                .`object`("shippingCosts")
                .eachKeyLike("DE")
                .numberValue("cia", 300)
                .closeObject() // eachKeyLike
                .closeObject() // shippingCosts
                .closeObject() // offer
```

Now I'm trying to use the new Java 8 DSL. However I could not find a way how to use _eachKeyLike_. It seems to assume that the value is an object or an array (_eachKeyMappedToAnArrayLike_). On the contrary with _minArrayLike_ its possible to pass in a _PactDslJsonRootValue_ value. Am I missing something?  How can I achieve this using the Java 8 DSL?

**Comment by uglyog** [comment]
Released 3.6.0-rc.1 with this change.
