### ISSUE TITLE
Why don't we have a @PactFile/PactFileLoader??

### ISSUE THREAD

**Issue by ekeoch** [DiUS/pact-jvm#780]
I see a BrokerLoader, URLLoader, and a PactFolderLoader but not a FileLoader to load files directly. It kinda sucks because if I am testing locally I have to run pactPublish every time before pactVerify, or delete the other pact files I don't want from the directory if I want to use the PactFolderLoader.

**Comment by pkubowicz** [comment]
PactUrlLoader can read single files. Just use file path as the URL, without any protocol.

**Comment by ekeoch** [comment]
Thanks for the response. Can we have the documentation updated to reflect this? Its just not intuitive at all.
