### ISSUE TITLE
Pact verification Junit via a pact broker: can communication problems be ignored?

### ISSUE THREAD

**Issue by mreno-EBSCO** [DiUS/pact-jvm#782]
Can we have an annotation, like `@IgnoreNoPactsToVerify`, to ignore communication problems with a pact broker or other problems such as missing pact broker config values (host/port/etc), such that the pact verification unit tests will not fail? We have situations where devs may not have access to the broker and we don't want this to cause their builds to fail.

Perhaps this could be an option to the `@PactBroker` annotation itself.

**Comment by uglyog** [comment]
I'll add it as an attribute to the annotation

**Comment by uglyog** [comment]
Added in 67b17f0b3a5a7
