### ISSUE TITLE
Stop mixing JUnit 4 with JUnit 5 for provider

### ISSUE THREAD

**Issue by pkubowicz** [DiUS/pact-jvm#783]
Currently pact-jvm-provider-junit5 depends on pact-jvm-provider-junit. As result anybody putting pact-jvm-provider-junit5 on classpath is also putting two conflicting JUnit versions.

Reason: there are some annotation classes shared between both subprojects.

Possible solutions:
- mark JUnit a `compileOnly` dependency
- extract classes common to those subprojects to an another project, like `pact-jvm-provider-junit-common`

**Comment by pkubowicz** [comment]
I can provide a pull request if you can state which approach you prefer.

**Comment by uglyog** [comment]
Just noticed you were the driver for the consumer fix :-D
