### ISSUE TITLE
unable to write Kotlin based Provider test

### ISSUE THREAD

**Issue by christian-draeger** [DiUS/pact-jvm#784]
I'm trying to write a kotlin based Provider test like this:

```kotlin
@RunWith(SpringRestPactRunner::class)
@Provider("user-data-provider")
@PactBroker(protocol = "http", host = "localhost", port = "8080")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class UserDataProviderContractIT {
    @TestTarget
    var target: Target = SpringBootHttpTarget()
}
```

It fails with 
`java.lang.RuntimeException: How did getFields return a field we couldn't access?
Caused by: java.lang.IllegalAccessException: Class org.junit.runners.model.FrameworkField can not access a member of class com.example.demo.UserDataProviderContractIT with modifiers "private"`

I tried to implement an Java example as well which works and looks like this:

```java
@RunWith(SpringRestPactRunner.class)
@Provider("user-data-provider")
@PactBroker(protocol = "http", host = "localhost", port = "8080")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class JavaUserDataProviderContractIT {

    @TestTarget
    public final Target target = new SpringBootHttpTarget();
}
```

You can find the example project here: https://github.com/christian-draeger/pact-example-kotlin
heres the Provider test written in kotlin: https://github.com/christian-draeger/pact-example-kotlin/blob/master/producer/src/test/kotlin/com/example/demo/UserDataProviderContractIT.kt

To reproduce just checkout the project and run `mvn clean verify`

**Comment by pkubowicz** [comment]
`@TestTarget` should be placed on a field. `val` and `var` in Kotlin create public accessor methods and a private field. You need to force Kotlin compiler to generate a public field:
```
    @TestTarget
    @JvmField
    final val target: Target = SpringBootHttpTarget()
```

**Comment by christian-draeger** [comment]
that fixed it, thx
