### ISSUE TITLE
The ability to generalise what we expect from an array

### ISSUE THREAD

**Issue by mortenlj** [DiUS/pact-jvm#80]
I have registered this as an issue on pact-specification, but figured I'd raise it here aswell, as implementers of the specification might have something to say about it, and this is the implementation I'm using. :)

If you would prefer the discussion to conclude in the pact-specification-project before commenting on it, that's perfectly understandable.

Here's my issue at pact-specification:
https://github.com/bethesque/pact-specification/issues/14

**Comment by uglyog** [comment]
I would find this very useful too.

**Comment by uglyog** [comment]
This has finally been implemented. Yay! I've updated both the JUnit and Groovy DSLs to support this.

**Comment by mortenlj** [comment]
Nice! Thanks!

**Comment by bethesque** [comment]
:+1:
