### ISSUE TITLE
eachKeyMappedToAnArrayLike is broken in 3.5.23

### ISSUE THREAD

**Issue by ghost** [DiUS/pact-jvm#800]
The method now requires an exact match of the key, where it did not in the past. It's broken on the provider side, because I switched back to 3.5.21 in that project and the test passed.

Consumer side test:
`
@Pact(provider = "donuts-ws", consumer = "donuts-consumer")
    public RequestResponsePact getAllDonutsByFloorFragment(PactDslWithProvider builder) {

        DslPart body =
                new PactDslJsonBody()
                        .eachKeyMappedToAnArrayLike("6")
                        .stringType("description", "Hostess Fruit Pies")
                        .integerType("id", 14)
                        .stringType("creator", "Loren")
                        .integerType("quantity", 8)
                        .object("location")
                        .integerType("floor", 6)
                        .stringType("room", "south break room")
                        .closeObject();

        return builder.given("there are Hostess Fruit pies available")
                .uponReceiving("a request for all available snacks mapped by floor")
                .method("GET")
                .path("/donuts/byFloors")
                .willRespondWith()
                .status(200)
                .matchHeader("Content-Type", APPLICATION_JSON)
                .body(body)
                .toPact();
    }

    @Test
    @PactVerification(fragment = "getAllDonutsByFloorFragment")
    public void canRequestAllDonutsMappedByFloor() throws IOException {
        DonutsClient donutsClient = new DonutsClient(httpClient, moshi, mockProvider.getConfig().getHostname(), mockProvider.getPort());
        Map<String, List<Snack>> snacks = donutsClient.fetchAllSnacksMappedByFloor();

        assertThat(snacks, Matchers.hasKey("6"));
    }`

Provider side test:
`
@State("there are Hostess Fruit pies available")
    public void getSnacksMappedByFloor() {
        when(mockSnackDao.loadCurrentSnacks(any(LocalDateTime.class), any(), anyInt(), anyString(), anyString(), anyInt(), anyInt(), anyString()))
                .thenReturn(
                        Collections.singletonList(defaultSnack.setDescription("Hostess Fruit Pies").setLocation(new Location(7, "north break room")).build()));
    }`

Relevant pact file section:
` {
            "description": "a request for all available snacks mapped by floor",
            "request": {
                "method": "GET",
                "path": "/donuts/byFloors"
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json"
                },
                "body": {
                    "6": [
                        {
                            "creator": "Loren",
                            "quantity": 8,
                            "description": "Hostess Fruit Pies",
                            "location": {
                                "floor": 6,
                                "room": "south break room"
                            },
                            "id": 14
                        }
                    ]
                },
                "matchingRules": {
                    "header": {
                        "Content-Type": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "application/json"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "body": {
                        "$.*": {
                            "matchers": [
                                {
                                    "match": "type",
                                    "min": 0
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].description": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].id": {
                            "matchers": [
                                {
                                    "match": "integer"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].creator": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].quantity": {
                            "matchers": [
                                {
                                    "match": "integer"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].location.floor": {
                            "matchers": [
                                {
                                    "match": "integer"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.*[*].location.room": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "there are Hostess Fruit pies available"
                }
            ]
        }`

With the current version of Pact, the provider side test passes if I make the location floor 6 and fails if I make it floor 7.

Let me know if you need any more of my code.

**Comment by uglyog** [comment]
Could you provide the debug logs of the failing provider test?

**Comment by LoraVolkert** [comment]
Of course, sorry! And again, I'll note that this passes with 3.5.21.

`donuts-consumer-java - a request for all available snacks mapped by floor(com.clearwateranalytics.pact.DonutsConsumerPactTest)  Time elapsed: 0.16 s  <<< FAILURE!
java.lang.AssertionError: 

0 - $ -> [{mismatch=Expected 6=List(Map(quantity -> 8, location -> Map(floor -> 6, room -> south break room), description -> Hostess Fruit Pies, creator -> Loren, id -> 14)) but was missing, diff={
-    "6": [
+    "7": [
        {
-            "quantity": 8,
+            "quantity": 1,
            "location": {
-                "floor": 6,
-                "room": "south break room"
+                "floor": 7,
+                "room": "north break room"
            },
+            "lastModified": "2018-11-05T13:59:23.926",
            "description": "Hostess Fruit Pies",
-            "creator": "Loren",
-            "id": 14
+            "creator": "loren",
+            "id": 1,
+            "created": "2018-11-05T13:59:23.923"
        }}]


Results:

Failures: 
  DonutsConsumerPactTest.donuts-consumer-java - a request for all available snacks mapped by floor 
0 - $ -> [{mismatch=Expected 6=List(Map(quantity -> 8, location -> Map(floor -> 6, room -> south break room), description -> Hostess Fruit Pies, creator -> Loren, id -> 14)) but was missing, diff={
-    "6": [
+    "7": [
        {
-            "quantity": 8,
+            "quantity": 1,
            "location": {
-                "floor": 6,
-                "room": "south break room"
+                "floor": 7,
+                "room": "north break room"
            },
+            "lastModified": "2018-11-05T13:59:23.926",
            "description": "Hostess Fruit Pies",
-            "creator": "Loren",
-            "id": 14
+            "creator": "loren",
+            "id": 1,
+            "created": "2018-11-05T13:59:23.923"
        }}]`

**Comment by uglyog** [comment]
Due to issue #759 I had to disable the wild card matching by default. There is a Java system property you can use to enable it: `pact.matching.wildcard`. Just set it to `true`.

**Comment by LoraVolkert** [comment]
Hmm. I have already changed the test in question to not use that method (as a workaround, but I probably won't change it back), and I'm generally encouraging people to use the lambda library, which does not have an equivalent to it. In order to use the java system property, I would need to make sure it was set that way in our Jenkins builds, and I don't know that I want to do that by default since, based on the other case you tagged, there's potential it could break other tests. I feel this method was always kind of a poor man's version of the regex keys I requested a while back anyhow. So I think I'm just going to tell people to avoid this method. 

My main concern is that we had no warning that the internal logic had changed. We had tests that were already written using this method that were passing on old versions of pact and started breaking on new versions because we didn't know we needed this system property all of a sudden. I'm trying to get more people to start using Pact at our company, but it doesn't help when the library doesn't maintain backwards compatibility.

Maybe you should deprecate the method? At least that would provide some warning to people.

**Comment by uglyog** [comment]
Sorry, I thought it was documented in the release notes. It was documented in https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#matching-any-key-in-a-map-331250 (see further notes section).
