### ISSUE TITLE
Non-idiomatic Kotlin experience with pact-jvm-consumer-java8

### ISSUE THREAD

**Issue by pkubowicz** [DiUS/pact-jvm#803]
When I want to use pact-jvm-consumer-java8 in Kotlin I cannot write:
```
newJsonArray { array -> array.object { o -> o.stringValue("foo", "Foo") } }
```
because 'object' is an reserved word in Kotlin. Escaping makes the DSL usage a bit clumsy:
```
newJsonArray { array -> array.`object` { o -> o.stringValue("foo", "Foo") } }
```

Escaping can be avoided by adding an extension method:
```
fun LambdaDslJsonArray.newObject(o: (LambdaDslObject) -> (Unit)): LambdaDslJsonArray {
    return this.`object`(o)
}
```

```
newJsonArray { array -> array.newObject { o -> o.stringValue("foo", "Foo") } }
```

Since pact-jvm is already heavy dependent on Kotlin, I don't see a need for creating a separate JAR with Kotlin extensions/API. The above extension could be packaged inside pact-jvm-consumer-java8.

I could provide a pull request.

**Comment by uglyog** [comment]
Good idea. PR more than welcome.
