### ISSUE TITLE
Pact keeps outdated interactions in contract JSON 

### ISSUE THREAD

**Issue by pkubowicz** [DiUS/pact-jvm#804]
See reproduction steps from https://github.com/pkubowicz/pact-merge

I remove an old interaction and define a new one - with a new description, new endpoint, new expected answer. However, the contract JSON on my disk does not reflect what I have in my test - it keeps the removed interaction.

As a workaround, I always clean pact directory to prevent Pact from doing strange things with already existing files:
```
test {
    doFirst {
        delete pactOutputDir
    }
}
```

This however has negative performance implications for Gradle, as described in https://github.com/gradle/gradle/issues/6864#issuecomment-423837703

Can this strange 'merging' be fixed as a bug, or can I have a system property to disable it?

**Comment by uglyog** [comment]
Unfortunately, a lot of people split their tests up over multiple test classes. This is why the pacts get merged into one file. See the thread on #522 for more info.

My recommendation is to put the directory the pact files get written to into the build directory, and then issue a clean before running the tests.

**Comment by uglyog** [comment]
We could add a property to force overwriting the pact files. The Ruby implementation has something like this.

**Comment by vinogradoff** [comment]
I would vote for a switch or annotation forcing overriding of the pact file. It's very easy to leave "slightly" outdate interaction (renamed a bit) and then spend hours deciphering why the tests are actually failing.

**Comment by uglyog** [comment]
Setting the Java system property `pact.writer.overwrite` to `true` will now force overwriting the file.

**Comment by vinogradoff** [comment]
@uglyog when do you plan to release it?

**Comment by uglyog** [comment]
Version 3.6.5 has been released
