### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by mdjnewman** [DiUS/pact-jvm#81]
I'm having issues with tests failing when `gradlew build` is run on Windows, but the same runs fine on OS X. The following is what happens on the Windows machines I've tried it on:
```
:pact-jvm-consumer_2.10:test

au.com.dius.pact.consumer.MockProviderSpec > Pact Mock Service Provider should::Respond to invalid and valid requests FAILED
    org.specs2.reporter.JUnitReporter$$anon$1

2 tests completed, 1 failed
:pact-jvm-consumer_2.10:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pact-jvm-consumer_2.10:test'.
> There were failing tests. See the report at: file:///C:/Dev/src/pact-jvm/pact-jvm-consumer/build/2.10/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 3.768 secs
```

The test output shows:
```
org.specs2.reporter.JUnitReporter$$anon$1: 'Some({
  "test" : true
})' is not equal to 'Some({
  "test" : true
})' expected:<Some({[
  "test" : true
]
})> but was:<Some({[
  "test" : true]
})>
	at au.com.dius.pact.consumer.MockProviderSpec$$anonfun$3$$anonfun$apply$5.compareRequests$1(MockProviderSpec.scala:65)
	at au.com.dius.pact.consumer.MockProviderSpec$$anonfun$3$$anonfun$apply$5.apply(MockProviderSpec.scala:83)
	at au.com.dius.pact.consumer.MockProviderSpec$$anonfun$3$$anonfun$apply$5.apply(MockProviderSpec.scala:35)
```

I've tried ignoring this test temporarily but there are some others that fail as well (in GitOpsSpec from memory).

Any ideas? :)

**Comment by uglyog** [comment]
I've actually never run it on windows, so it is more than likely that it won't work. Hopefully, it does not take too much effort to fix.

**Comment by uglyog** [comment]
I've setup a Windows 7 VM to test the build on. What version of Windows did you use?

**Comment by mdjnewman** [comment]
Windows 7 Professional, is it all working on your VM?

**Comment by uglyog** [comment]
No, I have the same issues as you. Just wanted to make sure I was using the same version. But I'll also check with Windows 8.1

**Comment by uglyog** [comment]
I have no idea what GitOpsSpec (and GitOps) are for. I'm assuming the author was trying to have pacts published via git, but as this is not used anywhere, it should be safe to delete.

**Comment by uglyog** [comment]
Build passes on my VM now

**Comment by mdjnewman** [comment]
All working for me too! :)
