### ISSUE TITLE
[Question] How can I add InputStream into request body for RequestResponsePact?

### ISSUE THREAD

**Issue by shailesh-waman** [DiUS/pact-jvm#810]
Hello There,

I am trying to write a pact test using `au.com.dius:pact-jvm-consumer-junit_2.11:3.5.24` and expected behaviour is to upload a zip file using http method PUT for a rest service

following is the request expected to be -

```
.method(HttpMethod.PUT.name)
.matchHeader(HttpHeaders.AUTHORIZATION, BEARER_REG_EX, "Bearer $VALID_TOKEN")
.matchHeader(HttpHeaders.CONTENT_TYPE, APPLICATION_OCTET_STREAM_VALUE)
.matchHeader(MD5_HEADER_KEY, VALID_MD5_DIGEST)
.body(temporaryFile.readBytes().toString(), APPLICATION_OCTET_STREAM_VALUE) // not sure about setting up body?
.willRespondWith()
.status(HttpStatus.OK.value())
.toPact()
```

I am not sure how to set `body` in this pact test, can you please guide me?

`temporaryFile` could be any zip file contains archived files and it is not zero bytes

Please let me know incase any additional information to help me out

Thank you!

**Comment by uglyog** [comment]
Have a look at [ExampleFileUploadSpec.groovy](https://github.com/DiUS/pact-jvm/blob/4106422f4b5ade4a63c5662818defc0a71f99473/pact-jvm-consumer-junit/src/test/groovy/au/com/dius/pact/consumer/junit/ExampleFileUploadSpec.groovy)
