### ISSUE TITLE
pact verification problem when upgrading from 3.5.21 -> 3.5.24

### ISSUE THREAD

**Issue by abendt** [DiUS/pact-jvm#814]
we have a AMQP Message test.
while trying to upgrade from 3.5.21 -> 3.5.24 we get some new verification errors.

in the message payload we have some maps that contain a varying number of entries:
``` 
 "offer": {
    "prices": {
      "DE": 1620,
      "AT": 1620
    },
    "costs": {
      "DE": {
        "abc": 300,
        "def": 300
      },
...
```

we are not interested in the actual values, only the types need to match (String -> Number)

the matching rule from the pact file:
```
         "$.offer.prices.*": {
            "matchers": [
              {
                "match": "type"
              }
            ],
            "combine": "AND"
          },
          "$.offer.costs.*": {
            "matchers": [
              {
                "match": "type"
              }
            ],
            "combine": "AND"
          }
```

while using Pact 3.5.21 (pact-jvm-provider-junit_2.12) on the provider side we were able to verify the pact by using the following response where the actual values would differ from the pact, but had the same type:

```
"offer": {
    "prices": {
      "0": 1000,
```

now while trying to upgrade to 3.5.24 we get a verification error:

```
0) an event generates a message which has a matching body
      $.offer.prices -> Expected DE=1620 but was missing

        Diff:

        {
        -    "DE": 1620
        +    "0": 1000
        }

```

**Comment by abendt** [comment]
also happens with 3.6.0 rc1

**Comment by uglyog** [comment]
Can you set the JVM property `pact.matching.wildcard` to `true`. See #800 for more info.
