### ISSUE TITLE
Publish verification results to pact broker is not working in pact-jvm-provider-spring_2.12

### ISSUE THREAD

**Issue by yoka791** [DiUS/pact-jvm#815]
Hi,
I am trying to publish the verification results to pact broker with pact for jvm/spring.
I am using junit4.
The test is executed and passed, A verification report is printed to console/ json file is added, but it's not publishing the results to pact broker.

In pom.xml:

    <dependency>
        <groupId>au.com.dius</groupId>
        <artifactId>pact-jvm-provider-spring_2.12</artifactId>
        <version>3.5.24</version>
    </dependency>

In TestContract.class:

    @RunWith(SpringRestPactRunner.class)
    @Provider("prov_test")
    @PactBroker(host="192.168.132.220",port="80")
    @VerificationReports({"console", "json"})
    @SpringBootTest(
        properties={
            "pact.provider.version=1.0.1",
            "pact.verifier.publishResults=true"
        },
        webEnvironment = SpringBootTest.webEnvironment.DEFINED_PORT
    )
    public class TestContract {
    ...
    ...
    }

In the output I get the warnning:

    Skipping publishing of verification results (pact.verifier.publishResults is not set to 'true')
Thanks for your help!

**Comment by cosmin-mogos** [comment]
Publishing works for me if I add `-Dpact.verifier.publishResults=true` in the JVM parameters used to run the unit test.

**Comment by uglyog** [comment]
`@SpringBootTest` properties is probably setting Spring properties, not JVM system properties. See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#plugin-properties for more info on setting JVM properties.

**Comment by leonleo997** [comment]
Hello, could you please share again the link. It's broken

**Comment by uglyog** [comment]
Here is the correct link: https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-maven#plugin-properties

**Comment by Norman-else** [comment]
@uglyog This link still not found: 404 error.

**Comment by anto-ac** [comment]
https://github.com/DiUS/pact-jvm/blob/master/provider/maven/README.md#plugin-properties
