### ISSUE TITLE
Question: publishing consumer contracts when consumer tests fails

### ISSUE THREAD

**Issue by cosmin-mogos** [DiUS/pact-jvm#816]
In my consumer tests I use the pattern listed below. I have noticed that unless there is a successful interaction for the fragment test (`test()`) the contract is not saved in the generated pact file.

1) Is it possible to publish contracts before the consumer tests pass? This can be useful for initial development, so the producer can see the interactions as fast as possible even if not yet implement consumer side.
2) Is it possible to fail the tests if one fragment has not been used in any test? Useful to validate that all expectations are actually tested, it could be that devs have forgotten to add one test.

```public class Test {

  @Rule
  public PactProviderRuleMk2 mockProvider =
      new PactProviderRuleMk2("provider", "localhost", null, this);

...

@Pact(consumer = "consumer", provider = "provider")
  public RequestResponsePact myfragment(PactDslWithProvider builder) {
    return builder
        .given("default")
        .uponReceiving("a request")
        .path("/apath")
        .method("POST")
        .headers(
            ImmutableMap.<String, String>builder()
                .put("Content-Type", "application/json;charset=UTF-8")
                .build()
        )
        .body("{}")
        .willRespondWith()
        .status(200)
        .headers(
            ImmutableMap.<String, String>builder()
                .put("Content-Type", "application/json;charset=UTF-8")
                .build()
        )
        .body("{\n"
            + "  \"id\": 321\n"
            + "}")
        .toPact();
  }

...

  @Test
  @PactVerification(fragment = "myfragment")
  public void test() {
     // test body
  }
```

**Comment by uglyog** [comment]
We have a dilemma with this. If there is an actual breaking change (for instance, the expectations are different to the actual consumer behaviour), but the contract is still generated and published then the failure could go unnoticed and cause a failure when the components are deployed. The provider could be deployed because it is verified against the contact, but then when run against the actual consumer it will break. It feels like a dangerous option to have.

As to point 2, that makes sense.

**Comment by uglyog** [comment]
I was able to add the check to the JUnit 5 module to fail if there are `@Pact` methods that were not called during the test execution. JUnit 4 support for this is not that trivial.
