### ISSUE TITLE
Please support publishing verification results to a pactbroker in pact-jvm-provider

### ISSUE THREAD

**Issue by ghost** [DiUS/pact-jvm#818]
Currently, pact-jvm-provider-junit has nice integration with publishing pact test results to the pactbroker on the provider side via annotations. However, if you're using clojure, for instance, the pact-jvm-provider library without those annotations is the way to go. There isn't much for working with the pactbroker in that library that I can see, however. My current workaround for fetching tests from the pactbroker is using `(.setPactSource (UrlSource. "http://{pactbroker-url}/pacts/provider/{provider-name}/consumer/{consumer-name}/latest/trunk"))`. Not the greatest for running multiple tagged versions of a pact against your provider, but at least it's a reasonable workaround. But I can't work out how to send my verification results to the pactbroker. It doesn't look like it's currently supported in this sub-library.

**Comment by LoraVolkert** [comment]
Once we get this working, I'm going to plan on submitting a pull request with an example of how to write a provider-side pact test in Clojure. You have one on the consumer side, but I don't see one on the provider side.

**Comment by LoraV** [comment]
I'm combining my GitHub accounts and deleting the one I used to generate this case, but I'm still very interested in this issue.

**Comment by uglyog** [comment]
The class that publishes the test results is (DefaultVerificationReporter)[https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider/src/main/kotlin/au/com/dius/pact/provider/ProviderVerifier.kt#L47]. 

For an example of how it is used in the JUnit support library, see (InteractionRunner)[https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/main/kotlin/au/com/dius/pact/provider/junit/InteractionRunner.kt#L155]
