### ISSUE TITLE
Publishing pact files to a pact broker with pact-jvm-consumer-junit

### ISSUE THREAD

**Issue by yoka791** [DiUS/pact-jvm#822]
Hi,
I am trying to use pact-jvm-consumer-junit for my consumer (it uses junit/spring).
I want to publish the pact file to my pact broker during the CI.
I saw [here](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit#publishing-your-pact-files-to-a-pact-broker) that the only (am I correct?) option to upload a pact from the consumer side is to use a plugin named pact-jvm-provider-gradle. There, when I add the plugin in pom.xml I can set pact broker's url/tag etc..

    <dependencies>
    ..
        <dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-consumer-junit_2.12</artifactId>
            <version>3.5.24</version>
            <scope>test</scope>
        </dependency>

    ..
    </dependencies>

    <build>
        <plugins>
            ..
            <plugin>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-provider-maven_2.12</artifactId>
                <version>3.5.24</version>
                <configuration>
                    <pactBrokerUrl>http://192.168.132.220/</pactBrokerUrl>
                    <pactDirectory>${project.build.directory}/pacts</pactDirectory> 
                    <projectVersion>${project.version}</projectVersion> 
                    <tags>
                        <tag>feature/pact_test</tag>
                    </tags>
                    <trimSnapshot>true</trimSnapshot> 
                </configuration>
            </plugin>
            ..
        </plugins>
    </build>

But - I want to have an option to set those options during the build phase in the CI.
How can I do that?
Thanks.

**Comment by uglyog** [comment]
The Pact-JVM Maven plugin supports publishing pact files to a broker. See https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-provider-maven#publishing-pact-files-to-a-pact-broker

**Comment by uglyog** [comment]
@pawarsum use this URL https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-maven#publishing-pact-files-to-a-pact-broker

**Comment by pmajcher** [comment]
hi, I think this is current url
https://github.com/DiUS/pact-jvm/tree/master/provider/maven#publishing-pact-files-to-a-pact-broker

**Comment by jonrosner** [comment]
Why is this plugin in a group that contains `provider` (au.com.dius.pact.provider) when actually you need it to publish consumer contracts as well? This confused me quite a lot.
