### ISSUE TITLE
Consumer side: How do I make sure that all of the calls to providers are contract-tested?

### ISSUE THREAD

**Issue by yoka791** [DiUS/pact-jvm#825]
Hi,
I just wondered if their any way to ensure that all the API calls to providers or handling with provider's return data (like status codes) are contract-tested?
In other words - In unit tests I can use code coverage tool as a part of my pipeline and fail it in case there is no 100% coverage. How can I do something similar for the purpose of contract testing?

**Comment by madhukar93** [comment]
Depends on how your web-framework's API exposes all endpoints. Then some custom code can be written to check off endpoints that have been tested I expect.
