### ISSUE TITLE
SpringRestPactRunner does not call "TEARDOWN" State change method

### ISSUE THREAD

**Issue by RusmanCool** [DiUS/pact-jvm#834]
I am running Provider verification tests using SpringRestPactRunner. I have setup SETUP @State method that is executed; however, TEARDOWN method for the same state is not getting executed. My workaround is to use @After junit method.

**Comment by RusmanCool** [comment]
Hello,
 I am using 
```xml
<dependency>
<groupId>au.com.dius</groupId>
<artifactId>pact-jvm-provider-spring_2.12</artifactId>
<version>3.6.0</version>
<scope>test</scope>
</dependency>
```

**Comment by uglyog** [comment]
I am unable to replicate this issue. Have a look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-spring/src/test/groovy/au/com/dius/pact/provider/spring/SpringRunnerWithBeanThatMustBeClosedProperlyTest.groovy#L50, with my test the teardown method is being called. I verified it by setting a breakpoint in that method.

**Comment by RusmanCool** [comment]
@uglyog I am using pure Java language, not groovy. I will try again based on the example but that what I was doing already.

**Comment by kvajjala59** [comment]
Hi any updates on this? I'm using the latest 4.0.0 

testImplementation 'au.com.dius:pact-jvm-provider-spring:4.0.0'

And the TearDown is never called.

**Comment by uglyog** [comment]
@kvajjala59 is your test failing when the teardown method is not being called?

**Comment by uglyog** [comment]
This should be working now in the latest version (4.0.6)
