### ISSUE TITLE
Provide @PactFolder for consumer tests too

### ISSUE THREAD

**Issue by octopus-prime** [DiUS/pact-jvm#840]
For provider tests we can use `@PactFolder`.
For consumer tests we should be able to use this annotation too.

**Comment by uglyog** [comment]
The consumer test create the pact files, so what behaviour do you expect when using the `@PactFolder` annotation with a consumer test?

**Comment by octopus-prime** [comment]
I would expect:
The created pact files should be saved in the folder given by `@PactFolder`.

**Comment by uglyog** [comment]
We can't use the same annotation, as that is part of the provider packages. But we can create an equivalent one for consumer tests.

**Comment by uglyog** [comment]
This has been released with version 3.6.2
