### ISSUE TITLE
pact-messaging: Additonal field for destination (suggestion)?

### ISSUE THREAD

**Issue by schustes** [DiUS/pact-jvm#841]
It is actually an issue that I came over when trying to use a message-pact with Spring-Cloud-Contracts (scc). For scc, you have to provide a destination (queue or exchange). In pact there is no equivalent, the message-pact only cares about the contract. Although interoperability might not be a goal for pact, I think the idea to have the destination also as part of the contract sounds natural (similar as the endpoint is part of a rest contract). I do think the destination is part of a contract (like 'receiveing a message from destination x, I expect it to be a json with contents ...')

Is that an idea you would consider? Or do you have a suggestion where the message destination should be located in the message-pact file?

**Comment by uglyog** [comment]
Definitely. The pact message model supports a map of key-values in the metadata. The destination could be set there. There is already an issue #479 to request this.
