### ISSUE TITLE
ClassCastException during provider verification

### ISSUE THREAD

**Issue by amsuggs** [DiUS/pact-jvm#848]
When running my provider test, I am able to pull pacts down from the broker and being the verification but my tests alway fail due to `java.lang.classcastexception: class jdk.internal.loader.classloaders$appclassloader cannot be cast to class java.net.urlclassloader`

After some debugging, I saw that in `AmpqTestTarget` seems to be the source of the problem during `ProviderVerifier` setup

I found that `ClassLoader` cannot be cast to `URLClassLoader` as of java9, I am on java11.

**Comment by uglyog** [comment]
Can you try with the latest version (3.6.2), the cast was changed to an instance of check.
