### ISSUE TITLE
Multiple set-cookie headers are being ignored in verification

### ISSUE THREAD

**Issue by hkarabakla** [DiUS/pact-jvm#851]
When we set multiple set-cookie headers to response in provider side, pact framework doesn't verify them.

Example response :

 ```
HTTP/1.1 200 OK
 Server: Apigee-Edge
 Set-Cookie: JSESSIONID=alphabeta120394049; HttpOnly
 Set-Cookie: AWSELBID=baaadbeef6767676767690220; Path=/alpha
```

Pact framework only checks AWSELBID cookie, ignores JSESSIONID.

**Comment by uglyog** [comment]
Could you provide the pact file?

**Comment by uglyog** [comment]
No need for the pact file, I can reproduce the issue.

**Comment by uglyog** [comment]
Version 3.6.3 has been released with this fix
