### ISSUE TITLE
TestTemplateInvocationContextProvider preconditions error

### ISSUE THREAD

**Issue by vistiyos** [DiUS/pact-jvm#854]
Hello there,

I'm migrating from junit4 to junit5 so I'm following the instructions to use `pact-jvm-provider-junit5_2.12` but I'm stuck with the following error:

`org.junit.platform.commons.util.PreconditionViolationException: You must register at least one TestTemplateInvocationContextProvider that supports @TestTemplate method`

but my class looks like the following:
```
import au.com.dius.pact.provider.junit5.*;
/**
 * Superclass for all provider contract tests.
 */
public class ProviderContractTest {

	@LocalServerPort
	private int port;

	@TestTemplate
	@ExtendWith(PactVerificationInvocationContextProvider.class)
	void pactVerificationTestTemplate(PactVerificationContext context) {
		context.verifyInteraction();
	}

	@BeforeEach
	public void setup(PactVerificationContext context) {
		context.setTarget(new HttpTestTarget("localhost", this.port, "/"));
	}
...
}
```
As far I can see everything is set up at it should but I'm still getting error. An additional comment is that I have migrated other service and we have a class that looks like the one above and the tests pass.

Any help would be really appreaciated.

**Comment by vistiyos** [comment]
Finally I managed to solved, my problem was the non-working class was not abstract however the one that works it is abstract.

**Comment by retsedoc** [comment]
I had a similar issue today. Spent a few hours on this. Turns out the @Test annotation had imported 
this -> import org.apache.camel.test.junit5.params.Test;
instead of ->import org.junit.jupiter.api.Test;
mvn dependency analysis, online searches nothing helped. dang

**Comment by naturzukunft** [comment]
> I had a similar issue today. Spent a few hours on this. Turns out the @test annotation had imported this -> import org.apache.camel.test.junit5.params.Test; instead of ->import org.junit.jupiter.api.Test; mvn dependency analysis, online searches nothing helped. dang

You saved my day !
