### ISSUE TITLE
provider junit5 does not report failed results to pact broker

### ISSUE THREAD

**Issue by czterocyty** [DiUS/pact-jvm#858]
Hi,

I use `au.com.dius:pact-jvm-provider-junit5_2.12:3.6.2` to run provider tests against pact broker. My interaction is of messaging type. Then I use publishing verification results back to pact broker.

When my provider tests adhere to the contract - the verification result is sent to broker. However if I spoil my test - the provider build breaks, due to test failures but no failing verification result is sent to broker. Is it intended?

From the pact source code, I found that it reports only successful responses:

https://github.com/DiUS/pact-jvm/blob/3d00fe492722c96557e775d7074112bf8f367540/pact-jvm-provider-junit5/src/main/kotlin/au/com/dius/pact/provider/junit5/TestResultAccumulator.kt#L33

Great job by the way!

**Comment by uglyog** [comment]
This fix has been released with version 3.6.4
