### ISSUE TITLE
[pact-jvm-consumer-junit5] OverlappingFileLockException when running tests in parallel

### ISSUE THREAD

**Issue by SchulteMarkus** [DiUS/pact-jvm#861]
This is a bug report related to au.com.dius:pact-jvm-consumer-junit5_2.12:3.6.2

I wanted to speed up my tests using the [JUnit jupiter feature "parallel execution"](https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution).
Doing so, normally succeeding Pact-tests end up in OverlappingFileLockException.

I have created the repository https://github.com/SchulteMarkus/pact-jvm-consumer-parallel-junit5-OverlappingFileLockException which demonstrates this issue / can be used for reproduction.

**Comment by uglyog** [comment]
Version 3.6.3 has been released with this fix

**Comment by SchulteMarkus** [comment]
This helps indeed.
