### ISSUE TITLE
When specifying TAG to verify against, the gradle plugin or/and the pact broker verify against all TAGs

### ISSUE THREAD

**Issue by evdjoint** [DiUS/pact-jvm#864]
I am using the gradle plugin to verify my provider against any pacts that are declared against it. The plugin is declared as:

> plugins {
>    id "au.com.dius.pact" version "3.5.24" 
> }

Then it is configured as:

>     pact {
>         serviceProviders {
>             'example-provider' {
>                 hasPactsFromPactBrokerWithTag("https://myBroker.com/", "master", authentication: ['Basic', myPactBrokerUser, myPactBrokerPassword])
>                 project.version = "1.0"
>             }
>         }
>     }

The above should retrieve all pacts declared with "example-provider" as the provider, and should filter only ones flagged with "master" tag. At the time when I execute the pactVerify gradle task, my pact broker has single consumer, which has published 2 pacts. One with with tag 'master' and one with tag 'DEV':

![image](https://user-images.githubusercontent.com/5751719/54031528-ed1d2e80-41a6-11e9-872b-04adb7d6ae46.png)

Upon executing the gradle task I get this: 

![image](https://user-images.githubusercontent.com/5751719/54031413-9152a580-41a6-11e9-999c-1432ae004997.png)

My issue/question is, why does the verification verify against both tags?

**Comment by uglyog** [comment]
I think this might be an issue with the pact broker UI showing the verification result against all versions. 
@bethesque ?

**Comment by bethesque** [comment]
It's because the content of both the pacts must be the same. When you verify one, the verification is also attached to the other. https://docs.pact.io/getting_started/versioning_in_the_pact_broker#provider-application-versions
