### ISSUE TITLE
"pactSpecification" not compatible with Provider verification JUnit 

### ISSUE THREAD

**Issue by nheitz** [DiUS/pact-jvm#869]
I hope this is quite straightforward to explain.

Using the pact jvm framework, a "Consumer" is generating the following json fragment in the pact file:

    "metadata": {
        "pactSpecification": {
        "version": "3.0.0"
     },
     "pact-jvm": {
        "version": "3.6.3"
      }
    }

However, on the Provider side, when using a junit test to do provider verification, the following groovy code (au.com.dist.pact.model.PactReader) exists when loading the pact:

    def version = '2.0.0'
    def specification = pactInfo.first.metadata?.'pact-specification'
    if (specification instanceof Map && specification.version) {
      version = specification.version
    }
    if (version == '3.0') {
        version = '3.0.0'
    }
    def specVersion = Version.valueOf(version)
    switch (specVersion.majorVersion) {
        case 3:
            return loadV3Pact(pactInfo.second, pactInfo.first)
        default:
            return loadV2Pact(pactInfo.second, pactInfo.first)
    }

As a result of the case mismatch in "pactSpecification" vs "pact-specification", the V3 loader never gets used, and critical features like "@State" callbacks don't get triggered properly.

**Comment by uglyog** [comment]
Please use at least version `3.5.20` on the provider side, that was fixed in that version.

**Comment by nheitz** [comment]
I was experiencing the bug in version 3.6.3 of the provider. Perhaps this is a regression?

**Comment by nheitz** [comment]
The latest codebase still had this logic, and the consumer output above was also generated by 3.6.3.

https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/groovy/au/com/dius/pact/model/PactReader.groovy

**Comment by uglyog** [comment]
The code you posted above is not from 3.6.3. Check https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-model/src/main/groovy/au/com/dius/pact/model/PactReader.groovy#L31 it first looks for `pactSpecification` and then `pact-specification`

**Comment by nheitz** [comment]
Wow. I swear that code changed between one view and another. My apologies. I will retest, although I am specifying 3.6.3 in gradle.
