### ISSUE TITLE
Provider tests not properly treating eachKeyLike matchingRules

### ISSUE THREAD

**Issue by JIGH** [DiUS/pact-jvm#870]
The issue is coming from pact-jvm-provider-junit_2.12  3.5.22 since it exists there
while the issue doesn't exist on 3.5.21

In the body response I will have something like the below, where both SERVICE_NAME_PORT and 12345 can change.
"ports": {
   "SERVICE_NAME_PORT": "12345"
}

I used in the consumer test:

.object("ports")
.eachKeyLike("SERVICE_NAME_PORT",PactDslJsonRootValue.stringType())
.closeObject()

which generated a pact

"body": [
   {
       "ports": {
           "SERVICE_NAME_PORT": "string"
       },
   }
],
"matchingRules": {
   "$.body[0].ports.*": {
       "match": "type"
   }
}

Yet the provider tests are failing with

0) test returns a response which has a matching body
     $.0.ports -> Expected SERVICE_NAME_PORT='string' but was missing

       Diff:

       {
       -    "SERVICE_NAME_PORT": "string"
       +    "MY_SERVICE_NAME_PORT": "10001"
       }

**Comment by uglyog** [comment]
You need to set the system property value `pact.matching.wildcard` to `true` when running the provider tests.
