### ISSUE TITLE
Inconsistent behaviour of publish verifier results

### ISSUE THREAD

**Issue by hendychua** [DiUS/pact-jvm#872]
Hi,

I've observed an inconsistent behaviour when publishing verification results. My project setup is as follows:
- Using `au.com.dius:pact-jvm-provider-junit_2.11:3.5.24`.
- Running local pact broker using the provided docker-compose file for testing.
- Not setting `pact.verifier.publishResults`.
- Not using pact's maven plugin.

Test class:
```
@ContextConfiguration
@RunWith(PactRunner.class)
@Provider("provider")
@PactBroker(host = "localhost", port = "80")
@SpringBootTest(...)
public class ProviderTest {
...
}
```
**Scenario 1:**
```
// Annotations
public class ProviderTest {
  @State("test something")
  public void testSomething() {
    // something that will make the test pass
  }
}
```
My test passes and results are not published to the broker as expected because I did not set `pact.verifier.publishResults` to `true`. ✅ 

**Scenario 2:**
```
// Annotations
public class ProviderTest {
  @State("test something")
  public void testSomething() {
    // something that will make the test fail
  }
}
```
My test fails and results are not published to the broker as expected because I did not set `pact.verifier.publishResults` to `true`. ✅ 

**Scenario 3:**
```
// Annotations
public class ProviderTest {
  // Completely remove the test state.
}
```
My test fails with `MissingStateChangeMethod: Did not find a test class method annotated with @State("test something")` **but** results are still published to pact broker despite not setting `pact.verifier.publishResults`. ❌ 

My understanding of `pact.verifier.publishResults` is that only when this is set to true will results be published to the broker. Does this not apply to the case of missing test states? Is there a documentation for this?

**Comment by uglyog** [comment]
Results should never be published if `pact.verifier.publishResults` is not set correctly.

**Comment by uglyog** [comment]
3.5.25 has been released with this fix

**Comment by hendychua** [comment]
Thank you!
