### ISSUE TITLE
pact for multiple setCookie Headers

### ISSUE THREAD

**Issue by benwilkes9** [DiUS/pact-jvm#873]
Hi,

We have a legacy API that is returning multiple Set-Cookie headers. e.g. (simplified)

```
Set-Cookie: someCookie=someValue; Path=/ 

Set-Cookie: someOtherCookie=someValue; Path=/ 

Set-Cookie: someThirdCookie=someValue; Path=/ 
```

These are set based on an input to the API. We would like to write a PACT test that verifies we get these headers set based off certain inputs, however we're struggling. 

If we use the matchHeader in Pact DSL, e.g.  

`.matchHeader("set-cookie", “someCookie=.*", "someCookie=someValue; Path=/")
.matchHeader("set-cookie", "someOtherCookie=.*", “someOtherCookie=someValue; Path=/”)
.matchHeader("set-cookie", "someThirdCookie=.*", "someThirdCookie=someValue; Path=/")
`

It only generates 1 value in the contract; the last one (someThirdCookie) 

`
 "matchingRules": {
                    "header": {
                        "set-cookie": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "someThirdCookie=.*"
                                }
                            ],
                            "combine": "AND"
                        },
                }
}
`

And the .setHeaders method is a Map  (i.e. 1 key)

Is this a known limitation or is there something I can do?  Thanks

**Comment by uglyog** [comment]
I've added a `matchSetCookie` method, so you will able to do

```java
        .matchSetCookie('someCookie', '.*', 'someValue; Path=/')
        .matchSetCookie('someOtherCookie', '.*', 'someValue; Path=/')
        .matchSetCookie('someThirdCookie', '.*', 'someValue; Path=/')
```

**Comment by uglyog** [comment]
Version 3.6.5 has been released
