### ISSUE TITLE
Feature: query parameter datetime pattern

### ISSUE THREAD

**Issue by dimovelev** [DiUS/pact-jvm#876]
currently I could not find a way to match query parameters against time formats. the alternative with regex is error prone and not sufficient. any plans to support this?

**Comment by uglyog** [comment]
What test framework are you using?

**Comment by uglyog** [comment]
Time formats are supported, there was just a regression with matching query parameters. I have fixed that issue. Are you asking about being able to apply matchers in the Java DSL?

**Comment by dimovelev** [comment]
Yes, I mean the java 8 DSL I use with junit4.

**Comment by uglyog** [comment]
I've updated the DSL, have a look at [QueryParameterMatchingTest](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/QueryParameterMatchingTest.java#L17) for an example.

**Comment by uglyog** [comment]
Released 3.6.7 with this change
