### ISSUE TITLE
Pact jvm consumer doesn't publish json values with "null"

### ISSUE THREAD

**Issue by oswaldquek** [DiUS/pact-jvm#877]
I upgraded the `pact-jvm-consumer-junit_2.12` library from version 3.6.2 to version 3.6.7 (https://github.com/alphagov/pay-publicapi/pull/468). This seems to have the effect of not publishing "null" values. for example, I had a pact (https://github.com/alphagov/pay-publicapi/blob/master/src/test/resources/pacts/publicapi-connector-get-payment-with-gateway-transaction-id.json#L63-L64) that defined the following:

```
          "settlement_summary": {
            "capture_submit_time": null,
            "captured_date": null
          }
```
However what gets published in 
```
"settlement_summary": {}
```
This causes matching to fail on the provider side if what the provider actually returns is
```
          "settlement_summary": {
            "capture_submit_time": null,
            "captured_date": null
          }
```
even both are equivalent.

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
