### ISSUE TITLE
encoding-problem with pact-jvm-consumer-junit5 3.6.x and windows

### ISSUE THREAD

**Issue by octopus-prime** [DiUS/pact-jvm#879]
lets have this code in the cdc-test
`
builder.uponReceiving("Request für ping")
`
note the umlaut 'ü'!

with version 3.5.x we find this in the generated pact-files (generates 1 interaction)
```
"description": "Request f\u00fcr ping",
```
does not change if re-running the cdc-tests

but with version 3.6.x we find this in the generated pact-files
1st execution of test (generates 1 interaction)
```
      "description": "Request fÃ¼r ping",
```
2nd execution of cdc-test (generates 2 interactions)
```
      "description": "Request fÃ¼r ping",
      "description": "Request fÃÂÃÂ¼r ping",
```
3rd execution of cdc-test (generates 3 interactions)
```
      "description": "Request fÃ¼r ping",
      "description": "Request fÃÂÃÂ¼r ping",
      "description": "Request fÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¼r ping",
```
and so on

**Comment by uglyog** [comment]
Confirmed with JUnit 4 test as well

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
