### ISSUE TITLE
Invalid `$.header.<...>` value for headers matching rule in V2.

### ISSUE THREAD

**Issue by skaggmannen** [DiUS/pact-jvm#882]
Hi,

I'm using `au.com.dius:pact-jvm-consumer-junit_2.12:3.6.7` to generate V2 pact files. These files fails to be properly consumed by the `pact-ruby-standalone` provider (used by [pact-go](https://github.com/pact-foundation/pact-go) among others).

It seems like `pact-ruby-standalone` expects the header matching rules to have the format `$.headers.<...>`, but `pact-jvm` generates them like `$.header.<...>` (notice the missing `s`).

This has been mentioned in the following issue: https://github.com/pact-foundation/pact-net/issues/184#issuecomment-460595883

Any chance this might get fixed in an upcoming release? Currently we're forced to manually edit all pact files, which is not sustainable.

**Comment by skaggmannen** [comment]
After looking at the pact specification I found the following: 

> The second element of the path is the http type that the matcher is applied to (e.g., $.body or $.header).

So it seems that pact-jvm is actually following the spec, and pact-ruby-standalone is not. I'll close this issue.

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
