### ISSUE TITLE
PactDslJsonRootValue as request body fails

### ISSUE THREAD

**Issue by sjcetx** [DiUS/pact-jvm#883]
I'm trying to use `PactDslJsonRootValue.stringType("\"example\"")` as the request body.
I believe this fails because the `PactDslRequestWithPath#body` method calling `toString` on the body parameter and `PactDslJsonRootValue` does not override `toString`.

The equivalent method in `PactDslResponse` explicitly deals with `PactDslJsonRootValue` and uses `parent.getBody().toString()` instead of `parent.toString()`.

Can you confirm if this is a bug or if my usage is incorrect?

Thanks.

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
