### ISSUE TITLE
[pact-jvm-provider-maven]  mvn pact:verify command  cannot detect pact files(No pact files were found for provider 'wProvider')

### ISSUE THREAD

**Issue by vasile21** [DiUS/pact-jvm#885]
I am using pact 3.6.7 and mvn pact:verify detects no pact files in <pactFileDirectory>, even tho I can run the test from Intellij without error.

Pom.xml set up:
`<plugin>
	<configuration>
        <groupId>au.com.dius</groupId>
        <artifactId>pact-jvm-provider-maven_2.12</artifactId>
        <version>3.6.7</version>
        <configuration>
            <serviceProviders>
                <serviceProvider>
                    <name>wProvider</name>
                    <protocol>http</protocol>
                    <host>http://localhost</host>
                    <port>80</port>
					<insecure>true</insecure>
                    <pactFileDirectory>/home/username/workspace/pactjava/projectName/pacts/</pactFileDirectory>
                </serviceProvider>
        </serviceProviders>
    </configuration>
</plugin>`

Console output:

> Loading pact files for provider wProvider from /home/username/workspace/pactjava/projectName/pacts/
>Found 0 pact files
>.......
>[ERROR] Failed to execute goal au.com.dius:pact-jvm-provider-maven_2.12:3.6.7:verify (default-cli) on project producer: No pact files were found for provider 'wProvider' -> [Help 1]

Pact file location: /home/username/workspace/pactjava/projectName/pacts/tConsumer-wProvider

  "provider": {
    "name": "wProvider"
  },
  "consumer": {
    "name": "tConsumer"
  },
......
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    },
    "pact-jvm": {
      "version": "3.6.7"
    }
  }

I someone experiencing this issue (mvn pact:verify not detecting the pact files for provider, but being able to run tests from IDE)?

Thanks :)

**Comment by vasile21** [comment]
Thanks :)

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix
