### ISSUE TITLE
Tag consumer version before publishing pacts

### ISSUE THREAD

**Issue by bethesque** [DiUS/pact-jvm#892]
The webhooks are not firing correctly because the tags have to belong on the consumer version before the pact is published.

The call to create the tag will auto create the relevant pacticipant.

**Comment by bethesque** [comment]
Related to https://github.com/pact-foundation/pact_broker/issues/270

**Comment by uglyog** [comment]
Version 3.6.8 has been released with this fix

**Comment by bethesque** [comment]
Thanks!
