### ISSUE TITLE
Error in provider verify DSL (stateChangeUrl = url(...))

### ISSUE THREAD

**Issue by abubics** [DiUS/pact-jvm#894]
tl;dr: class cast error thrown when using `stateChangeUrl = url('http://...')`

Plugin config: `{ id 'au.com.dius.pact' version '3.6.8' }`

From [Slack message](https://pact-foundation.slack.com/archives/C9UN99H24/p1560904683048200):
____

howdy, just setting up a gradle verify, following instructions on https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-gradle#using-a-state-change-url, but getting an unexpected error:
```
> Cannot cast object 'UrlSource(url=http://localhost:8080/pact-state-change, pact=null)'
with class 'au.com.dius.pact.model.UrlSource' to class 'java.net.URL'
```

My gradle file looks like
```
pact {
  serviceProviders {
    'app-api' {
      startProviderTask = startProvider
      terminateProviderTask = stopProvider

      hasPactWith('app-ui') {
        pactSource = file('pacts/app-ui-app-api.json')
        stateChangeUrl = url('http://localhost:8080/pact-state-change')
      }
    }
  }
}
```

**Comment by abubics** [comment]
Thanks to @TimothyJones for remembering we hit something like this before . . .

Moving `stateChangeUrl` outside of `hasPactWith` fixes it!

I'll try to make time for a docs PR.

**Comment by uglyog** [comment]
3.6.9 has been released with this fix
