### ISSUE TITLE
Extra $ in TypeMatcher when using a PactDslJsonObject as DslPart in object(String name, DslPart value)

### ISSUE THREAD

**Issue by gvaatstra** [DiUS/pact-jvm#895]
When I use a (closed) PctDslJsonBody as DslPart argument in the object method of PactDslJsonBody, I get an extra $ in the matcher in the generated contract. In this case for a Messaging contract.

**Using:**
pact-jvm-consumer-junit_2.12 - Version 3.6.2
pact-jvm-consumer-java8_2.12 - Version 3.6.2

**The contract:**
PactDslJsonBody body = new PactDslJsonBody();
        body.object("headers")
            .stringValue("bestandstype", "foo")
            .stringValue("Content-Type", "application/json")
            .closeObject();
        payload = new PactDslJsonBody();
        payload.stringValue("bestandstype", "foo")
               .stringValue("bestandsid", EXAMPLE_FOO_FILE_NAME)
               .closeObject();
        **_body.object("payload", payload);_**

**MatchingRule in the contract:**
```json
"matchingRules": {
                "body": {
                    "$.payload$.bestandsid": {
                        "matchers": [
                            {
                                "match": "type"
                            }
                        ],
                        "combine": "AND"
                    }
                }
            }
```

**Comment by uglyog** [comment]
3.6.9 has been released with this fix
