### ISSUE TITLE
Provider JVM doesn't execute states in the order they are specified

### ISSUE THREAD

**Issue by oswaldquek** [DiUS/pact-jvm#897]
Given I have a pact with multiple states, for example:
```
"providerStates": [
        {
          "name": "account exists",
          "params": {
            "account_id": "x
          }
        }, 
       {
          "name": "payment exists",
          "params": {
            "payment_id": "y"
          }
        }
      ]
```
they don't seem to be executed in order when run against the jvm provider. In this case the account would need to exist before a payment can exist as a payment is associated with an account.

**Comment by uglyog** [comment]
Could you provide some debug logs of the verification?

**Comment by uglyog** [comment]
Also, how are you running the verification (Gradle, Maven, JUnit, etc.) and how is the provider state being invoked (e.g, URL)?

**Comment by oswaldquek** [comment]
I'm using JVM version 3.6.10. The verification is run using JUnit, with the provider state being invoked via URL. There doesn't seem to be any logs in the JUnit output, only the error from my database about trying to insert a payment because the account doesn't exist.

**Comment by oswaldquek** [comment]
So I added another state:
```
      "providerStates": [
        {
          "name": "a gateway account with external id exists",
          "params": {
            "gateway_account_id": "9ddfcc27-acf5-43f9-92d5-52247540714c",
            "mandate_id": "test_mandate_id_xyz",
            "bank_mandate_reference": "410104",
            "unique_identifier": "MD1234"
          }
        },
        {
          "name": "a confirmed mandate exists",
          "params": {
            "gateway_account_id": "9ddfcc27-acf5-43f9-92d5-52247540714c",
            "mandate_id": "test_mandate_id_xyz",
            "bank_mandate_reference": "410104",
            "unique_identifier": "MD1234"
          }
        },
        {
          "name": "something else exists"
        }
      ]
```
and it seems "something else exists" gets hit first, followed by "a confirmed mandate exists", followed by "a gateway account with external id exists". so it seems they're being played in reverse order. I tried debugging to see where this happens but got lost.

**Comment by uglyog** [comment]
3.6.11 has been released with the fix

**Comment by oswaldquek** [comment]
I've tested this and can confirm its fixed. Thanks!
