### ISSUE TITLE
LambdaDsl - minimum occurrence of arrays

### ISSUE THREAD

**Issue by shefeequemohammed** [DiUS/pact-jvm#898]
final DslPart actualPactDsl = LambdaDsl.newJsonBody((bodyDsl) -> {
            bodyDsl
                    .stringType("id", "1")
                    .stringType("name","Dep 1")
                    .array("students",(stud) ->{
                        stud.object((s1->{
                            s1.stringType("id","1")
                               .stringType("firstName","John")
                               .stringType("lastName","Smith")
                               .numberType("age",21);
                        }));
                    });
student list in pact file will have only one member but the Provider might return more than one, I get the following log:-
java.lang.AssertionError: 
0 - $.students -> [{mismatch=Expected a List with 1 elements but received 2 elements, diff={
....}
How do I specify .minArrayLike or anything else in the above eg:?

**Comment by uglyog** [comment]
Use `eachLike` instead of `array`.

**Comment by shefeequemohammed** [comment]
Thank you @uglyog

final DslPart actualPactDsl = LambdaDsl.newJsonBody((bodyDsl) -> {
            bodyDsl
                    .stringType("id", "1")
                    .stringType("name","Dep 1")
                    .eachLike("students",(stud) ->{
                        stud
                            .stringType("id","1")
                               .stringType("firstName","John")
                               .stringType("lastName","Smith")
                               .numberType("age",21);

                    });

        })
                .build();

This worked for me :)
