### ISSUE TITLE
XmlBodyMatcher does not ignore unexpected elements

### ISSUE THREAD

**Issue by anddreiu** [DiUS/pact-jvm#899]
I am using pact-jvm-provider-junit_2.12 version 3.6.9 and I have a problem when verifying the matching rules on the provider side. I have an XML as request body and response body and I am trying to verify a specific field from the response, but there is a problem when the response contains more fields than what we expect, so the child element will have a different path.

I will try to explain what happens with the below example:

Actual response:
`
<note>
	<to>John</to>
	<from>Jane</from>
	<subject>Reminder</subject>
	<address>
		<firstName>John</firstName>
		<lastName>Doe</lastName>
		<street>Prince Street</street>
		<number>34</number>
		<city>Manchester</city>		
	</address>
</note>
`

Expected response:
`
<note>
	<to>John</to>
	<from>Jane</from>
	<subject>Reminder</subject>
	<address>
		<city>Manchester</city>		
	</address>
</note>
`

On the consumer side I am interested just in the city field, so I have the following matching rule in my pact file:
`
"$.note.*.address.*.city: {
	"matchers": [
		{
			"match": "equality"
		}
	],
	"combine": "AND"
}
`

But the problem is that everytime it takes the first child field
`
$.note.3.address.0.city -> Expected <firstName>John</firstName> to equal <city>Manchester</city>`

I am not sure if this is an issue or it's the expected behavior. Or is there another way to identify that element?

Thanks

**Comment by uglyog** [comment]
The current matching compares the elements in order. So for that to work, the `<city>` tag would have to be the first of the child tags and the rest would be ignored.

Maybe a better way would be to compare the tags in order by unique tag.

**Comment by anddreiu** [comment]
So there's no other way to identify `<city>` tag? I would need this because the consumer is not interested about the other child tags, it will use just this one.

**Comment by uglyog** [comment]
Well, there is now. I just implemented it.

**Comment by anddreiu** [comment]
Wow, you're a star! I can't wait for the next release!

Many thanks

**Comment by anddreiu** [comment]
Sorry if I'm rude, but do you know when a new version will be released with this feature ?

**Comment by uglyog** [comment]
Not rude, just demanding :-D 3.6.10 has been released

**Comment by anddreiu** [comment]
It looks like there is a regression in this version, some of the matching rules don't work for elements having attributes. For example, I have a field for year, having a regex:

`date['@year']":{"matchers":[{"match":"regex","regex":"\\d{4}"`

And the result is the following:

`date.@year -> Expected year='2050' but received 2023`

**Comment by anddreiu** [comment]
I think the equality matcher works ok, but type and regex not.

**Comment by uglyog** [comment]
I had to remove the intermediate indices (which imposed the order on the elements) to get it to match. So before the path would have been `a.0.b['@year']` which now becomes `a.b['@year']`
