### ISSUE TITLE
Pact published with empty body using gradle pactPublish task

### ISSUE THREAD

**Issue by diana-zaharia** [DiUS/pact-jvm#904]
I am using the gradle plugin to publish pacts but it uploads them with empty body, even though the pact json file also contains body specification.

![pact-published](https://user-images.githubusercontent.com/1020403/60654100-ff0c9680-9e53-11e9-99ce-da661aa06c9d.PNG)

Gradle task does not output any errors:
`> Task :pactPublish
Publishing 'Consumer-Provider.json' ... HTTP/1.1 201 Created
`

Attaching the pact file:
[Consumer-Provider.txt](https://github.com/DiUS/pact-jvm/files/3358488/Consumer-Provider.txt)

**Versions**: 
pact-jvm-provider-gradle 3.6.10

**Comment by uglyog** [comment]
It may just be the view in the Pact Broker that is wrong. Can you check the actual pact contents (via the HAL Browser)

**Comment by diana-zaharia** [comment]
Ah yes, you are right. In HAL browser the contract is displayed properly.
I investigated more on pact broker side and found my matching rules should've included array min size 1.
Thanks for your help!
