### ISSUE TITLE
Unable to set PactSpecVersion (junit5)

### ISSUE THREAD

**Issue by teunvdwijst** [DiUS/pact-jvm#905]
Hello all,

I'm currently writing Pact tests for a microservice we're creating. I'm writing tests using the JUnit5 plugin, and using this I'm writing tests for both Kafka events and REST calls. Because I'm doing both, I need to produce 2 Pact contracts, one with 
`"pactSpecification": {
      "version": "3.0.0"
    }` for the events.

and one with
`"pactSpecification": {
      "version": "2.0.0"
    }` for the REST calls.

However, i'm unable to specify the PactSpecVersion to V2 manually. And I need this one to be V2 to be handled by the pact broker properly.

Ways I've tried to set the version:

    @PactTestFor(providerName = "MyProvider", pactVersion = PactSpecVersion.V2)

or 

    private final HashMap PactMetaData = new HashMap<String, String>() {{
		put("pactSpecification", PactSpecVersion.V2.toString());
	}};
    contract.setMetadata(PactMetaData);

But whatever I do, the generated contract is version  3.0.0. I cannot seem to find any documentation on how to do this in the Junit package (I have seen many people using the `@Rule` annotation which isn't available in this package).

My test class looks roughly like this:

    @ExtendWith(PactConsumerTestExt.class)
    @PactTestFor(providerName = "MyProvider", pactVersion = PactSpecVersion.V2)
    @PactFolder("pacts")
    public class ProviderRestPactTest extends BaseConsumerRestPact {
    
    	private final String url = "/api/someurl";
    
    	@Pact(consumer = "MyConsumer", provider = "MyProvider")
    	public RequestResponsePact getRequest(PactDslWithProvider builder) {
    		PactDslJsonBody expectedResponse = new PactDslJsonBody()
    				.uuid("val1", "5a54d9ad-87f7-34c1-870c-8f05b9515d5a")
    				.uuid("val2", "617918a6-b819-11e8-96f8-529269fb1459")
    				.uuid("val2", "4a2bc1a3-baae-42fa-9c45-0680e819b4cb");
    
    		return builder.given("some senario")
    				.uponReceiving("a GET request")
    				.path(url)
    				.method(HttpMethod.GET.name())
    				.willRespondWith()
    				.status(HttpStatus.OK.value())
    				.headers(getDefaultMetadata()) // set content type
    				.body(expectedResponse)
    				.toPact();
    	}
    
    	@Test
    	@PactTestFor(pactMethod = "getRequest")
    	public void testgetRequest(MockServer mockServer) throws IOException {
    		//create expected response
    
    		JsonObject jsonBody = new JsonObject();
    		jsonBody.addProperty("val1", "5a54d9ad-87f7-34c1-870c-8f05b9515d5a");
    		jsonBody.addProperty("val2", "617918a6-b819-11e8-96f8-529269fb1459");
    		jsonBody.addProperty("val3", "4a2bc1a3-baae-42fa-9c45-0680e819b4cb");
    
    		HttpResponse httpResponse = callMockServerWithUrl(mockServer, url);
    
    		assertThat(httpResponse.getStatusLine().getStatusCode()).isEqualTo(200);
    		assertThat(IOUtils.toString(httpResponse.getEntity().getContent())).isEqualTo(jsonBody.toString());
    	}
    }

And my pom.xml:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion><artifactId>pact</artifactId>
        <description>
            A project to generate and verify the Pact contracts for HTTP REST calls and JMS Kafka events
        </description>
    	
    	<properties>
            <pact.version>4.0.0-beta.2</pact.version>
            <jupiter.version>5.3.1</jupiter.version>
        </properties>
    
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${jupiter.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
            </dependency>
            <dependency>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-consumer-junit5</artifactId>
                <version>${pact.version}</version>
            </dependency>
            <dependency>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-provider-junit5</artifactId>
                <version>${pact.version}</version>
            </dependency>
        </dependencies>
    	
    	<build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.22.0</version>
                </plugin>
            </plugins>
        </build>
    </project>

Thanks in advance.

**Comment by teunvdwijst** [comment]
I figured it out, I needed to put the `pactVersion = PactSpecVersion.V2` in the `@PactTestFor` annotation on the test function, not on the class.

I still think it could be usefull to add something about this to the documentation

**Comment by uglyog** [comment]
I worked out what is happening. The annotation has a default value of V3. So when you did not specify it on the method, it defaulted to V3 and overrode the value defined at the class level. It would have worked if you left the annotation off the method.

I'll update the annotation to default to null. That way we can detect if it has been assigned.

**Comment by dominic-jones** [comment]
Thanks for the fix, @uglyog ! 

Will this be fixed for 4.0.0 only? That's probably also fine for our case. I'll keep an eye out for a release.

**Comment by uglyog** [comment]
It was included in 3.6.12

**Comment by ZeinabAshjaei** [comment]
Hi,
I have the same issue now, using version 4.0.0-beta.5, the specversion is always V3. I tried it in class level,method level and both, But the spec version is not changing to any other version than 3.

**Comment by uglyog** [comment]
@ZeinabAshjaei I just checked master, and it definitely works. I changed this line in the test https://github.com/DiUS/pact-jvm/blob/master/consumer/pact-jvm-consumer-junit5/src/test/java/au/com/dius/pact/consumer/junit5/ArticlesTest.java#L24 ro have `@PactTestFor(providerName = "ArticlesProvider", port = "1234", pactVersion = PactSpecVersion.V2)` and I got a V2 pact generated.
