### ISSUE TITLE
Merging pact spec versions via PactTestFor annotations behaviour is unexpected

### ISSUE THREAD

**Issue by dominic-jones** [DiUS/pact-jvm#907]
We are attempting to use V2 of the pact-spec api with the latest versions of pact-jvm (3.6.10).

Simple annotating a class with `PactTestFor(..., pactVersion = V2)` should be sufficient, however the annotation defaults to V3. Test methods also require PactTestFor, and overwrite the manually specified V2 definition. 

There is code in `PactConsumerTestExt#lookupProviderInfo` that merges class/method annotations. Specifically, in `ProviderInfo#merge` this line `pactVersion = pactVersion ?: other.pactVersion,` again, appears to do what I want. However the conditional is only valid if `methodAnnotation.pactVersion` is null (which it never is due to defaulting).

That leads to a situation where 
```
@PactTestFor(..., pactVersion = V2)
class Foo {
@PactTestFor(pactMethod = "someMethod")
fun test { ... }
}
```

Leads to the V2 on the class being ignored with the default respecified at the method level.

**Comment by uglyog** [comment]
Fixed as part of #905
