### ISSUE TITLE
Pact Consumer 4.0.0-beta.3 generating numberValue as object instead of primitive 

### ISSUE THREAD

**Issue by xCoBaLTz** [DiUS/pact-jvm#908]
When building the consumer pact file with 4.0.0-beta.3, using the LambdaDSL, I noticed that it converts NumberValue to a Object with a value attribute containing the number expected instead of just expecting the number itself.

Expected Value:
`{
    "number": 1
}`

Actual Value:
`{
   "number":  {
       "value":  1
   }
}`

The code block I am referring to is the following:
`LambdaDsl.newJsonBody(o -> o.numberValue("number", 1)).build()`

This belongs to the pact-jvm-consumer-java8 artifact. This was not the case in 4.0.0-beta.2, and was working as expected. 

If this is an expected behaviour going forward, would it be possible to add another method in the LambdaDSL package to support such a case.

**Comment by uglyog** [comment]
I am unable to replicate this. The following code passes when run against the current master.

```java
        DslPart dslPart = LambdaDsl.newJsonBody(o -> o.numberValue("number", 1)).build();
        assertThat(dslPart.getBody().toString(), is("{\"number\":1}"));
```

**Comment by igordezky-blackberyy** [comment]
With 4.0.0-beta, when the map returned from Interaction.toMap() is serialized the type is a Number. The default gson serialization of Number is { "value": <value> }. This can be addressed using registerTypeHierarchyAdapter(Number.class, ...) to provide custom serialization.

**Comment by uglyog** [comment]
4.0.0-beta.5 has been released

**Comment by xCoBaLTz** [comment]
Thank you 👍
