### ISSUE TITLE
Wrong inline formatting in version: '4.0.0-beta.3'

### ISSUE THREAD

**Issue by Mastermindaxe** [DiUS/pact-jvm#909]
The 4.0.0-beta.3 DSL is formatting the pact file as follows: (some content is omitted as I don't see it as relevant)
```
...
"contents": "{\n  \"hometeamScore\": 0,\n  \"ownerId\": 0,\n  \"foreignteamScore\": 0,\n  \"matchId\": 0\n}",
...
```
When it should be formatted like this (to resemble a JSON object):
```
...
"contents": {"hometeamScore": 0,"ownerId": 0,"foreignteamScore": 0,"matchId": 0},
...
```
The issue exists with both DSL. The java8 one and the old generator.

[Link](https://pact-foundation.slack.com/archives/C5F4KFKR8/p1562581863420600) to the slack thread

**Comment by uglyog** [comment]
4.0.0-beta.4 has been released with this fix

**Comment by Mastermindaxe** [comment]
Thank you bunches! Can confirm for the java8 DSL.
