### ISSUE TITLE
LocalDate gets serialized as array, fails at producer

### ISSUE THREAD

**Issue by ngeor** [DiUS/pact-jvm#910]
On the consumer side, I create a pact file with jUnit 5.

```
    <dependency>
      <groupId>au.com.dius</groupId>
      <artifactId>pact-jvm-consumer-junit5</artifactId>
      <version>4.0.0-beta.3</version>
    </dependency>
```

The payload of the request contains a Java 8 LocalDate type. This gets serialized as an array of values:

```
            "date": [
              {
                "value": "2018"
              },
              {
                "value": "4"
              },
              {
                "value": "20"
              }
            ],
```

It should have been serialized as a string instead. On the provider side, the test fails because it can't deserialize the date:

```
    <dependency>
      <groupId>au.com.dius</groupId>
      <artifactId>pact-jvm-provider-junit5</artifactId>
      <version>4.0.0-beta.3</version>
    </dependency>
```

Both consumer and providers are Spring Boot 2 services using Jackson for JSON (de)serialization, which I think is not the same engine that Pact is using under the hood, which might be why this happens. Is it possible to explicitly configure the (de)serialization formats for Pact?

I have the same issue for Integer and BigDecimal already reported at #908 

Thank you!

**Comment by uglyog** [comment]
How are you creating the payloads in the tests? Are you using any of the consumer DSLs?

**Comment by ngeor** [comment]
Hi @uglyog ,

This is the method that creates the tests:

```java
    @Pact(provider = "shipping-connector", consumer = "shipping-service")
    public RequestResponsePact createPact(PactDslWithProvider builder) throws JsonProcessingException {
        createShipment();

        String resultJson = objectMapper.writeValueAsString(createResultClientModel);
        String requestJson = objectMapper.writeValueAsString(shipment);
        return builder
            .uponReceiving("Register shipment")
            .path("/create")
                .method("POST")
                .headers("CustomHeader", "custom value")
                .body(requestJson)
            .willRespondWith()
                .status(HttpStatus.OK.value())
                .body(resultJson, ContentType.APPLICATION_JSON)
            .toPact();
    }
```

The `createShipment()` method prepares the `shipment` variable that gets serialized into JSON.

I made some additional tests:

- when the `LocalDate` field of the `shipment` is `null`, everything works
- if I use my own `ObjectMapper` (this is what I was doing before), the JSON representation is an array of values and it gets serialized as an array of values. (but then it fails on the producer side)
- if I use Spring's ObjectMapper, the JSON representation is a string (this is what I want) but then the test fails with a 500

I also get the fields of type `Integer` (not `int`) and `BigDecimal` stored like this (related to the other issue I mentioned):

```
 "count": {
                "value": "1"
              },
              "weight": {
                "value": "1"
              },
              "length": {
                "value": "1"
              },
```

**Comment by uglyog** [comment]
Is shipment a POJO? And is the LocalDate just a field on that class?

The Number issue has been fixed with PR #913

**Comment by ngeor** [comment]
Yes it's a POJO. The LocalDate is a field on a different POJO which is a field on the first one.

Something like this:

```java
public class Shipment {
  private CollectionInfo collectionInfo;
  public CollectionInfo getCollectionInfo() { return collectionInfo; }
  public void setCollectionInfo(CollectionInfo collectionInfo) { this.collectionInfo = collectionInfo; }
}

public class CollectionInfo {
  private LocalDate date;
  public LocalDate getDate() { return date; }
  public void setDate(LocalDate date) { this.date = date; }
}
```

**Comment by uglyog** [comment]
Right. That's not really anything to do with Pact-JVM. It doesn't use Jackson, it uses GSon internally. 

Normally the expected pacts are setup using one of the DSL builders to define the shape that the body must have, and then the POJO would be used in the actual test method.

But you can use your POJO in the setup, you'll just have to configure Jackson appropriately. There is a module to enable the JDK 8 time classes with it.

**Comment by ngeor** [comment]
Yeah, I already have that module configured :-) So Jackson is configured correctly and the Java 8 time types get (de)serialized as expected over the network (which is as a string, e.g. "2019-07-27").

The problem is that Pact (or GSon, I don't care) doesn't pick that up and serializes it as an array `[2019, 07, 27]`. This gets also transmitted over the network when trying to verify the consumer contract on the producer side, which makes the test fail.

Is it possible to convince Pact or GSon to pick up the same configuration? Or how would you go about using these DLS builders you mentioned?

**Comment by uglyog** [comment]
I don't understand how Pact could be impacting that JSON. You are giving the JSON string to the DSL, and it will use what it gets and not change it. That will be persisted to the pact file, and used when verifying the provider. It knows nothing about your POJO.

Can you check the values of requestJson and resultJson when running your test?

Here is an example of a test using just the DSL: https://github.com/DiUS/pact-jvm/blob/master/consumer/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/examples/ArticlesTest.java#L29

**Comment by ngeor** [comment]
Hi,

I think you're correct, I think I was doing something wrong in the test configuration (not related to Pact). I managed to get it stored as a string and replay it as a string on the provider side as well.

Thank you for the help and for the link to the DSL, I'll give that a try too.
