### ISSUE TITLE
NumberValue is serialized in the wrong way in 4.0.0-beta.4

### ISSUE THREAD

**Issue by gmariotti** [DiUS/pact-jvm#912]
Hi team, I think I found a bug in `4.0.0-beta.4`. 
In `4.0.0-beta.3`, a json field `numberValue("version", 1)` was serialized in the pact as `"version": 1`, however, in `4.0.0-beta.4` the same field is serialized as `"version": { "value": "1"}`, making failing the provider test.

**Comment by uglyog** [comment]
Is this with the Groovy DSL?

**Comment by gmariotti** [comment]
no, it's with the `java8` dsl. I'm using the `LambdaDslObject.numberValue` method

**Comment by uglyog** [comment]
4.0.0-beta.5 has been released

**Comment by gmariotti** [comment]
Fixed, thank you so much
