### ISSUE TITLE
pact.consumer.junit5.PactConsumerTestExt WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by khillyard** [DiUS/pact-jvm#916]
Running a test method yields warning:

_20:55:40.880 [main] DEBUG au.com.dius.pact.consumer.junit5.PactConsumerTestExt - Invoking method 'locationMatch' to get Pact for the test 'locationMatchSucceeds'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/Joe/.m2/repository/org/codehaus/groovy/groovy/2.5.7/groovy-2.5.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release_

Should I report this to org.codehaus.groovy or is this a version dependency issue?

**Comment by uglyog** [comment]
Groovy 3.0 is going to support JDK 9+, but it is still in beta. Although this warning is displayed, I haven't noticed anything failing due to this. So you can ignore it and I'll update the Groovy version to 3.0 when it is out of beta.

**Comment by cogman** [comment]
Groovy 3 is (now?) released.  We've seen with our testing of Java 14 RC that this warning becomes an error.

**Comment by cogman** [comment]
I tried to do a bump, however, it looks like Spock 1.3 doesn't support groovy 3.

This looks like the root issue.

https://github.com/spockframework/spock/issues/997

Also, my build breaks in scala.  Is this expected?  I wasn't able to get a clean compile with no changes.  I saw this instead

```
pact-jvm\pact-jvm-server\src\main\scala\au\com\dius\pact\server\Complete.scala:13: non-variable type argument AnyRef in type pattern scala.collection.immutable.Map[AnyRef,AnyRef] (the underlying of Map[AnyRef,AnyRef]) is unchecked since it is eliminated by erasure
    case map: Map[AnyRef, AnyRef] => {
```

**Comment by cogman** [comment]
Looks like the changes are more fun than I thought.  http-builder does not work with groovy 3.  I tried moving to http-builder-ng, but looks like more changes are needed to make that work.

**Comment by uglyog** [comment]
I've been waiting for Spock to support Groovy 3.

**Comment by cogman** [comment]
Pull #1019 fixes this issue.  I'm ok if it doesn't get accepted just figured I could give ya'll a jumping off point on what needs to happen.

Main change was that http-builder no longer works with groovy 3.0.0.  This updates it to http-builder-ng.

This pull also fails the code narc currently (ABC violation). I'm not exactly sure on the best method of fixing this.
