### ISSUE TITLE
consumer annotation at method level

### ISSUE THREAD

**Issue by sab1l** [DiUS/pact-jvm#919]
I have the following scenario for a spring boot app:
A consumer points to a service provider (e.g. MyServiceProvider) serving 2 API endpoints (e.g. A and B).
For each different endpoint, a dedicated fragment is defined ( verifyAPIendpointA and  verifyAPIendpointB ).
So a single JSON is produced (with **2 interactions**) and published to the broker.

Then, I faced an issue upon trying to create the provider side test using ```@RunWith(RestPactRunner.class)``` and ```@InjectMocks``` for the 2 controllers involved (endpointA and endpointB). 
Each controller would be verified in the state described in pact declaration.
Since consumer annotation is applied at class level, I could successfully setup either A or B. One pact validation would pass and the other would fail since setup from ```@Before``` ended working successfully for either A or B. The other not working would fail to deliver a proper response because ```mockMvc``` could only be set successfully for one.

A workaround from consumer side was found then, splitting each pact into a dedicated provider ( MyServiceProviderEndpointA and MyServiceProviderEndpointB ), to get 2 distinct pacts and have each one addressed in a separate class. Solved! Well, almost.

The problem is now that on the broker side, I end up getting a separate entity for each combination of consumer to service provider with multiple endpoints. Then the nice graph from the broker showing our relationship of calls between services is loosing its interest.

I understand/hope it should be possible to setup each controller independently within its state declaration instead of within ```@Before``` section.

Thank you for considering this possible improvement and please let me know in case more explanations are needed.

**Comment by uglyog** [comment]
On investigation I have found that this is already supported via the provider state callbacks. See https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java, it has two different controllers and the expectations are setup via the state change methods.

So all you need to do to to make sure the two different endpoints have different provider states, and these will be called before the test for each one. No need for the consumer annotation.

**Comment by sab1l** [comment]
managed to have this working as expected after following advices from previous comment, closing.
