### ISSUE TITLE
Pact keeps running when the state change URL returns 500/404 etc

### ISSUE THREAD

**Issue by stefan-lz** [DiUS/pact-jvm#92]
Hi, I've got a pact which keeps running when state change URL errors.

Here it is the console output of it running:

	Verifying a pact between xxxxxxxxxxxxx and xxxxxxxxxxxxxxxxxxxxx
	  [from URL http://bamboo.hq.local:8085/browse/xxxxxxxxxxxxxxxxxxxxxxxxxx/pact.json]
	  Given There is a lost member xxxxxxxxxx
	[INFO] ERROR [2015-02-27 16:23:03,811] com.yammer.dropwizard.tasks.TaskServlet: Error running pactStateChange
	[INFO] ! java.lang.IllegalStateException: No xxxxxxxx xxxxx='xxxxxxxx'
	[INFO] ! at au.com.xxxx.asis.memberservice.pacts.PactStateChangeTask.execute(PactStateChangeTask.java:37) ~[member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at com.yammer.dropwizard.tasks.TaskServlet.doPost(TaskServlet.java:50) ~[member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.Server.handle(Server.java:368) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(Abstr
	[INFO] actHttpConnection.java:942) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [member-service-2.10-SNAPSHOT.jar:na]
	[INFO] ! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	  A request to get member details
	    returns a response which
	      has status code 200 (OK)
	      includes headers
		"Content-Type" with value "application/json" (OK)
	      has a matching body (OK)
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD SUCCESS
	[INFO] ------------------------------------------------------------------------

Here is a snippet of the pom.xml:

	<groupId>au.com.dius</groupId>
	<artifactId>pact-jvm-provider-maven_2.11</artifactId>
	<version>2.1.11</version>
	<configuration>
	<serviceProviders>
	<serviceProvider>
	<name>member-service</name>
	<stateChangeUrl>http://localhost:8031/tasks/pactStateChange</stateChangeUrl>
	<stateChangeUsesBody>false</stateChangeUsesBody> 

I believe this might be a regression?

**Comment by uglyog** [comment]
You believe correctly, it's a regression after changing from using the Groovy HTTP Builder to using Apache HTTP Client.

I sense a pull request in the near future.

**Comment by uglyog** [comment]
Updated the provider plugins to fail on bad responses after a stage change request.

But you might want to actually fix your state change URL handler! ;-)

**Comment by stefan-lz** [comment]
Cool, thanks for that! I was just about to take a look at it. I'll try out the fix in a few days and let you know how it goes.

**Comment by stefan-lz** [comment]
@uglyog, just trying the latest version and I'm now getting this:

	Verifying a pact between abc-service and member-service
	  [from URL http://bamboo.hq.local:8085/browse/COMMS-ABC/latestSuccessful/artifact/JOB1/Pacts/Member+Service.json]
	  Given There is a ABC member 012300001
		 State Change Request Failed - No such property: statusCode for class: org.apache.http.impl.execchain.HttpResponseProxy
	Possible solutions: statusCode, statusLine

version info:

	<groupId>au.com.dius</groupId>
	<artifactId>pact-jvm-provider-maven_2.11</artifactId>
	<version>2.1.12</version>


Cheers,

**Comment by uglyog** [comment]
Wow, No such property: statusCode, Possible solutions: statusCode

You think maybe someone is trying to pull our leg?
