### ISSUE TITLE
Special character pact validation

### ISSUE THREAD

**Issue by jdcano-bpe** [DiUS/pact-jvm#920]
Hello all,

First of all thanks for the great job you are doing with this project.

We are currently using pact broker to validate our testings in a Spring Boot application. These are the versions we are using:

- pact-jvm-provider-maven_2.12 - 3.6.12
- spring-boot: 2.1.6

In most of the cases all the tests are running fine and are validated without any problem.

But we are having some issues to validate few tests that contains special characters (like ç é à í, etc). The data in our application contains this characters due to the use of multiple languages in the application (like english, french, spanish and portuguese) and the file against we validate this information contains exactly the same characters, but at the validation time we get an error because they are not the same:

> name=[{mismatch=Expected 'L?neas de cr?dito' but received 'L??neas de cr??dito', diff=}]}

I have been diggin in the documentation but I did not find any information regarding this topic. Is there a way to validate allowing this special characters or we need to test only in english?

Thanks a lot in advance.

**Comment by uglyog** [comment]
It should support UTF-8, so the special characters should be supported (unless you are using a different charset). I'll setup some tests for this to get to the bottom of it.

**Comment by uglyog** [comment]
I setup a simple test (see https://github.com/uglyog/pact-maven-springboot-test/blob/master/src/main/java/com/github/uglyog/GreetingController.java#L15) and it worked. Could you confirm what charset you response is encoded as?

**Comment by jdcano-bpe** [comment]
Thanks for your answer.

The problems was related with the locale of the docker image where we are running the tests. If the locale is not installed, the tests will fail.

Sorry for the noise and thanks for your effort.

Best regards,
