### ISSUE TITLE
pact file decimal value trim issue while publishing to pact-broker

### ISSUE THREAD

**Issue by gituser-cmd** [DiUS/pact-jvm#924]
I am facing issue with the the decimal value ,while publishing the pact file to pact-broker ,the decimal value 1563454500.123456789 getting trimmed to 1563454500.1234567.
pact file has correct value , but when published to pact-broker ,it gets trimmed . How to address it .

**Comment by uglyog** [comment]
Just to confirm, you have a pact file with the correct precision. You publish it (via the Gradle or Maven publish tasks) and it displays truncated in the pact broker?

**Comment by gituser-cmd** [comment]
Yes that is correct

**Comment by uglyog** [comment]
The publish task does not change the content of the pact file (it just does a PUT request to the broker). This must be a issue with the broker. Are you seeing the truncation when the pact file is fetched from the broker, or from the screen displaying the pact in the broker?

**Comment by gituser-cmd** [comment]
I am seeing this from the screen displaying the pact in the broker. Whereas the local file before publishing to broker shows correct without truncating.

**Comment by uglyog** [comment]
Can you raise an issue for that on the pact broker project and link to this issue? https://github.com/pact-foundation/pact_broker
