### ISSUE TITLE
pact-jvm-provider-gradle uses project.version for both pactVerify and pactPublish tasks.

### ISSUE THREAD

**Issue by toastyblast** [DiUS/pact-jvm#929]
When I set
```
pact {
   serviceProviders {
      'Provider-Name' {
         // Mock server host settings...

         // This is changing the project.version, not just the provider version for pact!
         version = branchName() + '-' + abbreviatedId()

         if ('pactVerify' in gradle.startParameter.taskNames) {
            hasPactsFromPactBroker('http://localhost:80/')
         }
      }
   }
}
```
for pactVerify or for pactPublish
```
pact {
   serviceProviders {
        // Again, this is changing the project.version, not just the consumer version for pact!
        version = 'PROV-TEST-' + grgit.head().abbreviatedId
        tags = [grgit.branch.current.name]

        pactDirectory = file('./test/pact/consumerPacts')
        pactBrokerUrl = 'http://localhost:80/'
   }
}
```
The value setting version in either one of them also changes `project.version`. In our team we want the consumer and provider version to be the git name and hash of the branch the pact as been sent/verified from to the broker for clarity, and not the Gradle project version. This is currently causing a breaking issue, as the jar files we generate DO use the project.version, and we do not want those jar files to change names!

Can this please be changed/fixed to allow one to set provider and consumer versions different from project.version? I understand it as a _default_, but if someone wants it changed, they shouldn't have to change the _whole_ Gradle project's version.

We're using pact-jvm-provider-gradle-2.12 version 3.6.12.

**Comment by toastyblast** [comment]
My excuses, the second one is incorrect. Setting version in the publish section does not change the project.version. That only makes me more surprised though, why do that and not allow the same for verify?

**Comment by uglyog** [comment]
Response is on the PR #931

**Comment by toastyblast** [comment]
Thank you for the heads up. I've seen the release, I'll get to implementing it for my team now. Once again, many thanks for the help!
