### ISSUE TITLE
Failed verification results not being published when state is missing on provider side

### ISSUE THREAD

**Issue by DavidMendesOS** [DiUS/pact-jvm#930]
Dependencies used in the provider tests:
import au.com.dius.pact.provider.junit.Provider;
import au.com.dius.pact.provider.junit.State;
import au.com.dius.pact.provider.junit.loader.PactBroker;
import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;

Test output: 

Contract.Provider.ProviderTests > pactVerificationTestTemplate(PactVerificationContext)[3] STANDARD_OUT

    Verifying a pact between consumer and provider
      Valid Request
        returns a response which
          has status code 200 (OK)
          includes headers
            "Content-Type" with value "application/json; charset=utf-8" (OK)
          has a matching body (OK)

    2019-08-29 14:11:49.009  INFO 19043 --- [    Test worker] a.c.d.p.p.DefaultVerificationReporter    : Published verification result of 'au.com.dius.pact.pactbroker.TestResult$Ok@1d6b0542' for consumer 'Consumer(name=consumer)'
Contract.Provider.ProviderTests > pactVerificationTestTemplate(PactVerificationContext)[4] STANDARD_OUT
    2019-08-29 14:11:49.015  INFO 19043 --- [    Test worker] a.c.d.p.p.DefaultTestResultAccumulator   : Not all of the #3 were verified.
Contract.Provider.ProviderTests > pactVerificationTestTemplate(PactVerificationContext)[4] FAILED
    au.com.dius.pact.provider.junit.MissingStateChangeMethod: Did not find a test class method annotated with  @ State("Some State")

(...)

Notice that in this last case the failure is not Published which means the contract is seen as being verified when it is not the case.

**Comment by uglyog** [comment]
The test result will now be marked as failed when the state change is missing or fails.

**Comment by uglyog** [comment]
Fix has been released with version 3.6.13
