### ISSUE TITLE
GET on pact-jvm-server root (http://localhost:29999) delivers broken json

### ISSUE THREAD

**Issue by hstamminger** [DiUS/pact-jvm#938]
###### Environment
JDK: 1.8.0, 11, 12
pact-jvm-server: 3.5.15++ (issue raises perhaps with the merge of PR [#666])

###### Description
A call to `/` delivers broken json response if a mock is created before.

###### Example

1. start pact-jvm-server: `bin\pact-jvm-server.bat --host 0.0.0.0 --mock-port-lower 30000 --mock-port-upper 30999 --pact-version 3 --debug 29999`
1. create mock: `curl --request POST \
                   --url 'http://localhost:29999/create?state=Basistestfixture&path=%2Fresource' \
                   --header 'content-type: application/json' \
                   --data '{
                   "consumer": {
                     "name": "pact-consumer"
                   },
                   "provider": {
                     "name": "pact-provider"
                   },
                   "interactions": [
                     {
                       "description": "get time",
                       "request": {
                         "method": "GET",
                         "path": "/resource/time/current",
                 				"query": {
                 					"locale": ["de"]
                 				}
                       },
                       "response": {
                         "body": {
                           "time": "13:00:34.890"
                          },
                         "status": 200
                       },
                       "providerStates": [
                         {
                           "name": "Basistestfixture"
                         }
                       ]
                     }
                   ],
                   "metadata": {
                     "pact-specification": {
                       "version": "3.0.0"
                     }
                   }
                 }'` \
                 -> response: `{ "port": 30633 }`
1. call `http://localhost:29999/` to retrieve all created mocks (ports): `curl --request GET --url http://localhost:29999/` \
    -> response: header: `Content-Type: application/json`; body: `{ "ports": [ 30633, /resource ] }` (which not valid json) \
    => expected `{ "ports": [ 30633, "/resource" ] }`
    * Why is the `path`-fragment contained in `ports` array?

**Comment by uglyog** [comment]
It will return `{"ports": [30146], "paths": ["/resource"]}` now

**Comment by uglyog** [comment]
4.0.0 has been released with this fix
