### ISSUE TITLE
Mock-providers are not completed on call to `/complete`

### ISSUE THREAD

**Issue by hstamminger** [DiUS/pact-jvm#939]
###### Environment
JDK: 1.8.0, 11, 12
pact-jvm-server: 3.5.15++ (issue raises perhaps with the merge of PR [#666](https://github.com/DiUS/pact-jvm/issues/644))

###### Description
A call to `/complete` does not complete the mock. The created mock is still avaliable under the `path`-entry from the create request.

###### Example

1. start pact-jvm-server: `bin\pact-jvm-server.bat --host 0.0.0.0 --mock-port-lower 30000 --mock-port-upper 30999 --pact-version 3 --debug 29999`
1. create mock: `curl --request POST \
                   --url 'http://localhost:29999/create?state=Basistestfixture&path=%2Fresource' \
                   --header 'content-type: application/json' \
                   --data '{
                   "consumer": {
                     "name": "pact-consumer"
                   },
                   "provider": {
                     "name": "pact-provider"
                   },
                   "interactions": [
                     {
                       "description": "get time",
                       "request": {
                         "method": "GET",
                         "path": "/resource/time/current",
                 				"query": {
                 					"locale": ["de"]
                 				}
                       },
                       "response": {
                         "body": {
                           "time": "13:00:34.890"
                          },
                         "status": 200
                       },
                       "providerStates": [
                         {
                           "name": "Basistestfixture"
                         }
                       ]
                     }
                   ],
                   "metadata": {
                     "pact-specification": {
                       "version": "3.0.0"
                     }
                   }
                 }'` \
                 -> response: `{ "port": 30633 }`
1. call `http://localhost:29999/` to retrieve all created mocks (ports): `curl --request GET --url http://localhost:29999/` \
    -> response: header: `Content-Type: application/json`; body: `{ "ports": [ 30633, /resource ] }` (which not valid json see issue [#938](https://github.com/DiUS/pact-jvm/issues/938))
1. call `http://localhost:30633/resource/time/current?locale=de` to call the mock: `curl --request GET --url 'http://localhost:30633/resource/time/current?locale=de'`; you will get response with status 200 as expected
1. call `http://localhost:29999/resource/time/current?locale=de` to call the mock via server-port: `curl --request GET --url 'http://localhost:29999/resource/time/current?locale=de'`; you will get response with status 200 as expected
1. call `/complete` with port `30633` to complete the mock: `curl --request POST --url http://localhost:29999/complete --header 'content-type: application/json' --data '{ "port": 30633 }'`; you will get a response with status 200; assuming that all mocks are stopped now
1. call `http://localhost:29999/` to retrieve all created mocks (ports): `curl --request GET --url http://localhost:29999/`; response still contains mock with path `/resource`: body: `{ "ports": [ /resource ] }`
1. call `http://localhost:30633/resource/time/current?locale=de` to call the mock: `curl --request GET --url 'http://localhost:30633/resource/time/current?locale=de'`; you don't get a response as there is no server (as expected)
1. call `http://localhost:29999/resource/time/current?locale=de` to call the mock via server-port: `curl --request GET --url 'http://localhost:29999/resource/time/current?locale=de'`; you will get response with status 200 (not expected, mock is not stopped)
1. call `http://localhost:29999/INVALID_PATH` to enforce an error: `curl --request GET --url http://localhost:29999/INVALID_PATH` -> you get response with status 404 (expected) and body:
    ```
    /resource -> au.com.dius.pact.server.UnfilteredMockProvider@3120e150,
    path -> /INVALID_PATH
    ```
   You can see that there is still a mock running under path `/resource`. This surviving mock-provider could not be stopped with a call to `/complete` and the path-fragment as body.

\
If run step 10. before you complete the mock (step 6.) you get the following response: status 404 with body
```
30633 -> au.com.dius.pact.server.UnfilteredMockProvider@3120e150,
/resource -> au.com.dius.pact.server.UnfilteredMockProvider@3120e150,
path -> /INVALID_PATH
```
It seems that there are two references to the created mock-provider. `/complete` kills only one of the references and the mock-provider survives the complete command. Problem here is that this mock-provider still allocate system resources (cpu, mem, file handles, ...). We are using the pact-jvm-server for our e2e-tests which runs highly parallel. we are running out of system resources very quickly.

Can you please fix this issue? Thanks

**Comment by uglyog** [comment]
This has been fixed now. Thanks for the very detailed bug report, it made diagnosing this really easy.

As an aside, if system resources are an issue you should maybe look at https://github.com/pact-foundation/pact-reference/tree/master/rust/pact_mock_server_cli which is written in Rust and should be a lot more performant. There is a docker image for it at https://hub.docker.com/r/pactfoundation/pact-ref-mock-server

**Comment by uglyog** [comment]
4.0.0 has been released with this fix

**Comment by hstamminger** [comment]
Hi
Thank you very much!

**Comment by hstamminger** [comment]
One question regarding the rust implementation you mentioned. Does it implement version 3 of Pact specification? Documentation states that it implements only version 2 of the spec.

**Comment by uglyog** [comment]
Rust implementation is V3
