### ISSUE TITLE
class PactDslResponse does not handle encoding correctly

### ISSUE THREAD

**Issue by ogalimov** [DiUS/pact-jvm#941]
In pact-jvm-consumer:4.0.0-beta.6

```java
public PactDslResponse body(String body, String mimeType) {
  responseBody = OptionalBody.body(body.getBytes(), new au.com.dius.pact.core.model.ContentType(mimeType));
  responseHeaders.put(CONTENT_TYPE, Collections.singletonList(mimeType));
  return this;
}
```

This code is a bit dubious when it comes to encoding. Because the body has a charset, that is possibly encoded in the mimeType, but the method body.getBytes() uses system encoding. As there is no method `public PactDslResponse body(byte[] body, String mimeType)`, there is no workaround.

**Comment by uglyog** [comment]
Good pick up. And it is not only in 4.0.0 beta versions, it's like that in 3.5.x and 3.6.x

**Comment by uglyog** [comment]
4.0.0 has been released with this fix
