### ISSUE TITLE
provider state callbacks available from multiple classes

### ISSUE THREAD

**Issue by sab1l** [DiUS/pact-jvm#943]
Trying to reuse example from [1], I was not able to split in separate classes different @State methods related to a same provider, all must go within the class holding their @Provider declaration.
Unfortunately, this can lead to long classes, it would be great to be able to split each state logic in a dedicated class.

[1]: https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-spring/src/test/java/au/com/dius/pact/provider/spring/BooksPactProviderTest.java

**Comment by uglyog** [comment]
I implemented a mechanism to supply additional classes for the test target. The other option is to use interfaces. See https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-junit/README.md#using-multiple-classes-for-the-state-change-methods

**Comment by sab1l** [comment]
Many thanks for everything!

**Comment by uglyog** [comment]
4.0.1 has been released

**Comment by morbic** [comment]
@uglyog Is it possible to achieve the same in JUnit 5 without using interfaces (e.g. with `setStateHandlers` method)?

**Comment by uglyog** [comment]
@morbic that change will need to be ported to JUnit 5

**Comment by uglyog** [comment]
@morbic I've added it to JUnit 5. See https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-junit5/src/test/java/au/com/dius/pact/provider/junit5/StateAnnotationsOnAdditionalClassTest.java

**Comment by uglyog** [comment]
@morbic 4.0.3 has been released with JUnit 5 support

**Comment by morbic** [comment]
@uglyog wonderful, thank you for your extremely fast help! Love to be Pact JVM user 😄
