### ISSUE TITLE
dynamic tag values for provider validation

### ISSUE THREAD

**Issue by sab1l** [DiUS/pact-jvm#944]
I'm looking for a way to pass tag value from command line (using maven in my case), when using something as ```@PactBroker([...] tags = ["Release"])```
Our idea is here to be able to switch from a tag to another depending on the git branch, I tried to get system property propagated there but constant value is needed so I see no easy way.
I also tried removing tag there and use a maven systemPropertyVariables ```pact.provider.tag``` for this purpose, but it would only default to latest without considering another value there.

**Comment by Artem034** [comment]
Actually here answer: https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-junit/README.md#using-java-system-properties

Example:
in code:
@PactBroker( ..., tags ="${your.variable.name:latest}")
in command line:
-Dyour.variable.name=prod,master

**Comment by uglyog** [comment]
@sab1l are you able to check if @Artem034's answer works for you?

**Comment by sab1l** [comment]
thanks @Artem034 and @uglyog for clarifying this point, it's all I needed!
