### ISSUE TITLE
provider/HttpClientFactory should not create a http client that handles redirects

### ISSUE THREAD

**Issue by audunhalland** [DiUS/pact-jvm#952]
provider `HttpClientFactory` creates an apache HTTP client by calling `HttpClients.createDefault()`. I'm not sure that configuration is what is normally wanted, because that client will follow HTTP redirects, and redirects is part of what I'm testing with our use of pact. I think a better way to create the client by default would be `HttpClients.custom().disableRedirectHandling().build()`, at least this is closer to what I need in my test. 

In `HttpClientFactory` there are some ways to override the http client behaviour using groovy, but I cannot get this to work nicely with pure java/kotlin. So instead I needed to override `HttpTarget::testInteraction(...)` to inject my own custom HttpClientFactory.

**Comment by uglyog** [comment]
4.0.1 has been released
