### ISSUE TITLE
Body encoding in OptionalBody not used

### ISSUE THREAD

**Issue by ogalimov** [DiUS/pact-jvm#956]
In pact 4.0.0 https://github.com/DiUS/pact-jvm/issues/941 was fixed, however pact tests with alternative encodings still do not work. There are two places in the code that look suspicious:

OptionalBody.kt:
```kotlin
override fun toString(): String {
  return when (state) {
    State.PRESENT -> "PRESENT(${value!!.toString(Charset.defaultCharset())})"
    State.EMPTY -> "EMPTY"
    State.NULL -> "NULL"
    State.MISSING -> "MISSING"
  }
}

fun valueAsString(): String {
  return when (state) {
    State.PRESENT -> value!!.toString(Charset.defaultCharset())
    State.EMPTY -> ""
    State.NULL -> ""
    State.MISSING -> ""
  }
}
```
Here `Charset.defaultCharset()` is used instead of the charset encoded in the field `contentType` in `OptionalBody`. This leads to the string being incorrectly serialized in the `parseBody(...)` method of the class `RequestResponseInteraction`.

Request.kt / Response.kt
```kotlin
json["body"].isJsonPrimitive && json["body"].asJsonPrimitive.isString ->
  OptionalBody.body(json["body"].asJsonPrimitive.asString.toByteArray())
else -> OptionalBody.body(json["body"].toString().toByteArray())
```

In this code the `Content-Type` header is not being added to the body. I am however not sure, if this is required.

**Comment by uglyog** [comment]
I think I've updated all the places where bodies are converted. Are you able to provide the test that was failing so I can add it to the tests?

**Comment by octavian-h** [comment]
Hi,
The encoding issue still happens at pact-jvm-server -> Conversions.scala

```scala
  def toBody(request: HttpRequest[ReceivedMessage], charset: String = "UTF-8") = {
    val is = if (request.headers(ContentEncoding.GZip.name).contains("gzip")) {
      new GZIPInputStream(request.inputStream)
    } else {
      request.inputStream
    }
    if(is == null) "" else scala.io.Source.fromInputStream(is).mkString
  }

  def unfilteredRequestToPactRequest(request: HttpRequest[ReceivedMessage]): Request = {
    val headers = toHeaders(request)
    val contentType = new ContentType(request.headers("Content-Type").next())
    new Request(request.method, toPath(request.uri), toQuery(request), headers,
      OptionalBody.body(toBody(request).getBytes(contentType.asCharset), contentType))
  }
```

Although the OptionalBody gets the charset from the request, the method toBody doesn't take into consideration the request charset, also scala.io.Source.fromInputStream ignores the charset parameter.
