### ISSUE TITLE
Support array JSON body

### ISSUE THREAD

**Issue by jamessawle** [DiUS/pact-jvm#96]
Currently it is not possible to have a JSON body, with an array at the root. The array is automatically wrapped within an object.

**Comment by uglyog** [comment]
@jamessawle are you having this issue in the consumer tests, or when validating the pact against the provider?

**Comment by jamessawle** [comment]
When generating a PACT. The current API does not seem to allow an array to be at the root of the body. We have locally extended the JSON array object to implement a default constructor and  toString method and this seems to have fixed the issue.

We have the changes ready to submit a pull request.

**Comment by MichaelStephan** [comment]
Hello jamessawle, do you mind to give me access to your code changes already as I'm facing the same issue at this point in time?

**Comment by jamessawle** [comment]
I will work on a pull request in the morning.

**Comment by jamessawle** [comment]
Pull request has been created - https://github.com/DiUS/pact-jvm/pull/103

**Comment by jamessawle** [comment]
The pull request has been merged
