### ISSUE TITLE
Publish verification results to pact broker JUnit4

### ISSUE THREAD

**Issue by leonleo997** [DiUS/pact-jvm#962]
Hello,
I've been trying to uploads the verification results to a local broker but does not work. I'm following this instructions https://github.com/DiUS/pact-jvm/tree/master/provider/pact-jvm-provider-junit#publishing-verification-results-to-a-pact-broker.
Before all, these are my class annotations:
```
@RunWith(RestPactRunner.class)
@Provider("clarifi-loan-handler-service")
@PactBroker(host = "localhost", port = "80")
class DocProcessingContractSpec {
```

These are my attemps:
1) Execute on terminal:  `./gradlew clean test -Dpact.provider.version=1.0.0 -Dpact.verifier.publishResults=true`
2) Add properties using the following code:
```
@RunWith(RestPactRunner.class)
@Provider("clarifi-loan-handler-service")
@PactBroker(host = "localhost", port = "80")
@SpringBootTest(
        properties=
            ["pact.verifier.publishResults=true", "pact.provider.version=1.0.0"]

)
```
It looks that the pact is downloaded and tested against it but does not uploads any verification report...
Please help! hahaha

**Comment by roioteromorales** [comment]
I had a similar issue using the `au.com.dius:pact-jvm-provider-spring:4.0.1 ` 
For me it didnt read the properties from spring or env, so i had to put it in the system properties.
I put in gradle this in the test task:
 `   systemProperties['pact.verifier.publishResults'] =  System.getenv("PACT_PUBLISH_RESULTS") ?: "false"`

Then you set up your environment variable `PACT_PUBLISH_RESULTS`

**Comment by leonleo997** [comment]
It does not work for me, there is another solution :D ?

**Comment by leonleo997** [comment]
Forget it, it also works using `-Dpact.verifier.publishResults=true`

**Comment by Norman-else** [comment]
> -Dpact.verifier.publishResults=true

This does not work for me.

**Comment by uglyog** [comment]
@Norman-else how are you running your tests? Maven, Gradle, IntelliJ IDEA, Eclipse?
