### ISSUE TITLE
Matches are not allowing special characters like ':' and '/' in name fields

### ISSUE THREAD

**Issue by Sandhyagabbi** [DiUS/pact-jvm#965]
StringMatcher and numberType matchers are not allowing special characters like "/" and ":" in the name field in 4.0.x version. It was working fine till 3.6.x version.
Here is the error message returned:
ERROR a.c.d.p.c.BaseJdkMockServer:204 [Thread-2] Failed to generate response au.com.dius.pact.core.model.InvalidPathExpression: ":" is not allowed in an identifier in path expression "$.container_records[0].state[0].aDataItem[0].example:ABC" at index 149

**Comment by uglyog** [comment]
I've updated the matcher expressions to allow colons (':'). For other special characters, like slashes you'll need to use the bracket form (like `['example/ABC']`)

**Comment by Sandhyagabbi** [comment]
Thank you for making the changes.
