### ISSUE TITLE
Is there any way to avoid calling a dtd url from response when using XmlBodyMatcher?

### ISSUE THREAD

**Issue by anddreiu** [DiUS/pact-jvm#973]
I am using XML in body request and response, so I am using XmlBodyMatcher.

My request and response contain some urls for a dtd, which I think are called when the request is made and also when the response is verified with XmlBodyMatcher. For the request I have managed to avoid checking the dtd by setting some features on the DocumentBuilderFactory, like this:

```
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
factory.setValidating(false);
factory.setNamespaceAware(true);
factory.setFeature("http://xml.org/sax/features/namespaces", false);
factory.setFeature("http://xml.org/sax/features/validation", false);
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-dtd-grammar", false);
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
DocumentBuilder builder = factory.newDocumentBuilder();
```

But for the response I don't know how to instruct XmlBodyMatcher to not call my dtd. I need this because otherwise I get a connection timeout error, because that url is not available from my network. 

I think it tries to validate that dtd when the XML is parsed by the XmlBodyMatcher. Do you have any ideas how can I ignore the verification of the dtd?

Thanks!

**Comment by uglyog** [comment]
I've added the `pact.matching.xml.validating` system property, which if set to `false` will set the validating value on the document builder factory to false.

**Comment by uglyog** [comment]
4.0.3 has been released with this fix

**Comment by anddreiu** [comment]
@uglyog I've just tested this using 4.0.3 and it seems that even if I use `-Dpact.matching.xml.validating=false` it will still try to access the dtd url.

**Comment by anddreiu** [comment]
Hi @uglyog. In order to completely ignore the dtd url, I think you should set also the following on the document builder factory:
```
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-dtd-grammar", false);
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
```

Thanks
