### ISSUE TITLE
@Pact annotation with dynamic values

### ISSUE THREAD

**Issue by Yamuna-Rani** [DiUS/pact-jvm#989]
I want to pass the dynamic values to @Pact annotation from the property file.

@Pact(provider = "**Profile_Provider**", consumer = "**Profile_Consumer**")
	public PactFragment createFragment(PactDslWithProvider builder) {
		Map<String, String> headers = new HashMap<>();
		headers.put("Content-Type", "application/json;charset=UTF-8");
             return builder.uponReceiving("a request for 
            profile").path("/producers").method("GET").willRespondWith()
				.headers(headers).status(200)
				.body("[{\"producerId\":\"119bbacd\",\"firstName\":\"jomon\",\"lastName\":\"varghese\",\"email\":\"jomon@yahoomail.com\"},{\"producerId\":\"jkjk1jkjk2\",\"firstName\":\"joy\",\"lastName\":\"varghese\",\"email\":\"joy@abcd.com\"}]")	
				.toFragment();
	}

Can you please help the same.

Thanks,
Yamuna

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change
