### ISSUE TITLE
example junit5 message provider verification test 

### ISSUE THREAD

**Issue by davidlewine** [DiUS/pact-jvm#992]
I have been able to convert message consumer pact tests to junit5, but am not sure how to use the information in the junit5 provider readme to construct a message provider verification test.

I am trying to convert something like:

`import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.any;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import com.worldpay.waaus.cue.app.kafka.MsgObject;
import com.worldpay.waaus.cue.app.service.MessageProducer;

import java.io.IOException;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.util.concurrent.ListenableFuture;

import au.com.dius.pact.provider.PactVerifyProvider;
import au.com.dius.pact.provider.junit.Consumer;
import au.com.dius.pact.provider.junit.PactRunner;
import au.com.dius.pact.provider.junit.Provider;
import au.com.dius.pact.provider.junit.loader.PactFolder;
import au.com.dius.pact.provider.junit.target.AmqpTarget;
import au.com.dius.pact.provider.junit.target.Target;
import au.com.dius.pact.provider.junit.target.TestTarget;

@RunWith(PactRunner.class)
@Provider("provider")
@Consumer("consumer")
@PactFolder("target/pacts")
public class MessageProviderPact {

  @TestTarget
  public final Target target = new AmqpTarget();

  private KafkaTemplate<String, MsgObject> kafkaTemplate
      = (KafkaTemplate<String, MsgObject>)Mockito.mock(KafkaTemplate.class);

  private MessageProducer messageProducer = new MessageProducer(kafkaTemplate);

  @Test
  @PactVerifyProvider("case a")
  public String verifyCaseA() throws IOException {
    // given
    ListenableFuture<SendResult<String, MsgObject>> future =
        mock(ListenableFuture.class);
    doReturn(future).when(kafkaTemplate).send(any(String.class),
        any(MsgObject.class));

    // when
    DomainObj domainObj = new DomainObj();
    String topic = "kafka_add";
    messageProducer.send(topic, domainObj);

    // then
    ArgumentCaptor<MsgObject> messageCapture = ArgumentCaptor.forClass(
        MsgObject.class);
    verify(kafkaTemplate, times(1)).send(eq(topic),
        messageCapture.capture());

    // returning the message
    return objectMapper.writeValueAsString(messageCapture.getValue());
  }
}
`

**Comment by davidlewine** [comment]
Found it at https://github.com/DiUS/pact-jvm/blob/master/provider/pact-jvm-provider-junit5/src/test/java/au/com/dius/pact/provider/junit5/AmqpContractTest.java

**Comment by shivkavitha** [comment]
Above link returns 404. Please could you point to appropriate source? 

Many Thanks!

**Comment by uglyog** [comment]
@shivkavitha https://github.com/pact-foundation/pact-jvm/blob/master/provider/junit5/src/test/java/au/com/dius/pact/provider/junit5/AmqpContractTest.java
