### ISSUE TITLE
How to do variable interpolation for groovy

### ISSUE THREAD

**Issue by leonleo997** [DiUS/pact-jvm#993]
Hello,
I'm trying to do variable interpolation to set localhost as the default host but it doesn't work. I'm using 
`testImplementation group: 'au.com.dius', name: 'pact-jvm-provider-spring', version: '4.0.0'`

I think that is about Groovy syntax because that is the programming language that I'm using :(

**Comment by leonleo997** [comment]
> Hello,
> I'm trying to do variable interpolation to set localhost as the default host but it doesn't work. I'm using
> `testImplementation group: 'au.com.dius', name: 'pact-jvm-provider-spring', version: '4.0.0'`

**Comment by leonleo997** [comment]
my bad :)

**Comment by uglyog** [comment]
The verifier will default to localhost, so you can just leave the value out. Not sure why you're trying to do variable interpolation.
