### ISSUE TITLE
Create can-i-deploy maven plugin

### ISSUE THREAD

**Issue by bethesque** [DiUS/pact-jvm#994]
Great first issue for a beginner! @ me if you're reading this and are interested in an easy little OSS contribution.

**Comment by araknoid** [comment]
Hi @bethesque ,
since I've found a lot of value in using Pact, I'd like to contribute.
I'd like to take this issue if it's possible. 
If yes, can you please give me some details?
Thanks

**Comment by bethesque** [comment]
Awesome! You're very welcome to do this one, but there is one that's of a higher importance and urgency if you're interested. I don't think it will be too hard to do, but you'll need to do a bit of digging to understand how the code is currently working. I can give you some pointers, but I'm not one of the maintainers, so I'll only be a slight bit ahead of you anyway.

https://github.com/DiUS/pact-jvm/issues/942 (follow the link through to the master issue)

**Comment by araknoid** [comment]
Sorry for the delay.
Fine by me; I'll start looking at the other issue.
If you have any pointers/details that could make easier to understand what is needed and what is missing, I'll gladly welcome them.

**Comment by uglyog** [comment]
Basic version working:

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change

**Comment by bethesque** [comment]
I checked the code, and there is an extra parameter that needs adding - it won't work in its current form. The matrix endpoint started as a generalised "show me these versions and these versions together" and then later had the "and can they be deployed together safely" added, so the parameters are a little obscure. I wrote some docs on the matrix "selectors" here: https://docs.pact.io/pact_broker/advanced_topics/selectors

You'll need to add the top level parameter `latestby=cvp`, or you'll get every row for the version you're about to deploy, rather than the latest row for each provider. This will make the deployable flag incorrect.

If the user doesn't specify a `--to TAG` then you'll need a plain `latest=true` top level parameter, otherwise, it will include multiple rows for each provider, and make the deployable flag incorrect again.

The pacts for the matrix endpoint are here: https://github.com/pact-foundation/pact_broker-client/blob/master/spec/pacts/pact_broker_client-pact_broker.json

The other option is to use the simplified `can-i-deploy` endpoint which has only been released recently (so will force people to upgrade). The docs are here: https://github.com/pact-foundation/pact_broker/blob/master/lib/pact_broker/doc/views/can-i-deploy.markdown

Note that this does not support the --latest for the pacticipant you're about to deploy, which personally, I don't think should be needed. Someone should know which version they're deploying, and relying on the broker to know which the latest one seems dicey.

**Comment by bethesque** [comment]
You can see the effect of the 'latestby' by viewing the matrix for a integration, and changing the `Show latest results by ...` option.

**Comment by uglyog** [comment]
4.0.6 has been released with the updated fix (latestby query parameter)

**Comment by bethesque** [comment]
LGTM. Is the pact being published anywhere?

**Comment by uglyog** [comment]
Don't think so
