### ISSUE TITLE
Issues with new Maven plugin

### ISSUE THREAD

**Issue by rorymalcolm** [DiUS/pact-jvm#995]
Hi,

When I use [`maven-surefire-plugin` ](https://maven.apache.org/surefire/maven-surefire-plugin/) version `3.0.0-M4` pacts can no longer be published to the provider.

```
14:41:42  [INFO] --- pact-jvm-provider-maven_2.12:3.6.14:publish (default-cli) @ pay-ledger ---
14:41:43  Pact directory target/pacts does not exist, skipping uploading of pacts
```

Is this a known issue? Is there anything I can do to remedy it?

Thanks.

**Comment by uglyog** [comment]
You log example shows version 3.6.14, so do you have this issue with any version or only if you use 3.0.0-M4. BTW, the current released version is 4.0.4
