### ISSUE TITLE
PACT verification fails when header has comma separated values

### ISSUE THREAD

**Issue by PatrickNestmeyer** [DiUS/pact-jvm#997]
I have following PACT file:

```
"response": {
        "status": 200,
        "headers": {
          "Access-Control-Expose-Headers": "content-length,content-type",
          "X-XSS-Protection": "1; mode=block"
        },

```

When I start pact provider test I recieve assertionError:

```
java.lang.AssertionError: 
0 - Expected header 'Access-Control-Expose-Headers' to have value 'content-length' but was 'content-length,content-type', Expected header 'Access-Control-Expose-Headers' to have value 'content-type' but was ''

```

I am using spring-boot:2.2.2 and pact-jvm-provider-spring:4.0.4.

**Comment by winokurow** [comment]
This this correct behaviour - your PACT file is incorrect - you must use JsonArray:


```
"response": {
        "status": 200,
        "headers": {
          "Access-Control-Expose-Headers": ["content-length,content-type"],
          "X-XSS-Protection": "1; mode=block"
        },
```

**Comment by PatrickNestmeyer** [comment]
Our frontend consumer tests (JavaScript) can not generate pact files with headers as JsonArray using pact-foundation/pact-node.

Spring Provider tests run with mentioned changes, but tests with headers in the format as in the original comment is supposed to work. 

Works with: 
``
"Access-Control-Expose-Headers": ["content-length,content-type"],
``
But should work with: 
``
"Access-Control-Expose-Headers": "content-length,content-type",
``

**Comment by uglyog** [comment]
Version 4.0.5 has been released with this change

**Comment by PatrickNestmeyer** [comment]
Thank you.
